### ISSUE TITLE
Test and document upgrading from source to packaged releases

### ISSUE THREAD

**Issue by adam12** [dokku/dokku#4782] opened 2021-09-14 01:46 UTC
As discussed on Slack, the upgrade from source to a packaged release via `bootstrap.sh` failed. The process should be tested again and documented for how it should be done correctly.

**Comment by josegonzalez** [comment] 2023-01-15 04:38
I just went through the process of installing from source and upgrading, and it seemed to work fine. The logs in slack have rotated out so for now I'm just going to close it since the process works as intended for me.

**Closed by josegonzalez** 2023-01-15 04:38 UTC
Labels: type: documentation, merge-level: patch
