### ISSUE TITLE
`git:from-image` does not work if previous deployment failed

### ISSUE THREAD

**Issue by IgnisDa** [dokku/dokku#5538] opened 2022-12-22 04:27 UTC
### Description of problem

I have an app that I deploy via `dokku git:from-image`. The deploy failed during default check phase (an application error; nothing to do with dokku). However, now I can not deploy this image again. Here is the error:

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/60938164/209055253-3a6e9c28-ba64-4338-9635-39eeefa2fd48.png">

My only option is to rebuild a new image (so that the `sha` is different) and then use `git:from-image` again.

### Steps to reproduce

1. Deploy an app using sha (as described [here](https://dokku.com/docs/deployment/methods/git/#initializing-an-app-repository-from-a-docker-image))
2. Simulate an error in the deploy phase:
   
   <img width="1267" alt="image" src="https://user-images.githubusercontent.com/60938164/209055659-97d1ae61-6431-41ed-b894-4e95a243f365.png">

3. Try calling the same command in step one

### dokku report $APP_NAME

-----> uname: Linux main 5.4.0-135-generic #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:            976         594          86          17         295         200
       Swap:          3071        2008        1063
-----> docker version:
       Client: Docker Engine - Community
        Version:           20.10.22
        API version:       1.41
        Go version:        go1.18.9
        Git commit:        3a2c30b
        Built:             Thu Dec 15 22:28:08 2022
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true

       Server: Docker Engine - Community
        Engine:
         Version:          20.10.22
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.18.9
         Git commit:       42c8b31
         Built:            Thu Dec 15 22:25:58 2022
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.13
         GitCommit:        78f51771157abb6c9ed224c22013cdf09962315d
        runc:
         Version:          1.1.4
         GitCommit:        v1.1.4-0-g5fd4c4d
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
         compose: Docker Compose (Docker Inc., v2.14.1)
         scan: Docker Scan (Docker Inc., v0.23.0)

       Server:
        Containers: 40
         Running: 39
         Paused: 0
         Stopped: 1
        Images: 36
        Server Version: 20.10.22
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 78f51771157abb6c9ed224c22013cdf09962315d
        runc version: v1.1.4-0-g5fd4c4d
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-135-generic
        Operating System: Ubuntu 20.04.5 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 1
        Total Memory: 976.8MiB
        Name: main
        ID: PEEB:CHZO:EMP7:XJR5:2ZB7:QM5F:TPDW:PHRP:MO73:X7YR:V5PN:LJDA
        Docker Root Dir: /mnt/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> git version: git version 2.25.1
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version:
Unable to find image 'gliderlabs/herokuish:latest-20' locally
latest-20: Pulling from gliderlabs/herokuish
eaead16dc43b: Already exists
b742bb9acf04: Already exists
7be84fdf790e: Already exists
a5c4a27c565e: Already exists
84d15847b85b: Already exists
88cef5e3805c: Already exists
aa7dd27706b0: Already exists
e31390793b0a: Already exists
070f1db60ccf: Already exists
6c238cf76e61: Already exists
Digest: sha256:80d222c05b2d0e46020fb2a6af80cb41ff8be8edac5e2c0efb8ebafa3ec9a744
Status: Downloaded newer image for gliderlabs/herokuish:latest-20
       herokuish: v0.5.40
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v244
         heroku-buildpack-nodejs    v202
         heroku-buildpack-clojure   v90
         heroku-buildpack-python    v223
         heroku-buildpack-java      v72
         heroku-buildpack-gradle    v38
         heroku-buildpack-scala     v96
         heroku-buildpack-play      v26
         heroku-buildpack-php       v227
         heroku-buildpack-go        v169
         heroku-buildpack-nginx     v22
         buildpack-null             v3
-----> dokku version: dokku version 0.29.0
-----> plugn version: plugn: 0.12.0build+3a27594
-----> dokku plugins:
         00_dokku-standard    0.29.0 enabled    dokku core standard plugin
         20_events            0.29.0 enabled    dokku core events logging plugin
         app-json             0.29.0 enabled    dokku core app-json plugin
         apps                 0.29.0 enabled    dokku core apps plugin
         builder              0.29.0 enabled    dokku core builder plugin
         builder-dockerfile   0.29.0 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.29.0 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.29.0 enabled    dokku core builder-lambda plugin
         builder-null         0.29.0 enabled    dokku core builder-null plugin
         builder-pack         0.29.0 enabled    dokku core builder-pack plugin
         buildpacks           0.29.0 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.29.0 enabled    dokku core caddy-vhosts plugin
         certs                0.29.0 enabled    dokku core certificate management plugin
         checks               0.29.0 enabled    dokku core checks plugin
         clickhouse           0.18.0 enabled    dokku clickhouse service plugin
         common               0.29.0 enabled    dokku core common plugin
         config               0.29.0 enabled    dokku core config plugin
         cron                 0.29.0 enabled    dokku core cron plugin
         docker-options       0.29.0 enabled    dokku core docker-options plugin
         domains              0.29.0 enabled    dokku core domains plugin
         edgedb               0.0.0 enabled    dokku plugin for edgedb (https://edgedb.com)
         enter                0.29.0 enabled    dokku core enter plugin
         git                  0.29.0 enabled    dokku core git plugin
         letsencrypt          0.12.1 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.29.0 enabled    dokku core logs plugin
         mariadb              1.24.0 enabled    dokku mariadb service plugin
         mongo                1.22.0 enabled    dokku mongo service plugin
         network              0.29.0 enabled    dokku core network plugin
         nginx-max-upload-size 0.1.4 enabled    Set the NGINX maximum upload file size
         nginx-vhosts         0.29.0 enabled    dokku core nginx-vhosts plugin
         plugin               0.29.0 enabled    dokku core plugin plugin
         postgres             1.18.0 enabled    dokku postgres service plugin
         proxy                0.29.0 enabled    dokku core proxy plugin
         ps                   0.29.0 enabled    dokku core ps plugin
         redis                1.19.0 enabled    dokku redis service plugin
         registry             0.29.0 enabled    dokku core registry plugin
         repo                 0.29.0 enabled    dokku core repo plugin
         resource             0.29.0 enabled    dokku core resource plugin
         run                  0.29.0 enabled    dokku core run plugin
         scheduler            0.29.0 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.29.0 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.29.0 enabled    dokku core scheduler-null plugin
         shell                0.29.0 enabled    dokku core shell plugin
         ssh-keys             0.29.0 enabled    dokku core ssh-keys plugin
         storage              0.29.0 enabled    dokku core storage plugin
         trace                0.29.0 enabled    dokku core trace plugin
         traefik-vhosts       0.29.0 enabled    dokku core traefik-vhosts plugin
=====> codefarem--orchestrator app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:
=====> codefarem--orchestrator app information
       App created at:                1670755926
       App deploy source:             codefarem--orchestrator
       App deploy source metadata:    codefarem--orchestrator
       App dir:                       /home/dokku/codefarem--orchestrator
       App locked:                    false
=====> codefarem--orchestrator builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:
       Builder global build dir:
       Builder global selected:
       Builder selected:
=====> codefarem--orchestrator builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path:
=====> codefarem--orchestrator builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml
       Builder lambda global lambdayml path: lambda.yml
       Builder lambda lambdayml path:
=====> codefarem--orchestrator builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> codefarem--orchestrator buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
=====> codefarem--orchestrator ssl information
       Ssl dir:                       /home/dokku/codefarem--orchestrator/tls
       Ssl enabled:                   true
       Ssl hostnames:                 codefarem--orchestrator.ignisda.tech
       Ssl expires at:                Mar 12 09:14:12 2023 GMT
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = R3
       Ssl starts at:                 Dec 12 09:14:13 2022 GMT
       Ssl subject:                   subject=CN = codefarem--orchestrator.ignisda.tech
       Ssl verified:                  self signed
=====> codefarem--orchestrator checks information
       Checks disabled list:          none
       Checks skipped list:           none
       Checks computed wait to retire: 60
       Checks global wait to retire:  60
       Checks wait to retire:
=====> codefarem--orchestrator cron information
       Cron task count:               0
=====> codefarem--orchestrator docker options information
       Docker options build:          --link dokku.edgedb.codefarem-db:edgedb --volume /var/lib/dokku/services/edgedb/codefarem-db/config:/edgedb-config
       Docker options deploy:         --link dokku.edgedb.codefarem-db:edgedb --restart=on-failure:10 --volume /var/lib/dokku/services/edgedb/codefarem-db/config:/edgedb-config
       Docker options run:            --link dokku.edgedb.codefarem-db:edgedb --volume /var/lib/dokku/services/edgedb/codefarem-db/config:/edgedb-config
=====> codefarem--orchestrator domains information
       Domains app enabled:           true
       Domains app vhosts:            codefarem--orchestrator.ignisda.tech
       Domains global enabled:        true
       Domains global vhosts:         ignisda.tech
=====> codefarem--orchestrator git information
       Git deploy branch:             master
       Git global deploy branch:      main
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       efabb94
       Git last updated at:           1671682504
=====> codefarem--orchestrator logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:
       Logs vector sink:
=====> codefarem--orchestrator network information
       Network attach post create:           codefarem-network
       Network attach post deploy:
       Network bind all interfaces:          false
       Network computed attach post create:  codefarem-network
       Network computed attach post deploy:
       Network computed bind all interfaces: false
       Network computed initial network:
       Network computed tld:
       Network global attach post create:
       Network global attach post deploy:
       Network global bind all interfaces:   false
       Network global initial network:
       Network global tld:
       Network initial network:
       Network static web listener:
       Network tld:
       Network web listeners:                172.17.0.11:5000
=====> codefarem--orchestrator nginx information
       Nginx access log format:
       Nginx access log path:         /var/log/nginx/codefarem--orchestrator-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx client max body size:
       Nginx disable custom config:   false
       Nginx error log path:          /var/log/nginx/codefarem--orchestrator-error.log
       Nginx global hsts:             true
       Nginx computed hsts:           true
       Nginx hsts:
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx computed nginx conf sigil path: nginx.conf.sigil
       Nginx global nginx conf sigil path: nginx.conf.sigil
       Nginx nginx conf sigil path:
       Nginx proxy buffer size:       4096
       Nginx proxy buffering:         on
       Nginx proxy buffers:           8 4096
       Nginx proxy busy buffers size: 8192
       Nginx proxy read timeout:      60s
       Nginx last visited at:         1671408002
       Nginx x forwarded for value:   $remote_addr
       Nginx x forwarded port value:  $server_port
       Nginx x forwarded proto value: $scheme
       Nginx x forwarded ssl:
=====> codefarem--orchestrator proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 https:443:5000
       Proxy type:                    nginx
=====> codefarem--orchestrator ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: b041a8d3dbc)
=====> codefarem--orchestrator registry information
       Registry computed image repo:      dokku/codefarem--orchestrator
       Registry computed push on release: false
       Registry computed server:
       Registry global push on release:
       Registry global server:
       Registry image repo:
       Registry push on release:
       Registry server:
       Registry tag version:
=====> codefarem--orchestrator resource information
=====> codefarem--orchestrator scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:
=====> codefarem--orchestrator scheduler-docker-local information
       Scheduler docker local disable chown:
       Scheduler docker local init process: true
       Scheduler docker local parallel schedule count:
=====> codefarem--orchestrator storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:

**Comment by josegonzalez** [comment] 2022-12-22 04:33
Interesting, if it fails, the push to the repo should also fail. Do you have the output from the previous failed deploy?

As a workaround, you can use ps:rebuild

**Comment by IgnisDa** [comment] 2022-12-22 04:36
@josegonzalez I am not pushing to the repo at all. I am just calling `dokku git:from-image` on the dokku server itself.


`dokku ps:rebuild` works

**Comment by josegonzalez** [comment] 2022-12-22 05:55
The from image command triggers a push. But if the deploy fails, the repo should also revert iirc.

**Comment by IgnisDa** [comment] 2022-12-22 06:23
I do not think it is working like that at all.

**Comment by josegonzalez** [comment] 2022-12-22 07:09
Right, but I'm saying it should. Just thinking through your issue, as it shouldn't be possible to get into this state.

That said, yes, calling git:from-image on the same image will result in a no-op, and the only way to redeploy is to ps:rebuild. That is by design.

**Comment by IgnisDa** [comment] 2022-12-22 07:28
> That said, yes, calling git:from-image on the same image will result in a no-op, and the only way to redeploy is to ps:rebuild. That is by design.

Yep that makes sense. 

`git:from-image`  should not go into invalid state if the deploy failed.

**Comment by josegonzalez** [comment] 2022-12-27 07:05
Ah! Okay this is a side-effect of how git repositories are handled for `git:from-image`:

- When the repo has no code, the initial state is set to an automatically created commit for the image (all `git:from-image` calls create a commit).
- When the repo has code (regardless of how that code was set), we create a temp repo based on the existing source code, make an automated commit on top of that, and then fetch the change/reset the current working state to the new commit.

In both cases, we never revert on error, so the repo gets the new image, regardless of whether it succeeded or not. We could:

- reset the repo to a bare repo when there was no existing code
- go back to the old commit if there was existing code and somehow remove that new commit

Both of those seem like a good idea, and I think are in the spirit of the `git:from-image` command.

**Comment by IgnisDa** [comment] 2022-12-27 07:11
This sounds pretty good!

> go back to the old commit if there was existing code and somehow remove that new commit

maybe a `git reset --hard HEAD~`?

**Comment by josegonzalez** [comment] 2022-12-27 07:12
There seem to be a few ways to make the reset work, so I'm trying them out one-by-one 😅

**Comment by josegonzalez** [comment] 2022-12-27 07:24
Heh so this works when you have at least one commit:

```
git update-ref refs/heads/master master^
```

But not if it's the first commit.

**Comment by josegonzalez** [comment] 2022-12-27 07:26
What I'd love to do is just delete the git repo but Dokku still stores random things in there - docker-options, env file, vhosts (I think?), port stuff, nginx config, certs - so thats not a safe operation. I'll keep digging on something we can do for the current state of things...

**Comment by josegonzalez** [comment] 2022-12-27 07:37
Closing as there is an open PR for this.

**Closed by josegonzalez** 2022-12-27 07:37 UTC
Labels: type: bug, needs: investigation

**Comment by IgnisDa** [comment] 2023-01-19 12:09
@josegonzalez I am still experiencing this problem.

Here are steps to reproduce:

- Deployed an image using `git:from-image`
- Call `ps:stop` on the app
- Reboot the server
- Delete the image using `docker rmi dokku/appname`

After this, trying to use git:from-image` results in this:
```
-----> Generating build context
       Setting Dockerfile
-----> Pulling image
postgresql-latest: Pulling from umami-software/umami
213ec9aee27d: Pull complete
90d4f1a52341: Pull complete
96f9ff3b94d8: Pull complete
f05a94b04b95: Pull complete
1ad3aa7ede17: Pull complete
6dfb7e91b6b2: Pull complete
a9af10b42156: Pull complete
b10fcae2b267: Pull complete
c59ccd95e24d: Pull complete
5f8296911c17: Pull complete
04b22ab9be02: Pull complete
fe1519ac8426: Pull complete
d48a9c15f3f8: Pull complete
db3077e17fc1: Pull complete
0d411b1c3a5f: Pull complete
Digest: sha256:60fa8875aff8309c04d7f9e194bcabc8431d7eb628d427c8e0acaad2bb3bdaf0
Status: Downloaded newer image for docker.umami.dev/umami-software/umami:postgresql-latest
docker.umami.dev/umami-software/umami:postgresql-latest
-----> Updating git repository with specified build context
 !     No changes detected, skipping git commit
 !     Call 'ps:rebuild' on app to rebuild the app from existing source
```

And `ps:rebuild` results in:
```

**Comment by josegonzalez** [comment] 2023-01-19 15:24
You are having a different issue here than the original one. Do you mind opening another ticket?
