### ISSUE TITLE
Deployment continues when predeployment task fails

### ISSUE THREAD

**Issue by ngatti-tmm** [dokku/dokku#6919] opened 2024-06-03 16:48 UTC
### Description of problem

I have a node app deployed via dokku. Application is running ok, and deployment worked as expected. 
Then, I added a database migration to app.json. This is a new Ubuntu 22 server, everything up to date.

This is my app.json file:
```
{
  "scripts": {
    "dokku": {
      "predeploy": "npm run migrate"
    }
  },
  "healthchecks": {
    "web": [
      {
        "type": "startup",
        "name": "web check",
        "description": "Checking if the app responds wit 200 to / request",
        "path": "/",
        "attempts": 3
      }
    ]
  }
}
```
Currently there is an issue with the `npm run migrate` command, that failed, but the deployment went through and replaced my current container with the new.

To test it further I changed the `npm run migrate` to `ERROR` so as to force the error and be sure that I get a non-zero exit code from it. Here is the deployment interesting log output when trying to run "ERROR":

```
[...]
-----> Build succeeded!
-----> Discovering process types
       Procfile declares types -> web
-----> Releasing my-ai-app-dev...
-----> Checking for predeploy task
       Executing predeploy task from app.json: ERROR
=====> Start of my-ai-app-dev predeploy task (86adc4bb8) output
remote:  !     /bin/bash: line 1: ERROR: command not found
=====> End of my-ai-app-dev predeploy task (86adc4bb8) output
-----> Checking for release task
       No release task found, skipping
=====> Processing deployment checks
-----> Deploying my-ai-app-dev via the docker-local scheduler...
-----> Deploying web (count=1)
[...]
```

Am I understanding it wrong? I asumed that if a predeploy task fails, deployment should also fail, according to the docs:
https://dokku.com/docs/advanced-usage/deployment-tasks/

### Steps to reproduce

1. Create a new node app
2. Configure BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-nodejs.git
3. Configure a failing predeployment task on app.json
4. Test a deployment

### dokku report $APP_NAME

```
root@server1:~# dokku report my-ai-app-dev
-----> uname: Linux server1 5.15.0-107-generic #117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                      total        used        free      shared  buff/cache   available
       Mem:            3911         657         853          43        2401        2920
       Swap:              0           0           0
-----> disk utilization:
       Filesystem      Size  Used Avail Use% Mounted on
       /dev/vda1        78G   48G   30G  62% /
       /dev/vda15      105M  6.1M   99M   6% /boot/efi
       /dev/sda         50G   16M   47G   1% /mnt/volume_ams3_24
       /dev/sdb         20G  2.2G   17G  12% /mnt/varlogai1
-----> disk inode utilization:
       Filesystem     Inodes IUsed IFree IUse% Mounted on
       /dev/vda1        9.9M  2.2M  7.8M   22% /
       /dev/vda15          0     0     0     - /boot/efi
       /dev/sda         1.6M  2.8K  1.6M    1% /mnt/volume_ams3_24
       /dev/sdb         640K   309  640K    1% /mnt/varlogai1
-----> docker version:
       Client: Docker Engine - Community
        Version:           26.1.3
        API version:       1.45
        Go version:        go1.21.10
        Git commit:        b72abbb
        Built:             Thu May 16 08:33:29 2024
        OS/Arch:           linux/amd64
        Context:           default

       Server: Docker Engine - Community
        Engine:
         Version:          26.1.3
         API version:      1.45 (minimum version 1.24)
         Go version:       go1.21.10
         Git commit:       8e96db1
         Built:            Thu May 16 08:33:29 2024
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.32
         GitCommit:        8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89
        runc:
         Version:          1.1.12
         GitCommit:        v1.1.12-0-g51d5e94
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client: Docker Engine - Community
        Version:    26.1.3
        Context:    default
        Debug Mode: true
        Plugins:
         buildx: Docker Buildx (Docker Inc.)
           Version:  v0.14.0
           Path:     /usr/libexec/docker/cli-plugins/docker-buildx
         compose: Docker Compose (Docker Inc.)
           Version:  v2.27.0
           Path:     /usr/libexec/docker/cli-plugins/docker-compose

       Server:
        Containers: 9
         Running: 6
         Paused: 0
         Stopped: 3
        Images: 21
        Server Version: 26.1.3
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Using metacopy: false
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: systemd
        Cgroup Version: 2
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89
        runc version: v1.1.12-0-g51d5e94
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: builtin
         cgroupns
        Kernel Version: 5.15.0-107-generic
        Operating System: Ubuntu 22.04.4 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 3.82GiB
        Name: server1
        ID: 96fddca3-0ed0-4664-b453-70d5b5033ded
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
         File Descriptors: 103
         Goroutines: 142
         System Time: 2024-06-03T16:45:34.5619996Z
         EventsListeners: 8
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> herokuish version:
       herokuish: v0.9.1
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v267
         heroku-buildpack-nodejs    v240
         heroku-buildpack-clojure   v91
         heroku-buildpack-python    v246
         heroku-buildpack-java      v73
         heroku-buildpack-gradle    v39
         heroku-buildpack-scala     v98
         heroku-buildpack-play      v26
         heroku-buildpack-php       v248
         heroku-buildpack-go        v189
         heroku-buildpack-nginx     v25
         buildpack-null             v3
-----> dokku version: dokku version 0.34.4
-----> dokku-event-listener version: v0.16.0
-----> dokku-update version: dokku-update v0.9.1
-----> docker-container-healthchecker version: v0.10.2
-----> docker-image-labeler version: v0.7.0
-----> git version: git version 2.34.1
-----> lambda-builder version:        v0.7.0
-----> netrc version: v0.9.0
 !     pack binary is not available
-----> plugn version: plugn: v0.15.3
-----> sigil version: 0.10.1build+e443be0
-----> sshcommand version: sshcommand v0.18.0
-----> dokku plugins:
         00_dokku-standard    0.34.4 enabled    dokku core standard plugin
         20_events            0.34.4 enabled    dokku core events logging plugin
         app-json             0.34.4 enabled    dokku core app-json plugin
         apps                 0.34.4 enabled    dokku core apps plugin
         builder              0.34.4 enabled    dokku core builder plugin
         builder-dockerfile   0.34.4 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.34.4 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.34.4 enabled    dokku core builder-lambda plugin
         builder-nixpacks     0.34.4 enabled    dokku core builder-nixpacks plugin
         builder-null         0.34.4 enabled    dokku core builder-null plugin
         builder-pack         0.34.4 enabled    dokku core builder-pack plugin
         buildpacks           0.34.4 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.34.4 enabled    dokku core caddy-vhosts plugin
         certs                0.34.4 enabled    dokku core certificate management plugin
         checks               0.34.4 enabled    dokku core checks plugin
         common               0.34.4 enabled    dokku core common plugin
         config               0.34.4 enabled    dokku core config plugin
         cron                 0.34.4 enabled    dokku core cron plugin
         docker-options       0.34.4 enabled    dokku core docker-options plugin
         domains              0.34.4 enabled    dokku core domains plugin
         enter                0.34.4 enabled    dokku core enter plugin
         git                  0.34.4 enabled    dokku core git plugin
         haproxy-vhosts       0.34.4 enabled    dokku core haproxy-vhosts plugin
         letsencrypt          0.20.4 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.34.4 enabled    dokku core logs plugin
         network              0.34.4 enabled    dokku core network plugin
         nginx-vhosts         0.34.4 enabled    dokku core nginx-vhosts plugin
         openresty-vhosts     0.34.4 enabled    dokku core openresty-vhosts plugin
         plugin               0.34.4 enabled    dokku core plugin plugin
         ports                0.34.4 enabled    dokku core ports plugin
         postgres             1.36.4 enabled    dokku postgres service plugin
         proxy                0.34.4 enabled    dokku core proxy plugin
         ps                   0.34.4 enabled    dokku core ps plugin
         registry             0.34.4 enabled    dokku core registry plugin
         repo                 0.34.4 enabled    dokku core repo plugin
         resource             0.34.4 enabled    dokku core resource plugin
         run                  0.34.4 enabled    dokku core run plugin
         scheduler            0.34.4 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.34.4 enabled    dokku core scheduler-docker-local plugin
         scheduler-k3s        0.34.4 enabled    dokku core scheduler-k3s plugin
         scheduler-null       0.34.4 enabled    dokku core scheduler-null plugin
         shell                0.34.4 enabled    dokku core shell plugin
         ssh-keys             0.34.4 enabled    dokku core ssh-keys plugin
         storage              0.34.4 enabled    dokku core storage plugin
         trace                0.34.4 enabled    dokku core trace plugin
         traefik-vhosts       0.34.4 enabled    dokku core traefik-vhosts plugin
=====> my-ai-app-dev app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:
=====> my-ai-app-dev app information
       App created at:                1715970987
       App deploy source:             git-push
       App deploy source metadata:    26550fc346f86f37edfbff66abe7efa6b55b76ad
       App dir:                       /home/dokku/my-ai-app-dev
       App locked:                    false
=====> my-ai-app-dev builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:
       Builder global build dir:
       Builder global selected:
       Builder selected:
=====> my-ai-app-dev builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path:
=====> my-ai-app-dev builder-herokuish information
       Builder herokuish computed allowed: true
       Builder herokuish global allowed: true
       Builder herokuish allowed:
=====> my-ai-app-dev builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml
       Builder lambda global lambdayml path: lambda.yml
       Builder lambda lambdayml path:
=====> my-ai-app-dev builder-nixpacks information
       Builder nixpacks computed nixpackstoml path: nixpacks.toml
       Builder nixpacks global nixpackstoml path: nixpacks.toml
       Builder nixpacks nixpackstoml path:
       Builder nixpacks computed no cache: false
       Builder nixpacks global no cache: false
       Builder nixpacks no cache:
=====> my-ai-app-dev builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> my-ai-app-dev buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-22
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:              gliderlabs/herokuish:latest-22
=====> my-ai-app-dev caddy information
       Caddy image:                   lucaslorentz/caddy-docker-proxy:2.8
       Caddy letsencrypt email:
       Caddy letsencrypt server:      https://acme-v02.api.letsencrypt.org/directory
       Caddy log level:               ERROR
       Caddy polling interval:        5s
       Caddy tls internal:            false
=====> my-ai-app-dev ssl information
       Ssl dir:                       /home/dokku/my-ai-app-dev/tls
       Ssl enabled:                   true
       Ssl hostnames:                 app-dev.my.ai
       Ssl expires at:                Aug 19 18:44:24 2024 GMT
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = R3
       Ssl starts at:                 May 21 18:44:25 2024 GMT
       Ssl subject:                   subject=CN = app-dev.my.ai
       Ssl verified:                  verified by a certificate authority
=====> my-ai-app-dev checks information
       Checks disabled list:          none
       Checks skipped list:           none
       Checks computed wait to retire: 60
       Checks global wait to retire:  60
       Checks wait to retire:
=====> my-ai-app-dev docker options information
       Docker options build:          --link dokku.postgres.my-ai-app-dev:dokku-postgres-my-ai-app-dev
       Docker options deploy:         --link dokku.postgres.my-ai-app-dev:dokku-postgres-my-ai-app-dev --restart=on-failure:10 -v /var/lib/dokku/data/storage/app-fe-myai-dev/:/app/public/uploads/
       Docker options run:            --link dokku.postgres.my-ai-app-dev:dokku-postgres-my-ai-app-dev -v /var/lib/dokku/data/storage/app-fe-myai-dev/:/app/public/uploads/
=====> my-ai-app-dev domains information
       Domains app enabled:           true
       Domains app vhosts:            app-dev.my.ai
       Domains global enabled:        true
       Domains global vhosts:         packer-6481b5fa-f32f-c6ab-b44d-a2621ac2dcee
=====> my-ai-app-dev git information
       Git deploy branch:             develop
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       f71edb7f35c7646a1b33c58f5d60ab9d84a77c2f
       Git source image:
       Git last updated at:           1717432741
=====> my-ai-app-dev haproxy information
       Haproxy image:                 byjg/easy-haproxy:4.4.0
       Haproxy letsencrypt email:
       Haproxy letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Haproxy log level:             ERROR
=====> my-ai-app-dev letsencrypt information
       Letsencrypt active:            true
       Letsencrypt autorenew:         true
       Letsencrypt computed dns provider:
       Letsencrypt global dns provider:
       Letsencrypt dns provider:
       Letsencrypt computed email:    sysadmin@my.ventures
       Letsencrypt global email:      sysadmin@my.ventures
       Letsencrypt email:
       Letsencrypt expiration:        1724093064
       Letsencrypt computed graceperiod: 2592000
       Letsencrypt global graceperiod:
       Letsencrypt graceperiod:
       Letsencrypt computed lego docker args:
       Letsencrypt global lego docker args:
       Letsencrypt lego docker args:
       Letsencrypt computed server:   https://acme-v02.api.letsencrypt.org/directory
       Letsencrypt global server:
       Letsencrypt server:
=====> my-ai-app-dev logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:
       Logs vector global image:      timberio/vector:0.36.1-debian
       Logs vector sink:
=====> my-ai-app-dev network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:          false
       Network computed attach post create:
       Network computed attach post deploy:
       Network computed bind all interfaces: false
       Network computed initial network:
       Network computed tld:
       Network global attach post create:
       Network global attach post deploy:
       Network global bind all interfaces:   false
       Network global initial network:
       Network global tld:
       Network initial network:
       Network static web listener:
       Network tld:
       Network web listeners:                172.17.0.2:5000
=====> my-ai-app-dev nginx information
       Nginx access log format:
       Nginx computed access log format:
       Nginx global access log format:
       Nginx access log path:
       Nginx computed access log path: /var/log/nginx/my-ai-app-dev-access.log
       Nginx global access log path:  /var/log/nginx/my-ai-app-dev-access.log
       Nginx bind address ipv4:
       Nginx computed bind address ipv4:
       Nginx global bind address ipv4:
       Nginx bind address ipv6:
       Nginx computed bind address ipv6: ::
       Nginx global bind address ipv6: ::
       Nginx client max body size:
       Nginx computed client max body size: 1m
       Nginx global client max body size: 1m
       Nginx disable custom config:
       Nginx computed disable custom config: false
       Nginx global disable custom config: false
       Nginx error log path:
       Nginx computed error log path: /var/log/nginx/my-ai-app-dev-error.log
       Nginx global error log path:   /var/log/nginx/my-ai-app-dev-error.log
       Nginx hsts include subdomains:
       Nginx computed hsts include subdomains: true
       Nginx global hsts include subdomains: true
       Nginx hsts max age:
       Nginx computed hsts max age:   15724800
       Nginx global hsts max age:     15724800
       Nginx hsts preload:
       Nginx computed hsts preload:   false
       Nginx global hsts preload:     false
       Nginx hsts:
       Nginx computed hsts:           true
       Nginx global hsts:             true
       Nginx last visited at:
       Nginx nginx conf sigil path:
       Nginx computed nginx conf sigil path: nginx.conf.sigil
       Nginx global nginx conf sigil path: nginx.conf.sigil
       Nginx proxy buffer size:
       Nginx computed proxy buffer size: 4k
       Nginx global proxy buffer size: 4k
       Nginx proxy buffering:
       Nginx computed proxy buffering: on
       Nginx global proxy buffering:  on
       Nginx proxy buffers:
       Nginx computed proxy buffers:  8 4k
       Nginx global proxy buffers:    8 4k
       Nginx proxy busy buffers size:
       Nginx computed proxy busy buffers size: 8k
       Nginx global proxy busy buffers size: 8k
       Nginx proxy read timeout:
       Nginx computed proxy read timeout: 60s
       Nginx global proxy read timeout: 60s
       Nginx underscore in headers:
       Nginx computed underscore in headers: off
       Nginx global underscore in headers: off
       Nginx x forwarded for value:
       Nginx computed x forwarded for value: $remote_addr
       Nginx global x forwarded for value: $remote_addr
       Nginx x forwarded port value:
       Nginx computed x forwarded port value: $server_port
       Nginx global x forwarded port value: $server_port
       Nginx x forwarded proto value:
       Nginx computed x forwarded proto value: $scheme
       Nginx global x forwarded proto value: $scheme
       Nginx x forwarded ssl:
       Nginx computed x forwarded ssl:
       Nginx global x forwarded ssl:
=====> my-ai-app-dev openresty information
       Openresty access log format:
       Openresty access log path:     /var/log/nginx/my-ai-app-dev-access.log
       Openresty allowed letsencrypt domains func base64: cmV0dXJuIHRydWUK
       Openresty bind address ipv4:
       Openresty bind address ipv6:   ::
       Openresty client max body size:
       Openresty error log path:      /var/log/nginx/my-ai-app-dev-error.log
       Openresty global hsts:         true
       Openresty computed hsts:       true
       Openresty hsts:
       Openresty hsts include subdomains: true
       Openresty hsts max age:        15724800
       Openresty hsts preload:        false
       Openresty image:               dokku/openresty-docker-proxy:0.7.0
       Openresty letsencrypt email:
       Openresty letsencrypt server:  https://acme-v02.api.letsencrypt.org/directory
       Openresty proxy buffer size:   4k
       Openresty proxy buffering:     on
       Openresty proxy buffers:       8 4k
       Openresty proxy busy buffers size: 8k
       Openresty proxy read timeout:  60s
       Openresty underscore in headers: off
       Openresty x forwarded for value: $remote_addr
       Openresty x forwarded port value: $server_port
       Openresty x forwarded proto value: $scheme
       Openresty x forwarded ssl:
=====> my-ai-app-dev ports information
       Ports map:
       Ports map detected:            http:80:5000 https:443:5000
=====> my-ai-app-dev proxy information
       Proxy computed type:           nginx
       Proxy enabled:                 true
       Proxy global type:             nginx
       Proxy type:
=====> my-ai-app-dev ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: b244e46fd50)
=====> my-ai-app-dev registry information
       Registry computed image repo:        dokku/my-ai-app-dev
       Registry computed push on release:   false
       Registry computed server:
       Registry global image repo template:
       Registry global push on release:
       Registry global server:
       Registry image repo:
       Registry push extra tags:
       Registry push on release:
       Registry server:
       Registry tag version:
=====> my-ai-app-dev resource information
=====> my-ai-app-dev scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:
=====> my-ai-app-dev scheduler-docker-local information
       Scheduler docker local init process: true
       Scheduler docker local parallel schedule count:
=====> my-ai-app-dev scheduler-k3s information
       Scheduler k3s computed deploy timeout:       300s
       Scheduler k3s computed image pull secrets:
       Scheduler k3s computed letsencrypt server:   prod
       Scheduler k3s computed namespace:            default
       Scheduler k3s computed rollback on failure:  false
       Scheduler k3s deploy timeout:
       Scheduler k3s global deploy timeout:         300s
       Scheduler k3s global image pull secrets:
       Scheduler k3s global ingress class:          nginx
       Scheduler k3s global kube context:
       Scheduler k3s global kubeconfig path:        /etc/rancher/k3s/k3s.yaml
       Scheduler k3s global letsencrypt email prod:
       Scheduler k3s global letsencrypt email stag:
       Scheduler k3s global letsencrypt server:     prod
       Scheduler k3s global namespace:              default
       Scheduler k3s global network interface:      eth0
       Scheduler k3s global rollback on failure:    false
       Scheduler k3s image pull secrets:
       Scheduler k3s letsencrypt server:
       Scheduler k3s namespace:
       Scheduler k3s rollback on failure:
=====> my-ai-app-dev storage information
       Storage build mounts:
       Storage deploy mounts:         -v /var/lib/dokku/data/storage/app-fe-myai-dev/:/app/public/uploads/
       Storage run mounts:            -v /var/lib/dokku/data/storage/app-fe-myai-dev/:/app/public/uploads/
=====> my-ai-app-dev traefik information
       Traefik api enabled:           false
       Traefik api vhost:             traefik.dokku.me
       Traefik basic auth password:
       Traefik basic auth username:
       Traefik dashboard enabled:     false
       Traefik image:                 traefik:2.11.0
       Traefik letsencrypt email:
       Traefik letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Traefik log level:             ERROR
```

**Comment by josegonzalez** [comment] 2024-06-12 04:32
Thanks for reporting this. I can take a look at it this week and see what the issue is.

**Comment by matthewmueller** [comment] 2024-08-18 04:47
👋  also noticing this for the `pre-deploy`, `post-deploy` hook and `release` hooks for the Go buildpack.

```
dokku version 0.34.7
```

```
=====> Start of writebud predeploy task (b679bc73f) output
remote:  !     make: *** No rule to make target 'predeploy'.  Stop.
=====> End of writebud predeploy task (b679bc73f) output
-----> Checking for release task
       Executing release task from Procfile in ephemeral container: migrate up
=====> Start of writebud release task (d930786ed) output
remote:  !     /bin/bash: line 1: migrate: command not found
=====> End of writebud release task (d930786ed) output
=====> Processing deployment checks
remote:  !     No healthchecks found in app.json for web process type
       No web healthchecks found in app.json. Simple container checks will be performed.
       For more efficient zero downtime deployments, add healthchecks to your app.json. See https://dokku.com/docs/deployment/zero-downtime-deploys/ for examples
-----> Deploying writebud via the docker-local scheduler...
-----> Deploying web (count=1)
       Attempting pre-flight checks (web.1)
-----> Executing 2 healthchecks
       Running healthcheck name='default' type='uptime' uptime=10
       Running healthcheck name='port listening check' attempts=3 port=5000 retries=2 timeout=5 type='listening' wait=5
       Healthcheck succeeded name='port listening check'
       Healthcheck succeeded name='default'
       All checks successful (web.1)
=====> Start of writebud container output (f916cd2215d1 web.1)
       2024/08/18 04:42:31 INFO Listening on http://localhost:5000
=====> End of writebud container output (f916cd2215d1 web.1)
       Scheduling old container shutdown in 60 seconds (web.1)
=====> Triggering early nginx proxy rebuild
-----> Ensuring network configuration is in sync for writebud
-----> Configuring writebud.mat.tm...(using built-in template)
-----> Creating https nginx.conf
       Enabling HSTS (using built-in template)
       Reloading nginx
-----> Deploying release (count=0)
-----> Running post-deploy
-----> Ensuring network configuration is in sync for writebud
-----> Configuring writebud.mat.tm...(using built-in template)
-----> Creating https nginx.conf
       Enabling HSTS (using built-in template)
       Reloading nginx
-----> Renaming containers
       Found previous container(s) (c7e46ce9131b) named writebud.web.1
       Renaming container (c7e46ce9131b) writebud.web.1 to writebud.web.1.1723956172
       Renaming container writebud.web.1.upcoming-8146 (f916cd2215d1) to writebud.web.1
-----> Checking for postdeploy task
       Executing postdeploy task from app.json in ephemeral container: make postdeploy
=====> Start of writebud postdeploy task (cecaab4eb) output
remote:  !     make: *** No rule to make target 'postdeploy'.  Stop.
=====> End of writebud postdeploy task (cecaab4eb) output
-----> Updated schedule file
-----> Shutting down old containers in 60 seconds
=====> Application deployed:
...
```

This feels like a regression, I think I would have noticed this earlier.

**Comment by rome2o** [comment] 2024-08-30 14:21
@josegonzalez  same is the issue here. We are on `dokku version 0.34.8`. Our `release` job from Procfile fails but application continues to deploy.

Is there anything to be done to help you out on this?

**Comment by josegonzalez** [comment] 2024-09-29 02:32
Closing as there is a pull request open.

**Closed by josegonzalez** 2024-09-29 02:32 UTC
Labels: type: bug, needs: investigation, plugin: app-json
