### ISSUE TITLE
Fully qualified domain name being pushed as subdomain

### ISSUE THREAD

**Issue by samholmes1337** [dokku/dokku#2005] opened 2016-03-18 14:05 UTC
I have created a docker image that I am pushing to my dokku server hosted at `example.xyz`. I have set the git remote to `dokku@example.xyz:subdomain.example.xyz`, as I host multiple different primary domains from this server.

However after going through a brief building process it says that the application has been successfully deployed on `http://subdomain.example.xyz.example.xyz`. Was wondering if this was perhaps something to do with the TLD `xyz`?

Running `Dokku 0.4.14`, `Linux example 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`, `Docker 1.10.3`. It is currently being hosted on a 512mb DigitalOcean droplet that was setup through their app system.

**Comment by samholmes1337** [comment] 2016-03-18 15:32
I have been able to reproduce this issue when using a `herokuish` build. The following is the terminal output:

```

**Comment by josegonzalez** [comment] 2016-03-18 15:35
Can you add *all* the information we ask for in our [ISSUE_TEMPLATE.md](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)?

**Comment by samholmes1337** [comment] 2016-03-18 19:30
### uname -a
```
Linux example 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

### free -m
```
             total       used       free     shared    buffers     cached
Mem:           490        468         21          1         33        186
-/+ buffers/cache:        249        240
Swap:            0          0          0
```

### docker version
```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64
```

### docker -D info
```
Containers: 8
 Running: 3
 Paused: 0
 Stopped: 5
Images: 25
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 73
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-77-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 490 MiB
Name: example
ID: 2JNC:3DDT:V2PI:5RTS:6EME:S5EM:OMOX:WDMR:PNT5:53LM:XFJP:VIRH
```

### sigil -v
```
This command wasn't recognised.
```

### docker run -ti gliderlabs/herokuish:latest herokuish version
```
herokuish: 0.3.8
buildpacks:
  heroku-buildpack-clojure   v73
  heroku-buildpack-go        v22
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v19
  heroku-buildpack-java      v42
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v87
  heroku-buildpack-php       v90
  heroku-buildpack-play      v24
  heroku-buildpack-python    v74
  heroku-buildpack-ruby      v141
  heroku-buildpack-scala     v64
  buildpack-nginx            v5
```

### docker version
```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64
```

### dokku plugin
```
plugn: dev
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  letsencrypt          0.7.0 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.4.0 enabled    dokku core logs plugin
  mongo                1.0.0 enabled    dokku mongo service plugin
  named-containers     0.4.0.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin
```

### docker inspect dokku/test.example.xyz
```
[
    {
        "Id": "sha256:0256e7934867ac5aa37859bf48497a4892402fe8e99197121d8542fcb96fb6fe",
        "RepoTags": [
            "dokku/test.example.xyz:latest"
        ],
        "RepoDigests": [],
        "Parent": "sha256:9dc76adf1d37a5bf608419ae8b2327fe3f6f87d7277452b8fde544bd5a5953c2",
        "Comment": "",
        "Created": "2016-03-18T18:56:49.667683363Z",
        "Container": "1dcf8f632579597d457e3cc8def04f40f2e84e281b3db662993af0bdf6a41e2e",
        "ContainerConfig": {
            "Hostname": "1dcf8f632579",
            "Domainname": "",
            "User": "",
            "AttachStdin": true,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": true,
            "StdinOnce": true,
            "Env": [
                "CACHE_PATH=/cache",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/bash",
                "-c",
                "mkdir -p /app/.profile.d \u0026\u0026 cat \u003e /app/.profile.d/00-global-env.sh"
            ],
            "Image": "dokku/test.example.xyz:latest",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "dokku": ""
            },
            "StopSignal": "SIGTERM"
        },
        "DockerVersion": "1.10.1",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "CACHE_PATH=/cache",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/bash",
                "-c",
                "mkdir -p /app/.profile.d \u0026\u0026 cat \u003e /app/.profile.d/00-global-env.sh"
            ],
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "dokku": ""
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 1384201848,
        "VirtualSize": 1384201848,
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        }
    }
]
```

### cat /home/dokku/test.example.xyz/nginx.conf
```
server {
  listen      [::]:80;
  listen      80;
  server_name test.example.xyz.example.xyz ;
  access_log  /var/log/nginx/test.example.xyz-access.log;
  error_log   /var/log/nginx/test.example.xyz-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://test.example.xyz;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/test.example.xyz/nginx.conf.d/*.conf;
}
upstream test.example.xyz {
  server 172.17.0.2:5000;
}
```

### How was Dokku installed?
DigitalOcean preloaded application.


### How reproducible
Very. I deleted the droplet completely and reinstalled it from scratch, the error still occurred.

### Steps to reproduce
1. Create a new DigitalOcean droplet with the Dokku preinstalled app.
2. Configure Dokku with SSH key and virtualhost from browser.
3. Create new directory with basic NodeJS app in.
4. Set `git remote` to `deploy` with remote `dokku@example.xyz:test.example.xyz`
5. Push the code to the server with `git push deploy master -u`
6. The app will deploy to `test.example.xyz.example.xyz`.

### Actual results
The app will deploy to, and be available from, `test.example.xyz`.

### Expected results
The app is deploy to, and available from, `test.example.xyz.example.xyz`.

### Additional info
For the sake of personal information, I have replaced all instances of the actual `.xyz` hostname with `example`.

**Comment by josegonzalez** [comment] 2016-03-18 19:42
Can you gist the output of a deploy?

/cc @michaelshobbs since you've worked on the nginx side quite a bit so may have more knowledge on how this should work.

**Comment by samholmes1337** [comment] 2016-03-18 22:23
Of course 😊 You can find the output [here](https://gist.github.com/samholmes1337/0088890b894817e673e5). It's really odd behaviour, I've had a look over some of the source but I can't figure out why this is happening.

**Comment by michaelshobbs** [comment] 2016-03-18 23:42
The default logic for app domain config can be found here: https://github.com/dokku/dokku/blob/v0.4.14/plugins/domains/commands#L23-L55

What are the contents of `/home/dokku/VHOST` and `/home/dokku/test.example.xyz//VHOST`?

**Comment by samholmes1337** [comment] 2016-03-18 23:55
The content of `/home/dokku/VHOST` is simply `example.xyz`, and `/home/dokku/test.example.xyz/VHOST` contains `test.example.xyz.example.xyz`.

**Comment by michaelshobbs** [comment] 2016-03-18 23:56
So the easy answer is rename your app to `test`

**Comment by samholmes1337** [comment] 2016-03-18 23:57
Ah yes, but I'm hosting multiple different domains (`example.xyz` and `domain.com`) from this server. Otherwise I would.

**Comment by michaelshobbs** [comment] 2016-03-19 00:01
Please gist a deploy with dokku trace on. Make sure to scrub any secrets from that output.

**Comment by michaelshobbs** [comment] 2016-03-19 00:04
I was able to reproduce this locally. @josegonzalez what is the expected behavior here?

**Comment by michaelshobbs** [comment] 2016-03-19 00:05
notes:

```
root@dokku:~# dokku apps
=====> My Apps
node-js-app.dokku.me
root@dokku:~# cat /home/dokku/VHOST
dokku.me
```

deploy:
```
-----> Creating new /home/dokku/node-js-app.dokku.me/VHOST...
-----> Setting config vars
       DOKKU_NGINX_PORT: 80
-----> Configuring node-js-app.dokku.me.dokku.me...(using built-in template)
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Setting config vars
       DOKKU_APP_RESTORE: 1
=====> Application deployed:
       http://node-js-app.dokku.me.dokku.me
```

**Comment by michaelshobbs** [comment] 2016-03-19 00:08
Interesting. This works as I would expect it if the app's name is a FQDN and doesn't match the VHOST
```
-----> Configuring node-js-app.dokku2.me...(using built-in template)
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Setting config vars
       DOKKU_APP_RESTORE: 1
=====> Application deployed:
       http://node-js-app.dokku2.me
```

**Comment by samholmes1337** [comment] 2016-03-19 00:13
@michaelshobbs Huh, that's interesting. I just attempted deploying a FQDN (`test.domain.com`) that didn't match the default VHOST (`example.xyz`) and experienced the correct behaviour, same as you.

I'll have the dokku trace output with you shortly, it's a large amount of output to prune so may take me a few minutes!

**Comment by josegonzalez** [comment] 2016-03-19 00:17
Not sure what the expected result is. What do we have in our documentation as the expected?

**Comment by samholmes1337** [comment] 2016-03-19 00:19
Here is the [pruned output](https://gist.github.com/samholmes1337/2fa007c8b7678bc0c0c7) of deploying using `git push deploy master` where the deploy remote is `dokku@example.xyz:test.example.xyz` and the default `/home/dokku/VHOST` is `example.xyz`. Fair warning: it's over 10,000 lines long- but you probably anticipated that.

**Comment by michaelshobbs** [comment] 2016-03-19 00:26
The code below is prepending the app name to the VHOST because SUBDOMAIN doesn't match APP. Need to dig into what that bashfu is doing for subdomain.

Here is the code in master (same as 0.4.14)
```
      local SUBDOMAIN=${APP/%\.${VHOST}/}
      local hostname=$(: | plugn trigger nginx-hostname "$APP" "$SUBDOMAIN" "$VHOST")
      if [[ ! -n $hostname ]]; then
        if [[ "$APP" == *.* ]] && [[ "$SUBDOMAIN" == "$APP" ]]; then
          local hostname="${APP/\//-}"
        else
          local hostname="${APP/\//-}.$VHOST"
        fi
      fi
      local DEFAULT_VHOST="$hostname"
```



matching subdomain trace
```
remote: +++ get_global_vhost
remote: +++ declare 'desc=return global vhost'
remote: +++ local GLOBAL_VHOST_FILE=/home/dokku/VHOST
remote: +++ [[ -f /home/dokku/VHOST ]]
remote: +++ local GLOBAL_VHOST=dokku.me
remote: +++ echo dokku.me
remote: ++ local VHOST=dokku.me
remote: ++ [[ dokku.me =~ ([0-9]{1,3}[\.]){3}[0-9]{1,3}$ ]]
remote: ++ [[ dokku.me =~ ([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe08:(:[0-9a-fA-F]{1,4}){2,2}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}([0-9]{1,3}[\.]){3}[0-9]{1,3}|([0-9a-fA-F]{1,4}:){1,4}:([0-9]{1,3}[\.]){3}[0-9]{1,3}$ ]]
remote: ++ local SUBDOMAIN=node-js-app
remote: +++ :
remote: +++ plugn trigger nginx-hostname node-js-app.dokku.me node-js-app dokku.me
remote: + source /var/lib/dokku/core-plugins/available/common/functions
remote: ++ set -eo pipefail
remote: ++ [[ -n 1 ]]
remote: ++ set -x
remote: + [[ ! -n '' ]]
remote: ++ local hostname=
remote: ++ [[ ! -n '' ]]
remote: ++ [[ node-js-app.dokku.me == *.* ]]
remote: ++ [[ node-js-app == \n\o\d\e\-\j\s\-\a\p\p\.\d\o\k\k\u\.\m\e ]]
remote: ++ local hostname=node-js-app.dokku.me.dokku.me
remote: ++ local DEFAULT_VHOST=node-js-app.dokku.me.dokku.me
remote: ++ echo node-js-app.dokku.me.dokku.me
remote: + local DEFAULT_VHOST=node-js-app.dokku.me.dokku.me
```

non-matching subdomain
```
remote: +++ get_global_vhost
remote: +++ declare 'desc=return global vhost'
remote: +++ local GLOBAL_VHOST_FILE=/home/dokku/VHOST
remote: +++ [[ -f /home/dokku/VHOST ]]
remote: +++ local GLOBAL_VHOST=dokku.me
remote: +++ echo dokku.me
remote: ++ local VHOST=dokku.me
remote: ++ [[ dokku.me =~ ([0-9]{1,3}[\.]){3}[0-9]{1,3}$ ]]
remote: ++ [[ dokku.me =~ ([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe08:(:[0-9a-fA-F]{1,4}){2,2}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}([0-9]{1,3}[\.]){3}[0-9]{1,3}|([0-9a-fA-F]{1,4}:){1,4}:([0-9]{1,3}[\.]){3}[0-9]{1,3}$ ]]
remote: ++ local SUBDOMAIN=node-js-app.dokku2.me
remote: +++ :
remote: +++ plugn trigger nginx-hostname node-js-app.dokku2.me node-js-app.dokku2.me dokku.me
remote: + source /var/lib/dokku/core-plugins/available/common/functions
remote: ++ set -eo pipefail
remote: ++ [[ -n 1 ]]
remote: ++ set -x
remote: + [[ ! -n '' ]]
remote: ++ local hostname=
remote: ++ [[ ! -n '' ]]
remote: ++ [[ node-js-app.dokku2.me == *.* ]]
remote: ++ [[ node-js-app.dokku2.me == \n\o\d\e\-\j\s\-\a\p\p\.\d\o\k\k\u\2\.\m\e ]]
remote: ++ local hostname=node-js-app.dokku2.me
remote: ++ local DEFAULT_VHOST=node-js-app.dokku2.me
remote: ++ echo node-js-app.dokku2.me
remote: + local DEFAULT_VHOST=node-js-app.dokku2.me
```

**Comment by michaelshobbs** [comment] 2016-03-19 00:27
@josegonzalez to your question: http://dokku.viewdocs.io/dokku/nginx/#customizing-hostnames

what does that mean though?

**Comment by michaelshobbs** [comment] 2016-03-19 00:28
@samholmes1337 if I were you, i'd name your add something else that works for your naming scheme and use `domains:add` to put the correct domain name on the app. This, unfortunately, won't be fixed in `0.4.x`

**Comment by michaelshobbs** [comment] 2016-03-19 01:03
AFAICT this is actually how it's supposed to work. @josegonzalez let me know if we want to change this behavior but the workflow I mentioned should be sufficiently functional at least for now.

**Comment by samholmes1337** [comment] 2016-03-19 01:10
Thanks for the help @michaelshobbs, I will modify my workflow to use `domains:add`. I'm curious, what purpose does the default `VHOST` serve if I'll only be using fully qualified domain names for deployment? As in, can I just remove the content from `/home/dokku/VHOST` so that there's no clash that would exhibit this behaviour?

And just to add to that, this seems like odd default behaviour. I can't think of a reason why using a FQDN should ever be interpreted as a subdomain, even if it matches the default `VHOST` for the server.

**Comment by michaelshobbs** [comment] 2016-03-19 01:16
In my environments I pre populate `/home/dokku/APP/VHOST` with the domain name I want and name my app the same. 

By default the top level VHOST is meant to serve as a TLD for your apps. Let's say you have `example.com` as your top level or global VHOST and you have two apps names `www.dev` and `www.staging`. Then by default dokku would set the domains for those apps as `www.dev.example.com` and `www.staging.example.com` respectively.

**Comment by michaelshobbs** [comment] 2016-03-19 01:22
Crap wrong button. Totally deleted my last comment. Anywho.

In my environments I pre-populate `/home/dokku/APP/VHOST` with the domain name I want and I also name my app the same. 

By default, dokku uses `/home/dokku/VHOST` as a TLD for all apps on a host. For example, let's say you have three apps named `www.dev`, `www.staging` and `www`.
Additionally you have `example.com` in `/home/dokku/VHOST`. By default you would end up with domains on those apps thusly, `www.dev.example.com`, `www.staging.example.com` and `www.example.com` respectively.

**Comment by samholmes1337** [comment] 2016-03-19 01:35
That is incredibly helpful information, thank you! It also makes sense looking at the [default domain config logic](https://github.com/dokku/dokku/blob/v0.4.14/plugins/domains/commands#L23-L55). I'm going to give changing the behaviour for my installation a shot and see if I can get a FQDN that matches the default VHOST to remain nominal.

It does seem odd that this behaviour would be intentionally default. Having said that, regardless of whether this behaviour ends up being changed or not, should some info about it be added to the docs?

**Comment by michaelshobbs** [comment] 2016-03-19 01:38
It is documented here but if you think it can be made clearer feel free to open a doc update PR. 

http://dokku.viewdocs.io/dokku/nginx/#customizing-hostnames

**Comment by josegonzalez** [comment] 2016-03-19 06:48
@michaelshobbs do we want to just always prepend to the domain.tld? That might simplify docs and the implementation, and make it easier to understand what *will* happen.

**Comment by samholmes1337** [comment] 2016-03-19 11:44
I'm a huge fan of the ability to push a FQDN and have it resolve successfully with no additional configuration required (notably, in the case of the root/primary vhost). Perhaps make it a configurable option needs must, but the current behaviour would be preferable to no FQDN on push at all. Just my $0.02.

**Comment by michaelshobbs** [comment] 2016-03-19 14:01
@josegonzalez I prefer the current functionality personally.

**Comment by josegonzalez** [comment] 2016-03-19 19:49
Hmmm okay. Should we just always assume a `.` with a valid tld is a domain push then?

**Comment by michaelshobbs** [comment] 2016-03-19 20:00
No. That would change the current functionality

**Comment by josegonzalez** [comment] 2016-03-19 22:09
I know it would, I'm asking if we should do it given the (partial) ability to do so now, as I'd rather it be consistent one way or the other.

**Comment by michaelshobbs** [comment] 2016-03-19 22:25
As I said, I prefer the functionality as it stands today. To me, it's not a question of consistency as much as functionality. See my previous comment referring to `example.com` and multiple apps.

**Comment by josegonzalez** [comment] 2016-03-19 22:33
Fair enough, so this can be closed then.

**Comment by michaelshobbs** [comment] 2016-03-19 22:44
I believe so.

**Closed by michaelshobbs** 2016-03-19 22:44 UTC
Labels: status: needs more info, type: support

**Comment by samholmes1337** [comment] 2016-07-06 14:09
Just to revisit this briefly, I actually think we've been talking about [partially qualified domain names](https://en.wikipedia.org/wiki/Fully_qualified_domain_name#Partially_qualified_domain_name) instead of fully qualified domain names (ones that are absolutely terminated with a period). If a FQDN is pushed (as in, one terminated with a period to signify the DNS root), then could that be treated as absolute regardless?

**Comment by josegonzalez** [comment] 2016-07-06 15:56
That works for me. Assuming @michaelshobbs is on board, I'd welcome a PR.

**Comment by samholmes1337** [comment] 2016-07-06 15:58
Glad to hear it, I'll get working on one!
