### ISSUE TITLE
App image not found

### ISSUE THREAD

**Issue by dalou** [dokku/dokku#2208] opened 2016-05-23 08:12 UTC
Hello,

Sometime the app lost the image with no apparently reason

Example:

```
> dokku config:set MY_CONFIG_NAME=0
-----> Setting config vars
       MY_CONFIG_NAME: 0
-----> Restarting app my_app_name
-----> Releasing my_app_name (dokku/my_app_name:latest)...
app image (dokku/my_app_name:herokuish) not found
Releasing image source type my_app_name not supported!
```

**Comment by josegonzalez** [comment] 2016-05-23 17:20
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by dalou** [comment] 2016-05-23 20:16
sorry but i don't have no more information, that's happening with no reason.
with a push it's work : 
```
git push dokku master
Décompte des objets: 6, fait.
Delta compression using up to 8 threads.
Compression des objets: 100% (6/6), fait.
Écriture des objets: 100% (6/6), 504 bytes | 0 bytes/s, fait.
Total 6 (delta 5), reused 0 (delta 0)
-----> Cleaning up...
-----> Building my_app_name from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Python app detected
-----> Noticed cffi. Bootstrapping libffi.
       $ pip install -r requirements.txt

[... etc ...]

Reloading nginx
-----> Setting config vars
       DOKKU_APP_RESTORE: 1
-----> Shutting down old containers in 60 seconds
=====> f30f628ff6ab3e7b837bb503711ac8064a82bbe969c5e04ece2217455f214856
=====> Application deployed:
       http://www.my_app.fr

To dokku@host:my_app_name
   edc023f..c161bf4  master -> master
```
just after i try to change config like this for example:
```
dokku config:set COMPRESS_ENABLED=1                                                                                 
-----> Setting config vars
       COMPRESS_ENABLED: 1
-----> Restarting app my_app_name
-----> Releasing ittek (dokku/my_app_name:latest)...
app image (dokku/my_app_name:herokuish) not found
Releasing image source type my_app_name not supported!
```

the problem appear with no reason, it's worked well before yesterday

**Comment by josegonzalez** [comment] 2016-05-23 20:16
You need to fill out our issue template before I can help you.

**Comment by dalou** [comment] 2016-05-23 20:18
what do you need exactly ?

**Comment by josegonzalez** [comment] 2016-05-23 20:20
All of the information we ask for in the [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md).

**Comment by dalou** [comment] 2016-05-23 20:23
oh i just find an issue information.
Currently i use the dokku script (alias dokku='$HOME/.dokku/contrib/dokku_client.sh' ), with this result : 
```
> dokku config:set COMPRESS_ENABLED=1                                                                                  
-----> Setting config vars
       COMPRESS_ENABLED: 1
-----> Restarting app my_app_name
-----> Releasing ittek (dokku/my_app_name:latest)...
app image (dokku/my_app_name:herokuish) not found
Releasing image source type my_app_name not supported!

```

but i just try with another dokku toolbet (in ruby i think) with this result : 
```
> dt config:set COMPRESS_ENABLED=1                                                                                   
-----> Setting config vars
       COMPRESS_ENABLED: 1
-----> Restarting app my_app_name
-----> Releasing ittek (dokku/my_app_name:latest)...
-----> Deploying ittek (dokku/my_app_name:latest)...
-----> Attempting to run scripts.dokku.predeploy from app.json (if defined)
-----> App Procfile file found (/home/dokku/my_app_name/DOKKU_PROCFILE)
-----> DOKKU_SCALE file found (/home/dokku/my_app_name/DOKKU_SCALE)
=====> web=1
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
-----> Default container check successful!
-----> Running post-deploy
-----> Attempting to run scripts.dokku.postdeploy from app.json (if defined)
-----> Found previous container(s) (8ff2a82e575a) named my_app_name.web.1
=====> renaming container (8ff2a82e575a) my_app_name.web.1 to my_app_name.web.1.1464034795
=====> renaming container (8b622ab8db9f) admiring_noether to my_app_name.web.1
-----> Overriding default nginx.conf with detected nginx.conf.sigil
-----> Configuring www.my_app.fr...(using app-supplied template)
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Setting config vars
       DOKKU_APP_RESTORE: 1
-----> Shutting down old containers in 60 seconds
=====> 8ff2a82e575a1615183cfc59967aa21207ba55c51ab4af37c195604043861203
=====> Application deployed:
       http://www.my_app.fr

Connection to host closed.
```

**Comment by dalou** [comment] 2016-05-23 20:26
Sorry for the mistake, the template is: 

root@www:~# uname -a
Linux www 3.19.0-51-generic #57~14.04.1-Ubuntu SMP Fri Feb 19 14:36:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@www:~# free -m
             total       used       free     shared    buffers     cached
Mem:          3952       3364        587        157        290       2199
-/+ buffers/cache:        874       3077
Swap:         4095        120       3975
root@www:~# docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
root@www:~# docker -D info
Containers: 15
 Running: 5
 Paused: 0
 Stopped: 10
Images: 28
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 113
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.0-51-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.86 GiB
Name: www
ID: WLG7:GG4G:CT7N:MOVY:S5QS:RNJO:ZNGK:ZEYM:47V7:L5WR:MMNO:VE3Q
Docker Root Dir: /var/lib/docker
Debug mode (client): true
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
root@www:~# sigil -v
0.4.0
root@www:~# docker run -ti gliderlabs/herokuish:latest herokuish version
herokuish: 0.3.12
buildpacks:
  emberjs.tgz                latest
  buildpack-nginx            v5
  heroku-buildpack-clojure   v75
  heroku-buildpack-erlang    fa17af9
  heroku-buildpack-go        v34
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v20
  heroku-buildpack-java      v44
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v90
  heroku-buildpack-php       v101
  heroku-buildpack-play      v26
  heroku-buildpack-python    v80
  heroku-buildpack-ruby      v146
  heroku-buildpack-scala     v70
root@www:~# dokku version
0.5.6
root@www:~# dokku plugin
plugn: dev
  00_dokku-standard    0.5.6 enabled    dokku core standard plugin
  20_events            0.5.6 enabled    dokku core events logging plugin
  apps                 0.5.6 enabled    dokku core apps plugin
  build-env            0.5.6 enabled    dokku core build-env plugin
  certs                0.5.6 enabled    dokku core certificate management plugin
  checks               0.5.6 enabled    dokku core checks plugin
  common               0.5.6 enabled    dokku core common plugin
  config               0.5.6 enabled    dokku core config plugin
  docker-options       0.5.6 enabled    dokku core docker-options plugin
  domains              0.5.6 enabled    dokku core domains plugin
  enter                0.5.6 enabled    dokku core enter plugin
  git                  0.5.6 enabled    dokku core git plugin
  logs                 0.5.6 enabled    dokku core logs plugin
  memcached            1.0.0 enabled    dokku memcached service plugin
  named-containers     0.5.6 enabled    dokku core named containers plugin
  nginx-vhosts         0.5.6 enabled    dokku core nginx-vhosts plugin
  plugin               0.5.6 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.5.6 enabled    dokku core proxy plugin
  ps                   0.5.6 enabled    dokku core ps plugin
  redis                1.0.0 enabled    dokku redis service plugin
  shell                0.5.6 enabled    dokku core shell plugin
  storage              0.5.6 enabled    dokku core storage plugin
  tags                 0.5.6 enabled    dokku core tags plugin
  tar                  0.5.6 enabled    dokku core tar plugin

**Comment by josegonzalez** [comment] 2016-05-23 20:27
Duplicate of #2166. We handle `--app` incorrectly and we need to fix a few places where dokku calls itself internally. I'll have that fixed up for the next release (should be soon).

For now, the workaround is to run the `dokku` command on the server. Sorry.

**Closed by josegonzalez** 2016-05-23 20:27 UTC

**Comment by dalou** [comment] 2016-05-23 20:31
no problem, it's not a terrible bug in fact :) i was affraid about real image loss.
about the dt ruby plugin an antoher bug that dokku don't have is the tty input problematic.
dokku run bash : OK
dt run bash : KO (tty input doesn't work, because of ruby subcall program)

**Comment by josegonzalez** [comment] 2016-05-23 20:32
Yep, though thats not our gem, so we cannot offer support on it.

**Comment by dalou** [comment] 2016-05-23 20:33
yes i know, great job about dokku, i love that.

**Comment by MouadCh** [comment] 2021-02-25 15:22
This Error is due to heroku restarting after non activity. so when it restart, it deletes all files uploaded in app so you have to re-upload those files

**Comment by josegonzalez** [comment] 2021-02-25 20:42
@MouadCh please do not comment on a 5 year old issue - we're also not heroku so your comment doesn't apply here.
