### ISSUE TITLE
dokku:config seems to replace newlines with spaces

### ISSUE THREAD

**Issue by alexgleason** [dokku/dokku#2189] opened 2016-05-13 04:54 UTC
I'm trying to use a SSH private key file as a dokku configuration variable. This is probably wrong to begin with, so any suggestions on how to do this better would be helpful. I need load the contents of the file in Python, but it can't be synced with the repo (needs to be private).

Anyway, right now I'm using:
```
dokku config:set myapp PRIVATE_KEY=$'-----BEGIN PRIVATE KEY-----\nabcdefg...
```

There are newlines (`\n`) throughout, which dokku:config seems to ultimately convert to spaces. The formatting of this file is important, so I can't have it that way.

I've hacked around this by replacing all instances of `\n` with `\\n` then using a string replace in Python to replace `\\n` with `\n`, thereby creating the newlines.

Ideally Dokku would let me use newline characters directly in the config.

**Comment by michaelshobbs** [comment] 2016-05-13 05:00
Closing as duplicate of #1262. We'd definitely love a PR to address this.

**Closed** 2016-05-13 05:00 UTC
Labels: status: duplicate
