### ISSUE TITLE
.env file in the app folder was completely overridden

### ISSUE THREAD

**Issue by AndreyKomin** [dokku/dokku#4996] opened 2022-01-10 23:27 UTC
Hi guys. 
Just updated Dokku up to the last 0.26 version.
The problem I face is: 
1) I got my .env file in a root project folder
2) Then I deploy to server and see that .env file was not merged but completely overridden by dokku

Worked perfectly, at least in 0.17 and 0.24 (seemed like) versions

**Comment by josegonzalez** [comment] 2022-01-18 06:23
Duplicate of #4894. I'll look there.

**Closed by josegonzalez** 2022-01-18 06:23 UTC
