### ISSUE TITLE
504 Gateway Time-out error in nginx due to errors in iptable rules

### ISSUE THREAD

**Issue by rssc** [dokku/dokku#1456] opened 2015-09-10 18:34 UTC
I am getting 504 Gateaway Time-out errors from nginx after deploying an app in dokku, and I've narrowed it down to a problem in iptables. I vaguely remember having similar problems before, which eventually disappeared, but just now I updated dokku and now I am having this problem again.
I am unsure whether this is a problem of dokku, or of docker.

After deploying the app (with the redis plugin enabled for the app), I get the following (redacted) iptables:

```
# Generated by iptables-save v1.4.21 on Thu Sep 10 20:21:47 2015
*nat
:PREROUTING ACCEPT [156:10009]
:INPUT ACCEPT [15:864]
:OUTPUT ACCEPT [67:4660]
:POSTROUTING ACCEPT [70:4840]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
COMMIT
# Completed on Thu Sep 10 20:21:47 2015
# Generated by iptables-save v1.4.21 on Thu Sep 10 20:21:47 2015
*filter
:INPUT DROP [18:1384]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [500:99688]
:DOCKER - [0:0]
... some rules related to ssh ...
-A INPUT -p icmp -m icmp --icmp-type 8 -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -i eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A DOCKER -s 172.17.0.42/32 -d 172.17.0.39/32 -i docker0 -o docker0 -p tcp -m tcp --dport 6379 -j ACCEPT
-A DOCKER -s 172.17.0.39/32 -d 172.17.0.42/32 -i docker0 -o docker0 -p tcp -m tcp --sport 6379 -j ACCEPT
COMMIT
# Completed on Thu Sep 10 20:21:47 2015
```

You can see the rules presumably generated by the redis plugin, but there is no rule to allow access to port 5000 of the app container (IP 172.17.0.42). It seems that some rule like `-A INPUT -i docker0 -j ACCEPT`is missing (although I am not an expert in iptables).

Anybody experienced similar problems and knows where this problem is coming from, and why it is showing up?

**Comment by josegonzalez** [comment] 2015-09-15 18:24
I've never seen this issue, @michaelshobbs have you?

@rssc were you able to figure out any more details? Maybe include deploy output with `dokku trace on`?

**Comment by michaelshobbs** [comment] 2015-09-15 18:32
nope. please provide the information requested here and we'll see if we can help: https://github.com/progrium/dokku/blob/master/CONTRIBUTING.md#reporting-other-issues

**Comment by rssc** [comment] 2015-09-15 19:24
**Description of problem:** Dokku app is unreachable for nginx after deployment due to incorrect iptables configuration.

**Output of the following commands**

- `dokku version`: v0.3.26-128-g1b5756c
- `dokku plugins`:
/var/lib/dokku/plugins/00_dokku-standard/
/var/lib/dokku/plugins/20_events/
/var/lib/dokku/plugins/apps/
/var/lib/dokku/plugins/backup/
/var/lib/dokku/plugins/build-env/
/var/lib/dokku/plugins/certs/
/var/lib/dokku/plugins/checks/
/var/lib/dokku/plugins/common/
/var/lib/dokku/plugins/config/
/var/lib/dokku/plugins/debug/
/var/lib/dokku/plugins/docker-options/
/var/lib/dokku/plugins/dokku-name/
/var/lib/dokku/plugins/dokku-shoreman/
/var/lib/dokku/plugins/domains/
/var/lib/dokku/plugins/enter/
/var/lib/dokku/plugins/git/
/var/lib/dokku/plugins/link/
/var/lib/dokku/plugins/maintenance/
/var/lib/dokku/plugins/nginx-vhosts/
/var/lib/dokku/plugins/ps/
/var/lib/dokku/plugins/psql-sc/
/var/lib/dokku/plugins/rebuild/
/var/lib/dokku/plugins/redis/
/var/lib/dokku/plugins/shell/
/var/lib/dokku/plugins/tags/
/var/lib/dokku/plugins/tar/

- `docker version`:
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

- `docker info`:
Containers: 12
Images: 77
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 103
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 490 MiB
Name: xxx.yyy.zz
ID: BP4G:KONK:ZIKJ:R72B:QGJ2:JBCP:WKI2:HPPW:X44B:CW6F:IUTN:BRV6
WARNING: No swap limit support

- `uname -a`:
Linux xxx.yyy.zz 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

- `cat /home/dokku/<app>/nginx.conf` (if applicable): no changes to default

- Output of failing dokku commands with `dokku trace on`: command does not fail

**Environment details (AWS, VirtualBox, physical, etc.):** DigitalOcean VPS

**How was dokku installed?:** from source (I thought I had upgraded it to the package, but I can't see it in "dpkg -l")

**Steps to Reproduce:** Deploy or rebuild app. App starts up correctly, but is inaccessible through nginx, as iptables does not allow access to the docker container hosting the app. Manually adding rule "iptables -A INPUT -i docker0 -j ACCEPT" fixes the problem. 

**Additional info:** Deploying the app with `dokku trace on` does not give any hint of any problem, although I have no idea what I would be looking for. It certainly does not mention anything about iptables. So I would assume docker is responsible for updating iptables?
If you could let me know what I would be looking for in the trace I can provide more information.

**Comment by michaelshobbs** [comment] 2015-09-15 19:49
Thank you for doing that. To be frank, I have not seen the iptables issue specifically. So we're going to need to gather some more info here to rule out other causes.

Please include a gist of the following 
- output of a deployment with dokku trace on
- the contents of your app's nginx config (after that deployment)
- the output of `ps -ef | grep nginx` (after that deployment) 

I have seen nginx not reload cleanly and want to make that's the case here.

**Comment by josegonzalez** [comment] 2015-09-23 02:39
@rssc any luck with the requests by @michaelshobbs ?

**Comment by rssc** [comment] 2015-09-23 20:37
Sorry for the delay in getting back on this. Please find the requested information below.

Gist of deployment with dokku trace on:
https://gist.github.com/anonymous/2e57f45c9232071f2499

Gist of app's nginx config file:
https://gist.github.com/rssc/0328343cddb81da693d6

Output of `ps -ef | grep nginx`:
```
root       778     1  0 Sep10 ?        00:00:00 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
root     16272 14187  0 22:34 pts/0    00:00:00 grep --color=auto nginx
www-data 30467   778  0 Sep15 ?        00:00:00 nginx: worker process      
```

Note: I replaced the actual domain with "xyz" in the gists.

**Comment by michaelshobbs** [comment] 2015-09-30 16:25
@rssc thanks for putting the info together. that definitely rules out my hope for a simple resolution. as i cannot reproduce the issue, i'm not sure where to go from here.

out of curiosity, can you start up a standard docker container with a listener of some sort and access that? i'm wondering if maybe there is a docker setting we're not seeing here.

**Comment by josegonzalez** [comment] 2015-10-13 23:20
@rssc bump

**Comment by josegonzalez** [comment] 2015-10-25 20:22
*bump*

**Comment by rssc** [comment] 2015-10-25 21:24
Right. I am not entirely sure what exactly I am supposed to test, but here is what I found:

When I start a new container using the command line `docker run -ti -p 8888:5000 ubuntu bash` and start a netcat instance with `nc -l 5000`, then I can only connect to it (using `telnet 127.0.0.1 8888` on the host) if I have the iptables rule that allows traffic on the docker interface (i.e., `iptables -A INPUT -i docker0 -j ACCEPT`). Likewise, if I check the IP address within the docker container (something in the range of 172.17.x.x), then I can only ping it from the host if that rule exists.

My understanding is that if the default policy of the INPUT chain in iptables is DROP, then unless the rule allowing traffic on the docker0 interface is there, no traffic will be going to any docker container. So I suppose the question is whether docker should add that rule (maybe it did, and I inadvertently removed it before?), or whether that is something that the administrator should add at some point.

I just checked docker running on my local machine, and there isn't any explicit rule allowing traffic on the docker0 interface in the INPUT chain, but my default policy locally is ACCEPT, so it's not an issue. As soon as I would change that to DROP, I presume I would have exactly the same problem on my local machine. So in the end this is rather an issue with docker?

In any case, thanks for your help so far.

**Comment by josegonzalez** [comment] 2015-10-25 21:30
How are you managing this instance? Is it a custom installation where you are perhaps changing iptables config automatically via something like chef or puppet?

**Comment by rssc** [comment] 2015-10-25 21:34
The server in question doesn't use anything like chef or puppet, it's the DigitalOcean dokku image. The only thing that might interfere with iptables is the `iptables-persistent` package.

**Comment by josegonzalez** [comment] 2015-10-25 21:36
Can you try another dokku instance without that package installed and see if you can replicate it? I *think* docker is meant to handle iptables on it's own. Might be worth seeing what the docker folks say as well...

**Comment by josegonzalez** [comment] 2015-11-13 22:04
*bump*

**Comment by josegonzalez** [comment] 2015-12-31 10:55
Closing as there hasn't been an update in a few months. Please comment with more information if possible.

**Closed by josegonzalez** 2015-12-31 10:55 UTC
Labels: needs more info
