### ISSUE TITLE
Option to disable ANSI sequences

### ISSUE THREAD

**Issue by OmgImAlexis** [dokku/dokku#2644] opened 2017-03-07 03:27 UTC
When pushing to dokku using an env that doesn't support ANSI sequences the output you get is garbled with extra chars being added. This is really a problem in things like Travis-CI where they refuse to fix the "issue" on their end instead stating the user should fix it.

Ref: https://github.com/travis-ci/travis-ci/issues/7284, https://github.com/travis-ci/travis-ci/issues/1951

**Comment by josegonzalez** [comment] 2017-03-07 03:37
They are output here: https://github.com/dokku/dokku/search?utf8=%E2%9C%93&q=%5Ce%5B1G

You may want to figure out why we have that in the first place. I don't really mind removing it/making it optional, just need to know what the purpose is before we do anything.

**Comment by OmgImAlexis** [comment] 2017-03-07 04:10
The reason you guys use it is to push the `---->` over [like this](https://coderwall.com/p/gvevca/pretty-output-from-remote-git).

**Comment by michaelshobbs** [comment] 2017-03-07 04:13
For the record, it's been in there since day 1.

**Comment by josegonzalez** [comment] 2017-03-07 04:49
We could probably detect the `CI` env var and just skip pushing things over. Thoughts, @michaelshobbs ?

**Comment by michaelshobbs** [comment] 2017-03-07 06:02
Seems silly to let CI bleed further into the runtime. Not really sure what the problem is here. We test on CircleCI without an issue. Maybe move your project over to them. (He says glibly 😉)

Unless there's some real pain, I'm :-1: on a change here.

**Comment by OmgImAlexis** [comment] 2017-03-07 06:18
@michaelshobbs instead of detecting like @josegonzalez has suggested I'd rather see an option in dokku's server settings to just disable "pretty output" either for all or certain IP addresses. That way I could just load in all of the travis IPs and be done with it.

**Comment by josegonzalez** [comment] 2017-03-07 06:19
I would certainly not do it for a "certain ip". In either case, it's a bit overkill to try and detect things...

Maybe we just add an option to turn it on/off? If this user wants their CI to have the proper output, they can just globally turn it on or off. That seems reasonable to me...

**Comment by weyert** [comment] 2017-04-19 02:15
How would such an option be implemented? By checking if a file exists in the dokku app directory, if it exists don't do the ` | sed -u "s/^/"$'\e[1G'"/"` bits?

**Comment by josegonzalez** [comment] 2017-04-19 02:20
For now it should be a global config option only. DOKKU_DISABLE_ANSI_PREFIX_REMOVAL?

Long term we need a way of referencing global/app dokku config that isn't stored with regular config. I hope we do that before a 1.0, at which point we can break all the naming into something sensible.

**Comment by josegonzalez** [comment] 2017-04-19 02:21
And yeah, if it's set, maybe we change the default call to a noop?

**Comment by josegonzalez** [comment] 2017-07-15 06:00
Thinking about this further, maybe we should just remove the regex completely? I think its pretty silly of us to have it all over the place, and we can let other tooling that lives on top of dokku figure out if they want it or not.

Thoughts @michaelshobbs ?

**Comment by josegonzalez** [comment] 2018-02-19 20:10
Closing as there is a pull request open.

**Closed by josegonzalez** 2018-02-19 20:10 UTC
Labels: difficulty: easy, hacktoberfest, type: enhancement
