### ISSUE TITLE
dokku logs with vector-sink does not accept plus sign

### ISSUE THREAD

**Issue by CleitonDeLima** [dokku/dokku#5502] opened 2022-12-01 18:23 UTC
### Description of problem

To configure the Cloudwatch logs, you need to inform the aws keys.
My **secret_access_key** has a plus sign, even informing the sign code the configuration ends up being wrong.

### Steps to reproduce

Assuming my keys are these:
- **access_key_id**=KSDSIDJSAJD
- **secret_access_key**=2932JSDJ+KSDSDJ

I replace the plus sign with the code [`%2B`](https://www.fileformat.info/info/unicode/char/002b/index.htm).

```sh
dokku logs:set erp vector-sink "aws_cloudwatch_logs://?create_missing_group=true&create_missing_stream=true&group_name=groupname&encoding[codec]=json&region=sa-east-1&stream_name={{ host }}&auth[access_key_id]=KSDSIDJSAJD&auth[secret_access_key]=2932JSDJ%2BKSDSDJ"
```

The _/var/lib/dokku/data/logs/vector.json_ configuration looks like this.
```json
{
  "sources": {
    "docker-source:erp": {
      "type": "docker_logs",
      "include_labels": [
        "com.dokku.app-name=erp"
      ]
    }
  },
  "sinks": {
    "docker-sink:erp": {
      "auth": {
        "access_key_id": "KSDSIDJSAJD",
        "secret_access_key": "2932JSDJ KSDSDJ"
      },
      "create_missing_group": true,
      "create_missing_stream": true,
      "encoding": {
        "codec": "json"
      },
      "group_name": "groupname",
      "inputs": [
        "docker-source:erp"
      ],
      "region": "sa-east-1",
      "stream_name": "{{ host }}",
      "type": "aws_cloudwatch_logs"
    }
  }
}
```

### dokku report $APP_NAME

(out of context)

**Comment by josegonzalez** [comment] 2022-12-01 18:40
I think we need a hack for it like this: https://github.com/dokku/dokku/commit/0997fd33471c3cab8bf989c37eb9713fbeeb031d#diff-5b65f8e5ccbe63f491c30e3d82fac38921a0ccb4321f5ab2e894dfa608ef7df5R221

For the following unicode character: https://www.fileformat.info/info/unicode/char/002b/index.htm

**Comment by josegonzalez** [comment] 2022-12-04 20:41
Closing as there is a pull request open.

**Comment by CleitonDeLima** [comment] 2022-12-08 21:22
@josegonzalez 

Could you do a test with my example above? I updated the dokku version to 0.29 but it didn't work.

**Comment by josegonzalez** [comment] 2022-12-08 21:24
I'll reopen since I didn't do a test for your exact use case.

**Comment by josegonzalez** [comment] 2022-12-19 00:15
Okay I figured out a workaround. The problem is that we call `net/url.QueryUnescape` in a nested manner due to you using a nested value, so the escaped `%2B` turns into `+` which turns into ` `.

We can trick it though! You can use `%252B` if its one level of nesting for the `+` sign to show up. I'll add a test case for your use case so you can see what I mean :)

**Comment by josegonzalez** [comment] 2022-12-19 00:16
Closing as there is a pull request open.

**Closed by josegonzalez** 2022-12-19 00:16 UTC
Labels: type: bug, needs: investigation

**Comment by CleitonDeLima** [comment] 2022-12-19 14:44
> We can trick it though! You can use `%252B` if its one level of nesting for the `+` sign to show up. I'll add a test case for your use case so you can see what I mean :)

It worked! Thanks for the tip!
