### ISSUE TITLE
nginx-vhosts  does not set `{{ $.NGINX_SSL_PORT }}` 

### ISSUE THREAD

**Issue by glogiotatidis** [dokku/dokku#2535] opened 2016-12-20 13:26 UTC
Description of problem:
Plugin `nginx-vhosts` does not set `{{ $.NGINX_SSL_PORT }}` when parsing `/var/lib/dokku/plugins/available/nginx-vhosts/templates/nginx.conf.sigil` template.

Output of the following commands

- `uname -a`:
```
Linux x 4.5.7-std-3 #1 SMP Tue Jul 12 09:56:30 UTC 2016 x86_64 GNU/Linux
```
- `free -m`:
```
             total       used       free     shared    buffers     cached
Mem:          7976       2502       5474        239        286       1286
-/+ buffers/cache:        929       7047
Swap:          511         77        434
```
- `docker version`:
Docker version 1.12.5, build 7392c3b

- `docker -D info`:
```
Containers: 17
 Running: 15
 Paused: 0
 Stopped: 2
Images: 68
Server Version: 1.12.5
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.5.7-std-3
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.79 GiB
Name: xxx
ID: 5DUE:AFF6:LPOO:NCHO:H647:33E7:IYIX:OTFV:IQZW:KPML:6BN7:EE42
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```
- `sigil -v`:`0.4.0`

- `dokku version`:`0.7.2`

- `dokku plugin`:
```
  00_dokku-standard    0.7.2 enabled    dokku core standard plugin
  20_events            0.7.2 enabled    dokku core events logging plugin
  apps                 0.7.2 enabled    dokku core apps plugin
  build-env            0.7.2 enabled    dokku core build-env plugin
  certs                0.7.2 enabled    dokku core certificate management plugin
  checks               0.7.2 enabled    dokku core checks plugin
  common               0.7.2 enabled    dokku core common plugin
  config               0.7.2 enabled    dokku core config plugin
  docker-options       0.7.2 enabled    dokku core docker-options plugin
  domains              0.7.2 enabled    dokku core domains plugin
  enter                0.7.2 enabled    dokku core enter plugin
  git                  0.7.2 enabled    dokku core git plugin
  letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.7.2 enabled    dokku core logs plugin
  mysql                1.0.0 enabled    dokku mysql service plugin
  named-containers     0.7.2 enabled    dokku core named containers plugin
  nginx-vhosts         0.7.2 enabled    dokku core nginx-vhosts plugin
  plugin               0.7.2 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.7.2 enabled    dokku core proxy plugin
  ps                   0.7.2 enabled    dokku core ps plugin
  redirect             0.4.0 enabled    Simple redirects for apps
  repo                 0.7.2 enabled    dokku core repo plugin
  shell                0.7.2 enabled    dokku core shell plugin
  ssh-keys             0.7.2 enabled    dokku core ssh-keys plugin
  storage              0.7.2 enabled    dokku core storage plugin
  tags                 0.7.2 enabled    dokku core tags plugin
  tar                  0.7.2 enabled    dokku core tar plugin
```

Environment details (AWS, VirtualBox, physical, etc.):

How was Dokku installed?: Debian package

How reproducible:

Steps to Reproduce:
1. On a SSL enabled host run `proxy:port-add http:80:80` 

Actual Results:
Redirect does not contain ssl port and therefore is adds an extra `:` between `$host` and `$request_uri` 

```
server {
  listen      [::]:80;
  listen      80;
  server_name <removed> 
  access_log  /var/log/nginx/<removed>.log;
  error_log   /var/log/nginx/<removed>.log;

  return 301 https://$host:$request_uri;

}
```

Expected Results:

```
server {
  listen      [::]:80;
  listen      80;
  server_name <removed> 
  access_log  /var/log/nginx/<removed>.log;
  error_log   /var/log/nginx/<removed>.log;

  return 301 https://$host:443$request_uri;

}
```

Additional info:

This works OK with browsers but LetsEncrypt does work like this and fails to verify the host. Removing the extra `:` or setting the port works as expected.

**Comment by josegonzalez** [comment] 2017-01-09 07:14
@glogiotatidis do you have a sample app that I can use to replicate this? As well, *exact* steps you used to setup this application are necessary for us to be able to fix the issue.

The only way that `NGINX_SSL_PORT` would be empty is if this app is either not an ssl application *or* you don't have any raw tcp ports, so I'm guessing there is something else going on here that we don't know about your application.

https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/functions#L83

**Comment by glogiotatidis** [comment] 2017-01-09 11:21
Hey @josegonzalez. This is a simple dockerfile based app that serves static pages using the [`giorgos/dokku-static-site`](https://hub.docker.com/r/giorgos/dokku-static-site/) image. I've deployed the app a long time ago before the `proxy` plugin and maybe something got messed up somewhere during migrations or my configurations. I don't have any other data to provide to reproduce this one, so if that's incomplete feel free to close. It's useful that we documented it in the first place.

**Comment by josegonzalez** [comment] 2017-01-09 20:42
Seeing this confirmed on someone else's app in irc.

**Comment by josegonzalez** [comment] 2017-01-09 21:04
Current workaround:

```
dokku config:set APP DOKKU_NGINX_SSL_PORT=443
```

**Comment by josegonzalez** [comment] 2017-01-30 08:03
I think whats happening is for dockerfile applications, we have `DOKKU_DOCKERFILE_PORTS` being set to a value. Since this isn't an empty string, neither is `RAW_TCP_PORTS`. We currently only set the `NGINX_SSL_PORT` when:

- ssl is enabled
- there are no raw tcp ports set
- app vhosts are enabled

We should probably always default to port 443 as the ssl port when ssl is enabled, and when there are no raw ports AND vhosts are enabled, only then would we use a random port for ssh.

**Comment by josegonzalez** [comment] 2017-01-30 08:04
Closing as there is a pull request open.

**Closed** 2017-01-30 08:05 UTC
Labels: type: bug

**Comment by dmr** [comment] 2017-02-13 18:56
I came across this issue today, again.
This seems like a bug fix, is there anything that is breaking or can you release a new version?
You merge lots of things @josegonzalez since 0.8.0, great work!

**Comment by josegonzalez** [comment] 2017-02-20 00:43
@dmr can you test out the pull request I wrote? I didn't add any new tests as it's not super-clear as to what the best way to replicate/validate this is.
