### ISSUE TITLE
cat: /app/Procfile: No such file or directory

### ISSUE THREAD

**Issue by madshargreave** [dokku/dokku#2341] opened 2016-08-01 18:51 UTC
Description of problem:

I am no longer able to deploy my Elixir/Phoenix app using Dokku on a DigitalOcean Linux droplet, as I get the following error every time.

Buildpacks:

```
https://github.com/HashNuke/heroku-buildpack-elixir.git
https://github.com/madshargreave/geo_buildpack.git
```

No Dockerfile or Procfile

I am not sure if related, but the problem seemed to occur around the time I added a `docker-options`--restart=always`, I tried removing it, but it does not help

```
--- {}
-----> Discovering process types
-----> Releasing staging (dokku/staging:latest)...
-----> Deploying staging (dokku/staging:latest)...
-----> DOKKU_SCALE file found (/home/dokku/staging/DOKKU_SCALE)
=====> web=1
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...

f2a2447804bf47219c1d8b4e82ee2208e1985de7c0ddd4776f0e78c4d2bacd4b
remote: App container failed to start!!
=====> staging container output:
cat: /app/Procfile: No such file or directory
       setuidgid: usage: setuidgid account child
       cat: /app/Procfile: No such file or directory
       setuidgid: usage: setuidgid account child
       cat: /app/Procfile: No such file or directory
       setuidgid: usage: setuidgid account child
       cat: /app/Procfile: No such file or directory
       setuidgid: usage: setuidgid account child
       cat: /app/Procfile: No such file or directory
       setuidgid: usage: setuidgid account child
       cat: /app/Procfile: No such file or directory
       setuidgid: usage: setuidgid account child
       cat: /app/Procfile: No such file or directory
setuidgid: usage: setuidgid account child
=====> end staging container output
remote: Error response from daemon: Cannot kill container f2a2447804bf47219c1d8b4e82ee2208e1985de7c0ddd4776f0e78c4d2bacd4b: Container f2a2447804bf47219c1d8b4e82ee2208e1985de7c0ddd4776f0e78c4d2bacd4b is not running
```

Output of the following commands
- `uname -a`:
Darwin mads 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64

- `docker version`:
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

- `docker -D info`:
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 35
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 48
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: WHLQ:HRPL:II5S:HZFA:L5AM:JKT7:YRA3:F3ZE:BIMI:AV4Y:ODVN:LYUU
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 27
 System Time: 2016-08-01T18:50:39.200392454Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

- `dokku version`
0.4.14

- `dokku plugin`
00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  apt                  0.4.0 enabled    Inject deb packages into dokku based on files in project
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  letsencrypt          0.6.1 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.4.0 enabled    dokku core logs plugin
  named-containers     0.4.0.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin

**Comment by josegonzalez** [comment] 2016-08-01 18:58
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by madshargreave** [comment] 2016-08-01 19:07
Sorry about that, updated with as much info/outputs as I could

**Comment by michaelshobbs** [comment] 2016-08-01 19:10
I'm guessing those buildpacks don't spit out a `.release` file that is usable by herokuish. I wonder, does this app works on Heroku?

The quickest probable fix is to define a `Procfile` with a web proc type that runs your app as expected.
https://devcenter.heroku.com/articles/procfile

**Comment by josegonzalez** [comment] 2016-08-26 23:31
When Heroku writes the `.release` file, it doesn't "merge" the `.release` files, and your last buildpack doesn't write a proper `.release` file. Since you don't have a `Procfile`, neither Dokku nor Heroku will run a command.

Here is the relevant logging output from Heroku:

```
remote: -----> Discovering process types
remote:        Procfile declares types -> (none)
```

Dokku/Herokuish just doesn't output that nothing was detected:

```
-----> Discovering process types
```

App confirmed not to work on Dokku _or_ Heroku without the following Procfile:

```
web: mix run --no-halt
```

Closing as we're following what Heroku does here and it's clear that this is an app issue. If you reverse the order of the buildpacks, everything should start fine.

**Closed by josegonzalez** 2016-08-26 23:31 UTC
Labels: needs: more info
