### ISSUE TITLE
copy_from_image is "hard to use" (too many sources of failure on the way to the desired result)

### ISSUE THREAD

**Issue by SebastianApel** [dokku/dokku#3274] opened 2018-09-20 19:08 UTC
## Description of problem

Not directly a "bug", more a "usability issue". Let me explain:

I had to invest several hours of time in the past to make use of functionality that relies on "copy_from_image" (for example a non-standard nginx-config, or a non-standard app.json).

When I think about the "root cause" then a) I was using images that I did not develop myself (for example nextcloud, matomo). So I did not know if they were using a WORKDIR, or if so which was the WORKDIR. So I tried putting the file in "/app". Didn't work. Then I tried to find out the WORKDIR. Took a while of googeling and digging into the dokku sourcecode to find out how to obtain the WORKDIR.

Suggestion #1: Log the "$WORKDIR/$SRC_FILE"  in copy_from_image - so people can see where dokku is searching (shortens time to solution)

To make things worse, the nextcloud image uses a WORKDIR but ERASES the WORKDIR on initial setup via rsync in it's entrypoint.sh.  So even copying nginx.conf.sigil into the WORKDIR inside the Dockerfile fails. (Because it get's erased by entrypoint.sh when the cointainer "starts". THAT took me a very long time to understand).

Suggestion #2: Remove the WORKDIR or /app choice. Just say "Put the 'custom' dokku config (like app.json or nginx.conf.sigil) in this hard wired folder '/dokku_config'" and be done with it. If you want to change only one function, the change could be introduced into copy_from_image. For backwards compatibility, copy_from_image could try the "dokku_config" folder first, then fallback to the "old" logic (WORKDIR or /app). Plus: Add logging, so people can see where copy_from_image takes the file from (or looks for it).

### How reproducible

Try to get an nginx.conf.sigil file working with "FROM nextcloud:14-fpm-alpine"

### Steps to Reproduce

1. Dockerfile with FROM nextcloud:14-fpm-alpine
2. Add a "COPY nginx.conf.sigil ." to copy the conf file to WORKDIR
3. Start the app
4. Wait for custom ngix.conf

#### Actual Results

Spend 4 hours finding out what's going on

#### Expected Results

Just put the nginx.conf.sigil into a predefined folder (that is ideally DIFFERENT from a folder that the container will use). Enjoy more time with spouse & children.

### Additional information

see https://github.com/dokku/dokku/issues/3272

**Comment by josegonzalez** [comment] 2018-10-06 20:49
I think depending on the specified WORKDIR or `/app` for copying files out is what we're going to do. We don't currently support WORKDIR, but that is going to be implemented as part of #3263. Closing this out as a duplicate of that.

**Closed by josegonzalez** 2018-10-06 20:49 UTC
