### ISSUE TITLE
Error when push 

### ISSUE THREAD

**Issue by L2S2A** [dokku/dokku#3770] opened 2019-11-06 22:48 UTC
Hello, I made an update of dokku and since I always have the following error when I push

`dokku version 0.19.7`

Docker Version

```Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:52:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:51:05 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683The dockerfile with database link
```

Dockerfile
```
FROM openproject/community:latest
ENV DATABASE_URL postgres://......................
```

The extract of error with trace on

```
remote: ++ docker container run --label=com.dokku.container-type=deploy --label=com.dokku.app-name=op --label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku --detach --env PORT=5432 --env=DATABASE_URL=postgres://postgres:92cdda189fab73932abbfd4a69a0987e@dokku-postgres-op:5432/op --env=DOKKU_APP_TYPE=dockerfile '--env=DOKKU_DOCKERFILE_PORTS=5432/tcp 80/tcp ' --env=DOKKU_PROXY_PORT=80 '--env=DOKKU_PROXY_PORT_MAP=http:5432:5432 http:80:80  ' --env=GIT_REV=78c09657ef98aab6a100f1c4e96d68f66a1be4fb --link dokku.postgres.op:dokku-postgres-op --restart=on-failure:10 -e DYNO=web.1 -e TRACE=true dokku/op:latest ./packaging/scripts/web
remote: + cid=70333183f76e3abe156d2856b510b5147b821d97f2de479bb2b53cef57584855
remote: ++ plugn trigger network-get-ipaddr op web 70333183f76e3abe156d2856b510b5147b821d97f2de479bb2b53cef57584855
remote: + source /var/lib/dokku/core-plugins/available/common/functions
remote: ++ set -eo pipefail
remote: ++ [[ -n 1 ]]
remote: ++ set -x
remote: + [[ ! -n '' ]]
remote: + ipaddr=172.17.0.14
remote: ++ plugn trigger network-get-port op web false 70333183f76e3abe156d2856b510b5147b821d97f2de479bb2b53cef57584855
remote: + source /var/lib/dokku/core-plugins/available/common/functions
remote: ++ set -eo pipefail
remote: ++ [[ -n 1 ]]
remote: ++ set -x
remote: + [[ ! -n '' ]]
remote: FAILED: exit status 1
remote: + port=
remote: + rm -rf /tmp/dokku-15194-git_build_app_repo.YgHHcC
remote: + exit_code=1
remote: + set -e
remote: + [[ 1 -eq 10 ]]
remote: + implemented=1
remote: + [[ 1 -ne 0 ]]
remote: + exit 1
+ exit_code=0
+ set -e
+ [[ 0 -eq 10 ]]
+ implemented=1
+ [[ 0 -ne 0 ]]
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/letsencrypt/commands git-receive-pack ''\''op'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/logs/commands git-receive-pack ''\''op'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/mariadb/commands git-receive-pack ''\''op'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/network/commands git-receive-pack ''\''op'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/nginx-vhosts/commands git-receive-pack ''\''op'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/plugin/commands git-receive-pack ''\''op'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/postgres/commands git-receive-pack ''\''op'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/proxy/commands git-receive-pack ''\''op'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/ps/commands git-receive-pack ''\''op'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/redis/commands git-receive-pack ''\''op'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/repo/commands git-receive-pack ''\''op'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/resource/commands git-receive-pack ''\''op'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/scheduler-docker-local/commands git-receive-pack ''\''op'\'''
+ source /var/lib/dokku/plugins/available/scheduler-docker-local/internal-functions
++ source /var/lib/dokku/core-plugins/available/common/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
++ source /var/lib/dokku/core-plugins/available/common/property-functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
++ source /var/lib/dokku/plugins/available/config/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+++ source /var/lib/dokku/core-plugins/available/common/functions
++++ set -eo pipefail
++++ [[ -n 1 ]]
++++ set -x
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ case "$1" in
+ exit 10
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/shell/commands git-receive-pack ''\''op'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/ssh-keys/commands git-receive-pack ''\''op'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/storage/commands git-receive-pack ''\''op'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/tags/commands git-receive-pack ''\''op'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/tar/commands git-receive-pack ''\''op'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ for script in $PLUGIN_ENABLED_PATH/*/commands
+ set +e
+ /var/lib/dokku/plugins/enabled/trace/commands git-receive-pack ''\''op'\'''
+ exit_code=10
+ set -e
+ [[ 10 -eq 10 ]]
+ continue
+ [[ 1 -eq 0 ]]
+ set +f
+ exit 0
To 212.47.246.57:op
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@
```

Thank's for your help...

**Comment by josegonzalez** [comment] 2019-11-07 03:45
I think this is a duplicate of #3769, so closing this for now.

**Closed by josegonzalez** 2019-11-07 03:45 UTC

**Comment by L2S2A** [comment] 2019-11-07 07:08
Sorry
Thank's
