### ISSUE TITLE
Tags are deleted after build using dockerfile deploy

### ISSUE THREAD

**Issue by Kjwon15** [dokku/dokku#4380] opened 2021-02-04 08:01 UTC
> If you're using Dokku - especially for commercial purposes - consider donating to project development via [OpenCollective](https://opencollective.com/dokku) or [Patreon](https://www.patreon.com/dokku). Funds go to general development, support, and infrastructure costs.
>
> If you'd like to sponsor specific functionality, see the project's [Sponsoring](https://github.com/dokku/.github/blob/master/SPONSORING.md) document.
>
> If you need help figuring out how to use a specific buildpack, are seeing an issue in during the buildpack process, or are having issues using multiple buildpacks, please see our [slack channels or github discussion board](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#monitored-locations). Issues pertaining to buildpacks may be closed and locked.
>
> If you need support for a version of Dokku that is more than a year old, your issue may be closed without an answer. Please upgrade to a recent version.

## Description of problem
Saved tags are deleted after new build using Dockerfile build
### Steps to Reproduce
using app named testapp

1. dokku tags:save testapp v1.0.0
2. dokku ps:rebuild testapp
3. dokku tags testapp

#### Actual Results

There is only `latest` tag

#### Expected Results
There are `v1.0.0` tag and `latest`

---
I am using dokku v0.23.0

**Comment by Kjwon15** [comment] 2021-02-04 08:07
Also after successful deploy, old containers are not removed

**Comment by josegonzalez** [comment] 2021-02-04 17:32
Can you post an image I can replicate this with? Old containers should def be removed, as we're using the normal deployment flow for these images...

**Comment by josegonzalez** [comment] 2021-02-20 18:14
Closing this. There is a test for this behavior [here](https://github.com/dokku/dokku/blob/757a82913749c64e77b83aaeae7038684d9d0fbf/tests/unit/tags.bats#L101) and I am unable to reproduce this on the latest Dokku.

**Closed by josegonzalez** 2021-02-20 18:14 UTC
Labels: needs: more info, plugin: tags
