### ISSUE TITLE
Zombie containers after deploy

### ISSUE THREAD

**Issue by dilame** [dokku/dokku#3273] opened 2018-09-20 15:35 UTC
## Description of problem
When i push new version of app to repository, the older version still exists and respond to requests. Now i have 4 older zombie vesrions of my app, though i have scaled the app to 0. And i don't know how to kill it.
### How reproducible
I'm not sure i know how to reproduce it, because i just faced the consequences.
#### Actual Results
```bash
sudo docker ps -a
aae6d4db1a98        44add37e2135                          "/start web"             4 hours ago         Exited (0) 2 hours ago                                app.web.1
11bac6a2f64a        80132678f278                          "/start web"             4 hours ago         Exited (0) 4 hours ago                                app.web.1.1537440981
ad7e970cf175        b749f15ef8a7                          "/start web"             4 hours ago         Exited (0) 4 hours ago                                app.web.1.1537440660
b0addb098589        c7351db6e443                          "/start web"             8 days ago          Up 8 days                                             app.web.1.1537440612
```
```bash
dokku ps:report
=====> app ps information
       Processes:                     0                        
       Deployed:                      false                    
       Running:                       false                    
       Restore:                       true                     
       Restart policy:                on-failure:10            
```
#### Expected Results
I expect that if i have scale=0 then I have no processes of this app.
### `dokku report APP_NAME` output
```bash
dokku report app
-----> uname: Linux dota 4.9.33-mod-std-ipv6-64 #1 SMP Tue Jun 20 11:36:21 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:         128887        3911       62431        1802       62543      121342
       Swap:         10237          28       10209
-----> docker version: 
       Client:
        Version:           18.06.0-ce
        API version:       1.38
        Go version:        go1.10.3
        Git commit:        0ffa825
        Built:             Wed Jul 18 19:11:02 2018
        OS/Arch:           linux/amd64
        Experimental:      false
       
       Server:
        Engine:
         Version:          18.06.0-ce
         API version:      1.38 (minimum version 1.12)
         Go version:       go1.10.3
         Git commit:       0ffa825
         Built:            Wed Jul 18 19:09:05 2018
         OS/Arch:          linux/amd64
         Experimental:     false
-----> docker daemon info: 
       Containers: 49
        Running: 24
        Paused: 0
        Stopped: 25
       Images: 292
       Server Version: 18.06.0-ce
       Storage Driver: overlay2
        Backing Filesystem: extfs
        Supports d_type: true
        Native Overlay Diff: true
WARNING: No cpu cfs quota support
       Logging Driver: json-file
WARNING: No cpu cfs period support
       Cgroup Driver: cgroupfs
       Plugins:
        Volume: local
        Network: bridge host macvlan null overlay
        Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
       Swarm: inactive
       Runtimes: runc
       Default Runtime: runc
       Init Binary: docker-init
       containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
       runc version: 69663f0bd4b60df09991c08812a60108003fa340
       init version: fec3683
       Security Options:
        seccomp
         Profile: default
       Kernel Version: 4.9.33-mod-std-ipv6-64
       Operating System: Ubuntu 16.04.4 LTS
       OSType: linux
       Architecture: x86_64
       CPUs: 16
       Total Memory: 125.9GiB
       Name: dota
       ID: 6ITJ:EZUV:F2DO:XVIR:QHXD:I2OT:N272:DBTG:QCBC:C4SN:OS25:VNHP
       Docker Root Dir: /var/lib/docker
       Debug Mode (client): true
       Debug Mode (server): false
       Registry: https://index.docker.io/v1/
       Labels:
       Experimental: false
       Insecure Registries:
        127.0.0.0/8
       Live Restore Enabled: false
       
-----> sigil version: 0.4.0
-----> herokuish version: 
       herokuish: 0.4.3
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v188
         heroku-buildpack-nodejs    v123
         heroku-buildpack-clojure   v82
         heroku-buildpack-python    v136
         heroku-buildpack-java      v62
         heroku-buildpack-gradle    v27
         heroku-buildpack-scala     v82
         heroku-buildpack-play      v26
         heroku-buildpack-php       v137
         heroku-buildpack-go        v89
         buildpack-nginx            v9
-----> dokku version: 0.12.12
-----> dokku plugins: 
       plugn: 0.3.0
         00_dokku-standard    0.12.12 enabled    dokku core standard plugin
         20_events            0.12.12 enabled    dokku core events logging plugin
         apps                 0.12.12 enabled    dokku core apps plugin
         build-env            0.12.12 enabled    dokku core build-env plugin
         certs                0.12.12 enabled    dokku core certificate management plugin
         checks               0.12.12 enabled    dokku core checks plugin
         common               0.12.12 enabled    dokku core common plugin
         config               0.12.12 enabled    dokku core config plugin
         docker-options       0.12.12 enabled    dokku core docker-options plugin
         domains              0.12.12 enabled    dokku core domains plugin
         enter                0.12.12 enabled    dokku core enter plugin
         git                  0.12.12 enabled    dokku core git plugin
         logs                 0.12.12 enabled    dokku core logs plugin
         mysql                1.3.0 enabled    dokku mysql service plugin
         network              0.12.12 enabled    dokku core network plugin
         nginx-vhosts         0.12.12 enabled    dokku core nginx-vhosts plugin
         plugin               0.12.12 enabled    dokku core plugin plugin
         postgres             1.3.0 enabled    dokku postgres service plugin
         proxy                0.12.12 enabled    dokku core proxy plugin
         ps                   0.12.12 enabled    dokku core ps plugin
         redis                1.3.0 enabled    dokku redis service plugin
         repo                 0.12.12 enabled    dokku core repo plugin
         scheduler-docker-local 0.12.12 enabled    dokku core scheduler-docker-local plugin
         shell                0.12.12 enabled    dokku core shell plugin
         ssh-keys             0.12.12 enabled    dokku core ssh-keys plugin
         storage              0.12.12 enabled    dokku core storage plugin
         tags                 0.12.12 enabled    dokku core tags plugin
         tar                  0.12.12 enabled    dokku core tar plugin
=====> app app information
not deployed
```
> This is required! Issues missing this information may be closed.
>
> For problems affecting all applications, the report output for a broken application is useful for our debugging.
> You may also run `dokku report` without any arguments to display the top-level reporting information.

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
```bash
  wget https://raw.githubusercontent.com/dokku/dokku/v0.12.12/bootstrap.sh

  sudo DOKKU_TAG=v0.12.12 bash bootstrap.sh
```
On physical server

### Additional information
  - Application name - app
  - The type of application being deployed - node
  - the contents of your `Procfile`.
web: node app

**Comment by josegonzalez** [comment] 2018-09-20 15:38
The problem here is either you rebooted after deploying and docker starts stopped containers - feature, not a bug on their end... - or you are under high load so the system that kills old containers gets killed.

#3236 is supposed to fix it, we just need someone to verify it.

Closing as a duplicate.

**Closed by josegonzalez** 2018-09-20 15:38 UTC

**Comment by dilame** [comment] 2018-09-20 15:51
@josegonzalez thank you for your super-quick response. I did not reboot the server and i have more than enough resources on it. Soon I will launch this in production, so such situation is unacceptable for me. How can i fix it now and not to admit this in future?

**Comment by josegonzalez** [comment] 2018-09-20 15:56
You can help test that pull request.

**Comment by dilame** [comment] 2018-09-20 15:56
With pleasure. How can i install dokku version with this PR?

**Comment by josegonzalez** [comment] 2018-09-20 19:49
Just commented on the PR.

**Comment by skorokithakis** [comment] 2018-10-21 15:18
This looks good after a few deploys. There's a change (I don't know whether it's in this or another PR) that breaks my `app.json`, I had to change `/code/manage.py` to `python /code/manage.py` for it to work.

**Comment by josegonzalez** [comment] 2018-10-21 16:36
Please keep any comments on the PR, not in closed issues.
