### ISSUE TITLE
Dokku 0.5.6 returns "Please run: sudo dokku plugin:install" on each plugin request

### ISSUE THREAD

**Issue by lolorama** [dokku/dokku#2197] opened 2016-05-15 14:01 UTC
**Description of problem:**
I've just installed dokku and run postgres plugin install command:
`sudo dokku plugin:install https://github.com/dokku/dokku-postgres.git`
dokku returns:
```
-----> Cloning plugin repo https://github.com/dokku/dokku-postgres.git to /var/lib/dokku/plugins/available/postgres
Cloning into 'postgres'...
remote: Counting objects: 561, done.
remote: Total 561 (delta 0), reused 0 (delta 0), pack-reused 561
Receiving objects: 100% (561/561), 112.69 KiB | 0 bytes/s, done.
Resolving deltas: 100% (345/345), done.
Checking connectivity... done.
-----> Plugin postgres enabled
-----> Migrating zero downtime env variables. The following variables have been deprecated
=====> DOKKU_SKIP_ALL_CHECKS DOKKU_SKIP_DEFAULT_CHECKS
=====> Please use dokku checks:[disable|enable] <app> to control zero downtime functionality
=====> Migration complete
=====>
Adding user dokku to group adm
start: Job is already running: nginx
```
But when I've tried to create postgres db with:
`dokku postgres:create db_name`
dokku returns me an error
`Postgres: Please run: sudo dokku plugin:install`

When I'm trying to:
`sudo dokku plugin:install`
It returns:
```
sudo dokku plugin:install
-----> Migrating zero downtime env variables. The following variables have been deprecated
=====> DOKKU_SKIP_ALL_CHECKS DOKKU_SKIP_DEFAULT_CHECKS
=====> Please use dokku checks:[disable|enable] <app> to control zero downtime functionality
=====> Migration complete
=====>
Adding user dokku to group adm
start: Job is already running: nginx
```
But it doesn't solves the problem.

**Output of the following commands**

- `uname -a`:
Linux alext 3.13.0-86-generic #130-Ubuntu SMP Mon Apr 18 18:27:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`:
```
total       used       free     shared    buffers     cached
Mem:          2001       1592        409          0         53       1327
-/+ buffers/cache:        212       1789
Swap:            0          0          0
```
- `docker version`:
```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
- `docker -D info`:
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 6
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-86-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: alext
ID: MMQ5:VZC2:5Q4I:QLMK:3L4H:BR23:JVI2:RDVY:LJT6:SEUV:S2GO:MPDU
Docker Root Dir: /var/lib/docker
Debug mode (client): true
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```
- `sigil -v`: `0.4.0`
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
```
  emberjs.tgz                latest
  buildpack-nginx            v5
  heroku-buildpack-clojure   v75
  heroku-buildpack-erlang    fa17af9
  heroku-buildpack-go        v34
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v20
  heroku-buildpack-java      v44
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v90
  heroku-buildpack-php       v101
  heroku-buildpack-play      v26
  heroku-buildpack-python    v80
  heroku-buildpack-ruby      v146
  heroku-buildpack-scala     v70
```
- `dokku version`: `0.5.6`
- `dokku plugin`:
```
plugn: dev
  00_dokku-standard    0.5.6 enabled    dokku core standard plugin
  20_events            0.5.6 enabled    dokku core events logging plugin
  apps                 0.5.6 enabled    dokku core apps plugin
  build-env            0.5.6 enabled    dokku core build-env plugin
  certs                0.5.6 enabled    dokku core certificate management plugin
  checks               0.5.6 enabled    dokku core checks plugin
  common               0.5.6 enabled    dokku core common plugin
  config               0.5.6 enabled    dokku core config plugin
  docker-options       0.5.6 enabled    dokku core docker-options plugin
  domains              0.5.6 enabled    dokku core domains plugin
  enter                0.5.6 enabled    dokku core enter plugin
  git                  0.5.6 enabled    dokku core git plugin
  logs                 0.5.6 enabled    dokku core logs plugin
  named-containers     0.5.6 enabled    dokku core named containers plugin
  nginx-vhosts         0.5.6 enabled    dokku core nginx-vhosts plugin
  plugin               0.5.6 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.5.6 enabled    dokku core proxy plugin
  ps                   0.5.6 enabled    dokku core ps plugin
  redis                1.0.0 enabled    dokku redis service plugin
  shell                0.5.6 enabled    dokku core shell plugin
  storage              0.5.6 enabled    dokku core storage plugin
  tags                 0.5.6 enabled    dokku core tags plugin
  tar                  0.5.6 enabled    dokku core tar plugin
```

**Comment by lolorama** [comment] 2016-05-15 15:55
Probably it's because "/var/lib/dokku/services/postgres" doesn't exists.. But why so?
`+ [[ ! -d /var/lib/dokku/services/postgres ]]`

**Comment by michaelshobbs** [comment] 2016-05-15 18:27
My guess is that some `install` trigger is exiting 1 before the Postgres trigger is called. You can verify by running `dokku plugin:install; echo $?`. Paste that output here and if it is indeed exiting 1, run `dokku --trace plugin:install` and post a gist of that for us to check out.

**Comment by lolorama** [comment] 2016-05-15 18:56
It return 1, yes

https://gist.github.com/lolorama/6116d26e90f0ba029010724d6d87b027

**Comment by michaelshobbs** [comment] 2016-05-16 17:23
So the call to `/etc/init.d/nginx start` returned 1 😦 

I've seen this with some versions of the nginx init.d script. You might try stopping nginx temporarily and run `dokku plugin:install` again.

@josegonzalez should we `|| true` [these calls](https://github.com/dokku/dokku/blob/v0.5.6/plugins/nginx-vhosts/install#L50-L66)?

**Comment by lolorama** [comment] 2016-05-16 18:20
@michaelshobbs, problem solved. Thanks!

**Comment by lolorama** [comment] 2016-05-16 19:03
```
=====> renaming container (5fa7f4abefe9) agitated_borg to moviek.web.1
-----> Creating new /home/dokku/moviek/VHOST...
-----> Overriding default nginx.conf with detected nginx.conf.sigil
-----> Setting config vars
       DOKKU_NGINX_PORT: 80
-----> Configuring moviek.moviek.online...(using app-supplied template)
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
remote: sudo: no tty present and no askpass program specified
To dokku@moviek.online:moviek
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@moviek.online:moviek'
```

Can you help with this? I've used second type of installation (with docker + apt-get), maybe I have issue with setting up dokku user?

**Comment by michaelshobbs** [comment] 2016-05-16 19:19
What do you get from `cat /etc/sudoers.d/dokku-nginx`?

**Comment by lolorama** [comment] 2016-05-16 19:26
@michaelshobbs, 
`%dokku ALL=(ALL) NOPASSWD:/etc/init.d/nginx reload, /usr/sbin/nginx -t`

**Comment by michaelshobbs** [comment] 2016-05-16 19:28
It's not clear to me how you created the aforementioned output. Can you paste your entire terminal from the invocation of whatever command you ran to the failure?

**Comment by lolorama** [comment] 2016-05-16 19:33
Just:
```
git remote add dokku dokku@moviek.online:moviek
git push dokku master

```
maybe it's because I've installed dokku as root?

**Comment by michaelshobbs** [comment] 2016-05-16 19:43
No that's not the issue. dokku needs to be installed as root.
This is generally caused by the user you're pushing as not having sudo access to `nginx reload` on the dokku host. 

On the `moviek.online` does this work?
```
root@dokku:~/dokku# sudo su - dokku
dokku@dokku:~$ sudo /etc/init.d/nginx reload ; echo $?
 * Reloading nginx configuration nginx                                             [ OK ]
0
dokku@dokku:~$
```

**Comment by lolorama** [comment] 2016-05-16 19:46
@michaelshobbs, it requires password.
`[sudo] password for dokku:`

**Comment by michaelshobbs** [comment] 2016-05-16 19:47
Where did you run `cat /etc/sudoers.d/dokku-nginx`?
Where did you run the sudo command?

Those two can't be the same host....

**Comment by josegonzalez** [comment] 2016-05-16 19:48
@lolorama did you add a password to the `dokku` user?

**Comment by lolorama** [comment] 2016-05-16 19:52
I've ran `cat /etc/sudoers.d/dokku-nginx` as root.

running `cat /etc/sudoers.d/dokku-nginx` with dokku user gives me 
`cat: /etc/sudoers.d/dokku-nginx: Permission denied`

No, i did not add password.. 1 min

**Comment by michaelshobbs** [comment] 2016-05-16 19:57
To clarify, you wouldn't be able to run that `cat` command as `dokku`.

My question was did you run both the `nginx reload` and `cat` commands on the same host?

**Comment by michaelshobbs** [comment] 2016-05-16 20:01
At this point it might be faster to start with a new instance. Can you try starting with a fresh instance, install dokku, stop nginx, install the plugins you want, then deploy your app?

**Comment by lolorama** [comment] 2016-05-16 20:01
It's definitely one host.

```
root@alext:/home/dokku/moviek# dokku plugin:install; echo $?
-----> Migrating zero downtime env variables. The following variables have been deprecated
=====> DOKKU_SKIP_ALL_CHECKS DOKKU_SKIP_DEFAULT_CHECKS
=====> Please use dokku checks:[disable|enable] <app> to control zero downtime functionality
=====> Migration complete
=====>
Adding user dokku to group adm
start: Job is already running: nginx
1
root@alext:/home/dokku/moviek# cat /etc/sudoers.d/dokku-nginx
%dokku ALL=(ALL) NOPASSWD:/etc/init.d/nginx reload, /usr/sbin/nginx -t
root@alext:/home/dokku/moviek#
```

**Comment by lolorama** [comment] 2016-05-16 20:02
Yes, actually I was prepared for that :)

**Comment by michaelshobbs** [comment] 2016-05-16 20:02
We can spin the wheels and try to debug remotely or we can start with a clean slate 😄

**Comment by josegonzalez** [comment] 2016-05-16 20:03
May also be worth hopping on slack/irc so we can debug this interactively. We can come back and update the issue with any findings if necessary.

**Comment by lolorama** [comment] 2016-05-16 20:06
as you wish, if you have interest to debug this I can provide you an access. Or just reinstall VPS..

**Comment by michaelshobbs** [comment] 2016-05-16 20:10
Yeah I'd like to take a look actually. My pub keys are here: https://github.com/michaelshobbs.keys

**Comment by josegonzalez** [comment] 2016-05-16 20:56
User somehow added a password to the dokku user. I ended up dropping the dokku user and group, and subsequently recreated them to fix the issue. The `dokku` user should never have a password.

Closing as there isn't any debugging left to do :)

**Closed by josegonzalez** 2016-05-16 20:56 UTC
Labels: type: bug, type: support

**Comment by diegoponciano** [comment] 2018-01-22 11:55
@josegonzalez is there a recipe for this user re-creation (like, do I keep the same uid, etc)? I've upgraded my system and now dokku is asking for password, even though I tried dropping it with `sudo passwd -d dokku`.

**Comment by diego-brainnco** [comment] 2018-01-22 13:10
To follow up: I tried dropping the user and recreating it, taking hints from `debian/postrm` and `debian/postinst` I ran and it still didn't work:

```
deluser dokku || true
delgroup dokku || true
/usr/local/bin/sshcommand create dokku /usr/bin/dokku
egrep -i "^docker" /etc/group || groupadd docker
usermod -aG docker dokku
```

Comparing it to another box with dokku working fine, turns out this box missed this line on the bottom of `/etc/sudoers`:
```
#includedir /etc/sudoers.d
```

Everything's working fine now!
