### ISSUE TITLE
Worker automatically exit after some time without restarting

### ISSUE THREAD

**Issue by BoluwajiDavids** [dokku/dokku#6580] opened 2024-02-11 11:11 UTC
### Description of problem

I have an application that uses a worker to process some jobs in the background. The worker works fine after building the app but it exit with exitcode 1 after sometime. After running dokku ps:inspect app_name, I noticed that the restart policy was set as follows 
{
MaximumRetryCount:0,
Name:'no'
}
This was fixed by running dokku ps:set app_name restart-policy on-failure:10 and rebuilding the app afterwards.

The expected behavior is for this policy to be set without having to run the above command

### Steps to reproduce

Deploy a new app and set dokku ps:scale app_name worker=1 

### dokku report $APP_NAME

Got the following after running dokku docker-options:report app_name

=====> app_name docker options information
       Docker options build:
       Docker options deploy:
       Docker options run:

**Comment by josegonzalez** [comment] 2024-02-12 01:41
I think what we should do:

- In the `install` trigger, set the property for each app (takes care of existing apps)
- In the `post-create` trigger, set the property on the app (takes care of new apps)

**Comment by josegonzalez** [comment] 2024-02-12 03:41
Okay I just tested this, and we already do the above. My guess is that somehow you manually deleted the docker-options file or removed the settings, and thats why we weren't auto-restarting things.

Going to close this for now since I think things are working as intended.

**Closed by josegonzalez** 2024-02-12 03:41 UTC
Labels: type: bug, merge-level: patch, difficulty: easy, status: has plan, plugin: docker-options, estimate: 1h
