### ISSUE TITLE
Debian 12 installation failed

### ISSUE THREAD

**Issue by leandroembu** [dokku/dokku#6090] opened 2023-08-02 21:49 UTC
### Description of problem

Debian 12 installation results in dependency errors below:

```
Os pacotes a seguir têm dependências desencontradas:
 dokku : Pré-Depende: gliderlabs-sigil mas não é instalável
         Pré-Depende: plugn (>= 0.3.0) mas não é instalável
         Depende: sshcommand (>= 0.12.0) mas não será instalado
         Depende: docker-image-labeler (>= 0.2.2) mas não é instalável
         Depende: lambda-builder mas não é instalável
         Depende: netrc mas não é instalável
         Depende: procfile-util (>= 0.11.0) mas não é instalável
         Recomenda: herokuish (>= 0.3.4) mas não é instalável
         Recomenda: dokku-update mas não é instalável
         Recomenda: dokku-event-listener mas não é instalável
E: Impossível corrigir problemas, você manteve (hold) pacotes quebrados.
```

### Steps to reproduce

- Get a new Debian 12 box.
- Run the commands from [the docs](https://dokku.com/docs/getting-started/install/debian/).

### dokku report $APP_NAME

There's no apps.

**Comment by josegonzalez** [comment] 2023-08-03 20:26
Duplicate of #6077.

**Closed by josegonzalez** 2023-08-03 20:26 UTC
Labels: type: bug, needs: investigation
