### ISSUE TITLE
Can't map port

### ISSUE THREAD

**Issue by leonardoarroyo** [dokku/dokku#3943] opened 2020-04-20 02:50 UTC
## Description of problem
I get an error when attempting to map a port.

### Steps to Reproduce

1. Deploy an application with Dockerfile exposing port 4000
2. Run `dokku proxy:ports-add mv-client http:80:4000`

#### Actual Results
Output is:
```
template: nginx.conf.sigil:4:19: executing "nginx.conf.sigil" at <index $port_map_list...>: error calling index: index out of range: 1                                                                                                                                   
```
#### Expected Results
Successfully map port 80 to 4000.

## Environment Information
-----> uname: Linux meuvitae-dokku 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:            985         273         285           0         426         571
       Swap:             0           0           0
-----> docker version: 
       Client:
        Version:           18.09.6
        API version:       1.39
        Go version:        go1.10.8
        Git commit:        481bc77
        Built:             Sat May  4 02:35:57 2019
        OS/Arch:           linux/amd64
        Experimental:      false
       
       Server: Docker Engine - Community
        Engine:
         Version:          18.09.6
         API version:      1.39 (minimum version 1.12)
         Go version:       go1.10.8
         Git commit:       481bc77
         Built:            Sat May  4 01:59:36 2019
         OS/Arch:          linux/amd64
         Experimental:     false
-----> docker daemon info: 
       Containers: 4
        Running: 2
        Paused: 0
        Stopped: 2
       Images: 43
       Server Version: 18.09.6
       Storage Driver: overlay2
        Backing Filesystem: extfs
        Supports d_type: true
        Native Overlay Diff: true
       Logging Driver: json-file
       Cgroup Driver: cgroupfs
       Plugins:
        Volume: local
        Network: bridge host macvlan null overlay
        Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
       Swarm: inactive
       Runtimes: runc
       Default Runtime: runc
       Init Binary: docker-init
       containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
       runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
       init version: fec3683
       Security Options:
        apparmor
        seccomp
         Profile: default
       Kernel Version: 4.15.0-52-generic
       Operating System: Ubuntu 18.04.2 LTS
       OSType: linux
       Architecture: x86_64
       CPUs: 1
       Total Memory: 985.5MiB
       Name: meuvitae-dokku
       ID: REN5:ZCN5:TGZC:CALL:HYRW:PSAP:F7LU:GCNR:SL2U:E6O4:3DFF:3US4
       Docker Root Dir: /var/lib/docker
       Debug Mode (client): true
       Debug Mode (server): false
       Registry: https://index.docker.io/v1/
       Labels:
       Experimental: false
       Insecure Registries:
        127.0.0.0/8
       Live Restore Enabled: false
       Product License: Community Engine
       
-----> sigil version: 0.4.0
-----> herokuish version: 
       herokuish: 0.5.0
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v200
         heroku-buildpack-nodejs    v142
         heroku-buildpack-clojure   v83
         heroku-buildpack-python    v149
         heroku-buildpack-java      v63
         heroku-buildpack-gradle    v28
         heroku-buildpack-scala     v84
         heroku-buildpack-play      v26
         heroku-buildpack-php       v151
         heroku-buildpack-go        v104
         buildpack-nginx            v10
-----> dokku version: dokku version 0.17.9
-----> dokku plugins: 
       plugn: 0.3.2
         00_dokku-standard    0.17.9 enabled    dokku core standard plugin
         20_events            0.17.9 enabled    dokku core events logging plugin
         app-json             0.17.9 enabled    dokku core app-json plugin
         apps                 0.17.9 enabled    dokku core apps plugin
         build-env            0.17.9 enabled    dokku core build-env plugin
         buildpacks           0.17.9 enabled    dokku core buildpacks plugin
         certs                0.17.9 enabled    dokku core certificate management plugin
         checks               0.17.9 enabled    dokku core checks plugin
         common               0.17.9 enabled    dokku core common plugin
         config               0.17.9 enabled    dokku core config plugin
         docker-options       0.17.9 enabled    dokku core docker-options plugin
         domains              0.17.9 enabled    dokku core domains plugin
         enter                0.17.9 enabled    dokku core enter plugin
         git                  0.17.9 enabled    dokku core git plugin
         logs                 0.17.9 enabled    dokku core logs plugin
         network              0.17.9 enabled    dokku core network plugin
         nginx-vhosts         0.17.9 enabled    dokku core nginx-vhosts plugin
         plugin               0.17.9 enabled    dokku core plugin plugin
         proxy                0.17.9 enabled    dokku core proxy plugin
         ps                   0.17.9 enabled    dokku core ps plugin
         repo                 0.17.9 enabled    dokku core repo plugin
         resource             0.17.9 enabled    dokku core resource plugin
         scheduler-docker-local 0.17.9 enabled    dokku core scheduler-docker-local plugin
         shell                0.17.9 enabled    dokku core shell plugin
         ssh-keys             0.17.9 enabled    dokku core ssh-keys plugin
         storage              0.17.9 enabled    dokku core storage plugin
         tags                 0.17.9 enabled    dokku core tags plugin
         tar                  0.17.9 enabled    dokku core tar plugin
         trace                0.17.9 enabled    dokku core trace plugin
=====> mv-client app information
       App dir:                       /home/dokku/mv-client    
       Git sha:                       8c1de09                  
       Deploy source:                 git                      
       Locked:                        false                    
=====> mv-client buildpacks information
       Buildpacks list:               
=====> mv-client ssl information
       Ssl dir:                       /home/dokku/mv-client/tls
       Ssl enabled:                   false                    
       Ssl hostnames:                                          
       Ssl expires at:                                         
       Ssl issuer:                                             
       Ssl starts at:                                          
       Ssl subject:                                            
       Ssl verified:                                           
=====> mv-client checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> mv-client docker options information
       Docker options build:                                   
       Docker options deploy:         --restart=on-failure:10  
       Docker options run:                                     
=====> mv-client domains information
       Domains app enabled:           false                    
       Domains app vhosts:                                     
       Domains global enabled:        false                    
       Domains global vhosts:                                  
=====> mv-client git information
       Git rev env var:               GIT_REV                  
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
=====> mv-client network information
       Network bind all interfaces:   false
       Network listeners:             172.17.0.4:4000
=====> mv-client proxy information
       Proxy enabled:                 true                     
       Proxy type:                    nginx                    
       Proxy port map:                http:4000:4000 http:80:4000 mv-client
=====> mv-client ps information
       Processes:                     1                        
       Deployed:                      true                     
       Running:                       true                     
       Restore:                       true                     
       Restart policy:                on-failure:10            
       Ps can scale:                  true                     
       Status web.1:                  running    (CID: 90f21b286b3d)
=====> mv-client scheduler-docker-local information
       Scheduler docker local disable chown:                          
=====> mv-client storage information
       Storage build mounts:                                   
       Storage deploy mounts:                                  
       Storage run mounts:                                     

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
Digital ocean one click install.

**Comment by leonardoarroyo** [comment] 2020-04-20 03:16
I also seem unable to set configs:
```
dokku config:set mv-client DOKKU_PROXY_PORT_MAP=http:80:4000
FAILED: Invalid env pair: mv-client
```

**Comment by leonardoarroyo** [comment] 2020-04-20 03:23
Okay, I was able to get it working by running `dokku config:set DOKKU_PROXY_PORT_MAP=http:80:4000` without the app name. It's confusing because `dokku config:help` seems to indicate I need to either supply an app name or a --global flag.

I still don't know why I can't use `dokku proxy:ports-add`, I got the env variable solution from [here](https://github.com/dokku/dokku-redirect/issues/19).

**Comment by leonardoarroyo** [comment] 2020-04-30 01:49
Hello Jose, thanks for the response. Yes, I was using the local client, not the one on the server and indeed that was the issue. Everything worked well once I removed the app name.
Maybe the client could omit the app name parameter when issuing commands such as `dokku config:help` inside a git repository with dokku set up?

**Comment by josegonzalez** [comment] 2020-05-01 16:00
The feature of the remote client is to auto-inject the app parameter by setting the `--app` flag, so I don't think that makes sense. Updating the `help` output is kind of a non-starter because that would require re-parsing the output locally, or duplicating help remotely.

This Dokku install is also a bit older. Newer versions of Dokku have proper validation on the port input. As such, I'm going to close this as wontfix, since the thing that is "breaking" is actually a feature of that remote client - not a bug - and there isn't anything else we could do for this.

**Closed by josegonzalez** 2020-05-01 16:00 UTC
