### ISSUE TITLE
Git remote with full path messes with the container name

### ISSUE THREAD

**Issue by haggen** [dokku/dokku#2807] opened 2017-06-14 03:34 UTC
I'm using a different SSH port so I had to change my repository remote from SCP format:

    dokku@example.org:my-app

To SSH format:

    ssh://dokku@example.org:1234/home/dokku/my-app

Now every time I push I'm getting this:

    remote: Error response from daemon: Error when allocating new name: Invalid container name (/home/dokku/my-app.web.1), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

To me it's clear that dokku is trying to figure out the container name using the whole path part of the remote address but it's failing since now it contains slashes.

Maybe simply splitting the path by `/` and using the very last part could work this out?

**Comment by michaelshobbs** [comment] 2017-06-14 03:40
This is the remote format we use in our [test suite](https://github.com/dokku/dokku/blob/0e08134a7c86116dd8631efd0162c910e7b83188/tests/unit/40_core_2.bats#L79)
```
ssh://dokku@example.org:22333/my-app
```

**Comment by josegonzalez** [comment] 2017-06-14 07:35
Shouldn't we error immediately on that app name, @michaelshobbs ?

**Comment by haggen** [comment] 2017-06-14 12:31
@michaelshobbs Oh my bad. Thank you very much! 🍻 
@josegonzalez Yea it seems weird that dokku accepted my push even though the repository path was invalid.

**Comment by michaelshobbs** [comment] 2017-06-14 15:11
> Shouldn't we error immediately on that app name, @michaelshobbs ?

That would be in the git plugin. Perhaps we're not doing the app check there.

**Comment by josegonzalez** [comment] 2017-08-19 23:18
Closing as there is a pull request available.

**Closed by josegonzalez** 2017-08-19 23:18 UTC
Labels: level: easy, type: bug

**Comment by PAStheLoD** [comment] 2017-11-22 14:19
Hello,

I'm 100% sure, but I think the fix is not working as intended.

I cannot see the "(core) git-remote (off-port)" test in the CI output, and currently doing a git fetch on a working app with a SSH URI causes it to be deleted. (Because it fails the name validation.)

So, push currently works (0.10.5), but fetch doesn't.

Adding this line to `is_valid_app_name` (in core-plugins/available/common/functions) after the first if seems to solve the problem:

```
  if [[ "${APP:0:1}" = "/" ]] ; then APP="${APP:1}" ; fi
```

**Comment by josegonzalez** [comment] 2017-11-22 16:24
@PAStheLoD the change for fetch hasn't been released to master, so thats why it would still be broken for fetch.

**Comment by PAStheLoD** [comment] 2017-11-23 14:55
Oops, I haven't checked that! Thanks! (I use the very helpful Debian/Ubuntu package/repo.)
