### ISSUE TITLE
Create extendable nginx config for portability

### ISSUE THREAD

**Issue by enjikaka** [dokku/dokku#2138] opened 2016-04-23 17:31 UTC
Adding

```
ssl_trusted_certificate {{ .DOKKU_ROOT }}/{{ .APP }}/letsencrypt/certs/current/fullchain.pem;
```

can't be done efficiently since:

- You can't add stuff to you repo that end up in `<dokku_app>/nginx.conf.d/`
- `<dokku_app>/nginx.conf` cannot be extended. And creating a nginx.cong.sigil thats identical to the default with the only difference being the staplin', ain't a good solution.

**Comment by josegonzalez** [comment] 2016-04-23 17:34
What do you propose we do here? Your second solution seems reasonable to me, we don't often change the default.

**Comment by enjikaka** [comment] 2016-04-23 17:42
Imagine I have 10 dokku apps, each running with Let's Encrypt on them. (via the plugin) I want OSCR stapling on them, and other shard SSL configurations.

Manually creating files to enable this in each apps `nginx.conf.d/` is too cumbersome. So it creating a `nginx.cong.sigil` for each one of them, since they do not have one already. I tried tinkering with /etc/nginx/conf.d/dokku.conf but it had no affect. Neither did adding things to /etc/nginx/nginx.conf.

If I remember correctly. There was another way for templating in 0.4.12, and in that template (that each app inherited) I added stapling and it worked. I can not find such a template in 0.5.5 though.

What are the expected ways from you guys to handle this?  `nginx.conf.d/` and `nginx.cong.sigil`? They aren't good enough...

**Comment by josegonzalez** [comment] 2016-04-23 17:49
You add the `nginx.conf.sigil` to each service's root repository. We never had a "global" override in 0.4.x, and we removed the ability to set the conf on disk instead of the repo as it was error prone and such configuration should be contained within your application.

**Comment by enjikaka** [comment] 2016-04-23 17:52
Somewhere there must be a default template dokku uses to generate the nginx.conf in my app. Can I not change that? Why? Can you enable change in that case?

**Comment by josegonzalez** [comment] 2016-04-23 17:58
Yes, there is a default template in the core plugin. We don't currently have plans to make that configurable.

By default, it includes configuration in `/home/dokku/APP/nginx.conf.d/`.

Is there a reason you cannot just change your default `nginx.conf.sigil` in every app, other than "I don't want to do it `N` times"?

In an ideal world, what would you implement to "solve" your problem?

**Comment by enjikaka** [comment] 2016-04-23 18:12
_Is there a reason you cannot just change your default nginx.conf.sigil in every app, other than "I don't want to do it N times"?_

The reason I don't want to change my default `nginx.conf.sigil` is because I do not have one. In any of my apps. If I were to go this path I first need to try to make `nginx.conf.sigil` similar to the one Dokku generates, then add my stapling, find or checkout all repos for my apps, change them, push them (rebuild all apps again, which doesn't feel efficient for changing a nginx config). I image my apps should be able to share the NGINX SSL config I set, which are to be the same among them. "Doing stuff N times is" what we are making computer programs for. ;)

_In an ideal world, what would you implement to "solve" your problem?_

One of these:
- Make dokku-letsencrypt add it in the apps nginx.conf when it adds the rest of the SSL conf.
- Make `ssl_trusted_certificate {{ .DOKKU_ROOT }}/{{ .APP }}/letsencrypt/certs/current/fullchain.pem;` (i.e. templating) to work for files in `/home/dokku/APP/nginx.conf.d/`. Then I could just copy them to each app and it would work. (Maybe even symlink then?) Without templating (i.e. today), I'd also have to change the dokku app name. And when dokku fucks up again and I need to reinstall everything on a new VPS. I need to redo this. Again. And again. And again.
- Last step but make it possible to add templated conf files to `/home/dokku/APP/nginx.conf.d/` via the repo
- Make the default template extensible, via for example a server.conf in the repo which is injected into the nginx.conf's server block in my app.

**Comment by josegonzalez** [comment] 2016-04-23 18:17
Would you be willing to implement the above functionality? I can help guide you through the relevant PRs.

**Comment by josegonzalez** [comment] 2016-04-23 18:19
Also, would be great if you can explain what you mean by "when dokku fucks up". Seems like you have a bit of rage around how dokku works, and we can't really solve those issues without knowing what they are.

**Comment by enjikaka** [comment] 2016-04-23 18:41
I don't think I have time, nor the experience with the languages used in this repo. Sorry. I can probably try some weekend though, but I don't want to promise something I maybe can't do. :)

_Also, would be great if you can explain what you mean by "when dokku fucks up". Seems like you have a bit of rage around how dokku works, and we can't really solve those issues without knowing what they are._

Each Dokku updated I've tried on my VPS has resulted in troubles for me. Only done it 2-3 times though. Lastly, today, from 0.4.12->0.5.5, this was my flow, with backstory:

- Me thinking: "I wonder if I can push to dokku without it building my apps on each push, doesn't feel necessary when I only need to change the background color on my website, and thus only the CSS file changes..."
- I google "git repo in dokku" and end up here: https://github.com/dokku/dokku/issues/116
- Concludes this is not helping me
- I google "update files in dokku without building"
- Got here: http://dokku.viewdocs.io/dokku/troubleshooting/
- Concludes this is not helping me
- Goes to http://dokku.viewdocs.io/dokku/installation/
- See newer version is out
- Tries to update
- Runs `apt-get update`
- Dokku fails with `E: Sub-process /usr/bin/dpkg returned an error code (1)`
- Didn't see that error and though I was on 0.5.0
- I test my sites
- All sites running via Dockerfile with `ÈXPOSE 80` is broken. Gets the wrong cert. Namely the cert for the first Dokku app in alphabetical order.
- Make issue: https://github.com/dokku/dokku-letsencrypt/issues/51
- Google "Sub-process /usr/bin/dpkg returned an error code (1)" like hell
- Ended up here http://askubuntu.com/questions/688338/e-sub-process-usr-bin-dpkg-returned-an-error-code-1-related-to-google-chrom
- Ran `sudo rm /etc/apt/sources.list`
- Ran `sudo software-properties-gtk` (didn't work)
- Google "dpkg: error processing package dokku (--configure):"
- Ended up here: https://github.com/dokku/dokku/issues/1205
- Didn't find a solution
- Made issue https://github.com/dokku/dokku/issues/2137
- Ended up here: https://github.com/dokku/dokku/issues/946
- Didn't find a solution
- Ended up here: https://github.com/dokku/dokku/issues/1203
- Didn't find a solution
- Ended up here: https://github.com/dokku/dokku/issues/1387
- Didn't find a solution
- Find this: https://github.com/dokku/dokku/issues/2059
- Try to update nginx
- Dokku fails with `E: Sub-process /usr/bin/dpkg returned an error code (1)`
- Try to apt-get update, went fine
- Try to apt-get upgrade
- Dokku fails with `E: Sub-process /usr/bin/dpkg returned an error code (1)`
- Removed `/etc/apt/sources.list.d/nginx.list`
- Try to apt-get dist-upgrade
- Dokku fails with `E: Sub-process /usr/bin/dpkg returned an error code (1)`
- Removes nginx (Dokku was also removed, that was a surprise)
- Try to apt-get update, went fine
- Try to apt-get upgrade
- Try to apt-get dist-upgrade
- Looks good.
- Try to install Dokku.
- Doesn't work. (don't remember output here, sorry)
- Tried 10 times.
- Realises removal of `/etc/apt/sources.list` might have done harm
- Adds things back in `/etc/apt/sources.list`
- Try to apt-get update, went fine
- Try to apt-get upgrade
- Try to apt-get dist-upgrade
- Looks good.
- Try to install Dokku.
- Works.

**Comment by josegonzalez** [comment] 2016-04-23 18:48
Dokku is just shell scripting, I believe in you! :)

- If you'd like to skip a deployment, [see here](http://dokku.viewdocs.io/dokku/application-deployment/#skipping-deployment).
- We ship breaking changes in minor releases (once we hit a 1.0.0, it'll be major releases). We have upgrade notes [here](http://dokku.viewdocs.io/dokku/upgrading/), and specifically called out a bunch of gotchas for [0.5.0 here](http://dokku.viewdocs.io/dokku/appendices/0.5.0-migration-guide/). We definitely *hate* breaking backwards compatibility and did not make these changes lightly.
- We have an open issue for upgrading when you are using nginx `1.9.x`. I haven't yet had time to debug whats going on there, but I suspect it has something to do with the fact that we install our own nginx apt repo in the nginx-vhosts plugin.

We've certainly gotten better at making upgrades more seamless, but I'd always suggest taking a look at release notes, especially between our minor releases. Patch releases *shouldn't* have breaking changes, but when they do, we fix them and then add tests for whatever feature was broken that didn't already have tests.

**Comment by enjikaka** [comment] 2016-04-23 19:16
Just putting "You can not have nginx 1.9.x" in install/upgrade notes and saying "Change your application to listen on the PORT env variable or expose 5000 in your Dockerfile" instead of "Dockerfiles with EXPOSE clauses will get all tcp ports proxied by default" would have saved me 6 hours today.

Make notes suitable for dumb humans like me!

**Comment by abulava** [comment] 2016-04-25 21:12
@enjikaka mentioned a lack of a management tool for <dokku_app>/nginx.conf.d/ and @sseemayer referenced OSCP Stapling. Well, my humble input addressing the issue is [dokku-nginx-conf.d-files](https://github.com/abulava/dokku-nginx-conf.d-files) plugin (beware, it's been developed for pre-0.5.0 Dokku without support for templates).

Probably, my README needs some real world examples. Here it is for my customized SSL setup:

```shell
cat <<EOF | $REMOTE_DOKKU_COMMAND nginx:conf.d:add $APP ssl.conf
ssl_ciphers 'EECDH+AESGCM:AES256+EECDH:AES128-SHA:AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:DES-CBC3-SHA';

# HSTS
add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
EOF
```

It handles OSCP Stapling setup in a similar way. Sure thing, "/home/dokku/$APP/nginx.conf.d" path is interpolated before running $REMOTE_DOKKU_COMMAND, so I don't need support for server-side templates.

**Comment by sseemayer** [comment] 2016-04-26 09:04
@enjikaka would you be interested in contributing a PR to the [0.5 migration guide](https://github.com/dokku/dokku/blob/master/docs/appendices/0.5.0-migration-guide.md)? You could clarify the Dockerfile deployment changes and help the next person encountering these problems.

As discussed in dokku/dokku-letsencrypt#52 and mentioned by @abulava , placing a custom config in the app's `nginx.conf.d` folder will include it in the 'server' section of the nginx config and thus take care of the OCSP stapling use case and other custom nginx SSL configuration. 

IMO it's easy and elegant enough to place a file into `nginx.conf.d` so I'm not sure if we need other more complicated config customization features.

@enjikaka ,  if you want this automated, it would make sense for you to implement the functionality to add config files to `nginx.conf.d` from the git repository. Have a look at how files from the app's git repository are accessed in the [CHECKS file mechanism](https://github.com/dokku/dokku/blob/master/plugins/checks/check-deploy#L77-L80) as a starting point. This could reasonably be a nice first-time contribution to dokku/dokku or would also be a nice enhancement for [dokku-nginx-conf.d-files](https://github.com/abulava/dokku-nginx-conf.d-files) .

**Comment by enjikaka** [comment] 2016-04-26 19:24
@sseemayer I'll see if I can manage to get time for it this weekend. :)

**Comment by pythdasch** [comment] 2016-06-01 13:53
Hi everyone @enjikaka did you have some time to add to the dock the dockerfile migration ? Because I'm not a pro in all this configs and don't know exactly what to do ...

Thanks in advance.
I just would like to increase the client_max_body_size

**Comment by sseemayer** [comment] 2016-06-01 14:35
@pythdasch check out [this section in the dokku documentation](http://dokku.viewdocs.io/dokku/nginx/#customizing-via-configuration-files-included-by-the-default-tem) - it literally uses your use case as the example :)

**Comment by pythdasch** [comment] 2016-06-01 15:31
@sseemayer Oh thanks ! didn't see this !

**Comment by enjikaka** [comment] 2016-06-02 13:45
I haven' had time to check yet.

**Comment by josegonzalez** [comment] 2016-06-18 03:24
@michaelshobbs thoughts on dropping that extra source call completely? Given that there hasn't been movement on this *and* we provide a pretty robust way for developers to override the dokku config file, I don't see the utility in adding support for copying yet more files from the main repo into the top-level, especially given the removal of each sub-template in 0.6.x.

**Comment by josegonzalez** [comment] 2016-06-18 04:40
I've spoken offline with others on the core team, and I think we're going to close this issue for the following reasons:

- The entrypoint (adding files to that directory) is a nice feature for users, so we shouldn't remove it.
- There is a plugin from the community (thanks @abulava!) to handle this issue.
  - Copying from within the letsencrypt plugin doesn't seem like a good place.
- Creating a custom `nginx.conf.sigil` is not very different from creating a custom `nginx.conf.d/ssl.sigil`. In 0.6.x, we don't have several template files, so knowing what _should_ be in that file is easier.

Closing as I don't think there is anything further we should do here at the moment.

**Closed by josegonzalez** 2016-06-18 04:40 UTC
Labels: type: enhancement
