### ISSUE TITLE
dokku:certs - CSR not re-generated if domain is already linked to app

### ISSUE THREAD

**Issue by codyyc** [dokku/dokku#2298] opened 2016-07-05 08:16 UTC
Description of problem:

If you generate a CSR using `certs:generate [APP] [URL]` then remove it using `certs:remove [APP]`, when trying to generate a new one using `certs:generate` it won't work if the domain name is linked to the app already.

For example:
`dokku certs:generate hello hello.com`
`dokku certs:remove hello`
`dokku certs:generate hello hello.com`

The last generate will end on a this domain is already connected' message and it's not immediately obvious why the key and cert aren't being generated.

This is more of an experience problem as it is resolvable and easy to reproduce.

**Comment by u2mejc** [comment] 2016-07-05 20:59
@codyyc Following your three steps, I'm unable to reproduce the issue, working off the master branch. Can you please complete the full ISSUE_TEMPLATE.md doc, including the associtate debug gist?

**Comment by u2mejc** [comment] 2016-07-12 18:12
@codyyc If you have a chance, can you please provide some more information about your environment and how to reproduce the issue? I'm happy to help if I can reproduce the issue.

**Comment by josegonzalez** [comment] 2016-08-26 23:34
Also not able to reproduce from the latest 0.7.0 release. Closing as there hasn't been movement in a while.

**Closed by josegonzalez** 2016-08-26 23:34 UTC
Labels: needs: more info
