### ISSUE TITLE
Poor throughput

### ISSUE THREAD

**Issue by meskyanichi** [dokku/dokku#1576] opened 2015-10-18 15:24 UTC
I've done some basic `wrk` benchmarks using type-1 Packet dedicated servers and I'm seeing poor results when using Dokku.

* Using Dokku: `1.2k rps`
* Using Docker (`docker run`): `200k rps`
* Using Host: `300k rps`

In all cases the CPU hits 100%.

My deployment process is simple (just an executable), and given the significant loss of `100.000 rps` even when using Docker directly, I'll probably end up simply using Upstart to manage the process in order to get the most out of the hardware.

Regardless, I just wanted to point this out in case someone else runs into throughput issues, to help narrow down the cause a little. Perhaps the bottleneck lies within the nginx configuration?

**Comment by michaelshobbs** [comment] 2015-10-18 17:55
1200 > 300 > 200?? I'm confused. Your issue details seem to indicate dokku performs the best. Out of curiosity, what are the correct numbers?

**Comment by meskyanichi** [comment] 2015-10-18 17:56
1.2k > 200k > 300k

**Comment by michaelshobbs** [comment] 2015-10-18 18:00
Ah! Got it. What version of dokku and docker did you test?

**Comment by meskyanichi** [comment] 2015-10-18 18:06
Dokku version 0.4.2 (latest). Sorry, I unfortunately forgot to check the Docker version that I used, but it was the one that ships with Dokku 0.4.2 (already terminated the servers).

**Comment by michaelshobbs** [comment] 2015-10-18 18:09
Any other configuration you can share? App details? Test scripts? (See edit in previous comment)

**Comment by meskyanichi** [comment] 2015-10-18 18:36
Sure.

This Go program emulates what was benchmarked:

```go
package main

import (
	"fmt"
	"net/http"
	"os"
)

var (
	HOST = os.Getenv("HOST")
	PORT = os.Getenv("PORT")
)

func main() {
	fmt.Printf("Listening on %s\n", PORT)
	http.HandleFunc("/", handler)
	http.ListenAndServe(HOST+":"+PORT, nil)
}

func handler(w http.ResponseWriter, r *http.Request) {
	return
}
```

For stand-alone deployment I just use `go build` and run it with:

```
PORT=3000 ./main
```

For use with Dokku I used `Procfile`:

```
web: ./main # PORT is already set by Dokku
```

---

I spawned two dedicated servers from Packet.net (Type-1). I have have used them as-is, with no additional configuration after deployment (other than installing `dokku` and `wrk`).

**On server A:** I installed Dokku as per usual following the "Getting Started" guide, and deployed the above-mentioned application to it. Then I added a custom domain to it to get `<appname>.example.com`.

**On server B:** I installed [wrk](https://github.com/wg/wrk) and simply ran:

```
wrk -t 8 -c 500 http://<appname>.example.com
```

This is what yields `1.2k rps` with a bunch of non-2xx/3xx HTTP responses.

---

After that, on **ServerA**, I `docker images` to find the image of the currently running container, and used that to use Docker directly.

```
docker run --env-file=./env -p 3000:3000 -ti dokku/appname /start web
```

The `./env` file simply contains:

```
PORT=3000
```

Then from **Server B** I run `wrk` again:

```
wrk -t 8 -c 500 http://example.com:3000
```

This yields `200k rps` without issues.

---

Then I tried to run executable without any containerization on **Server A**:

```
PORT=3000 ./main 
```

Again, from **Server B** I run `wrk`:

```
wrk -t 8 -c 500 http://example.com:3000
```

This yields `300k rps` without issues.

---

Unless I missed something, or made a typo, this should be the gist of it.

**Comment by michaelshobbs** [comment] 2015-10-18 22:45
Excellent! Thank you for the detail.

**Comment by josegonzalez** [comment] 2015-10-18 22:53
Maybe relevant to our own nginx tuning: https://gist.github.com/hgfischer/7965620

**Comment by josegonzalez** [comment] 2015-10-24 11:13
I just played around with this a bit. At least when containers are involved on my test 512mb instance, I am not reaching anywhere near the numbers he is seeing. At least the container traffic is within range (4.5x) of the dokku container traffic.

There are a few things we can do to 3x our performance, but at least a small part of the problem is the `docker-proxy` we are using. I see an increase the perf of container-based deployment by avoiding containerizing the network stack as mentioned [here via `--net=host`](https://docs.docker.com/articles/networking/#container-networking). No idea if that overhead can be avoided somehow.

Summary table

| type | Requests/sec | Transfer/sec |
| ------|--------------------|------------------|
| dokku container: nginx | 1449.23 | 219.40KB |
| dokku container: nginx (upstream keepalive 300) | 3343.11 | 506.04KB |
| dokku container: nginx (upstream keepalive 300, worker_rlimit_nofile 200000, worker_connections 10000, use epoll, multi_accept on) | 3939.13 | 596.25KB |
| dokku container: nginx (upstream keepalive 300, worker_rlimit_nofile 200000, worker_connections 10000, use epoll, multi_accept on, no logging, no gzip) | 4387.63 | 664.14KB |
| dokku container | 5630.84 | 637.87KB |
| straight container homie | 5830.85 | 660.53KB |
| straight container homie: host networking | 6761.65 | 765.97KB |
| straight bin homie | 10366.96 | 1.15MB |

<sup>*non-scientific, result pulled at random from several attempts at each type</sup>

Raw results:

---

dokku container: nginx

```
Running 10s test @ http://go-test.dokku.josediazgonzalez.com
  8 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   231.73ms  228.18ms   2.00s    91.82%
    Req/Sec   242.25     88.67   470.00     72.32%
  14617 requests in 10.09s, 2.16MB read
  Socket errors: connect 0, read 364, write 0, timeout 112
  Non-2xx or 3xx responses: 2
Requests/sec:   1449.23
Transfer/sec:    219.40KB
```

dokku container: nginx (upstream keepalive 300)

```
Running 10s test @ http://go-test.dokku.josediazgonzalez.com
  8 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   128.77ms  118.31ms   1.99s    95.06%
    Req/Sec   439.40    127.16     0.93k    72.05%
  33768 requests in 10.10s, 4.99MB read
  Socket errors: connect 0, read 316, write 0, timeout 121
Requests/sec:   3343.11
Transfer/sec:    506.04KB
```

dokku container: nginx (upstream keepalive 300, worker_rlimit_nofile 200000, worker_connections 10000, use epoll, multi_accept on)

```
Running 10s test @ http://go-test.dokku.josediazgonzalez.com
  8 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   128.43ms  126.62ms   1.79s    97.46%
    Req/Sec   532.97    115.39   800.00     75.64%
  39784 requests in 10.10s, 5.88MB read
  Socket errors: connect 0, read 0, write 0, timeout 2
Requests/sec:   3939.13
Transfer/sec:    596.25KB
```

dokku container: nginx (upstream keepalive 300, worker_rlimit_nofile 200000, worker_connections 10000, use epoll, multi_accept on, no logging, no gzip)

```
Running 10s test @ http://go-test.dokku.josediazgonzalez.com
  8 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   124.52ms  150.49ms   2.00s    95.80%
    Req/Sec   583.96    108.45   820.00     72.45%
  44247 requests in 10.08s, 6.54MB read
  Socket errors: connect 0, read 8, write 0, timeout 6
Requests/sec:   4387.63
Transfer/sec:    664.14KB
```

dokku container

```
Running 10s test @ http://go-test.dokku.josediazgonzalez.com:5000
  8 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    95.48ms   85.01ms   1.26s    96.06%
    Req/Sec   721.27    151.82     1.05k    77.78%
  56580 requests in 10.05s, 6.26MB read
Requests/sec:   5630.84
Transfer/sec:    637.87KB
```

straight container homie

```
Running 10s test @ http://go-test.dokku.josediazgonzalez.com:3000
  8 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    96.62ms   98.87ms   1.76s    95.15%
    Req/Sec   748.12    171.07     1.21k    82.86%
  58578 requests in 10.05s, 6.48MB read
Requests/sec:   5830.85
Transfer/sec:    660.53KB
```

straight container homie: host networking

```
Running 10s test @ http://go-test.dokku.josediazgonzalez.com:3000
  8 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    38.42ms   29.54ms   1.82s    98.02%
    Req/Sec     0.88k   271.84     1.52k    66.28%
  67927 requests in 10.05s, 7.51MB read
  Socket errors: connect 0, read 0, write 0, timeout 1
Requests/sec:   6761.65
Transfer/sec:    765.97KB
```

straight bin homie

```
Running 10s test @ http://go-test.dokku.josediazgonzalez.com:3001
  8 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    60.59ms  137.90ms   1.95s    96.26%
    Req/Sec     1.41k   371.15     2.10k    73.05%
  104295 requests in 10.06s, 11.54MB read
  Socket errors: connect 0, read 0, write 0, timeout 124
Requests/sec:  10366.96
Transfer/sec:      1.15MB
```

**Comment by josegonzalez** [comment] 2015-10-24 20:16
Note: I built the binary inside the container and then copied it out of the container.

**Comment by josegonzalez** [comment] 2016-03-18 14:32
Closing. Configuring nginx to work out of the box for every situation is outside of the scope of dokku, and I believe we've documented the fact that people should configure nginx for their use case/resources.

**Closed by josegonzalez** 2016-03-18 14:32 UTC
Labels: type: question

**Comment by josegonzalez** [comment] 2017-05-13 05:58
Update: Seems the docker throughput has gotten better over the years: https://jtway.co/docker-network-performance-b95bce32b4b9

**Comment by AlexBlokh** [comment] 2021-08-25 11:20
@josegonzalez how do I config `upstream keepalive` value through dokku nginx config? Is using `sigil` template is the only way?

**Comment by josegonzalez** [comment] 2021-08-25 14:13
@AlexBlokh mind opening a new issue? This one is 4 years old now…
