### ISSUE TITLE
Vector logging mount point in docs is wrong

### ISSUE THREAD

**Issue by tdeck** [dokku/dokku#4469] opened 2021-03-10 07:11 UTC
## Description of problem

My dokku version is 0.24.1 with docker 18.09.7. I'm describing my issue in full in case others have the same one, although I found a workaround (see below).

I was trying to use the new vector logging support to stream my logs to disk in a way that will persist between deploys.

I ran these commands against my container

`dokku logs:set APP vector-sink 'file://?encoding=text&path=/var/log/dokku/apps/APP.log`
`dokku logs:vector-start`

No logs appear in /var/log/dokku/apps/APP.log

While inspecting the Vector logging container, I discovered this was because the source does not match the documentation. The docs say this:

And the container config says this:
```
            {
                "Type": "bind",
                "Source": "/var/log/dokku",
                "Destination": "/var/logs/dokku/apps",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
```

> The vector container will be started with the following volume mounts:
> 
>     /var/lib/dokku/data/logs/vector.json:/etc/vector/vector.json
>     /var/run/docker.sock:/var/run/docker.sock
>     /var/log/dokku/apps:/var/log/dokku/apps
> 
> The final volume mount - /var/log/dokku/apps - may be used for users that wish to ship logs to a file on disk that may be later logrotated. This directory is owned by the dokku user and group, with permissions set to 0755. At this time, log-rotation is not configured for this directory.

Note the differences. First of all, in the container the directory is `/var/logs` with an "s". Secondly, it has the `/apps` suffix which isn't present on the host.

I can probably put together a PR to fix this, but I'm not sure if that would break things for others who are working around the issue today. At any rate, the workaround was to simply log into `/var/logs/dokku/apps/apps` in my log sink.

**Comment by LoranKloeze** [comment] 2021-03-12 11:24
I can confirm this (0.24.1)
![image](https://user-images.githubusercontent.com/12978070/110933802-826ed280-832d-11eb-9a93-ee61201a8265.png)
If you ask me, I'd rather see an update in the docs then a fix in the mount because, like @tdeck says, this will break current configs.
Or add a second mount with the correct directories?

**Comment by josegonzalez** [comment] 2021-03-12 11:31
Closing as there is a pull request open.

**Closed by josegonzalez** 2021-03-12 11:31 UTC
Labels: type: bug
