### ISSUE TITLE
Previous images are not cleaned up on git push.

### ISSUE THREAD

**Issue by samgclarke** [dokku/dokku#1740] opened 2015-12-02 21:49 UTC
Whenever I push an new commit to my Dokku server a new image is generated. More specifically it seems that the old image is not cleaned up automatically. This  get this:

    $ docker images
    dokku/myapp                latest              7b0263338afc        About a minute ago   1.574 GB
	<none>                     <none>              d11c6f58fa03        About 15 minutes ago 1.533 GB
	<none>                     <none>              eef0bd3d3a70        About an hour ago    1.534 GB
	<none>                     <none>              4821172d7f4d        1 week ago           1.535 GB
	<none>                     <none>              a75d40b4fd46        1 week ago           1.539 GB
	<none>                     <none>              786d7263d237        1 week ago           1.532 GB
	<none>                     <none>              57e84c5a8015        2 weeks ago          1.528 GB
	<none>                     <none>              741df46bad32        2 weeks ago          1.511 GB
	gliderlabs/herokuish       latest              7ffe793a54a3        7 weeks ago          1.285 GB
	redis                      3.0.4               ddd1d8d3317a        7 weeks ago          109.3 MB
	svendowideit/ambassador    latest              7feb6b1d3d04        7 weeks ago          6.454 MB
	heroku/cedar               14                  59c44b748d4a        8 weeks ago          1.265 GB
	dokkupaas/wait             latest              c0df71274c7a        10 weeks ago         1.096 MB
	postgres                   9.4.4               eddb1e6071fb        11 weeks ago         265.3 MB
	gliderlabs/logspout        latest              162bb99d02d4        8 months ago         13.84 MB
	<none>                     <none>              9187d5605e70        2 weeks ago          13.84 MB    13.84 MB

This extremely frustrating as disk space rapidly fills up with these images.

`$ dokku cleanup` doesn't seem to do anything.

If I try and remove the offending images:

    $ docker images | grep '<none>' |  awk '{print $3}'  | xargs docker rmi
    Error response from daemon: Conflict, cannot delete d11c6f58fa03 because the container 0a63c389f59f is using it, use -f to force
	Error response from daemon: Conflict, cannot delete eef0bd3d3a70 because the container e058a5e87961 is using it, use -f to force
	Error response from daemon: Conflict, cannot delete 4821172d7f4d because the container ae47afdb958b is using it, use -f to force
	Error response from daemon: Conflict, cannot delete a75d40b4fd46 because the container e34e296512f3 is using it, use -f to force
	Error response from daemon: Conflict, cannot delete 786d7263d237 because the container 2274100a3d93 is using it, use -f to force
	Error response from daemon: Conflict, cannot delete 57e84c5a8015 because the container 0bd0a2776e83 is using it, use -f to force
	Error response from daemon: Conflict, cannot delete 741df46bad32 because the container 0a4559f5ddb5 is using it, use -f to force
	Error response from daemon: Conflict, cannot delete 9187d5605e70 because the running container 50ae92ebfb3f is using it, stop it and use -f to force
	Error: failed to remove images: [d11c6f58fa03 eef0bd3d3a70 4821172d7f4d a75d40b4fd46 786d7263d237 57e84c5a8015 741df46bad32 9187d5605e70]

So if I look at the containers:

     CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                      PORTS                       NAMES
	d2e437bb5266        dokku/myapp:latest   "/exec python"           39 hours ago        Exited (0) 39 hours ago                                 drunk_elion
	606b13709e18        dokku/myapp:latest   "/start web"             39 hours ago        Up 39 hours                                             myapp.web.1
	de8e38bb9cc6        dokku/myapp:latest   "/bin/bash -c 'cat > "   39 hours ago        Exited (0) 39 hours ago                                 jolly_ramanujan
	f3f6e1c7da05        dokku/myapp:latest   "/bin/bash -c 'if [[ "   39 hours ago        Exited (0) 39 hours ago                                 cocky_goldstine
	746bbd60b449        dokku/myapp:latest   "/usr/bin/dpkg -s sup"   39 hours ago        Exited (0) 39 hours ago                                 loving_visvesvaraya
	94d88e41b846        dokku/myapp:latest   "/bin/bash -c 'cat > "   39 hours ago        Exited (0) 39 hours ago                                 insane_mayer
	dce1316804d4        dokku/myapp:latest   "test -f app/Procfile"   39 hours ago        Exited (0) 39 hours ago                                 admiring_goodall
	81d7a10a2cf5        dokku/myapp:latest   "/bin/bash -c 'cat > "   39 hours ago        Exited (0) 39 hours ago                                 elated_nobel
	f53e74ff4aaa        dokku/myapp:latest   "/bin/bash -c 'mkdir "   39 hours ago        Exited (0) 39 hours ago                                 modest_hypatia
	18465ac257e9        dokku/myapp:latest   "/bin/bash -c 'mkdir "   39 hours ago        Exited (0) 39 hours ago                                 thirsty_aryabhata
	f68587586157        dokku/myapp:latest   "/exec bash"             39 hours ago        Exited (127) 39 hours ago                               romantic_hypatia
	1939d1af6c31        dokku/myapp:latest   "/start web"             39 hours ago        Exited (0) 39 hours ago                                 myapp.web.1.1448949245
	41bd8729db79        dokku/myapp:latest   "/bin/bash -c 'cat > "   39 hours ago        Exited (0) 39 hours ago                                 dreamy_bohr
	bbc0d9796c71        dokku/myapp:latest   "/bin/bash -c 'if [[ "   39 hours ago        Exited (0) 39 hours ago                                 backstabbing_poitras
	8653ee62e395        dokku/myapp:latest   "/usr/bin/dpkg -s sup"   39 hours ago        Exited (0) 39 hours ago                                 tender_blackwell
	0b3787dd1e00        dokku/myapp:latest   "/bin/bash -c 'cat > "   39 hours ago        Exited (0) 39 hours ago                                 adoring_pare
	e6bbeb79f064        dokku/myapp:latest   "test -f app/Procfile"   39 hours ago        Exited (0) 39 hours ago                                 adoring_goldstine
	a1e64b48dc0c        dokku/myapp:latest   "/bin/bash -c 'cat > "   39 hours ago        Exited (0) 39 hours ago                                 backstabbing_meitner
	a1f4d8c8748b        dokku/myapp:latest   "/bin/bash -c 'mkdir "   39 hours ago        Exited (0) 39 hours ago                                 hopeful_engelbart
	2faa5028c0ea        dokku/myapp:latest   "/bin/bash -c 'mkdir "   39 hours ago        Exited (0) 39 hours ago                                 hungry_yalow
	25c2e05effa7        dokku/myapp:latest   "/start web"             39 hours ago        Exited (0) 39 hours ago                                 myapp.web.1.1448949007
	38fe53e8c0cf        dokku/myapp:latest   "/bin/bash -c 'cat > "   39 hours ago        Exited (0) 39 hours ago                                 elegant_ardinghelli
	868caefc49cf        dokku/myapp:latest   "/bin/bash -c 'if [[ "   39 hours ago        Exited (0) 39 hours ago                                 silly_mahavira
	f26c3bba512c        dokku/myapp:latest   "/usr/bin/dpkg -s sup"   39 hours ago        Exited (0) 39 hours ago                                 nostalgic_almeida
	13ea423cb350        dokku/myapp:latest   "/bin/bash -c 'cat > "   39 hours ago        Exited (0) 39 hours ago                                 berserk_yonath
	a3d956da7a69        dokku/myapp:latest   "test -f app/Procfile"   39 hours ago        Exited (0) 39 hours ago                                 goofy_perlman
	7f66e4079722        dokku/myapp:latest   "/bin/bash -c 'cat > "   39 hours ago        Exited (0) 39 hours ago                                 furious_ptolemy
	8fda718aaf5e        dokku/myapp:latest   "/bin/bash -c 'mkdir "   39 hours ago        Exited (0) 39 hours ago                                 stoic_bohr
	9c1f9aa970db        dokku/myapp:latest   "/bin/bash -c 'mkdir "   39 hours ago        Exited (0) 39 hours ago                                 cocky_albattani
	3132fb9e8d52        dokku/myapp:latest   "/start web"             39 hours ago        Exited (0) 39 hours ago                                 myapp.web.1.1448948978
	0092b328e0c9        dokku/myapp:latest   "/bin/bash -c 'cat > "   39 hours ago        Exited (0) 39 hours ago                                 loving_sammet
	5dbbd96c7dfd        dokku/myapp:latest   "/bin/bash -c 'if [[ "   39 hours ago        Exited (0) 39 hours ago                                 grave_engelbart
	6a3163ba080a        dokku/myapp:latest   "/usr/bin/dpkg -s sup"   39 hours ago        Exited (0) 39 hours ago                                 trusting_darwin
	9811d1666468        dokku/myapp:latest   "/bin/bash -c 'cat > "   39 hours ago        Exited (0) 39 hours ago                                 pensive_morse
	fcf4ba64650f        dokku/myapp:latest   "test -f app/Procfile"   39 hours ago        Exited (0) 39 hours ago                                 lonely_blackwell
	e437380f2466        dokku/myapp:latest   "/bin/bash -c 'cat > "   39 hours ago        Exited (0) 39 hours ago                                 mad_raman
	4e9f00e87e18        dokku/myapp:latest   "/bin/bash -c 'mkdir "   39 hours ago        Exited (0) 39 hours ago                                 modest_kalam
	3e9bc6106f8d        dokku/myapp:latest   "/bin/bash -c 'mkdir "   39 hours ago        Exited (0) 39 hours ago                                 nostalgic_sinoussi
	35820dbf85d5        dokku/myapp:latest   "/exec bash"             39 hours ago        Exited (1) 39 hours ago                                 determined_noyce
	00ee96e8f13c        dokku/myapp:latest   "/start web"             39 hours ago        Exited (137) 39 hours ago                               myapp.web.1.1448948949
	c0eadc243a16        dokku/myapp:latest   "/bin/bash -c 'cat > "   39 hours ago        Exited (0) 39 hours ago                                 lonely_ptolemy
	f5093dcfd707        dokku/myapp:latest   "/bin/bash -c 'if [[ "   39 hours ago        Exited (0) 39 hours ago                                 reverent_turing
	e6d31a17a7e2        dokku/myapp:latest   "/usr/bin/dpkg -s sup"   39 hours ago        Exited (0) 39 hours ago                                 insane_wozniak
	b3c8d616de79        dokku/myapp:latest   "/bin/bash -c 'cat > "   39 hours ago        Exited (0) 39 hours ago                                 condescending_cori
	852c51fad631        dokku/myapp:latest   "test -f app/Procfile"   39 hours ago        Exited (0) 39 hours ago                                 hungry_carson
	5265d1bab439        dokku/myapp:latest   "/bin/bash -c 'cat > "   39 hours ago        Exited (0) 39 hours ago                                 desperate_brahmagupta
	b395f381df2a        dokku/myapp:latest   "/bin/bash -c 'mkdir "   39 hours ago        Exited (0) 39 hours ago                                 happy_wilson
	b5ddf2a21a15        dokku/myapp:latest   "/bin/bash -c 'mkdir "   39 hours ago        Exited (0) 39 hours ago                                 hopeful_hodgkin
	7483cc89f85f        dokku/myapp:latest   "/exec bash"             39 hours ago        Exited (1) 39 hours ago                                 stupefied_mccarthy
	6db1b90cfb30        dokku/myapp:latest   "/start web"             39 hours ago        Exited (0) 39 hours ago                                 myapp.web.1.1448948850
	0c6c2470668b        dokku/myapp:latest   "/bin/bash -c 'cat > "   39 hours ago        Exited (0) 39 hours ago                                 pensive_mclean
	66f9c786134c        dokku/myapp:latest   "/bin/bash -c 'if [[ "   39 hours ago        Exited (0) 39 hours ago                                 thirsty_rosalind
	2e91b7eafcc8        dokku/myapp:latest   "/bin/bash -c 'apt-ge"   39 hours ago        Exited (0) 39 hours ago                                 pensive_hoover
	e8c443cf502a        dokku/myapp:latest   "/usr/bin/dpkg -s sup"   39 hours ago        Exited (1) 39 hours ago                                 romantic_yalow
	d5d16f4734bb        dokku/myapp:latest   "/bin/bash -c 'cat > "   39 hours ago        Exited (0) 39 hours ago                                 ecstatic_blackwell
	bc0207769a36        dokku/myapp:latest   "test -f app/Procfile"   39 hours ago        Exited (0) 39 hours ago                                 jolly_einstein
	62f539219ea1        dokku/myapp:latest   "/bin/bash -c 'cat > "   39 hours ago        Exited (0) 39 hours ago                                 nostalgic_babbage
	61adb000fb84        dokku/myapp:latest   "/bin/bash -c 'mkdir "   39 hours ago        Exited (0) 39 hours ago                                 lonely_brown
	2afe3d42cafa        dokku/myapp:latest   "/bin/bash -c 'mkdir "   39 hours ago        Exited (0) 39 hours ago                                 sick_wright
	5bd7d877f72a        dokku/myapp:latest   "/build"                 39 hours ago        Exited (0) 39 hours ago                                 naughty_brattain
	e688bfa23fc5        dokku/myapp:latest   "/bin/bash -c 'cat >>"   39 hours ago        Exited (0) 39 hours ago                                 thirsty_mayer
	01ef642cfdbd        dokku/myapp:latest   "/bin/bash -c 'for EN"   39 hours ago        Exited (0) 39 hours ago                                 hopeful_hoover
	46626acaeb49        gliderlabs/herokuish              "/bin/bash -c 'mkdir "   39 hours ago        Exited (0) 39 hours ago                                 loving_lalande
	0a63c389f59f        dokku/myapp:latest   "/start web"             5 weeks ago         Exited (0) 39 hours ago                                 myapp.web.1.1448948055
	50ae92ebfb3f        gliderlabs/logspout               "/bin/logspout"          5 weeks ago         Up 5 weeks                  127.0.0.1:18000->8000/tcp   logspout
	4f4ca06ca9e8        dokku/myapp:latest   "/start web"             5 weeks ago         Dead                                                    
	e058a5e87961        dokku/myapp:latest   "/start web"             6 weeks ago         Dead                                                    
	ae47afdb958b        dokku/myapp:latest   "/start web"             6 weeks ago         Dead                                                    
	e34e296512f3        dokku/myapp:latest   "/start web"             6 weeks ago         Dead                                                    
	2274100a3d93        dokku/myapp:latest   "/start web"             6 weeks ago         Dead                                                    
	0bd0a2776e83        dokku/myapp:latest   "/start web"             6 weeks ago         Dead                                                    
	c3f98614072e        dokku/myapp:latest   "/start web"             6 weeks ago         Dead                                                    
	0a4559f5ddb5        dokku/myapp:latest   "/start web"             6 weeks ago         Dead                                                    
	736bfb6e8330        redis:3.0.4                       "/entrypoint.sh redis"   6 weeks ago         Up 6 weeks                  6379/tcp                    dokku.redis.myapp
	732e2601a21a        postgres:9.4.4                    "/docker-entrypoint.s"   6 weeks ago         Up 6 weeks                  5432/tcp                    dokku.postgres.myapp

Where the `Dead` containers seem to correspond to the `<none>` images.

If I try to remove the containers:

    root@myapp:~# docker rm $(docker ps -a -f 'status=dead' -q)
	Error response from daemon: Cannot destroy container 4f4ca06ca9e8: Driver aufs failed to remove root filesystem 4f4ca06ca9e83b959fe79ffdb6775a8c4271424d5f401df7f774a460921d47c9: device or resource busy
	Error response from daemon: Cannot destroy container e058a5e87961: Driver aufs failed to remove root filesystem e058a5e87961d2e32f8023252dd773af3f20c110f7261207f885e387401f7c39: device or resource busy
	Error response from daemon: Cannot destroy container ae47afdb958b: Driver aufs failed to remove root filesystem ae47afdb958bf026a12999dda2d10439bc3a2229eeb3eef9af9deb14aca90424: device or resource busy
	Error response from daemon: Cannot destroy container e34e296512f3: Driver aufs failed to remove root filesystem e34e296512f3cc1259b4c26ede3b47ed5d68664574b6e3f70e7137c297db4c4c: device or resource busy
	Error response from daemon: Cannot destroy container 2274100a3d93: Driver aufs failed to remove root filesystem 2274100a3d937c5d65f6d890f8718180353fe47823afe52aa9f6a04168bbe890: device or resource busy
	Error response from daemon: Cannot destroy container 0bd0a2776e83: Driver aufs failed to remove root filesystem 0bd0a2776e832a3942ae099f7d8c33fcbb123da0ae23d991a2340832efb32f4e: device or resource busy
	Error response from daemon: Cannot destroy container c3f98614072e: Driver aufs failed to remove root filesystem c3f98614072e8ae45bef71e3156ac2e58b5cd560c6fe7857603e2ff11ce0791d: device or resource busy
	Error response from daemon: Cannot destroy container 0a4559f5ddb5: Driver aufs failed to remove root filesystem 0a4559f5ddb5dda58e26ccc2b22ee581763af3cf9202eadbe2412b344e63c910: device or resource busy
	Error: failed to remove containers: [4f4ca06ca9e8 e058a5e87961 ae47afdb958b e34e296512f3 2274100a3d93 0bd0a2776e83 c3f98614072e 0a4559f5ddb5]

My application is a Python web application with an AngularJS frontend running on Dokku0.4.5 on Digital Ocean.

I bootstrap my application using a bash script. Two relevant lines may be the following: 

    echo "setting up persisent storage..."
    dokku docker-options:add myapp deploy "-v /var/www/files:/app/myapp/static/files"
    dokku docker-options:add myapp deploy "-v /var/www/files/voices:/app/myapp/static/files/voices"

Which allows me to have persistent file storage on the DO Droplet. The rest is pretty standard biolerplate. 

My Procfile:

    web: gunicorn myapp:app --timeout 60 --log-file -
    worker: celery worker -A myapp.celery --loglevel=info -Ofair    

After issuing several remove commands and then doing nothing for a while the Dead containers went away and I was able to cleanup the <none> images, but as yet I am unable to reproduce that.

**Comment by michaelshobbs** [comment] 2015-12-02 23:27
This sounds like docker internals gone awry. As you may know, there is a dependency graph of sorts between image layers (each line from `docker images -a` is a layer) and containers. Your re-running of remove commands would seem to indicate to me that you were removing 1 or more layers each time you ran the remove command until you finally removed all dependencies. 

This is unfortunately the docker world in which we live and I'm not sure what more can be done. @josegonzalez  I know you were discussing this on IRC, did you have some thoughts on what dokku can do here?

**Comment by samgclarke** [comment] 2015-12-03 00:48
It seems like if I do

    docker rm -f $(docker ps -a -f 'status=dead' -q)

twice in quick succession, then that removes my dead containers, then

    dokku cleanup

successfully takes care of the `<none>` images.

The strange thing though, is that I don't seem to get all that space back.

        root@myapp:~# df -h
	Filesystem      Size  Used Avail Use% Mounted on
	/dev/vda1        30G  8.6G   20G  31% /
	none            4.0K     0  4.0K   0% /sys/fs/cgroup
	udev            487M  4.0K  487M   1% /dev
	tmpfs           100M  364K  100M   1% /run
	none            5.0M     0  5.0M 


    	root@myapp:~# docker ps -a
	CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAMES
	94e014dabba7        dokku/myapp:latest           "/start web"            4 minutes ago       Up 4 minutes                             myapp.web.1
	d06d90a0765a        redis:3.0.5                  "/entrypoint.sh redis"   26 hours ago        Up 17 hours         6379/tcp            dokku.redis.myapp
	4e5a52200a20        postgres:9.4.4               "/docker-entrypoint.s"   26 hours ago        Up 17 hours         5432/tcp            dokku.postgres.myapp



    root@myapp:~# docker images
	REPOSITORY                TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
	dokku/myapp               latest              7fe37fa9b573        5 minutes ago       1.58 GB
	gliderlabs/herokuish      latest              e1793943656c        2 days ago          1.29 GB
	heroku/cedar              14                  56b31ddc05ad        8 days ago          1.267 GB
	redis                     3.0.5               e5bd4f6f1bad        12 days ago         109.2 MB
	svendowideit/ambassador   latest              7feb6b1d3d04        7 weeks ago         6.454 MB
	dokkupaas/wait            latest              c0df71274c7a        10 weeks ago        1.096 MB
	postgres                  9.4.4               eddb1e6071fb        11 weeks ago      


I know my app is definitely not using up 8GB of space and this value keeps increasing with every push, which is obviously unsustainable.

**Comment by josegonzalez** [comment] 2015-12-03 02:34
Try `du -ch /` to see where things are being stored. Maybe there is a way to interactively explore docker's disk usage?

Try checking out http://blog.eye48.com/post/98551740424/when-dockerio-eats-up-your-disc-space . Might be helpful.

**Comment by samgclarke** [comment] 2015-12-03 22:33
I can confirm that

     docker rm -f $(docker ps -a -f 'status=dead' -q)
     docker rm -f $(docker ps -a -f 'status=dead' -q)
     dokku cleanup

Removes the Dead containers and <none> images following a deploy.

The first time the `rm` command is run Docker complains that `device or resource busy`, and the second say there are no matching containers. But then there are no Dead containers left.

However, I am still seeing my used space mount up - something in the region of 0.6GB per deploy. I have no idea where that space is being eaten up.

**Comment by josegonzalez** [comment] 2015-12-03 23:07
What happens after you reboot the server? Do you recoup used space?

**Comment by samgclarke** [comment] 2015-12-03 23:21
No, the space is not recouped. Actually when I reboot, then ssh back in MORE space is being used up!

Seems like several exited containers show up....

    		root@myapp:~# docker ps -a
		CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS                     PORTS               NAMES
		8bf2d45a32f3        dokku/myapp:latest   "/start web"             2 minutes ago       Up 2 minutes                                   myapp.web.1
		1e367ca7944f        dokku/myapp:latest   "/bin/bash -c 'cat > "   2 minutes ago       Exited (0) 2 minutes ago                       insane_poincare
		6119d402df87        dokku/myapp:latest   "/bin/bash -c 'if [[ "   2 minutes ago       Exited (0) 2 minutes ago                       compassionate_ramanujan
		0ed583bf4b14        dokku/myapp:latest   "/usr/bin/dpkg -s sup"   2 minutes ago       Exited (0) 2 minutes ago                       naughty_hawking
		54c99f658b4f        dokku/myapp:latest   "/bin/bash -c 'cat > "   2 minutes ago       Exited (0) 2 minutes ago                       naughty_panini
		9bc28788a441        dokku/myapp:latest   "test -f app/Procfile"   2 minutes ago       Exited (0) 2 minutes ago                       stupefied_pasteur
		452e59103107        dokku/myapp:latest   "/bin/bash -c 'cat > "   2 minutes ago       Exited (0) 2 minutes ago                       goofy_payne
		66260501b69a        dokku/myapp:latest   "/bin/bash -c 'mkdir "   2 minutes ago       Exited (0) 2 minutes ago                       grave_fermi
		1443eac7eb6e        dokku/myapp:latest   "/bin/bash -c 'mkdir "   2 minutes ago       Exited (0) 2 minutes ago                       determined_saha
		99b060cb0568        dokku/myapp:latest   "/start web"             4 minutes ago       Exited (0) 2 minutes ago                       myapp.web.1.1449184513
		736bfb6e8330        redis:3.0.4          "/entrypoint.sh redis"   6 weeks ago         Up 2 minutes               6379/tcp            dokku.redis.myapp
		732e2601a21a        postgres:9.4.4       "/docker-entrypoint.s"   6 weeks ago         Up 2 minutes               5432/tcp            dokku.postgres.myapp


These can be removed with

    docker rm -f $(docker ps -a -f 'status=exited' -q)

And I get ALMOST all the space back. In this instance I am still 100mb over where I was before reboot.

**Comment by josegonzalez** [comment] 2015-12-03 23:25
Thats so goddamn strange.

**Comment by samgclarke** [comment] 2015-12-04 00:42
Possibly related? https://github.com/docker/docker/issues/12328

**Comment by samgclarke** [comment] 2015-12-04 00:57
So, I can find where the space is being occupied:

    		root@myapp:~# ll /var/lib/docker/aufs/
		total 128
		drwxr-xr-x   5 root root  4096 Oct 14 11:33 ./
		drwx------   8 root root  4096 Dec  3 18:17 ../
		drwxr-xr-x 223 root root 36864 Dec  3 18:17 diff/
		drwxr-xr-x   2 root root 36864 Dec  3 18:17 layers/
		drwxr-xr-x 150 root root 36864 Dec  3 18:17 mnt/
		root@myapp:~# du -sh /var/lib/docker/aufs/diff/
		6.7G	/var/lib/docker/aufs/diff/
		root@myapp:~# du -sh /var/lib/docker/aufs/mnt/
		2.4G	/var/lib/docker/aufs/mnt/

Does the `diff` dir contain leftovers from old containers maybe??

**Comment by josegonzalez** [comment] 2015-12-12 23:20
@samgclarke unsure. Have you made any other progress on this? It seems like it's a docker bug, but maybe we're doing something stupid in regards to image handling.

**Comment by anton-yordanov** [comment] 2015-12-16 09:23
Is there any progress on that issue.
I have the same problem.
```
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                      PORTS                                              NAMES
6f715ce8a074        dokku/seo-test:latest             "/start web"             31 seconds ago      Up 30 seconds                                                                  seo-test.web.1
cd8572607a82        761c8d76e0c0                      "/bin/bash -c 'mkdir "   34 seconds ago      Exited (0) 33 seconds ago                                                      adoring_albattani
ccf14b8365c5        a7d91e1affb1                      "/bin/bash -c 'mkdir "   34 seconds ago      Exited (0) 34 seconds ago                                                      stoic_mestorf
c26c8569b6d8        b6a662a94707                      "/build"                 44 seconds ago      Exited (0) 36 seconds ago                                                      adoring_tesla
bb1f2ad95c17        2d5af68244ac                      "/bin/bash -c 'cat >>"   45 seconds ago      Exited (0) 44 seconds ago                                                      happy_spence
0b602f8542bf        fd7e5c0fd6dc                      "/bin/bash -c 'for EN"   46 seconds ago      Exited (0) 45 seconds ago                                                      compassionate_albattani
1ceeb0a48ba7        gliderlabs/herokuish              "/bin/bash -c 'mkdir "   46 seconds ago      Exited (0) 45 seconds ago
```

**Comment by michaelshobbs** [comment] 2015-12-17 18:38
@anton-yordanov those containers all look normal to me. Those particular ids will get cleaned up on subsequent pushes and replaced by the container steps taken to build the current running app container.

**Comment by michaelshobbs** [comment] 2015-12-17 18:45
I'm not sure what there is left to do here for dokku. 

The dead state is odd but almost certainly environmental. The space issue would need to be investigated further to determine actual root cause. I will say, however, that it is possible that the running containers are eating up that space if any of them are generating data on disk...logs, redis snapshots, db writes.....?

Closing, but let us know if you find anything else out.

**Closed by michaelshobbs** 2015-12-17 18:45 UTC

**Comment by kamagatos** [comment] 2016-01-21 06:56
Had the same issue today. It happened after many pushes in a short period of time. `/var/lib/docker/aufs` was eating up gigs of data. `dokku cleanu`p did remove dead containers, but still my disk was almost over capacity. I had to remove all containers (`docker rm -f $(docker ps -a -q)`) and `ps:restartall` to get back a green state.

**Comment by josegonzalez** [comment] 2016-01-21 07:48
The only difference between what you ran and [what we run](https://github.com/dokku/dokku/blob/master/plugins/common/functions#L344) is the `-f` flag.

**Comment by kamagatos** [comment] 2016-01-21 07:51
Yea I know. I purposely removed all the containers to make it work again. I'm just sharing how it happened on my case and saying that this issue might be worth investigating further.
