### ISSUE TITLE
dokku plugin:update seems broken on 0.4

### ISSUE THREAD

**Issue by rvalyi** [dokku/dokku#1531] opened 2015-10-07 05:49 UTC
```
dokku plugin:install https://github.com/dokku/dokku-postgres.git
```
-> OK

then
```
dokku plugin:update https://github.com/dokku/dokku-postgres.git
fatal: destination path 'postgres' already exists and is not an empty directory.
```

I believe update should be idempotent en ensure last version is install instead of breaking this way, no?

**Comment by michaelshobbs** [comment] 2015-10-07 12:13
I agree that `plugin:update` should be idempotent. However, this is an issue with the postgres plugin itself when dokku calls its update trigger. Will you please file the issue there?

**Comment by rvalyi** [comment] 2015-10-07 16:58
@michaelshobbs ah ok, sorry for the mistake, I'll fill an issue in the postgres plugin project

**Comment by josegonzalez** [comment] 2015-10-07 17:36
Actually it's not a bug in the postgres plugin. Here is the output from `DOKKU_TRACE=1`:

```
++ echo https://github.com/dokku/dokku-postgres.git
+ local PLUGIN_NAME=postgres
+ dokku_log_info1_quiet 'Cloning plugin repo https://github.com/dokku/dokku-postgres.git to /var/lib/dokku/plugins/available/postgres'
+ [[ -z '' ]]
+ echo '-----> Cloning plugin repo https://github.com/dokku/dokku-postgres.git to /var/lib/dokku/plugins/available/postgres'
-----> Cloning plugin repo https://github.com/dokku/dokku-postgres.git to /var/lib/dokku/plugins/available/postgres
+ download_plugin https://github.com/dokku/dokku-postgres.git postgres
+ local PLUGIN_GIT_URL=https://github.com/dokku/dokku-postgres.git
+ local PLUGIN_NAME=postgres
+ plugn install https://github.com/dokku/dokku-postgres.git postgres
fatal: destination path 'postgres' already exists and is not an empty directory.
+ exit_code=128
+ set -e
+ [[ 128 -eq 10 ]]
+ implemented=1
+ [[ 128 -ne 0 ]]
+ exit 128
```

**Comment by michaelshobbs** [comment] 2015-10-07 19:59
my bad. i misread the output initially. however this is an issue within `plugn` as it just does a `git checkout`. 

https://github.com/progrium/plugn/blob/2a2dc1c3d8862e5611186ed0d6ce19ee8ab133bf/bashenv/plugn.bash#L6

we could work around it in dokku by doing a `plugn uninstall` and `plugn install`. thoughts?

**Comment by josegonzalez** [comment] 2015-10-07 20:10
That seems fine to me.

**Comment by josegonzalez** [comment] 2015-12-22 20:13
@michaelshobbs we can probably handle this in `plugn` now that it's in the dokku org. Since you're on a roll right now, mind taking a look at this one?

**Comment by michaelshobbs** [comment] 2015-12-22 22:05
I have an open PR against plugn. Lemme take a look where that ended up.

**Comment by michaelshobbs** [comment] 2015-12-23 00:44
I'll take a stab at docs in the next few days and get that merged.

**Comment by michaelshobbs** [comment] 2015-12-24 18:43
Merged. Still have some work on the dokku side to cinch this up. I should get to it in the next couple days

**Comment by michaelshobbs** [comment] 2015-12-31 19:28
I think this is complete now with plugn [v0.2.1](https://github.com/dokku/plugn/pull/12)

**Comment by michaelshobbs** [comment] 2015-12-31 19:30
Sorry that's a lie. Forgot I still need to make the `plugin:update` command use `plugn update`

**Closed** 2016-01-05 19:17 UTC
Labels: upstream-issue
