### ISSUE TITLE
Idea: Use a dokku directory for all Dokku related configuration

### ISSUE THREAD

**Issue by klenis** [dokku/dokku#2562] opened 2017-01-13 14:31 UTC
Hi!

First of all, thanks for all your incredible work on this project!

I have noticed lately that the root directory of my projects that are using a lot of Dokku features gets filled up with specific files with completely unrelated filenames like _.buildpacks_, _CHECKS_, _Procfile_, _nginx.conf.sigil_, _app.json_. I understand that there are reasons behind the placement/ name of these files and I guess Heroku is one of them. But would it be feasible to:

1. Have an optional/alternative _dokku/_ dir in the root where these files could be placed instead/also
2. Use consistent filenames (caps/lower/dotfile/extension)
3. The same file type. Sticking to either json, shell, sigil as far as possible. Maybe a dokku.yml combining multiple configuration files in one file?

Then on deploy copy these files and rename/reformat them accordingly to the needs of other dependencies?

**Comment by josegonzalez** [comment] 2017-01-13 15:24
Duplicate of #2312.

**Closed by josegonzalez** 2017-01-13 15:24 UTC
