### ISSUE TITLE
Dokku adding environment variables when .env does not contain an end of file line

### ISSUE THREAD

**Issue by Nezia1** [dokku/dokku#4050] opened 2020-07-08 21:16 UTC
## Description of problem
I have an application I'm writing in Vue, and I'm using environment variables. I have a VUE_APP_VARIABLE that I'm using in a URL, and I noticed that if I don't add an end of file to the .env file, Dokku adds its own environment variables to mine. For example, if the content of the variable is \<value\>, I get \<value\>CURL_TIMEOUT=90 when the application is built.
### How reproducible
Not sure.
### Steps to Reproduce

1. Create an application using .env files and log one of the variables you're using to the console
2. Deploy it on Dokku
3. It should show \<value\>CURL_TIMEOUT=90 or some sort of CURL variable

#### Actual Results
The environment variable contains \<value\>CURL_TIMEOUT=90.
#### Expected Results
The environment variable should contain \<value\>.

### `dokku report stats` output
```
-----> uname: Linux nezia 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:            985         168         175           0         640         655
       Swap:             0           0           0
-----> docker version: 
       Client:
        Version:           18.09.6
        API version:       1.39
        Go version:        go1.10.8
        Git commit:        481bc77
        Built:             Sat May  4 02:35:57 2019
        OS/Arch:           linux/amd64
        Experimental:      false
       
       Server: Docker Engine - Community
        Engine:
         Version:          18.09.6
         API version:      1.39 (minimum version 1.12)
         Go version:       go1.10.8
         Git commit:       481bc77
         Built:            Sat May  4 01:59:36 2019
         OS/Arch:          linux/amd64
         Experimental:     false
-----> docker daemon info: 
       Containers: 8
        Running: 1
        Paused: 0
        Stopped: 7
       Images: 14
       Server Version: 18.09.6
       Storage Driver: overlay2
        Backing Filesystem: extfs
        Supports d_type: true
        Native Overlay Diff: true
       Logging Driver: json-file
       Cgroup Driver: cgroupfs
       Plugins:
        Volume: local
        Network: bridge host macvlan null overlay
        Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
       Swarm: inactive
       Runtimes: runc
       Default Runtime: runc
       Init Binary: docker-init
       containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
       runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
       init version: fec3683
       Security Options:
        apparmor
        seccomp
         Profile: default
       Kernel Version: 4.15.0-52-generic
       Operating System: Ubuntu 18.04.2 LTS
       OSType: linux
       Architecture: x86_64
       CPUs: 1
       Total Memory: 985.5MiB
       Name: nezia
       ID: VKSP:NGZ2:O47V:2ALJ:U5K3:OS7F:WFBA:PQHF:XM3P:TKRJ:RKHR:GA66
       Docker Root Dir: /var/lib/docker
       Debug Mode (client): true
       Debug Mode (server): false
       Registry: https://index.docker.io/v1/
       Labels:
       Experimental: false
       Insecure Registries:
        127.0.0.0/8
       Live Restore Enabled: false
       Product License: Community Engine
       
-----> sigil version: 0.4.0
-----> herokuish version: 
       herokuish: 0.5.0
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v200
         heroku-buildpack-nodejs    v142
         heroku-buildpack-clojure   v83
         heroku-buildpack-python    v149
         heroku-buildpack-java      v63
         heroku-buildpack-gradle    v28
         heroku-buildpack-scala     v84
         heroku-buildpack-play      v26
         heroku-buildpack-php       v151
         heroku-buildpack-go        v104
         buildpack-nginx            v10
-----> dokku version: dokku version 0.17.9
-----> dokku plugins: 
       plugn: 0.3.2
         00_dokku-standard    0.17.9 enabled    dokku core standard plugin
         20_events            0.17.9 enabled    dokku core events logging plugin
         app-json             0.17.9 enabled    dokku core app-json plugin
         apps                 0.17.9 enabled    dokku core apps plugin
         build-env            0.17.9 enabled    dokku core build-env plugin
         buildpacks           0.17.9 enabled    dokku core buildpacks plugin
         certs                0.17.9 enabled    dokku core certificate management plugin
         checks               0.17.9 enabled    dokku core checks plugin
         common               0.17.9 enabled    dokku core common plugin
         config               0.17.9 enabled    dokku core config plugin
         docker-options       0.17.9 enabled    dokku core docker-options plugin
         domains              0.17.9 enabled    dokku core domains plugin
         enter                0.17.9 enabled    dokku core enter plugin
         git                  0.17.9 enabled    dokku core git plugin
         letsencrypt          0.9.4 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.17.9 enabled    dokku core logs plugin
         network              0.17.9 enabled    dokku core network plugin
         nginx-vhosts         0.17.9 enabled    dokku core nginx-vhosts plugin
         plugin               0.17.9 enabled    dokku core plugin plugin
         proxy                0.17.9 enabled    dokku core proxy plugin
         ps                   0.17.9 enabled    dokku core ps plugin
         repo                 0.17.9 enabled    dokku core repo plugin
         resource             0.17.9 enabled    dokku core resource plugin
         scheduler-docker-local 0.17.9 enabled    dokku core scheduler-docker-local plugin
         shell                0.17.9 enabled    dokku core shell plugin
         ssh-keys             0.17.9 enabled    dokku core ssh-keys plugin
         storage              0.17.9 enabled    dokku core storage plugin
         tags                 0.17.9 enabled    dokku core tags plugin
         tar                  0.17.9 enabled    dokku core tar plugin
         trace                0.17.9 enabled    dokku core trace plugin
=====> stats app information
       App dir:                       /home/dokku/stats        
       Git sha:                       38aa289                  
       Deploy source:                 git                      
       Locked:                        false                    
=====> stats buildpacks information
       Buildpacks list:               
CN = stats.nezia.xyz
error 20 at 0 depth lookup: unable to get local issuer certificate
=====> stats ssl information
       Ssl dir:                       /home/dokku/stats/tls    
       Ssl enabled:                   true                     
       Ssl hostnames:                 stats.nezia.xyz          
       Ssl expires at:                Oct  6 19:03:01 2020 GMT 
       Ssl issuer:                    C = US, O = Lets Encrypt, CN = Lets Encrypt Authority X3
       Ssl starts at:                 Jul  8 19:03:01 2020 GMT 
       Ssl subject:                   subject=CN = stats.nezia.xyz
       Ssl verified:                  self signed              
=====> stats checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> stats docker options information
       Docker options build:                                   
       Docker options deploy:         --restart=on-failure:10  
       Docker options run:                                     
=====> stats domains information
       Domains app enabled:           true                     
       Domains app vhosts:            stats.nezia.xyz          
       Domains global enabled:        true                     
       Domains global vhosts:         nezia.xyz                
=====> stats git information
       Git rev env var:               GIT_REV                  
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
=====> stats network information
       Network bind all interfaces:   false
       Network listeners:             172.17.0.3:5000
=====> stats proxy information
       Proxy enabled:                 true                     
       Proxy type:                    nginx                    
       Proxy port map:                http:80:5000 https:443:5000
=====> stats ps information
       Processes:                     1                        
       Deployed:                      true                     
       Running:                       true                     
       Restore:                       true                     
       Restart policy:                on-failure:10            
       Ps can scale:                  true                     
       Status web.1:                  running    (CID: 43c0dabcafe5)
=====> stats scheduler-docker-local information
       Scheduler docker local disable chown:                          
=====> stats storage information
       Storage build mounts:                                   
       Storage deploy mounts:                                  
       Storage run mounts:   
```
### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
I installed Dokku on a One-Click DigitalOcean droplet.

### Additional information

- Container Inspect Output (if applicable) via `dokku ps:inspect stats`
```
[
    {
        "AppArmorProfile": "docker-default", 
        "Args": [
            "web"
        ], 
        "Config": {
            "AttachStderr": false, 
            "AttachStdin": false, 
            "AttachStdout": false, 
            "Cmd": [
                "/start", 
                "web"
            ], 
            "Domainname": "", 
            "Entrypoint": null, 
            "Env": [
                "PORT=5000", 
                "USER=herokuishuser", 
                "DYNO=web.1", 
                "CACHE_PATH=/cache", 
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", 
                "DEBIAN_FRONTEND=XXXXXX"
            ], 
            "Hostname": "43c0dabcafe5", 
            "Image": "dokku/stats:latest", 
            "Labels": {
                "dokku": ""
            }, 
            "OnBuild": null, 
            "OpenStdin": false, 
            "StdinOnce": false, 
            "Tty": false, 
            "User": "", 
            "Volumes": null, 
            "WorkingDir": ""
        }, 
        "Created": "2020-07-08T20:41:33.673769084Z", 
        "Driver": "overlay2", 
        "ExecIDs": null, 
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/64c166636dbdddb215a3299f8b92ee0879b5144a85a221756ffd8d0867b061df-init/diff:/var/lib/docker/overlay2/3a1f78c168b3a666a8df030a1c2599e5c683a39cc3d5f3a32132e7289f28c82c/diff:/var/lib/docker/overlay2/57460f83df2bc62cc70f47eaad8ec41add579ebe1d7e31e8f86eda87dddc88dc/diff:/var/lib/docker/overlay2/437837df58e6a860063710c29a242bd85ce404ac92569d665b90ecdfc1a53ab0/diff:/var/lib/docker/overlay2/872a1f0c870f48827709d4e79d62545276412eb21fad167570d0ad6f12ee2133/diff:/var/lib/docker/overlay2/60fac8a1339c129d3f70c99ccc8801a157bcc6514ccb39d58c107c6be6db7cdd/diff:/var/lib/docker/overlay2/8568a9f89394682cd9f401721475575c38fa68f520988d8a6f65c07389b79f7c/diff:/var/lib/docker/overlay2/526ddc8a27404f1e2bb7a1675913f83b80141fd6c8491add89a141fe25863854/diff:/var/lib/docker/overlay2/4894f6c6e97fadb41fc4bcf04afdd7ec55a4324a19692696774b5a2073226302/diff:/var/lib/docker/overlay2/8c38de69b613e4ae2c777531347559a7837802c790c20e267a39491b3d928a5a/diff:/var/lib/docker/overlay2/95d89bb552dd1b85be39d751f1f1a99ec00f03d54e7e81643378f7dac85d7d16/diff:/var/lib/docker/overlay2/7f9a5408da83848ecc39bfcf60411b9e8728e67d120baf9fa53ecc6d2396e8d6/diff:/var/lib/docker/overlay2/fc850a08cf92ea659475f3984d226dd2b7bedc9680303eae4e84f1cb381146c4/diff:/var/lib/docker/overlay2/5ac3abf0f2a20b61f1ffdf3a53b7e261237ee7d87e0a1fb84a3c6090502e665d/diff:/var/lib/docker/overlay2/7170cb2b68cefae34b6df9fbbf7bffb00fc9d2962a6ece340d715d06d642a9f9/diff:/var/lib/docker/overlay2/7a8708fc3ff9603a672180488b087e71405e31ac5238b607f896e941c01fa98e/diff:/var/lib/docker/overlay2/0003343961ab7ae69beda400cd2e3db047eb6df4cf2f4754a85d5d7278a93386/diff:/var/lib/docker/overlay2/1c7f90265269dd73e5eaec0c2b338f23c076273f35348a974d4fb0e74af6c44b/diff:/var/lib/docker/overlay2/ff20f433d4fd1a8fe263ff176b187f78f5d0daf8f22d4a5c40a86e4bb85abce1/diff:/var/lib/docker/overlay2/8f6caf13697834922738890f181fc420aa487669ca09a005395122d837d66788/diff", 
                "MergedDir": "/var/lib/docker/overlay2/64c166636dbdddb215a3299f8b92ee0879b5144a85a221756ffd8d0867b061df/merged", 
                "UpperDir": "/var/lib/docker/overlay2/64c166636dbdddb215a3299f8b92ee0879b5144a85a221756ffd8d0867b061df/diff", 
                "WorkDir": "/var/lib/docker/overlay2/64c166636dbdddb215a3299f8b92ee0879b5144a85a221756ffd8d0867b061df/work"
            }, 
            "Name": "overlay2"
        }, 
        "HostConfig": {
            "AutoRemove": false, 
            "Binds": null, 
            "BlkioDeviceReadBps": null, 
            "BlkioDeviceReadIOps": null, 
            "BlkioDeviceWriteBps": null, 
            "BlkioDeviceWriteIOps": null, 
            "BlkioWeight": 0, 
            "BlkioWeightDevice": [], 
            "CapAdd": null, 
            "CapDrop": null, 
            "Cgroup": "", 
            "CgroupParent": "", 
            "ConsoleSize": [
                0, 
                0
            ], 
            "ContainerIDFile": "", 
            "CpuCount": 0, 
            "CpuPercent": 0, 
            "CpuPeriod": 0, 
            "CpuQuota": 0, 
            "CpuRealtimePeriod": 0, 
            "CpuRealtimeRuntime": 0, 
            "CpuShares": 0, 
            "CpusetCpus": "", 
            "CpusetMems": "", 
            "DeviceCgroupRules": null, 
            "Devices": [], 
            "DiskQuota": 0, 
            "Dns": [], 
            "DnsOptions": [], 
            "DnsSearch": [], 
            "ExtraHosts": null, 
            "GroupAdd": null, 
            "IOMaximumBandwidth": 0, 
            "IOMaximumIOps": 0, 
            "IpcMode": "shareable", 
            "Isolation": "", 
            "KernelMemory": 0, 
            "Links": null, 
            "LogConfig": {
                "Config": {}, 
                "Type": "json-file"
            }, 
            "MaskedPaths": [
                "/proc/asound", 
                "/proc/acpi", 
                "/proc/kcore", 
                "/proc/keys", 
                "/proc/latency_stats", 
                "/proc/timer_list", 
                "/proc/timer_stats", 
                "/proc/sched_debug", 
                "/proc/scsi", 
                "/sys/firmware"
            ], 
            "Memory": 0, 
            "MemoryReservation": 0, 
            "MemorySwap": 0, 
            "MemorySwappiness": null, 
            "NanoCpus": 0, 
            "NetworkMode": "default", 
            "OomKillDisable": false, 
            "OomScoreAdj": 0, 
            "PidMode": "", 
            "PidsLimit": 0, 
            "PortBindings": {}, 
            "Privileged": false, 
            "PublishAllPorts": false, 
            "ReadonlyPaths": [
                "/proc/bus", 
                "/proc/fs", 
                "/proc/irq", 
                "/proc/sys", 
                "/proc/sysrq-trigger"
            ], 
            "ReadonlyRootfs": false, 
            "RestartPolicy": {
                "MaximumRetryCount": 10, 
                "Name": "on-failure"
            }, 
            "Runtime": "runc", 
            "SecurityOpt": null, 
            "ShmSize": 67108864, 
            "UTSMode": "", 
            "Ulimits": null, 
            "UsernsMode": "", 
            "VolumeDriver": "", 
            "VolumesFrom": null
        }, 
        "HostnamePath": "/var/lib/docker/containers/43c0dabcafe56ba0d650a2df1e0e42bbc396cd2626fd2e2cd8f08699859df6f3/hostname", 
        "HostsPath": "/var/lib/docker/containers/43c0dabcafe56ba0d650a2df1e0e42bbc396cd2626fd2e2cd8f08699859df6f3/hosts", 
        "Id": "43c0dabcafe56ba0d650a2df1e0e42bbc396cd2626fd2e2cd8f08699859df6f3", 
        "Image": "sha256:3a35bc0c2c444015254836a97fa4155f85d215e2a1a3d0237199991a9e2109f1", 
        "LogPath": "/var/lib/docker/containers/43c0dabcafe56ba0d650a2df1e0e42bbc396cd2626fd2e2cd8f08699859df6f3/43c0dabcafe56ba0d650a2df1e0e42bbc396cd2626fd2e2cd8f08699859df6f3-json.log", 
        "MountLabel": "", 
        "Mounts": [], 
        "Name": "/stats.web.1", 
        "NetworkSettings": {
            "Bridge": "", 
            "EndpointID": "2439f48cb2d708a52d12e31fc40f0a99d6ee6b05c404d8d98669d58d1d2f38f7", 
            "Gateway": "172.17.0.1", 
            "GlobalIPv6Address": "", 
            "GlobalIPv6PrefixLen": 0, 
            "HairpinMode": false, 
            "IPAddress": "172.17.0.3", 
            "IPPrefixLen": 16, 
            "IPv6Gateway": "", 
            "LinkLocalIPv6Address": "", 
            "LinkLocalIPv6PrefixLen": 0, 
            "MacAddress": "02:42:ac:11:00:03", 
            "Networks": {
                "bridge": {
                    "Aliases": null, 
                    "DriverOpts": null, 
                    "EndpointID": "2439f48cb2d708a52d12e31fc40f0a99d6ee6b05c404d8d98669d58d1d2f38f7", 
                    "Gateway": "172.17.0.1", 
                    "GlobalIPv6Address": "", 
                    "GlobalIPv6PrefixLen": 0, 
                    "IPAMConfig": null, 
                    "IPAddress": "172.17.0.3", 
                    "IPPrefixLen": 16, 
                    "IPv6Gateway": "", 
                    "Links": null, 
                    "MacAddress": "02:42:ac:11:00:03", 
                    "NetworkID": "f1e1c7695518e6fed5304615e521e4e38b72292a7bd3b5175d8c234e8e2de1b4"
                }
            }, 
            "Ports": {}, 
            "SandboxID": "a82195ac4a6a94290a7bf51cb5f7544be638a7324fe71b8f425c3461e8cc2558", 
            "SandboxKey": "/var/run/docker/netns/a82195ac4a6a", 
            "SecondaryIPAddresses": null, 
            "SecondaryIPv6Addresses": null
        }, 
        "Path": "/start", 
        "Platform": "linux", 
        "ProcessLabel": "", 
        "ResolvConfPath": "/var/lib/docker/containers/43c0dabcafe56ba0d650a2df1e0e42bbc396cd2626fd2e2cd8f08699859df6f3/resolv.conf", 
        "RestartCount": 0, 
        "State": {
            "Dead": false, 
            "Error": "", 
            "ExitCode": 0, 
            "FinishedAt": "0001-01-01T00:00:00Z", 
            "OOMKilled": false, 
            "Paused": false, 
            "Pid": 20581, 
            "Restarting": false, 
            "Running": true, 
            "StartedAt": "2020-07-08T20:41:34.654385256Z", 
            "Status": "running"
        }
    }
]
```
- Link to the exact repository being deployed (if possible/applicable): https://github.com/Nezia1/spotify-stats

**Comment by josegonzalez** [comment] 2020-07-08 21:57
The annoying part of this one is that we have two test apps that _should_ be verifying this, but dont?

- https://github.com/dokku/dokku/blob/master/tests/apps/static/.env
- https://github.com/dokku/dokku/blob/master/tests/apps/ruby/.env

I've def seen this before and thought I fixed it... Maybe we need a new test, or maybe the one we setup for this was changed a while back?

**Comment by Nezia1** [comment] 2020-07-09 00:12
Do you get the same issue with my own repo? Create a .env file inside it and fill the VUE_APP_CLIENT_ID variable with whatever and when you click the button, you get some CURL_* variable mixed in there.

I'd assume it's an issue with the way Dokku handles environment variables, maybe it doesn't stop until it sees an empty line, hence why it's mixing some variables of its own here and there?

**Comment by josegonzalez** [comment] 2020-12-20 21:21
Apologies for the delay, but I just tried your app with 0.22.2, seems like the problem isn't there anymore. I also entered the container to check on the generated `.env`, looks like environment variables are being properly set now.

May have been an issue with an older version of Dokku - you were running 0.17.9, and 0.20.x was out at the time of the issue creation. If you can replicate the issue with a more current version of Dokku, I'll be happy to re-investigate, but closing this for now.

**Closed by josegonzalez** 2020-12-20 21:21 UTC
Labels: merge-level: patch, needs: investigation, plugin: config, type: bug
