### ISSUE TITLE
Crash when apps don't have default process scale (web=1)

### ISSUE THREAD

**Issue by iplanwebsites** [dokku/dokku#5692] opened 2023-02-20 03:15 UTC
### Description of problem

V30 crash when updating from v20, where apps don't have default process scale (web=1)

### Steps to reproduce

DO fresh install. update to v30. 

### dokku report $APP_NAME

fixed now so unrelaible

### Additional information

See:
https://serverfault.com/questions/1123094/after-upgrading-dokku-cant-start-applications

### Output of failing commands after running: dokku trace:off

```shell
----> Running post-deploy
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/dokku/dokku/plugins/common.ParseScaleOutput({0xc0000aa400, 0x0, 0xc0000506d0?})
        /go/src/github.com/dokku/dokku/plugins/common/common.go:399 +0x154
github.com/dokku/dokku/plugins/network.BuildConfig({0x7ffe6738d21e, 0xa})
        /go/src/github.com/dokku/dokku/plugins/network/network.go:55 +0x116
main.main()
        /go/src/github.com/dokku/dokku/plugins/network/src/triggers/triggers.go:34 +0x534
 !     Error running rebuild against app bye-mailin: exit status 2
-----> Running rebuild against app bye-server
-----> Cleaning up...
-----> Building bye-server from herokuish
-----> Adding BUILD_ENV to build environment...
       BUILD_ENV added successfully
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  unspecified
```

### Output of failing commands after running: dokku trace:on

```shell
fig_sub get --global DOKKU_SKIP_DEPLOY
++ true
+ local DOKKU_GLOBAL_SKIP_DEPLOY=
+ local DOKKU_SKIP_DEPLOY=
+ dokku_log_info1 'Releasing bye-server...'
+ declare 'desc=log info1 formatter'
+ echo '-----> Releasing bye-server...'
+ dokku_release bye-server herokuish latest
-----> Releasing bye-server...
+ declare 'desc=release phase'
+ declare APP=bye-server IMAGE_SOURCE_TYPE=herokuish IMAGE_TAG=latest
++ get_app_image_name bye-server latest
++ declare 'desc=return image identifier for a given app, tag tuple. validate if tag is presented'
++ local APP=bye-server
++ local IMAGE_TAG=latest
++ IMAGE_REPO=
++ [[ -z '' ]]
+++ get_app_image_repo bye-server
+++ declare 'desc=central definition of image repo pattern'
+++ local APP=bye-server
+++ local IMAGE_REPO=dokku/bye-server
+++ echo dokku/bye-server
++ IMAGE_REPO=dokku/bye-server
++ [[ -n latest ]]
++ local IMAGE=dokku/bye-server:latest
++ verify_image dokku/bye-server:latest
++ declare 'desc=verify image existence'
++ local IMAGE=dokku/bye-server:latest
++ docker image inspect dokku/bye-server:latest
++ return 0
++ echo dokku/bye-server:latest
+ local IMAGE=dokku/bye-server:latest
+ is_image_cnb_based dokku/bye-server:latest
+ declare 'desc=returns true if app image is based on cnb'
+ declare IMAGE=dokku/bye-server:latest
++ /var/lib/dokku/core-plugins/available/common/common --quiet image-is-cnb-based dokku/bye-server:latest
+ [[ false != \t\r\u\e ]]
+ return 1
+ plugn trigger builder-release herokuish bye-server latest
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ ! -n '' ]]
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ trigger-builder-dockerfile-builder-release herokuish bye-server latest
+ declare 'desc=builder-dockerfile builder-release plugin trigger'
+ declare trigger=builder-release
+ declare BUILDER_TYPE=herokuish APP=bye-server IMAGE_TAG=latest
+ [[ herokuish != \d\o\c\k\e\r\f\i\l\e ]]
+ return
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ source /var/lib/dokku/plugins/available/config/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
++ source /var/lib/dokku/core-plugins/available/common/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+ trigger-builder-herokuish-builder-release herokuish bye-server latest
+ declare 'desc=builder-herokuish builder-release plugin trigger'
+ declare trigger=builder-release
+ declare BUILDER_TYPE=herokuish APP=bye-server IMAGE_TAG=latest
+ [[ herokuish != \h\e\r\o\k\u\i\s\h ]]
++ get_app_image_name bye-server latest
++ declare 'desc=return image identifier for a given app, tag tuple. validate if tag is presented'
++ local APP=bye-server
++ local IMAGE_TAG=latest
++ IMAGE_REPO=
++ [[ -z '' ]]
+++ get_app_image_repo bye-server
+++ declare 'desc=central definition of image repo pattern'
+++ local APP=bye-server
+++ local IMAGE_REPO=dokku/bye-server
+++ echo dokku/bye-server
++ IMAGE_REPO=dokku/bye-server
++ [[ -n latest ]]
++ local IMAGE=dokku/bye-server:latest
++ verify_image dokku/bye-server:latest
++ declare 'desc=verify image existence'
++ local IMAGE=dokku/bye-server:latest
++ docker image inspect dokku/bye-server:latest
++ return 0
++ echo dokku/bye-server:latest
+ local IMAGE=dokku/bye-server:latest
+ DOCKER_BUILD_LABEL_ARGS=("--label=org.label-schema.schema-version=1.0" "--label=org.label-schema.vendor=dokku" "--label=com.dokku.app-name=$APP" "--label=com.dokku.image-stage=release" "--label=dokku")
+ local DOCKER_BUILD_LABEL_ARGS
+ plugn trigger pre-release-buildpack bye-server latest
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ ! -n '' ]]
++ mktemp -d /tmp/dokku-107443-trigger-builder-herokuish-builder-release.XXXXXX
+ TMP_WORK_DIR=/tmp/dokku-107443-trigger-builder-herokuish-builder-release.BoC8DR
+ trap 'rm -rf '\''/tmp/dokku-107443-trigger-builder-herokuish-builder-release.BoC8DR'\'' >/dev/null' RETURN INT TERM EXIT
+ config_export global
+ declare 'desc=returns export command for config variable of specified type (app/global)'
+ local CONFIG_TYPE=global
+ shift
+ local APP=
+ [[ global == \g\l\o\b\a\l ]]
+ APP=--global
+ config_sub export --global
+ declare 'desc=executes a config subcommand'
+ local name=export
+ shift
+ /var/lib/dokku/plugins/available/config/config_sub export --global
+ return 0
+ config_export app bye-server
+ declare 'desc=returns export command for config variable of specified type (app/global)'
+ local CONFIG_TYPE=app
+ shift
+ local APP=bye-server
+ [[ app == \g\l\o\b\a\l ]]
+ shift
+ config_sub export bye-server
+ declare 'desc=executes a config subcommand'
+ local name=export
+ shift
+ /var/lib/dokku/plugins/available/config/config_sub export bye-server
+ return 0
+ suppress_output docker image build --label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=com.dokku.app-name=bye-server --label=com.dokku.image-stage=release --label=dokku --label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku -f /var/lib/dokku/plugins/available/builder-herokuish/dockerfiles/builder-release.Dockerfile --build-arg APP_IMAGE=dokku/bye-server:latest -t dokku/bye-server:latest /tmp/dokku-107443-trigger-builder-herokuish-builder-release.BoC8DR
+ declare 'desc=suppress all output from a given command unless there is an error'
+ local TMP_COMMAND_OUTPUT
++ mktemp /tmp/dokku-107443-suppress_output.XXXXXX
+ TMP_COMMAND_OUTPUT=/tmp/dokku-107443-suppress_output.f8425i
+ trap 'rm -rf '\''/tmp/dokku-107443-suppress_output.f8425i'\'' >/dev/null' RETURN
+ docker image build --label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=com.dokku.app-name=bye-server --label=com.dokku.image-stage=release --label=dokku --label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku -f /var/lib/dokku/plugins/available/builder-herokuish/dockerfiles/builder-release.Dockerfile --build-arg APP_IMAGE=dokku/bye-server:latest -t dokku/bye-server:latest /tmp/dokku-107443-trigger-builder-herokuish-builder-release.BoC8DR
+ return 0
++ rm -rf /tmp/dokku-107443-suppress_output.f8425i
+ plugn trigger post-release-builder herokuish bye-server dokku/bye-server:latest
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ ! -n '' ]]
 ?     plugn trigger pre-deploy [bye-server latest]
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ ! -n '' ]]
-----> Checking for predeploy task
       No predeploy task found, skipping
-----> Checking for release task
 ?     plugn trigger procfile-get-command [bye-server release 5000]
 ?     plugn trigger procfile-get-command stderr: + source /var/lib/dokku/core-plugins/available/common/functions
 ?     plugn trigger procfile-get-command stderr: ++ set -eo pipefail
 ?     plugn trigger procfile-get-command stderr: ++ [[ -n 1 ]]
 ?     plugn trigger procfile-get-command stderr: ++ set -x
 ?     plugn trigger procfile-get-command stderr: + [[ ! -n '' ]]
 ?     plugn trigger procfile-get-command stderr: 
 ?     plugn trigger procfile-get-command stdout: 
 ?     plugn trigger ps-can-scale [bye-server true]
       No release task found, skipping
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ ! -n '' ]]
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ source /var/lib/dokku/core-plugins/available/common/property-functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ source /var/lib/dokku/plugins/available/config/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
++ source /var/lib/dokku/core-plugins/available/common/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+ trigger-scheduler-docker-local-pre-deploy bye-server latest
+ declare 'desc=scheduler-docker-local pre-deploy plugin trigger'
+ declare trigger=pre-deploy
+ declare APP=bye-server IMAGE_TAG=latest
++ get_app_scheduler bye-server
++ declare 'desc=fetch the scheduler for a given application'
++ declare APP=bye-server
++ /var/lib/dokku/core-plugins/available/common/common --quiet scheduler-detect bye-server
 ?     plugn trigger scheduler-detect [--global]
 ?     plugn trigger scheduler-detect [bye-server]
 ?     plugn trigger scheduler-detect stderr: + source /var/lib/dokku/core-plugins/available/common/functions
 ?     plugn trigger scheduler-detect stderr: ++ set -eo pipefail
 ?     plugn trigger scheduler-detect stderr: ++ [[ -n 1 ]]
 ?     plugn trigger scheduler-detect stderr: ++ set -x
 ?     plugn trigger scheduler-detect stderr: + [[ ! -n '' ]]
 ?     plugn trigger scheduler-detect stderr: 
 ?     plugn trigger scheduler-detect stdout: docker-local
 ?     plugn trigger scheduler-detect stdout: 
 ?     plugn trigger scheduler-detect stderr: + source /var/lib/dokku/core-plugins/available/common/functions
 ?     plugn trigger scheduler-detect stderr: ++ set -eo pipefail
 ?     plugn trigger scheduler-detect stderr: ++ [[ -n 1 ]]
 ?     plugn trigger scheduler-detect stderr: ++ set -x
 ?     plugn trigger scheduler-detect stderr: + [[ ! -n '' ]]
 ?     plugn trigger scheduler-detect stderr: 
 ?     plugn trigger scheduler-detect stdout: docker-local
 ?     plugn trigger scheduler-detect stdout: 
+ local DOKKU_SCHEDULER=docker-local
+ [[ docker-local != \d\o\c\k\e\r\-\l\o\c\a\l ]]
+ scheduler-docker-local-pre-deploy-chown-app bye-server latest
+ declare 'desc=Runs chown against the /app directory for herokuish images'
+ declare APP=bye-server IMAGE_TAG=la...
```

**Comment by iplanwebsites** [comment] 2023-02-20 03:15
Running this fixes it:
dokku ps:scale <appname> web=1

**Comment by iplanwebsites** [comment] 2023-02-20 03:25
total 52K
drwx------  6 root root 4.0K Feb 20 02:50 .
drwxr-xr-x 19 root root 4.0K Feb 20 02:28 ..
-rw-r--r--  1 root root 1.8K Feb 20 02:27 .bash_history
drwxr-xr-x  2 root root 4.0K Oct 17 10:46 .basher
-rw-r--r--  1 root root 3.1K Dec  5  2019 .bashrc
drwx------  2 root root 4.0K Oct 17 10:41 .cache
-rw-r--r--  1 root root    0 Feb 20 02:28 .cloud-locale-test.skip
-rw-r--r--  1 root root  161 Dec  5  2019 .profile
drwx------  2 root root 4.0K Feb 20 02:32 .ssh
-rw-r--r--  1 root root  275 Feb 20 02:26 .wget-hsts
-rw-r--r--  1 root root 8.3K Oct 17 10:44 bootstrap.sh
drwx------  3 root root 4.0K Oct 17 10:41 snap
-rw-------  1 root root    0 Feb 20 02:50 swap.img

**Comment by iplanwebsites** [comment] 2023-02-20 03:25
No  app.json

**Comment by josegonzalez** [comment] 2023-02-20 21:13
This is likely related to needing to have the settings converted in a version below 0.29.x. I added a note [here](https://github.com/dokku/dokku/pull/5695) on that requirement.

I'm unlikely to re-add that since 0.25.x came out in August 2021, almost two years ago. Removing deprecated code _has_ to happen at some point, so I think this will just need to be a pain point for upgraders.

The network.go panic is a bug though, so I'll keep this open for that.

**Comment by josegonzalez** [comment] 2023-03-18 09:18
This is the same as #5710 and should error out more nicely per #5750.

For anyone that sees this same problem, can you do:

```shell
# where $APP is your app name
ls -lah /var/lib/dokku/config/ps/$APP
cat /var/lib/dokku/config/ps/$APP/scale || true
```

The problem is the scale output is incorrect, but I don't know what the invalid value looks like, so I don't know what the correct conversion is.

**Comment by josegonzalez** [comment] 2023-03-18 09:19
Closing as there is a pull request open.

**Closed by josegonzalez** 2023-03-18 09:19 UTC
Labels: type: bug, needs: investigation
