### ISSUE TITLE
how to define git safe.directory for github-author mkdocs plugin

### ISSUE THREAD

**Issue by makayabou** [dokku/dokku#6403] opened 2024-01-04 18:05 UTC
### Description of problem

I want to deploy a mkocs website with dokku.
I'm using git-authors plugin, which needs access to git history.

I configured the app with dokku git:set docs keep-git-dir true

I use heroku/python buildpack.
Here's my Procfile:
`web: git config --global --add safe.directory /app && mkdir public && mkdocs build && python -m http.server --directory public 5000
`

But when i try to deploy i have the following error: 
```
       mkdocs_git_authors_plugin.git.command.GitCommandError: GitCommand error:
       Command "git rev-parse --show-toplevel" failed
       Return code: 128
       Output:
       Error messages:
       fatal: detected dubious ownership in repository at '/app'
       To add an exception for this directory, call:
        git config --global --add safe.directory /app
=====> End of  container output (.)
remote: parallel: This job failed:
remote: /var/lib/dokku/plugins/available/scheduler-docker-local/bin/scheduler-deploy-process-container docs herokuish dokku/docs:latest latest web 1 1
To legaragenumerique.eu:docs
 ! [remote rejected]   main -> main (pre-receive hook declined)
erreur : impossible de pousser des références vers 'legaragenumerique.eu:docs'
```

Know what I should do?

### Steps to reproduce

Create an app. Push a mkdocs project with github-authors plugin. Deploy and see it fail

### dokku report $APP_NAME

admin@web-hosting:~$ dokku git:report docs
=====> docs git information
       Git deploy branch:             master                   
       Git global deploy branch:      main                     
       Git keep git dir:              true                     
       Git rev env var:               GIT_REV                  
       Git sha:                                                
       Git source image:                                       
       Git last updated at:           1704381026

**Comment by josegonzalez** [comment] 2024-01-07 05:34
A few things:

- You didn't provide the entire deploy output, and cherry-picked what you thought was useful from the `dokku report` command. I ask for that informations so that I can accurately help diagnose what the problem is. Displaying only portions of it is both frustrating for me and doesn't give me enough context to help you.
- Dokku doesn't support `&&` in commands - you'll need to wrap that in a single script of some sort. Since I don't have the entire deploy output, I'm not entirely sure its even running your Procfile
- You shouldn't run `mkdocs build` on container start, but actually during the container build process. For the python buildpack, if you have an executable shell script at `bin/post_compile`, you can have it run what you want (including this build process). You'll still want the `keep-git-dir` git plugin property set to true.

Closing as I can't help without more information and this isn't actually a Dokku issue. Feel free to post in our Discussion forum or on Discord/Slack, where the community may help you debug what is going on.

**Closed by josegonzalez** 2024-01-07 05:34 UTC
Labels: type: bug, needs: investigation
