### ISSUE TITLE
docker container wrong ip after reboot

### ISSUE THREAD

**Issue by agalisteo** [dokku/dokku#2846] opened 2017-07-21 17:54 UTC
Description of problem:

I am hosting applications set to restart always and when an error occurs and the server is rebooted the docker container some times obtain a different IP but the nginx config is not updated to the new IP address. So, i can't access to the server because i get 502 error.

How reproducible:
```
/usr/bin/docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(cat /home/dokku/$app/CONTAINER.web.1) | (sudo -i -u dokku tee /home/dokku/$app/IP.web.1)

reboot

# wait server is alive

/usr/bin/docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(cat /home/dokku/$app/CONTAINER.web.1) | (sudo -i -u dokku tee /home/dokku/$app/IP.web.1)
```

Actual Results:
Sometimes the command responds with a new ip different than the previous ip

Expected Results:
Assign the same ip all time or a new flag--reserve-ip which would assign static, unchangable IP address to the container

Additional info:
I tried executing *dokku ps:restart $app* on every reboot or executing a bash script like this:
```
/usr/bin/docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(cat /home/dokku/$app/CONTAINER.web.1) | ( tee /home/dokku/$app/IP.web.1)
/usr/bin/dokku nginx:build-config $app
```
or creating my own network in docker and assigning the ip like this:
```
docker network create --subnet=172.18.0.0/16 mynet
dokku docker-options:add $app deploy,run "--net mynet --ip 172.18.0.22"
```
but i obtain the error **Address already in use** on every restart or new deploy.

**Comment by josegonzalez** [comment] 2017-07-21 17:55
Duplicate of a ton of issues where docker changed how they allocate ip addresses on reboot. Should be closed by #2736. Please follow along that PR for more information.

**Closed by josegonzalez** 2017-07-21 17:55 UTC
