### ISSUE TITLE
Error updating from 0.4.12

### ISSUE THREAD

**Issue by enjikaka** [dokku/dokku#2137] opened 2016-04-23 15:38 UTC
Description of problem:

Trying to run to bootstrap or `apt-get dist-upgrade` gives this error:

```
dpkg: error processing package dokku (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 dokku
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

All results on Google to issues in this repos I found were closed with no solution in the closing comment.

Output of the following commands

- `uname -a`: 
Linux Dokku.Website 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`:
```
             total       used       free     shared    buffers     cached
Mem:           994        617        376         11         67        257
-/+ buffers/cache:        292        701
Swap:            0          0          0
```
- `docker version`:
```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64
```
- `docker -D info`:
```
Containers: 16
 Running: 2
 Paused: 0
 Stopped: 14
Images: 173
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 207
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-71-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 994 MiB
Name: Dokku.Website
ID: 4Q7Z:TCMK:BHGC:GZPJ:HMK2:FSCQ:ILEA:AAMC:WZ5V:6RNV:PVXY:SZLW
Docker Root Dir: /var/lib/docker
Debug mode (client): true
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```
- `sigil -v`: 0.4.0
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
```
herokuish: 0.3.11
buildpacks:
  heroku-buildpack-clojure   v75
  heroku-buildpack-erlang    fa17af9
  heroku-buildpack-go        v31
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v20
  heroku-buildpack-java      v44
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-nodejs    v89
  heroku-buildpack-php       v100
  heroku-buildpack-play      v26
  heroku-buildpack-python    v80
  heroku-buildpack-ruby      v146
  heroku-buildpack-scala     v67
  buildpack-nginx            v5
```
- `dokku version`: 0.4.12
- `dokku plugin`:
```
plugn: dev
  00_dokku-standard    0.5.5 enabled    dokku core standard plugin
  20_events            0.5.5 enabled    dokku core events logging plugin
  apps                 0.5.5 enabled    dokku core apps plugin
  build-env            0.5.5 enabled    dokku core build-env plugin
  certs                0.5.5 enabled    dokku core certificate management plugin
  checks               0.5.5 enabled    dokku core checks plugin
  common               0.5.5 enabled    dokku core common plugin
  config               0.5.5 enabled    dokku core config plugin
  docker-options       0.5.5 enabled    dokku core docker-options plugin
  domains              0.5.5 enabled    dokku core domains plugin
  enter                0.5.5 enabled    dokku core enter plugin
  git                  0.5.5 enabled    dokku core git plugin
  letsencrypt          0.7.2 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.5.5 enabled    dokku core logs plugin
  mongo                1.0.0 enabled    dokku mongo service plugin
  named-containers     0.5.5 enabled    dokku core named containers plugin
  nginx-vhosts         0.5.5 enabled    dokku core nginx-vhosts plugin
  plugin               0.5.5 enabled    dokku core plugin plugin
  proxy                0.5.5 enabled    dokku core proxy plugin
  ps                   0.5.5 enabled    dokku core ps plugin
  shell                0.5.5 enabled    dokku core shell plugin
  storage              0.5.5 enabled    dokku core storage plugin
  tags                 0.5.5 enabled    dokku core tags plugin
  tar                  0.5.5 enabled    dokku core tar plugin
```
Environment details (AWS, VirtualBox, physical, etc.):

How was dokku installed?: Don't remeber. Either Digital Ocean droplet image or bootstrap.sh

**Comment by josegonzalez** [comment] 2016-04-23 15:41
What version of nginx are you using?

**Comment by enjikaka** [comment] 2016-04-23 15:42
nginx version: nginx/1.9.10

**Comment by enjikaka** [comment] 2016-04-23 15:44
Can't even update nginx, Dokku fucks it up.

**Comment by enjikaka** [comment] 2016-04-23 15:50
grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/* gives:
```
grep: /etc/apt/sources.list: No such file or directory
/etc/apt/sources.list.d/docker.list:deb https://apt.dockerproject.org/repo ubuntu-trusty main
/etc/apt/sources.list.d/dokku.list:deb https://packagecloud.io/dokku/dokku/ubuntu/ trusty main
/etc/apt/sources.list.d/nginx.list:#deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx
/etc/apt/sources.list.d/nginx.list:#deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx
```

Might help

**Comment by josegonzalez** [comment] 2016-04-23 16:04
It's basically a bug where we try and force downgrade you. Duplicate of #2059.

**Comment by enjikaka** [comment] 2016-04-23 16:05
So... how can I get it to work then?

**Closed by josegonzalez** 2016-04-23 16:04 UTC
