### ISSUE TITLE
Can't override EXPOSE port via docker-option -p

### ISSUE THREAD

**Issue by sglebs** [dokku/dokku#2066] opened 2016-04-02 01:30 UTC
If you try the steps at https://github.com/sglebs/kibana you will see that the Dockerfile exposes 5601 but the docker-options uses -p to redirect 80 to 5601. Unfortunately I can't seem to be able to go to port 80, just 5601.

Is there an elegant way to make this work? I am using a Dockerfile which is already configured for 5601, unfortunately. 0.5.3 here. Thanks!

**Comment by michaelshobbs** [comment] 2016-04-02 01:39
I think you'll need to do this with a custom nginx template as discussed in #2028 and #2053 

http://dokku.viewdocs.io/dokku/deployment/dockerfiles/#exposed-ports

**Comment by michaelshobbs** [comment] 2016-04-02 01:42
Upon further reading, you'll want to specify the `deploy` phase for the `docker-options` plugin. See docs here: http://dokku.viewdocs.io/dokku/docker-options/#about-dokku-phases

**Comment by sglebs** [comment] 2016-04-02 02:09
yes, deploy, I noticed that after posting. But just changing to deploy did not do it. I will look at the template stuff.

**Comment by michaelshobbs** [comment] 2016-04-02 02:13
Can you share the output of `docker inspect` for the running container?

**Comment by sglebs** [comment] 2016-04-02 02:14
Readig https://github.com/dokku/dokku/issues/2028 leads me to believe that I can remove "EXPOSE 5601" and use "-p 5000:5601" and let nginx default to 5000. Will that work?

**Comment by sglebs** [comment] 2016-04-02 02:16
```
vagrant@dokku-vagrant:~$ sudo docker inspect 570bf02a281c
[
    {
        "Id": "570bf02a281cc92630aa2eaebdf69e58a1256d1608e1193a0c83a1c68e84bb36",
        "Created": "2016-04-02T02:01:51.796092045Z",
        "Path": "/docker-entrypoint.sh",
        "Args": [
            "kibana"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 31797,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2016-04-02T02:01:51.981766195Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:b846f772da6e6ee6f483ceafa7bccdd1d97eaf5f8ba7161a8ee4d74374d4b4dd",
        "ResolvConfPath": "/var/lib/docker/containers/570bf02a281cc92630aa2eaebdf69e58a1256d1608e1193a0c83a1c68e84bb36/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/570bf02a281cc92630aa2eaebdf69e58a1256d1608e1193a0c83a1c68e84bb36/hostname",
        "HostsPath": "/var/lib/docker/containers/570bf02a281cc92630aa2eaebdf69e58a1256d1608e1193a0c83a1c68e84bb36/hosts",
        "LogPath": "/var/lib/docker/containers/570bf02a281cc92630aa2eaebdf69e58a1256d1608e1193a0c83a1c68e84bb36/570bf02a281cc92630aa2eaebdf69e58a1256d1608e1193a0c83a1c68e84bb36-json.log",
        "Name": "/kibana.web.1",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "5601/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "80"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "ShmSize": 67108864,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "KernelMemory": 0,
            "Memory": 268435456,
            "MemoryReservation": 0,
            "MemorySwap": -1,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [],
        "Config": {
            "Hostname": "570bf02a281c",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5601/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PSQL_SC_BIND_IP=0.0.0.0",
                "PSQL_SC_IMAGE=mdillon/postgis:9.5",
                "DOKKU_APP_TYPE=dockerfile",
                "DOKKU_DOCKERFILE_PORTS=5601",
                "ELASTICSEARCH_URL=http://elasticsearch.dokku-vagrant.sglebs.com:9200",
                "NODE_OPTIONS=--max-old-space-size=200",
                "PORT=5601",
                "DYNO='web.1'",
                "PATH=/opt/kibana/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.7",
                "TINI_VERSION=v0.9.0",
                "KIBANA_MAJOR=4.5",
                "KIBANA_VERSION=4.5.0"
            ],
            "Cmd": [
                "kibana"
            ],
            "Image": "dokku/kibana:latest",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": [
                "/docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "dokku": ""
            },
            "StopSignal": "SIGTERM"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "b1dad04e3787cdda1ca5714d1fffa6d17fe061271732744c2bc5b899dac15dff",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5601/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "80"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/b1dad04e3787",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "e13d33f84cb542d60534b3702851bc3ca4f38aa4e8593a250fd5a6ed329c2704",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.3",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:03",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "288e2e84e350100908f982bef3609dd6c8185fc4e41af61fd059e357ecf7125a",
                    "EndpointID": "e13d33f84cb542d60534b3702851bc3ca4f38aa4e8593a250fd5a6ed329c2704",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:03"
                }
            }
        }
    }
]
```

**Comment by michaelshobbs** [comment] 2016-04-02 02:20
I believe that should work. Additionally, you wouldn't be able to bind to port 80 if nginx was installed and running. (dokku forces this...)

**Comment by michaelshobbs** [comment] 2016-04-02 02:21
I was able to get your app running using your `README` by just shutting off nginx.

**Comment by michaelshobbs** [comment] 2016-04-02 02:22
However, subsequent deploys fail as the previous deployed container is using the external port.

**Comment by michaelshobbs** [comment] 2016-04-02 02:25
You docker container looks like it has the correct port bindings. Mine also looked correct here:
```
02988f50c479        dokku/kibana:latest        "/docker-entrypoint.s"   34 seconds ago      Up 33 seconds       0.0.0.0:80->5601/tcp                kibana.web.1
```

Closing as this seems to work as designed. Let us know if you have further questions.

**Closed by michaelshobbs** 2016-04-02 02:25 UTC
Labels: type: question

**Comment by sglebs** [comment] 2016-04-02 02:34
You mean you got it working just by adding this following step?
```
ssh dokku@10.0.0.2 proxy:disable kibana
```
(for me it does not do it)

**Comment by michaelshobbs** [comment] 2016-04-02 02:37
I destroyed the app. Shut down nginx (`service nginx stop`). Then followed your readme. It's not how'd do it though. I'd use nginx to proxy port 80 to the docker container with a custom nginx template or make the app listen on 5000 inside the container and remove the `EXPOSE` line

**Comment by sglebs** [comment] 2016-04-02 02:55
I have to expose 5601 because this is what I "inherit" (FROM in Dockerfile). I will study how to do a custom nginx template.

But it does feel like a lot of pain for something simple - make the nginx honor the -p and not the EXPOSE. An env var for an override would be wonderful here.

**Comment by sglebs** [comment] 2016-04-02 03:39
I spent some time with the nginx template. I guess it needs many hours of investment. Here, it worked:

```
upstream {{ .APP }} {
{{ range .DOKKU_APP_LISTENERS | split " " }}
  server {{ . }}:{{ 5601 }};
{{ end }}
}
server {
  listen      [::]:{{ 80 }};
  listen      {{ 80 }};
  server_name {{ .NOSSL_SERVER_NAME }};
  access_log  /var/log/nginx/{{ .APP }}-access.log;
  error_log   /var/log/nginx/{{ .APP }}-error.log;

  location    / {
    proxy_pass  http://{{ .APP }};
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include {{ .DOKKU_ROOT }}/{{ .APP }}/nginx.conf.d/*.conf;
}
```
although at the end of the git push it prints: 
```
=====> Application deployed:
       http://kibana.dokku-vagrant.sglebs.com:5601
```
but that port in the url is wrong. It is 80 now.

**Comment by michaelshobbs** [comment] 2016-04-02 04:31
The `-p` docker-option does work but you'll run into issues with the zero-downtime deployment.

**Comment by michaelshobbs** [comment] 2016-04-02 04:33
Regarding the custom nginx template and the app URLs there's an open issue about that. 

#2054

**Comment by sglebs** [comment] 2016-04-02 13:02
My nginx solution did not work. If I ry to go to http://10.0.0.2 I end up in the cabin page.

**Comment by michaelshobbs** [comment] 2016-04-04 18:34
This indeed sounds like an issue with your template. What did you end up doing?
