### ISSUE TITLE
Error using dokku run --rm on cronjob "no entries found in Procfile"

### ISSUE THREAD

**Issue by sicutdeux** [dokku/dokku#4083] opened 2020-07-24 17:03 UTC
## Description of problem
I have a several cron jobs running with command: dokku run --rm, randomly and a few times a day the command does not run and throws an error: "no entries found in Procfile"

### How reproducible
No idea, it happens randomly over time, few times a day.

### Steps to Reproduce
1. Create cron job that runs a bash script every 5 minutes:
Script:

```
#!/bin/bash
SECONDS=0
dokku --rm run appname php -d memory_limit=4096M artisan --no-ansi scriptnameofartisan 
TOTAL_TIME=$(date -d@$SECONDS -u +%H:%M:%S)
echo "Total time: $TOTAL_TIME"
```

#### Actual Results
Most of the time it works but sometimes it does not with the error output shown before.

### `dokku report APP_NAME` output

```
-----> uname: Linux ngapps 5.3.0-1020-gcp #22~18.04.1-Ubuntu SMP Mon May 11 18:45:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:          60291       12934        1887         407       45469       46311
       Swap:             0           0           0
-----> docker version:
       Client: Docker Engine - Community
        Version:           19.03.9
        API version:       1.40
        Go version:        go1.13.10
        Git commit:        9d988398e7
        Built:             Fri May 15 00:25:18 2020
        OS/Arch:           linux/amd64
        Experimental:      false

       Server: Docker Engine - Community
        Engine:
         Version:          19.03.9
         API version:      1.40 (minimum version 1.12)
         Go version:       go1.13.10
         Git commit:       9d988398e7
         Built:            Fri May 15 00:23:50 2020
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.2.13
         GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
        runc:
         Version:          1.0.0-rc10
         GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
        docker-init:
         Version:          0.18.0
         GitCommit:        fec3683
-----> docker daemon info:
       Client:
        Debug Mode: true

       Server:
        Containers: 68
         Running: 23
         Paused: 0
         Stopped: 45
        Images: 679
        Server Version: 19.03.9
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
        runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
        init version: fec3683
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.3.0-1020-gcp
        Operating System: Ubuntu 18.04.4 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 16
        Total Memory: 58.88GiB
        Name: ngapps
        ID: JNIH:SWQ6:AVU2:B44V:H2MY:Y5HI:UVEQ:IS5D:SRN5:WDFU:5RKQ:YY2R
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
WARNING: No swap limit support
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> sigil version: 0.6.0
-----> herokuish version:
       herokuish: 0.5.13
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v215
         heroku-buildpack-nodejs    v171
         heroku-buildpack-clojure   v84
         heroku-buildpack-python    v169
         heroku-buildpack-java      v66
         heroku-buildpack-gradle    v31
         heroku-buildpack-scala     v87
         heroku-buildpack-play      v26
         heroku-buildpack-php       v174
         heroku-buildpack-go        v142
         buildpack-nginx            v13
-----> dokku version: dokku version 0.20.4
-----> dokku plugins:
       plugn: 0.5.0
         00_dokku-standard    0.20.4 enabled    dokku core standard plugin
         20_events            0.20.4 enabled    dokku core events logging plugin
         app-json             0.20.4 enabled    dokku core app-json plugin
         apps                 0.20.4 enabled    dokku core apps plugin
         builder-dockerfile   0.20.4 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.20.4 enabled    dokku core builder-herokuish plugin
         buildpacks           0.20.4 enabled    dokku core buildpacks plugin
         certs                0.20.4 enabled    dokku core certificate management plugin
         checks               0.20.4 enabled    dokku core checks plugin
         common               0.20.4 enabled    dokku core common plugin
         config               0.20.4 enabled    dokku core config plugin
         docker-options       0.20.4 enabled    dokku core docker-options plugin
         domains              0.20.4 enabled    dokku core domains plugin
         enter                0.20.4 enabled    dokku core enter plugin
         git                  0.20.4 enabled    dokku core git plugin
         letsencrypt          0.9.1 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.20.4 enabled    dokku core logs plugin
         network              0.20.4 enabled    dokku core network plugin
         nginx-proxy-timeout  0.1.0 enabled    Dokku plugin for setting proxy timeout in nginx config
         nginx-vhosts         0.20.4 enabled    dokku core nginx-vhosts plugin
         plugin               0.20.4 enabled    dokku core plugin plugin
         proxy                0.20.4 enabled    dokku core proxy plugin
         ps                   0.20.4 enabled    dokku core ps plugin
         repo                 0.20.4 enabled    dokku core repo plugin
         resource             0.20.4 enabled    dokku core resource plugin
         scheduler-docker-local 0.20.4 enabled    dokku core scheduler-docker-local plugin
         shell                0.20.4 enabled    dokku core shell plugin
         ssh-keys             0.20.4 enabled    dokku core ssh-keys plugin
         storage              0.20.4 enabled    dokku core storage plugin
         tags                 0.20.4 enabled    dokku core tags plugin
         tar                  0.20.4 enabled    dokku core tar plugin
         trace                0.20.4 enabled    dokku core trace plugin
=====> MYAPPLICATION_NAME_REDACTED app information
       App deploy source:
       App dir:                       /home/dokku/MYAPPLICATION_NAME_REDACTED
       App locked:                    false
=====> MYAPPLICATION_NAME_REDACTED buildpacks information
       Buildpacks list:
CN = api.DOMAIN_REDACTED.com
error 20 at 0 depth lookup: unable to get local issuer certificate
=====> MYAPPLICATION_NAME_REDACTED ssl information
       Ssl dir:                       /home/dokku/MYAPPLICATION_NAME_REDACTED/tls
       Ssl enabled:                   true
       Ssl hostnames:                 api.DOMAIN_REDACTED.com MYAPPLICATION_NAME_REDACTED.DOMAIN_REDACTED.com SUBDOMAIN1_REDACTED.DOMAIN_REDACTED.com
       Ssl expires at:                Oct  7 23:00:15 2020 GMT
       Ssl issuer:                    C = US, O = Lets Encrypt, CN = Lets Encrypt Authority X3
       Ssl starts at:                 Jul  9 23:00:15 2020 GMT
       Ssl subject:                   subject=CN = api.DOMAIN_REDACTED.com
       Ssl verified:                  self signed
=====> MYAPPLICATION_NAME_REDACTED checks information
       Checks disabled list:          none
       Checks skipped list:           none
=====> MYAPPLICATION_NAME_REDACTED docker options information
       Docker options build:
       Docker options deploy:         --restart=on-failure:10 -v /mnt/disks/data/MYAPPLICATION_NAME_REDACTED-logs:/app/storage/logs -v /mnt/disks/data/MYAPPLICATION_NAME_REDACTED:/app/storage/app
       Docker options run:            -v /mnt/disks/data/MYAPPLICATION_NAME_REDACTED-logs:/app/storage/logs -v /mnt/disks/data/MYAPPLICATION_NAME_REDACTED:/app/storage/app
=====> MYAPPLICATION_NAME_REDACTED domains information
       Domains app enabled:           true
       Domains app vhosts:            api.DOMAIN_REDACTED.com MYAPPLICATION_NAME_REDACTED.DOMAIN_REDACTED.com SUBDOMAIN1_REDACTED.DOMAIN_REDACTED.com
       Domains global enabled:        true
       Domains global vhosts:         DOMAIN_REDACTED.com
=====> MYAPPLICATION_NAME_REDACTED git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       57daa4d
=====> MYAPPLICATION_NAME_REDACTED network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:   false
       Network web listeners:         172.17.0.12:5000
=====> MYAPPLICATION_NAME_REDACTED nginx information
       Nginx access log path:         /var/log/nginx/MYAPPLICATION_NAME_REDACTED-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx error log path:          /var/log/nginx/MYAPPLICATION_NAME_REDACTED-error.log
       Nginx hsts:                    true
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
=====> MYAPPLICATION_NAME_REDACTED proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 https:443:5000
       Proxy type:                    nginx
=====> MYAPPLICATION_NAME_REDACTED ps information
       Processes:                     2
       Deployed:                      true
       Running:                       true
       Restore:                       true
       Restart policy:                on-failure:10
       Ps can scale:                  true
       Status web.1:                  running    (CID: f3ab89ec7941)
       Status worker.1:               running    (CID: 77061df49e04)
=====> MYAPPLICATION_NAME_REDACTED scheduler-docker-local information
       Scheduler docker local disable chown:
=====> MYAPPLICATION_NAME_REDACTED storage information
       Storage build mounts:
       Storage deploy mounts:         -v /mnt/disks/data/MYAPPLICATION_NAME_REDACTED-logs:/app/storage/logs -v /mnt/disks/data/MYAPPLICATION_NAME_REDACTED:/app/storage/app
       Storage run mounts:            -v /mnt/disks/data/MYAPPLICATION_NAME_REDACTED-logs:/app/storage/logs -v /mnt/disks/data/MYAPPLICATION_NAME_REDACTED:/app/storage/app

```

### Additional information

- Container Inspect Output (if applicable) via `dokku ps:inspect APP_NAME`

```
+ export DOKKU_HOST_ROOT=/home/dokku
+ DOKKU_HOST_ROOT=/home/dokku
+ export DOKKU_DISTRO
++ . /etc/os-release
++ echo ubuntu
+ DOKKU_DISTRO=ubuntu
+ export DOCKER_BIN=docker
+ DOCKER_BIN=docker
+ export DOKKU_IMAGE=gliderlabs/herokuish:latest
+ DOKKU_IMAGE=gliderlabs/herokuish:latest
+ export DOKKU_LIB_ROOT=/var/lib/dokku
+ DOKKU_LIB_ROOT=/var/lib/dokku
+ export PLUGIN_PATH=/var/lib/dokku/plugins
+ PLUGIN_PATH=/var/lib/dokku/plugins
+ export PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ export PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ export PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ export PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ export PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ export DOKKU_SYSTEM_GROUP=dokku
+ DOKKU_SYSTEM_GROUP=dokku
+ export DOKKU_SYSTEM_USER=dokku
+ DOKKU_SYSTEM_USER=dokku
+ export DOKKU_API_VERSION=1
+ DOKKU_API_VERSION=1
+ export DOKKU_NOT_IMPLEMENTED_EXIT=10
+ DOKKU_NOT_IMPLEMENTED_EXIT=10
+ export DOKKU_VALID_EXIT=0
+ DOKKU_VALID_EXIT=0
+ export DOKKU_PID=3278
+ DOKKU_PID=3278
+ export DOKKU_LOGS_DIR=/var/log/dokku
+ DOKKU_LOGS_DIR=/var/log/dokku
+ export DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ export DOKKU_CONTAINER_LABEL=dokku
+ DOKKU_CONTAINER_LABEL=dokku
+ export 'DOKKU_GLOBAL_BUILD_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ DOKKU_GLOBAL_BUILD_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ export 'DOKKU_GLOBAL_RUN_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ DOKKU_GLOBAL_RUN_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ parse_args ps:inspect APP_NAME_REDACTED
+ declare 'desc=top-level cli arg parser'
+ local next_index=1
+ local skip=false
+ args=("$@")
+ local args
+ local flags
+ for arg in "$@"
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ [[ false == \t\r\u\e ]]
+ [[ ps:inspect == \-\-\a\p\p ]]
+ [[ ps:inspect =~ ^--.* ]]
+ next_index=2
+ for arg in "$@"
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ [[ false == \t\r\u\e ]]
+ [[ APP_NAME_REDACTED == \-\-\a\p\p ]]
+ [[ APP_NAME_REDACTED =~ ^--.* ]]
+ next_index=3
+ [[ -z '' ]]
++ echo -e ''
++ sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
+ export DOKKU_GLOBAL_FLAGS=
+ DOKKU_GLOBAL_FLAGS=
+ return 0
+ args=("$@")
+ skip_arg=false
+ [[ ps:inspect =~ ^--.* ]]
+ has_tty
+ declare 'desc=return 0 if we have a tty'
++ LC_ALL=C
++ /usr/bin/tty
+ [[ /dev/pts/1 == \n\o\t\ \a\ \t\t\y ]]
+ return 0
++ id -un
+ [[ root != \d\o\k\k\u ]]
+ [[ ! ps:inspect =~ plugin:* ]]
+ [[ ps:inspect != \s\s\h\-\k\e\y\s\:\a\d\d ]]
+ [[ ps:inspect != \s\s\h\-\k\e\y\s\:\r\e\m\o\v\e ]]
++ id -un
+ export SSH_USER=root
+ SSH_USER=root
+ sudo -u dokku -E -H /usr/bin/dokku ps:inspect APP_NAME_REDACTED
+ export DOKKU_HOST_ROOT=/home/dokku
+ DOKKU_HOST_ROOT=/home/dokku
+ export DOKKU_DISTRO
++ . /etc/os-release
++ echo ubuntu
+ DOKKU_DISTRO=ubuntu
+ export DOCKER_BIN=docker
+ DOCKER_BIN=docker
+ export DOKKU_IMAGE=gliderlabs/herokuish:latest
+ DOKKU_IMAGE=gliderlabs/herokuish:latest
+ export DOKKU_LIB_ROOT=/var/lib/dokku
+ DOKKU_LIB_ROOT=/var/lib/dokku
+ export PLUGIN_PATH=/var/lib/dokku/plugins
+ PLUGIN_PATH=/var/lib/dokku/plugins
+ export PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
+ export PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
+ export PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
+ export PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
+ export PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
+ export DOKKU_SYSTEM_GROUP=dokku
+ DOKKU_SYSTEM_GROUP=dokku
+ export DOKKU_SYSTEM_USER=dokku
+ DOKKU_SYSTEM_USER=dokku
+ export DOKKU_API_VERSION=1
+ DOKKU_API_VERSION=1
+ export DOKKU_NOT_IMPLEMENTED_EXIT=10
+ DOKKU_NOT_IMPLEMENTED_EXIT=10
+ export DOKKU_VALID_EXIT=0
+ DOKKU_VALID_EXIT=0
+ export DOKKU_PID=3289
+ DOKKU_PID=3289
+ export DOKKU_LOGS_DIR=/var/log/dokku
+ DOKKU_LOGS_DIR=/var/log/dokku
+ export DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
+ export DOKKU_CONTAINER_LABEL=dokku
+ DOKKU_CONTAINER_LABEL=dokku
+ export 'DOKKU_GLOBAL_BUILD_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ DOKKU_GLOBAL_BUILD_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ export 'DOKKU_GLOBAL_RUN_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ DOKKU_GLOBAL_RUN_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ parse_args ps:inspect APP_NAME_REDACTED
+ declare 'desc=top-level cli arg parser'
+ local next_index=1
+ local skip=false
+ args=("$@")
+ local args
+ local flags
+ for arg in "$@"
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ [[ false == \t\r\u\e ]]
+ [[ ps:inspect == \-\-\a\p\p ]]
+ [[ ps:inspect =~ ^--.* ]]
+ next_index=2
+ for arg in "$@"
+ [[ false == \t\r\u\e ]]
+ case "$arg" in
+ [[ false == \t\r\u\e ]]
+ [[ APP_NAME_REDACTED == \-\-\a\p\p ]]
+ [[ APP_NAME_REDACTED =~ ^--.* ]]
+ next_index=3
+ [[ -z '' ]]
++ echo -e ''
++ sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
+ export DOKKU_GLOBAL_FLAGS=
+ DOKKU_GLOBAL_FLAGS=
+ return 0
+ args=("$@")
+ skip_arg=false
+ [[ ps:inspect =~ ^--.* ]]
+ has_tty
+ declare 'desc=return 0 if we have a tty'
++ LC_ALL=C
++ /usr/bin/tty
+ [[ /dev/pts/1 == \n\o\t\ \a\ \t\t\y ]]
+ return 0
++ id -un
+ [[ dokku != \d\o\k\k\u ]]
+ [[ ps:inspect =~ ^plugin:.* ]]
+ [[ ps:inspect == \s\s\h\-\k\e\y\s\:\a\d\d ]]
+ [[ ps:inspect == \s\s\h\-\k\e\y\s\:\r\e\m\o\v\e ]]
+ [[ -n '' ]]
+ dokku_auth ps:inspect APP_NAME_REDACTED
+ declare 'desc=calls user-auth plugin trigger'
+ export SSH_USER=root
+ SSH_USER=root
+ export SSH_NAME=default
+ SSH_NAME=default
++ wc -l
++ find /var/lib/dokku/plugins/enabled/20_events/user-auth
+ [[ 1 == 1 ]]
+ return 0
+ case "$1" in
+ execute_dokku_cmd ps:inspect APP_NAME_REDACTED
+ declare 'desc=executes dokku sub-commands'
+ local PLUGIN_NAME=ps:inspect
+ local PLUGIN_CMD=ps:inspect
+ local implemented=0
+ local script
+ argv=("$@")
+ local argv
+ case "$PLUGIN_NAME" in
++ readlink -f /var/lib/dokku/plugins/enabled/ps
+ [[ /var/lib/dokku/core-plugins/available/ps == *core-plugins* ]]
+ [[ ps:inspect == \p\s\:\i\n\s\p\e\c\t ]]
+ shift 1
+ [[ -n '' ]]
+ set -- ps:inspect APP_NAME_REDACTED
+ [[ -x /var/lib/dokku/plugins/enabled/ps:inspect/subcommands/default ]]
+ [[ -x /var/lib/dokku/plugins/enabled/ps:inspect/subcommands/ps:inspect ]]
+ [[ -x /var/lib/dokku/plugins/enabled/ps/subcommands/inspect ]]
+ [[ -n inspect ]]
+ /var/lib/dokku/plugins/enabled/ps/subcommands/inspect ps:inspect APP_NAME_REDACTED
++ source /var/lib/dokku/plugins/available/docker-options/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+++ source /var/lib/dokku/core-plugins/available/common/functions
++++ set -eo pipefail
++++ [[ -n 1 ]]
++++ set -x
+++ AVAILABLE_PHASES=(build deploy run)
++ source /var/lib/dokku/plugins/available/config/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+++ source /var/lib/dokku/core-plugins/available/common/functions
++++ set -eo pipefail
++++ [[ -n 1 ]]
++++ set -x
++ source /var/lib/dokku/plugins/available/ps/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+++ source /var/lib/dokku/core-plugins/available/common/functions
++++ set -eo pipefail
++++ [[ -n 1 ]]
++++ set -x
+++ source /var/lib/dokku/plugins/available/config/functions
++++ set -eo pipefail
++++ [[ -n 1 ]]
++++ set -x
++++ source /var/lib/dokku/core-plugins/available/common/functions
+++++ set -eo pipefail
+++++ [[ -n 1 ]]
+++++ set -x
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ set -eo pipefail
+ [[ -n 1 ]]
+ set -x
+ cmd-ps-inspect ps:inspect APP_NAME_REDACTED
+ declare 'desc=displays a sanitized version of docker inspect for an app'
+ declare cmd=ps:inspect
+ [[ ps:inspect == \p\s\:\i\n\s\p\e\c\t ]]
+ shift 1
+ declare APP=APP_NAME_REDACTED
+ verify_app_name APP_NAME_REDACTED
+ declare 'desc=verify app name format and app existence'
+ local APP=APP_NAME_REDACTED
+ is_valid_app_name APP_NAME_REDACTED
+ declare 'desc=verify app name format'
+ local APP=APP_NAME_REDACTED
+ [[ -z APP_NAME_REDACTED ]]
+ [[ APP_NAME_REDACTED =~ ^[a-z].* ]]
+ [[ ! APP_NAME_REDACTED =~ [A-Z] ]]
+ [[ ! APP_NAME_REDACTED =~ [:] ]]
+ return 0
+ [[ ! -d /home/dokku/APP_NAME_REDACTED ]]
+ dokku_log_fail 'App APP_NAME_REDACTED does not exist'
+ declare 'desc=log fail formatter'
+ echo 'App APP_NAME_REDACTED does not exist'
App APP_NAME_REDACTED does not exist
+ exit 1
```

### Side Notes:

i'm using procfile with a php-buildpack

**Comment by josegonzalez** [comment] 2020-08-02 00:47
Fix for this should be to extract the Procfile in pre-release and then reference that extracted file until it gets extracted again.

Note that we should handle the case where a deploy fails, so we should extract to a temporary location for the duration of the deploy, and then move the extracted file to the "normal" place so that future invocations that utilize the Procfile reference one that works with the deployed app.

**Comment by bobwhitelock** [comment] 2020-08-05 00:51
I'm also running into this issue sometimes - do you know what's causing this? Is there anything that can be done to work around it - would using `dokku enter` as suggested at http://dokku.viewdocs.io/dokku/deployment/one-off-processes/#using-enter-for-cron-tasks help (no idea if it would without knowing the cause, but just a thought)?

**Comment by sicutdeux** [comment] 2020-08-07 13:52
I still keep a look on this because I have quite a few jobs that runs on cron, so, I started noticing that the errors occurs once a job is started and another a few seconds after tries to run, the latter fails with the message of `no entries found in Procfile` while the other keeps running.

**Comment by bobwhitelock** [comment] 2020-08-07 14:13
That's interesting @sicutdeux - I have a job that runs once a day and a job that runs every minute, and have seen the once a day job fail like this a few times. So I could be facing the same cause, with the job that runs every minute causing the daily job to occasionally fail.

**Comment by josegonzalez** [comment] 2020-11-22 22:15
Closing as there is a pull request open.

**Closed by josegonzalez** 2020-11-22 22:15 UTC
Labels: difficulty: hard, merge-level: minor, plugin: schedulers, status: has plan, type: bug
