### ISSUE TITLE
remote: Error response from daemon: no such id

### ISSUE THREAD

**Issue by kilianc** [dokku/dokku#1746] opened 2015-12-03 20:03 UTC
Hello there!

So I have an app called dev, the Dockerfile builds and runs ok locally but when I push it to dokku after everything passes as well I get this:

```
Successfully built 2f6b8f8a6b49
-----> Releasing dev (dokku/dev:latest)...
-----> Deploying dev (dokku/dev:latest)...
-----> DOKKU_SCALE file not found in app image. Generating one based on Procfile...
-----> New DOKKU_SCALE file generated
=====> web=1
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://progrium.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
-----> Default container check successful!
=====> dev container output:
=====> end dev container output
-----> Running post-deploy
remote: Error response from daemon: no such id: dev.web.1
remote: Error: failed to rename container named dev.web.1
```

**Comment by josegonzalez** [comment] 2015-12-03 20:13
Can you provide all the info we ask for in the contributing.md?

**Comment by kilianc** [comment] 2015-12-03 20:18
```
$ uname -a
Linux **** 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ free -m
             total       used       free     shared    buffers     cached
Mem:           994        693        300          0         98        277
-/+ buffers/cache:        317        676
Swap:         4095        338       3757

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

$ docker -D info
Containers: 12
Images: 100
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 124
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-68-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 994 MiB
Name: ***
ID: HIN5:KUAQ:C2OJ:PUXY:EVAM:FKBH:XQEV:747D:A4NJ:H7P4:IFKJ:UVKE

$ docker run -ti gliderlabs/herokuish:latest herokuish version
herokuish: 0.3.5
buildpacks:
  heroku-buildpack-clojure   v70
  heroku-buildpack-go        v18
  heroku-buildpack-gradle    v12
  heroku-buildpack-grails    v19
  heroku-buildpack-java      v40
  heroku-buildpack-multi     26fa21a
  heroku-buildpack-nodejs    v86
  heroku-buildpack-php       v80
  heroku-buildpack-play      v24
  heroku-buildpack-python    v70
  heroku-buildpack-ruby      v140
  heroku-buildpack-scala     v63
  https://github.com/dokku/buildpack-nginx v5

$ dokku version
0.4.5

$ dokku plugin
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
  named-containers     0.4.0.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin

**Comment by josegonzalez** [comment] 2015-12-03 20:20
Also a dokku trace deploy.

**Comment by kilianc** [comment] 2015-12-03 20:23
`2>&1 deploy.log` doesn't work, suggestions?

**Comment by josegonzalez** [comment] 2015-12-03 20:24
Use a proper terminal that supports infinite terminal scroll?

**Comment by josegonzalez** [comment] 2015-12-03 20:30
That was a serious comment, I don't know why you wouldn't be able to redirect output, so I assume it has something to do with your terminal emulator.

Were you able to figure out why dokku is freaking out about your containers?

**Comment by michaelshobbs** [comment] 2015-12-03 22:07
@kilianc The original error was fixed with #1707 and released in `0.4.5`
```
remote: Error response from daemon: no such id: dev.web.1
remote: Error: failed to rename container named dev.web.1
```

**Comment by josegonzalez** [comment] 2015-12-03 22:10
@michaelshobbs He is running 0.4.5 though...

**Comment by michaelshobbs** [comment] 2015-12-03 22:24
Ah my bad. I overlooked the plugins output

**Comment by zenzire** [comment] 2015-12-11 21:32
I have the same problem.

Reproduction procedure:
1. dokku apps:create subdomain.domain.com
2. Application created successfully
3. Deploy application (push to dokku repository)
4. Application deployed successfully
5. dokku apps:create domain.com
6. Application created successfully
7. Deploy application (push to dokku repository)
8. **Application deployment failed**

Error log:
```
remote: Error response from daemon: no such id: domain.com.web.1
remote: Error: failed to rename container named domain.com.web.1
```

The problem is in plugin named-containers/post-deploy in line 9:
https://github.com/dokku/dokku/blob/master/plugins/named-containers/post-deploy#L9


```
PREVIOUS=$(docker ps -a -q -f name="$NAME\$") || true
```
Command returns **subdomain.domain.com** container ID instead of **domain.com**.

**Comment by michaelshobbs** [comment] 2015-12-11 21:37
@Flink can you take a look?

**Comment by Flink** [comment] 2015-12-13 22:29
@michaelshobbs done! :)

**Closed** 2015-12-14 01:39 UTC
Labels: needs more info

**Comment by zenzire** [comment] 2015-12-14 15:59
@michaelshobbs @josegonzalez 
Confirmed, it works now.

**Comment by michaelshobbs** [comment] 2015-12-14 16:57
thanks @Flink !!!!

**Comment by Flink** [comment] 2015-12-14 17:02
You’re welcome :)
