### ISSUE TITLE
Dokku build keeps failing when installing npm packages

### ISSUE THREAD

**Issue by tejans24** [dokku/dokku#1891] opened 2016-01-28 20:40 UTC
```
➜  project git:(master) ✗ git push dokku master
Counting objects: 707, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (355/355), done.
Writing objects: 100% (707/707), 751.53 KiB | 0 bytes/s, done.
Total 707 (delta 349), reused 578 (delta 307)
-----> Cleaning up...
-----> Building project from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Node.js app detected

-----> Creating runtime environment

       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true

-----> Installing binaries
       engines.node (package.json):  5.4.0
       engines.npm (package.json):   unspecified (use default)

       Downloading and installing node 5.4.0...
       Using default npm version: 3.3.12

-----> Restoring cache
       Skipping cache restore (new runtime signature)

-----> Building dependencies
       Pruning any extraneous modules
       Installing node modules (package.json)

       > bufferutil@1.2.1 install /tmp/build/node_modules/bufferutil
       > node-gyp rebuild




-----> Build failed

       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys

       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/

       Love,
       Heroku

To dokku@ipaddress:project
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@ipaddress:project'`
```

More Information:

uname -a
Linux ubuntu-1gb-nyc2-01 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

dokku version
0.4.13

dokku plugin
  00_dokku-standard    0.4.0 enabled    dokku core standard plugin
  20_events            0.4.0 enabled    dokku core events logging plugin
  apps                 0.4.0 enabled    dokku core apps plugin
  backup               0.4.0 enabled    dokku core backup plugin
  build-env            0.4.0 enabled    dokku core build-env plugin
  certs                0.4.0 enabled    dokku core certificate management plugin
  checks               0.4.0 enabled    dokku core checks plugin
  common               0.4.0 enabled    dokku core common plugin
  config               0.4.0 enabled    dokku core config plugin
  docker-options       0.4.0 enabled    dokku core docker-options plugin
  domains              0.4.0 enabled    dokku core domains plugin
  enter                0.4.0 enabled    dokku core enter plugin
  git                  0.4.0 enabled    dokku core git plugin
  logs                 0.4.0 enabled    dokku core logs plugin
  named-containers     0.4.0.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.4.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.4.0 enabled    dokku core plugin plugin
  ps                   0.4.0 enabled    dokku core ps plugin
  shell                0.4.0 enabled    dokku core shell plugin
  tags                 0.4.0 enabled    dokku core tags plugin
  tar                  0.4.0 enabled    dokku core tar plugin

Environment details: Digital Ocean
Dokku was installing using the installation shell script

This project has a lot of npm packages to be installed even in production, Is  it just timing out when running npm install?

This works on Heroku!

**Comment by josegonzalez** [comment] 2016-01-28 20:58
Can you gist deploy output after running the following command:

```
dokku trace on
```
?

**Comment by tejans24** [comment] 2016-01-28 21:11
I'm rebuilding the instance, I'll post the information right after I push again.

**Comment by tejans24** [comment] 2016-01-28 22:51
@josegonzalez here is the gist: https://gist.github.com/tejans24/c8961caa73c5601fba0f

**Comment by federicous** [comment] 2016-02-05 05:16
@tejans24 I was having the same problem. I was using node 5.5.0 by default in my local, then especified a lower version in my package.json file just to test and the deploy worked. You could also try adding npm version too.

`"engines": {
      "node": "0.12.7"
  }`

`"engines": {
      "node": "0.12.7",
      "npm": "2.11.3"
  }`


This might not be a definite solution but may help you.

**Comment by josegonzalez** [comment] 2016-02-05 05:46
@tejans24 can you post your `package.json`?

**Comment by josegonzalez** [comment] 2016-02-19 01:40
Closing as there hasn't been any update. Feel free to comment with more information.

**Closed by josegonzalez** 2016-02-19 01:40 UTC
Labels: needs more info

**Comment by figalex** [comment] 2016-02-23 05:04
I'm having a similar issue, here is the output I get:

```
Writing objects: 100% (12/12), 16.22 KiB | 0 bytes/s, done.
Total 12 (delta 7), reused 0 (delta 0)
-----> Cleaning up...
-----> Building dev from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Node.js app detected

-----> Creating runtime environment

       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true

-----> Installing binaries
       engines.node (package.json):  0.12.7
       engines.npm (package.json):   2.11.3

       Downloading and installing node 0.12.7...
       npm 2.11.3 already installed with node

-----> Restoring cache
       Skipping cache restore (new runtime signature)

-----> Building dependencies
       Pruning any extraneous modules
       Installing node modules (package.json + shrinkwrap)

       > spawn-sync@1.0.15 postinstall /tmp/build/node_modules/spawn-sync
       > node postinstall


remote: /tmp/buildpacks/heroku-buildpack-nodejs/lib/dependencies.sh: line 1:   253 Killed                  npm install --unsafe-perm --userconfig $build_dir/.npmrc 2>&1

-----> Build failed

       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys

       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/

       Love,
       Heroku
```

Any ideas of what does the "npm install --unsafe-perm" thing means?

**Comment by josegonzalez** [comment] 2016-02-23 05:25
That's just how the package is built.

You are probably having your build fail due to insufficient memory. We recommend at least 1GB of memory, and possibly more depending upon your buildpack etc. You can add [swap to fix that issue](http://dokku.viewdocs.io/dokku/advanced-installation/#vms-with-less-than-1gb-of-memory).

**Comment by FilipLukac** [comment] 2016-05-09 13:16
@josegonzalez also fixed my similar problem. I've resized my VPS up to 1GB+ ram

**Comment by jasonrhodes** [comment] 2016-06-19 14:39
Was just having this same problem—bumped my DO droplet up to $10/mo 1GB memory size, fixed it. Thanks @josegonzalez

**Comment by newbreedofgeek** [comment] 2016-07-11 07:18
@josegonzalez @figalex I had the same problem. free -m indicated my memory was running very low. Added more swap space to fix it (temporarily until I upgrade RAM that is)

**Comment by josegonzalez** [comment] 2016-07-11 07:31
Thanks for giving this a 👍, but no need to comment on old issues. It sends notifications to repo collaborators and also doesn't really add to the conversation, especially as we've documented this and several people have already confirmed the fix.
