### ISSUE TITLE
Deleting an app is not possible when Nginx is not running

### ISSUE THREAD

**Issue by bastianh** [dokku/dokku#6832] opened 2024-04-17 15:20 UTC
### Description of problem

When using Traefik for example as proxy it's not possible to delete a freshly created app that is configured as Nginx app

### Steps to reproduce

```
ubuntu@instance-20220825-1332:~$ dokku apps:create testapp
-----> Creating testapp...
-----> Creating new app virtual host file...


ubuntu@instance-20220825-1332:~$ dokku apps:destroy testapp
 !     WARNING: Potentially Destructive Action
 !     This command will destroy app testapp.
 !     To proceed, type "testapp"
> testapp
-----> Destroying testapp (including all add-ons)
nginx.service is not active, cannot reload.
 !     nginx.service is not active, cannot reload.

```

### dokku report $APP_NAME

```
-----> uname: Linux instance-20220825-1332 6.5.0-1020-oracle #20~22.04.1-Ubuntu SMP Fri Mar 15 00:53:59 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
-----> memory:
                      total        used        free      shared  buff/cache   available
       Mem:           23981         637       21590          19        1753       23031
       Swap:              0           0           0
-----> disk utilization:
       Filesystem      Size  Used Avail Use% Mounted on
       /dev/sda1        45G   18G   28G  39% /
       /dev/sda15       98M  6.3M   92M   7% /boot/efi
-----> disk inode utilization:
       Filesystem     Inodes IUsed IFree IUse% Mounted on
       /dev/sda1        5.8M  397K  5.4M    7% /
       /dev/sda15          0     0     0     - /boot/efi
-----> docker version:
       Client: Docker Engine - Community
        Version:           26.0.0
        API version:       1.45
        Go version:        go1.21.8
        Git commit:        2ae903e
        Built:             Wed Mar 20 15:18:14 2024
        OS/Arch:           linux/arm64
        Context:           default

       Server: Docker Engine - Community
        Engine:
         Version:          26.0.0
         API version:      1.45 (minimum version 1.24)
         Go version:       go1.21.8
         Git commit:       8b79278
         Built:            Wed Mar 20 15:18:14 2024
         OS/Arch:          linux/arm64
         Experimental:     false
        containerd:
         Version:          1.6.31
         GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
        runc:
         Version:          1.1.12
         GitCommit:        v1.1.12-0-g51d5e94
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client: Docker Engine - Community
        Version:    26.0.0
        Context:    default
        Debug Mode: true
        Plugins:
         buildx: Docker Buildx (Docker Inc.)
           Version:  v0.13.1
           Path:     /usr/libexec/docker/cli-plugins/docker-buildx
         compose: Docker Compose (Docker Inc.)
           Version:  v2.25.0
           Path:     /usr/libexec/docker/cli-plugins/docker-compose

       Server:
        Containers: 9
         Running: 7
         Paused: 0
         Stopped: 2
        Images: 10
        Server Version: 26.0.0
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Using metacopy: false
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: systemd
        Cgroup Version: 2
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: e377cd56a71523140ca6ae87e30244719194a521
        runc version: v1.1.12-0-g51d5e94
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: builtin
         cgroupns
        Kernel Version: 6.5.0-1020-oracle
        Operating System: Ubuntu 22.04.4 LTS
        OSType: linux
        Architecture: aarch64
        CPUs: 4
        Total Memory: 23.42GiB
        Name: instance-20220825-1332
        ID: 2d7ea676-8489-410a-bf74-ff79a21fc932
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
         File Descriptors: 69
         Goroutines: 80
         System Time: 2024-04-17T15:20:10.494575478Z
         EventsListeners: 2
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> herokuish version:
 !     herokuish not supported on arm64 architecture
-----> dokku version: dokku version 0.34.4
-----> dokku-event-listener version: 0.15.0build+5268732
-----> dokku-update version: dokku-update 0.8.0
-----> docker-container-healthchecker version: 0.9.0
-----> docker-image-labeler version: 0.6.1build+c6e15a9
-----> git version: git version 2.34.1
-----> lambda-builder version:        0.6.0
-----> netrc version: 0.8.0build+0751c1b
 !     pack binary is not available
-----> plugn version: plugn: 0.13.0build+fd5297a
-----> sigil version: 0.10.1build+e443be0
-----> sshcommand version: sshcommand 0.17.1
-----> dokku plugins:
         00_dokku-standard    0.34.4 enabled    dokku core standard plugin
         20_events            0.34.4 enabled    dokku core events logging plugin
         app-json             0.34.4 enabled    dokku core app-json plugin
         apps                 0.34.4 enabled    dokku core apps plugin
         builder              0.34.4 enabled    dokku core builder plugin
         builder-dockerfile   0.34.4 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.34.4 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.34.4 enabled    dokku core builder-lambda plugin
         builder-nixpacks     0.34.4 enabled    dokku core builder-nixpacks plugin
         builder-null         0.34.4 enabled    dokku core builder-null plugin
         builder-pack         0.34.4 enabled    dokku core builder-pack plugin
         buildpacks           0.34.4 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.34.4 enabled    dokku core caddy-vhosts plugin
         certs                0.34.4 enabled    dokku core certificate management plugin
         checks               0.34.4 enabled    dokku core checks plugin
         common               0.34.4 enabled    dokku core common plugin
         config               0.34.4 enabled    dokku core config plugin
         cron                 0.34.4 enabled    dokku core cron plugin
         docker-options       0.34.4 enabled    dokku core docker-options plugin
         domains              0.34.4 enabled    dokku core domains plugin
         enter                0.34.4 enabled    dokku core enter plugin
         git                  0.34.4 enabled    dokku core git plugin
         haproxy-vhosts       0.34.4 enabled    dokku core haproxy-vhosts plugin
         logs                 0.34.4 enabled    dokku core logs plugin
         network              0.34.4 enabled    dokku core network plugin
         nginx-vhosts         0.34.4 enabled    dokku core nginx-vhosts plugin
         openresty-vhosts     0.34.4 enabled    dokku core openresty-vhosts plugin
         plugin               0.34.4 enabled    dokku core plugin plugin
         ports                0.34.4 enabled    dokku core ports plugin
         postgres             1.36.4 enabled    dokku postgres service plugin
         proxy                0.34.4 enabled    dokku core proxy plugin
         ps                   0.34.4 enabled    dokku core ps plugin
         redis                1.37.4 enabled    dokku redis service plugin
         registry             0.34.4 enabled    dokku core registry plugin
         repo                 0.34.4 enabled    dokku core repo plugin
         resource             0.34.4 enabled    dokku core resource plugin
         run                  0.34.4 enabled    dokku core run plugin
         scheduler            0.34.4 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.34.4 enabled    dokku core scheduler-docker-local plugin
         scheduler-k3s        0.34.4 enabled    dokku core scheduler-k3s plugin
         scheduler-null       0.34.4 enabled    dokku core scheduler-null plugin
         shell                0.34.4 enabled    dokku core shell plugin
         ssh-keys             0.34.4 enabled    dokku core ssh-keys plugin
         storage              0.34.4 enabled    dokku core storage plugin
         trace                0.34.4 enabled    dokku core trace plugin
         traefik-vhosts       0.34.4 enabled    dokku core traefik-vhosts plugin
```

**Comment by josegonzalez** [comment] 2024-09-24 01:20
I think this might be by design if the proxy type is nginx. Currently, proxies are associated per-app, so its attempting to interact with nginx as it thinks nginx should be used.

```
root@4ef29e9e89a1:~/go/src/github.com/dokku/dokku# dokku apps:create testapp
-----> Creating testapp...
-----> Creating new app virtual host file...
root@4ef29e9e89a1:~/go/src/github.com/dokku/dokku# dokku apps:destroy testapp --force 
-----> Destroying testapp (including all add-ons)
-----> Cleaning up...
-----> Retiring old containers and images
```

All that said, if nginx is stopped, thats effectively the same as the config not being loaded, so I think we should check if nginx is running prior to stopping it.

**Comment by josegonzalez** [comment] 2024-09-24 01:25
Closing as there is a pull request open.

**Closed by josegonzalez** 2024-09-24 01:25 UTC
Labels: type: bug, merge-level: patch, needs: investigation, plugin: proxy
