### ISSUE TITLE
Panic when deploying app on 18.04

### ISSUE THREAD

**Issue by eljojo** [dokku/dokku#3226] opened 2018-07-08 18:46 UTC
Hello, I ran into an issue that fixed itself, but that I have never seen before. I thought I'd share it anyway.
I am using Ubuntu 18.04 so please disregard if unsupported.

## Description of problem
I am deploying a Scala app on a newly installed machine.
This is the first app I try to run on it. It also fails on heroku's [ruby-sample](https://github.com/heroku/ruby-sample) app.
In both cases it fails after compiling the app using the buildpack.

### How reproducible
It failed every time I tried deploying the app (never deployed before).
**Deploying "fixed itself"** after turning `dokku trace on` and deploying.
Followup deploys were successful, even after turning `dokku trace off`.

### Steps to Reproduce

1. git push dokku master

#### Actual Results

```
       [info] Packaging /tmp/scala_buildpack_build_dir/target/scala-2.12/willie2_2.12-0.1.0-SNAPSHOT-javadoc.jar ...
       [info] Done packaging.
       [success] Total time: 3 s, completed Jul 8, 2018 6:19:11 PM
-----> Dropping ivy cache from the slug
-----> Dropping sbt boot dir from the slug
-----> Dropping compilation artifacts from the slug
remote: shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
remote: chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
remote: chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
remote: chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
-----> Discovering process types
remote: unexpected fault address 0x0
remote: fatal error: fault
remote: [signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x456995]
remote:
remote: goroutine 1 [running]:
remote: runtime.throw(0x5561e5, 0x5)
remote:         /usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc420041638 sp=0xc420041618 pc=0x428d75
remote: runtime.sigpanic()
remote:         /usr/local/go/src/runtime/signal_unix.go:374 +0x227 fp=0xc420041688 sp=0xc420041638 pc=0x43e5d7
remote: runtime.memmove(0xc4200b21b1, 0xc4200b9ffc, 0x4)
remote:         /usr/local/go/src/runtime/memmove_amd64.s:34 +0x5 fp=0xc420041690 sp=0xc420041688 pc=0x456995
remote: compress/flate.(*dictDecoder).writeCopy(0xc420026988, 0x1b5, 0xa, 0x0)
remote:         /usr/local/go/src/compress/flate/dict_decoder.go:121 +0xcf fp=0xc4200416e0 sp=0xc420041690 pc=0x4b242f
remote: compress/flate.(*decompressor).huffmanBlock(0xc420025900)
remote:         /usr/local/go/src/compress/flate/inflate.go:607 +0xace fp=0xc420041798 sp=0xc4200416e0 pc=0x4b57ae
remote: compress/flate.(*decompressor).Read(0xc420025900, 0xc42027c000, 0x67e00, 0x67e00, 0x6fe00, 0xd0ab19b7, 0x0)
remote:         /usr/local/go/src/compress/flate/inflate.go:347 +0x72 fp=0xc4200417d0 sp=0xc420041798 pc=0x4b4222
remote: compress/gzip.(*Reader).Read(0xc4200aa000, 0xc42027c000, 0x67e00, 0x67e00, 0x8000, 0x0, 0x0)
remote:         /usr/local/go/src/compress/gzip/gunzip.go:251 +0x96 fp=0xc420041880 sp=0xc4200417d0 pc=0x4b9366
remote: bytes.(*Buffer).ReadFrom(0xc420097180, 0x5f83a0, 0xc4200aa000, 0x7fb06d76c058, 0xc420097180, 0x1)

...

remote:         /usr/local/go/src/bytes/buffer.go:209 +0x177 fp=0xc4200418f8 sp=0xc420041880 pc=0x4679d7
remote: io.copyBuffer(0x5f8360, 0xc420097180, 0x5f83a0, 0xc4200aa000, 0x0, 0x0, 0x0, 0x5406c0, 0x1, 0xc420097180)
remote:         /usr/local/go/src/io/io.go:386 +0x2bb fp=0xc420041968 sp=0xc4200418f8 pc=0x45f59b
remote: io.Copy(0x5f8360, 0xc420097180, 0x5f83a0, 0xc4200aa000, 0x0, 0x0, 0x6a0620)
remote:         /usr/local/go/src/io/io.go:362 +0x68 fp=0xc4200419c8 sp=0xc420041968 pc=0x45f298
remote: github.com/progrium/go-basher.bindata_read(0x607dc0, 0x90ba7, 0x90ba7, 0x55601f, 0x4, 0xc, 0xc, 0xc, 0xc, 0x40fda7)
remote:         /home/circleci/.go_workspace/src/github.com/progrium/go-basher/bash_linux.go:25 +0x224 fp=0xc420041aa0 sp=0xc4200419c8 pc=0x4c55f4
remote: github.com/progrium/go-basher.bash_bytes(0xc420018380, 0xc420041b88, 0x4bc426, 0x55601f, 0x4)
remote:         /home/circleci/.go_workspace/src/github.com/progrium/go-basher/bash_linux.go:69 +0x5e fp=0xc420041b00 sp=0xc420041aa0 pc=0x4c58ee
remote: github.com/progrium/go-basher.bash(0x5315a0, 0xc42007a150, 0x55601f)
remote:         /home/circleci/.go_workspace/src/github.com/progrium/go-basher/bash_linux.go:76 +0x34 fp=0xc420041bc8 sp=0xc420041b00 pc=0x4c5974
remote: github.com/progrium/go-basher.Asset(0x55601f, 0x4, 0x0, 0xc420041cc8, 0x410508, 0x30, 0x53c660)
remote:         /home/circleci/.go_workspace/src/github.com/progrium/go-basher/bash_linux.go:92 +0xca fp=0xc420041c80 sp=0xc420041bc8 pc=0x4c5c2a
remote: github.com/progrium/go-basher.RestoreAsset(0xc420018380, 0xc, 0x55601f, 0x4, 0x5f85a0, 0xc42007a7e0)
remote:         /home/circleci/.go_workspace/src/github.com/progrium/go-basher/bash_linux.go:187 +0x4d fp=0xc420041d30 sp=0xc420041c80 pc=0x4c622d
remote: github.com/progrium/go-basher.Application(0xc42007a7b0, 0xc420041f10, 0x6, 0x6, 0x55f6a0, 0x1)
remote:         /home/circleci/.go_workspace/src/github.com/progrium/go-basher/basher.go:52 +0x81e fp=0xc420041ed8 sp=0xc420041d30 pc=0x4c6ffe
remote: main.main()
remote:         /home/circleci/gliderlabs/herokuish/herokuish.go:81 +0x1d0 fp=0xc420041f80 sp=0xc420041ed8 pc=0x50d340
remote: runtime.main()
remote:         /usr/local/go/src/runtime/proc.go:185 +0x20d fp=0xc420041fe0 sp=0xc420041f80 pc=0x42a44d
remote: runtime.goexit()
remote:         /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420041fe8 sp=0xc420041fe0 pc=0x4561e1
remote:
remote: goroutine 5 [syscall]:
remote: os/signal.signal_recv(0x0)
remote:         /usr/local/go/src/runtime/sigqueue.go:131 +0xa6
remote: os/signal.loop()
remote:         /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
remote: created by os/signal.init.0
remote:         /usr/local/go/src/os/signal/signal_unix.go:28 +0x41
To localhost:willie2
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@localhost:willie2'
```

#### Expected Results
_app deploys successfully_

## Environment Information
The installation is brand new and has no plugins installed.
I tried on 0.12.something and the newest master. Failed in both cases.

```
Description:    Ubuntu 18.04 LTS
Codename:       bionic

-----> uname: Linux bart 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:           6405        1365        1691          12        3348        4713
       Swap:           979           0         979
-----> docker version:
       Client:
        Version:      18.05.0-ce
        API version:  1.37
        Go version:   go1.9.5
        Git commit:   f150324
        Built:        Wed May  9 22:16:13 2018
        OS/Arch:      linux/amd64
        Experimental: false
        Orchestrator: swarm

       Server:
        Engine:
         Version:      18.05.0-ce
         API version:  1.37 (minimum version 1.12)
         Go version:   go1.9.5
         Git commit:   f150324
         Built:        Wed May  9 22:14:23 2018
         OS/Arch:      linux/amd64
         Experimental: false
-----> docker daemon info:
       Containers: 4
        Running: 0
        Paused: 0
        Stopped: 4
       Images: 9
       Server Version: 18.05.0-ce
       Storage Driver: overlay2
        Backing Filesystem: extfs
        Supports d_type: true
        Native Overlay Diff: true
       Logging Driver: json-file
       Cgroup Driver: cgroupfs
       Plugins:
        Volume: local
        Network: bridge host macvlan null overlay
        Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
       Swarm: inactive
       Runtimes: runc
       Default Runtime: runc
       Init Binary: docker-init
       containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
       runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
       init version: 949e6fa
       Security Options:
        apparmor
WARNING: No swap limit support
        seccomp
         Profile: default
       Kernel Version: 4.15.0-23-generic
       Operating System: Ubuntu 18.04 LTS
       OSType: linux
       Architecture: x86_64
       CPUs: 8
       Total Memory: 6.255GiB
       Name: bart
       ID: X6EG:JWMO:MDIZ:UYQA:DAVT:TOE3:2WYT:7LAA:YGSK:SAYR:IXQD:BSCI
       Docker Root Dir: /var/lib/docker
       Debug Mode (client): true
       Debug Mode (server): false
       Registry: https://index.docker.io/v1/
       Labels:
       Experimental: false
       Insecure Registries:
        127.0.0.0/8
       Live Restore Enabled: false

-----> sigil version: 0.4.0
-----> herokuish version:
       herokuish: 0.4.2
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v183
         heroku-buildpack-nodejs    v123
         heroku-buildpack-clojure   v82
         heroku-buildpack-python    v134
         heroku-buildpack-java      v61
         heroku-buildpack-gradle    v26
         heroku-buildpack-scala     v81
         heroku-buildpack-play      v26
         heroku-buildpack-php       v135
         heroku-buildpack-go        v87
         buildpack-nginx            v9
-----> dokku version: v0.12.8-13-gf6fc32a0
-----> dokku plugins:
       plugn: 0.3.0
         00_dokku-standard    0.12.10 enabled    dokku core standard plugin
         20_events            0.12.10 enabled    dokku core events logging plugin
         apps                 0.12.10 enabled    dokku core apps plugin
         build-env            0.12.10 enabled    dokku core build-env plugin
         certs                0.12.10 enabled    dokku core certificate management plugin
         checks               0.12.10 enabled    dokku core checks plugin
         common               0.12.10 enabled    dokku core common plugin
         config               0.12.10 enabled    dokku core config plugin
         docker-options       0.12.10 enabled    dokku core docker-options plugin
         domains              0.12.10 enabled    dokku core domains plugin
         enter                0.12.10 enabled    dokku core enter plugin
         git                  0.12.10 enabled    dokku core git plugin
         logs                 0.12.10 enabled    dokku core logs plugin
         network              0.12.10 enabled    dokku core network plugin
         nginx-vhosts         0.12.10 enabled    dokku core nginx-vhosts plugin
         plugin               0.12.10 enabled    dokku core plugin plugin
         proxy                0.12.10 enabled    dokku core proxy plugin
         ps                   0.12.10 enabled    dokku core ps plugin
         repo                 0.12.10 enabled    dokku core repo plugin
         scheduler-docker-local 0.12.10 enabled    dokku core scheduler-docker-local plugin
         shell                0.12.10 enabled    dokku core shell plugin
         ssh-keys             0.12.10 enabled    dokku core ssh-keys plugin
         storage              0.12.10 enabled    dokku core storage plugin
         tags                 0.12.10 enabled    dokku core tags plugin
         tar                  0.12.10 enabled    dokku core tar plugin
=====> willie2 app information
not deployed
```

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
KVM Virtual machine

### Additional information

- Link to the exact repository being deployed (if possible/applicable):
https://github.com/heroku/ruby-sample

**Comment by josegonzalez** [comment] 2018-07-08 20:37
Since its fixed on your end and there isn't a clear way to replicate, I'm going to close this for now. Please feel free to comment if you have a way for me to reproduce.

**Closed by josegonzalez** 2018-07-08 20:37 UTC
