### ISSUE TITLE
Pushes aren't triggering build after app rename

### ISSUE THREAD

**Issue by natanrolnik** [dokku/dokku#2221] opened 2016-06-01 20:20 UTC
Description of problem:
I've renamed one of my apps that I have from `myappname-dev` to `myappname`. After pushing new commits, the build process is not triggered. I have seen the issue in #1867, where it seemed to be solved.

Output of the following commands

- `uname -a`: Linux ip-172-31-22-210 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`:
<img width="593" alt="captura de tela 2016-06-01 as 23 06 09" src="https://cloud.githubusercontent.com/assets/1164565/15723951/780bf40c-284d-11e6-8177-0c719ac239ec.png">
- `docker version`:
<img width="333" alt="captura de tela 2016-06-01 as 23 07 43" src="https://cloud.githubusercontent.com/assets/1164565/15723986/b3d08368-284d-11e6-87d2-a6ae90a88bba.png">

- `docker -D info`:
<img width="512" alt="captura de tela 2016-06-01 as 23 15 58" src="https://cloud.githubusercontent.com/assets/1164565/15724235/dbffc2b2-284e-11e6-935e-38ca2770f20a.png">

- `sigil -v`: 0.4.0
- `docker run -ti gliderlabs/herokuish:latest herokuish version`: herokuish: 0.3.12, heroku-buildpack-nodejs v90
- `dokku version`: 0.5.6
- `dokku plugin`: 
<img width="669" alt="captura de tela 2016-06-01 as 23 17 35" src="https://cloud.githubusercontent.com/assets/1164565/15724305/2181b8d6-284f-11e6-979f-253ead5f3791.png">

- If a deploy is failing or behaving unexpectedly:
  - Application name: myappname
  - The type of application being deployed: nodejs
  - If using buildpacks, which custom buildpacks are in use - standard buildpack for nodejs
  - If using a `Dockerfile`, the contents of that file - not using
  - If it exists, the contents of your `Procfile`.
- Output of failing dokku commands after running `dokku trace on`
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

Environment details: 
AWS EC2 t2.micro

How was dokku installed?:
```
wget https://raw.githubusercontent.com/dokku/dokku/v0.5.7/bootstrap.sh
sudo DOKKU_TAG=v0.5.6 bash bootstrap.sh
```

How reproducible:
2nd time it happened, in a different Dokku instance, after renaming an app

Steps to Reproduce:
1. Create an app in your Dokku
2. Push and deploy
3. Rename it via `apps:rename <old-app> <new-app>`
4. Push and check if build is triggered

Actual Results:
`git push` succeeds, but doesn't trigger build

Expected Results:
`git push` succeeds and triggers build

Additional info:
`dokku trace on` was enabled before pushing, and the result [can be seen here](https://github.com/dokku/dokku/files/294302/DokkuGitPushNotTriggeringBuild.txt)

If there is more information I can provide, please let me know

**Comment by josegonzalez** [comment] 2016-06-01 21:32
We definitely fixed this a while back [here](https://github.com/dokku/dokku/blob/master/plugins/apps/subcommands/rename#L22).

**Comment by natanrolnik** [comment] 2016-06-01 21:46
Yes, I noticed these lines mentioned in #1867, but I don't know why I got this bug twice.

**Comment by josegonzalez** [comment] 2016-06-01 21:50
Can you gist the trace output from a rename?

**Comment by natanrolnik** [comment] 2016-06-01 21:56
I've tried again, with another app, and the `newappname/hooks/pre-receive` is still the same, having the old name.
Here is the trace: [RenameOutput.txt](https://github.com/dokku/dokku/files/294435/RenameOutput.txt)

**Comment by josegonzalez** [comment] 2016-06-02 01:33
@natanrolnik it looks like the nginx reload is failing, especially if that is all the output of the rename command. This is halting the entire rename process, and you'll notice the new app is probably not serving anything up until you rebuild it. Maybe try doing `nginx -t` and `service nginx reload` manually to see whats going on?

If you're on slack/irc, I'd be happy to take a look at the server directly to investigate more thoroughly..

**Comment by michaelshobbs** [comment] 2016-06-10 20:13
Any updates here?

**Comment by josegonzalez** [comment] 2016-06-25 05:53
I've tried to reproduce this with the latest 0.6.3 and cannot. Closing as there hasnt been any update in a few weeks, and I'm going to guess that the user has a custom nginx conf that is maybe hardcoding a now non-existent directory or something.

**Closed by josegonzalez** 2016-06-25 05:53 UTC
Labels: type: bug

**Comment by PAStheLoD** [comment] 2017-06-28 13:29
Hello, 

We've just run into this with 0.9.4.

Haven't tried to reproduce it, sorry :(

**Comment by josegonzalez** [comment] 2017-06-28 21:30
@PAStheLoD please file a new issue, especially one with a reproduction, otherwise not much we can do here.
