### ISSUE TITLE
Question about Restart Policy?

### ISSUE THREAD

**Issue by HillLiu** [dokku/dokku#3405] opened 2019-01-19 12:13 UTC
## Description of problem
Need make sure which restart policy was correct?

I check each dokku container's restart policy was set to on-failure, 
When I use [portainer](https://www.portainer.io/) to manage docker, I notice portainer will follow restart policy to reboot docker.

The issue is when I deploy a new release, dokku will keep old container, and the old container still leave it's restart policy with on-failure.

When I reboot machine, the old container will also boot.

### How reproducible
deploy new version, reboot machine. old container also boot.

### Steps to Reproduce

1. deploy new version
2. old container was disabled. 
3. reboot machine
4. new and old container both enabled.

#### Actual Results
old container was boot when machine reboot.

#### Expected Results
old container should not boot after machine was rebooted.

I think is it make sense to set old container's restart policy to no?

**Comment by josegonzalez** [comment] 2019-01-20 16:17
What version of Dokku are you using? This is partially fixed in 0.13.x - and completely in 0.14.x. We have a `ps:retire` command that should happen in cron to fix this issue.

The issue is that docker doesn't respect stopped/killed containers on reboot - it assumes anything that is lying around should be restarted. On certain servers with low resources, the forked process that _should_ kill the container doesn't run because that forked process gets oomkilled (or similar).

The newer versions of Dokku have a workaround that will keep track of what should be a dead container, and kill it in the background.

**Comment by josegonzalez** [comment] 2019-01-21 07:17
The next release will _additionally_ set the restart policy to `no` for stopped containers.

**Closed by josegonzalez** 2019-01-21 07:17 UTC
Labels: needs: more info
