### ISSUE TITLE
Dokku deploys errors with gzip: stdin: invalid compressed data--format violated

### ISSUE THREAD

**Issue by jvanbaarsen** [dokku/dokku#2411] opened 2016-09-08 09:01 UTC
Description of problem:
On a freshly installed Dokku 0.7.1 installation app deployment of a Ruby on Rails app fails with the following error:

```
-----> Cleaning up...
-----> Building testapp from herokuish...
-----> Setting config vars
       CURL_CONNECT_TIMEOUT: 5
-----> Setting config vars
       CURL_TIMEOUT: 30
-----> Adding BUILD_ENV to build environment...
-----> Ruby app detected
-----> Compiling Ruby/Rails
       !
       !     An error occurred while installing Ruby ruby-2.3.0
       !     For supported Ruby versions see https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
       !     Note: Only the most recent version of Ruby 2.1 is supported on Cedar-14
       !     Command: 'set -o pipefail; curl -L --fail --retry 3 --retry-delay 1 --connect-timeout 5 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.3.0.tgz -s -o - | tar zxf - ' failed unexpectedly:
       !
       !     gzip: stdin: invalid compressed data--format violated
       !     tar: Unexpected EOF in archive
       !     tar: Unexpected EOF in archive
       !     tar: Error is not recoverable: exiting now
```

Output of the following commands
- `uname -a`: 
  Linux ic-jeroen-test-app 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 
  x86_64 x86_64 x86_64 GNU/Linux
- `free -m`: 
  Mem:            992         107         132          12         752         672
- `docker version`:
  Client:
  Version:      1.12.1
  API version:  1.24
  Go version:   go1.6.3
  Git commit:   23cf638
  Built:        Thu Aug 18 05:33:38 2016
  OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
- `docker -D info`:
  Containers: 6
  Running: 2
  Paused: 0
  Stopped: 4
  Images: 13
  Server Version: 1.12.1
  Storage Driver: aufs
  Root Dir: /var/lib/docker/aufs
  Backing Filesystem: extfs
  Dirs: 51
  Dirperm1 Supported: true
  Logging Driver: json-file
  Cgroup Driver: cgroupfs
  Plugins:
  Volume: local
  Network: bridge overlay null host
  Swarm: inactive
  Runtimes: runc
  Default Runtime: runc
  Security Options: apparmor seccomp
  Kernel Version: 4.4.0-36-generic
  Operating System: Ubuntu 16.04.1 LTS
  OSType: linux
  Architecture: x86_64
- `sigil -v`: 0.4.0
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
  herokuish: 0.3.18
  buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v146
  heroku-buildpack-nodejs    v91
  heroku-buildpack-clojure   v75
  heroku-buildpack-python    v81
  heroku-buildpack-java      v44
  heroku-buildpack-gradle    v17
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v72
  heroku-buildpack-play      v26
  heroku-buildpack-php       v109
  heroku-buildpack-go        v44
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v5
  emberjs.tgz                latest
- `dokku version`: 0.7.1
- `dokku plugin`:
  00_dokku-standard    0.7.1 enabled    dokku core standard plugin
  20_events            0.7.1 enabled    dokku core events logging plugin
  apps                 0.7.1 enabled    dokku core apps plugin
  build-env            0.7.1 enabled    dokku core build-env plugin
  certs                0.7.1 enabled    dokku core certificate management plugin
  checks               0.7.1 enabled    dokku core checks plugin
  common               0.7.1 enabled    dokku core common plugin
  config               0.7.1 enabled    dokku core config plugin
  docker-options       0.7.1 enabled    dokku core docker-options plugin
  domains              0.7.1 enabled    dokku core domains plugin
  enter                0.7.1 enabled    dokku core enter plugin
  git                  0.7.1 enabled    dokku core git plugin
  logs                 0.7.1 enabled    dokku core logs plugin
  named-containers     0.7.1 enabled    dokku core named containers plugin
  nginx-vhosts         0.7.1 enabled    dokku core nginx-vhosts plugin
  plugin               0.7.1 enabled    dokku core plugin plugin
  postgres             1.0.0 enabled    dokku postgres service plugin
  proxy                0.7.1 enabled    dokku core proxy plugin
  ps                   0.7.1 enabled    dokku core ps plugin
  redis                1.0.0 enabled    dokku redis service plugin
  repo                 0.7.1 enabled    dokku core repo plugin
  shell                0.7.1 enabled    dokku core shell plugin
  ssh-keys             0.7.1 enabled    dokku core ssh-keys plugin
  storage              0.7.1 enabled    dokku core storage plugin
  tags                 0.7.1 enabled    dokku core tags plugin
  tar                  0.7.1 enabled    dokku core tar plugin
- If a deploy is failing or behaving unexpectedly:
  - Application name: testapp
  - The type of application being deployed (node, php, python, ruby, etc.) Ruby (on Rails)
  - If it exists, the contents of your `Procfile`.

```
web: bundle exec puma -C config/puma.rb
```

Environment details (AWS, VirtualBox, physical, etc.): Digitalocean
How was Dokku installed?: Using bootstrap.sh (The one in the readme)
How reproducible: Install Dokku on a server with postgres plugin, and deploy: https://github.com/jvanbaarsen/rails-example
This might succeed once, but add an extra commit, and try again. It will probably fail. But can also fail the first time.

Actual Results:

```
-----> Cleaning up...
-----> Building testapp from herokuish...
-----> Setting config vars
       CURL_CONNECT_TIMEOUT: 5
-----> Setting config vars
       CURL_TIMEOUT: 30
-----> Adding BUILD_ENV to build environment...
-----> Ruby app detected
-----> Compiling Ruby/Rails
       !
       !     An error occurred while installing Ruby ruby-2.3.0
       !     For supported Ruby versions see https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
       !     Note: Only the most recent version of Ruby 2.1 is supported on Cedar-14
       !     Command: 'set -o pipefail; curl -L --fail --retry 3 --retry-delay 1 --connect-timeout 5 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.3.0.tgz -s -o - | tar zxf - ' failed unexpectedly:
       !
       !     gzip: stdin: invalid compressed data--format violated
       !     tar: Unexpected EOF in archive
       !     tar: Unexpected EOF in archive
       !     tar: Error is not recoverable: exiting now
```

Expected Results:
That my app was deployed

Additional info:
I have the feeling that Dokku tries to recompile ruby on every deploy. Has this behaviour changed? Since I feel it did not do this before.

**Comment by CezarT** [comment] 2016-09-09 11:14
Same issue here. Installed 0.7.1 two days ago, and have seen plenty of times this error. It goes through approximatively 1 in 5 times.

**Comment by michaelshobbs** [comment] 2016-09-09 14:37
Unfortunately we've a long history of issues with this buildpack. It is up to date in herokuish 0.3.18. So that's not the issue this time around. You might try raising the values for `CURL_CONNECT_TIMEOUT` and/or `CURL_TIMEOUT` to see if that helps. Otherwise you'll need to jump into a container and try curling the tgz file to see what error curl is giving.

Something like this:
```
$ docker run -ti gliderlabs/herokuish:latest /bin/bash -c "curl -L --fail --retry 3 --retry-delay 1 --connect-timeout 5 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.3.0.tgz -s -o /tmp/ruby-2.3.0.tgz && tar -tzvf /tmp/ruby-2.3.0.tgz"
```

**Comment by jvanbaarsen** [comment] 2016-09-10 10:47
@michaelshobbs already tried raising those values :( will try going into the container though.

**Comment by jvanbaarsen** [comment] 2016-09-12 12:53
@michaelshobbs I get the exact same error by jumping in the container:

```
gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

**Comment by jvanbaarsen** [comment] 2016-09-12 13:05
@michaelshobbs I tried with this command:
```
docker run -ti gliderlabs/herokuish:latest /bin/bash -c "set -o pipefail; curl -L --fail --retry 3 --retry-delay 1 --connect-timeout 60 --max-time 120 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.3.0.tgz -s -o - | tar zxf - "
```
So the `connect-timeout=60` and `--max-time=120`  (both increased a lot); but it is still giving me the exact same error.

**Comment by michaelshobbs** [comment] 2016-09-12 13:13
Run the command I provided and remove the -s so you can see what error curl is throwing.

**Comment by jvanbaarsen** [comment] 2016-09-12 13:28
@michaelshobbs Will do!

**Comment by jvanbaarsen** [comment] 2016-09-12 13:30
@michaelshobbs 
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 12 17.3M   12 2209k    0     0  75423      0  0:04:00  0:00:29  0:03:31 83107
Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
  0 17.3M    0 50846    0     0  57793      0  0:05:14 --:--:--  0:05:14 57779
curl: (23) Failed writing body (708 != 16384)
```

**Comment by jvanbaarsen** [comment] 2016-09-12 13:30
This was with the max-time of 30

**Comment by michaelshobbs** [comment] 2016-09-12 13:32
Looks like network issues to me.

**Comment by jvanbaarsen** [comment] 2016-09-12 13:34
@michaelshobbs Which is odd, since its a normal Digitalocean droplet. (A freshly created one). But I have the same feeling.

Is there a way to "pre-download" them?

**Comment by michaelshobbs** [comment] 2016-09-12 13:43
That is odd. I'm sure you could come up with a solution to "pre-download" but that seems unsustainable. Try contacting DO support and see if they can point you in the right direction.

@josegonzalez you work with DO quite a bit more than I do. Do you have any thoughts on this?

**Comment by jvanbaarsen** [comment] 2016-09-12 13:47
@michaelshobbs I think I have found the problem. I uploaded the ruby file to my own AWS bucket, and now it is quick again (like 19mb/s quick).

When I download it from the original source, it is very slow. Maybe the original author is rate-limiting the downloads?

**Comment by jvanbaarsen** [comment] 2016-09-12 13:49
@michaelshobbs I came to this when I tried downloading the ubuntu image, which downloaded with 40 mb/s.

**Comment by michaelshobbs** [comment] 2016-09-12 13:51
Could be. 

To clarify the original issue language, dokku doesn't do anything language or framework specific. This functionality is performed and maintained by the language-specific buildpack and its maintainer(s).

**Comment by jvanbaarsen** [comment] 2016-09-12 13:52
@michaelshobbs I'm aware of that :-) I was just trying to give as much information as possible :)

**Comment by michaelshobbs** [comment] 2016-09-12 13:58
No worries. I was clarifying for other folks that might come across this issue.

**Comment by jvanbaarsen** [comment] 2016-09-12 13:59
@michaelshobbs More information: I tried creating a bucket in the same region as the original file, and it is also slow. So this might be a Digitalocean issue after all

**Comment by josegonzalez** [comment] 2016-09-12 14:23
Some DigitalOcean droplets end up having bad networking, so retrying on a new droplet is my goto.

I wonder if we can have like a "droplet network test"...

Would also be maybe good to see if we can modify the download urls and then tell people to put the uploads somewhere else if they are seeing trouble...

**Comment by jvanbaarsen** [comment] 2016-09-12 14:52
@josegonzalez I like that idea! Do we download the buildpack on every build? Or only first build?

**Comment by josegonzalez** [comment] 2016-09-12 14:53
Only on first build with that buildpack.

**Comment by jvanbaarsen** [comment] 2016-09-12 14:53
@josegonzalez Also, I noticed this problem on almost any droplet I create in the past 1 - 2 weeks. So in my experience its not "some" droplets

**Comment by josegonzalez** [comment] 2016-09-12 14:54
Well it's not *my* infrastructure, so something you should bring up with digitalocean ;)

**Comment by jvanbaarsen** [comment] 2016-09-12 14:55
@josegonzalez I know ;) I was not blaming or pointing fingers. I value yours and @michaelshobbs help very much :-)

**Comment by jvanbaarsen** [comment] 2016-09-12 14:57
@josegonzalez Would it be an idea that we increase the download time to default to for example 5 minutes? That makes the first deploy possibly very slow, but at least it will not fail. All other deploys will be fast. Right?

**Comment by josegonzalez** [comment] 2016-09-12 15:05
It seems like its having a network blip during the download, so upping the download time wouldn't help. What happens when you run with that setting in a bad box?

**Comment by jvanbaarsen** [comment] 2016-09-12 18:13
@josegonzalez That works, since even if the download time is very bad, it takes around 4,5 minutes. So that was for me the reason that upping it to 5 might solve a ton of this kind of issues.

**Comment by jvanbaarsen** [comment] 2016-09-12 18:14
@josegonzalez The reason its failing is because of the `max-time` (It defaults to 30 seconds) so after 30 seconds, it just stops the download.

**Comment by josegonzalez** [comment] 2016-09-12 18:14
We can default to that if everyone is comfortable with it.

**Comment by jvanbaarsen** [comment] 2016-09-12 18:15
@josegonzalez I'll keep an eye out on this issue. if there is consensus I'll create a PR for it :)

**Comment by jvanbaarsen** [comment] 2016-09-12 18:15
Also ❤️ for yours and @michaelshobbs help! You guys rock!

**Comment by josegonzalez** [comment] 2016-09-12 18:16
@jvanbaarsen https://opencollective.com/dokku ;)

**Comment by jvanbaarsen** [comment] 2016-09-13 05:43
@josegonzalez Thanks :-) I've been doing some tests, but it looks like it tries the "Compiling Ruby/Rails" step on every deploy (And thus also downloading the buildpack). I only notice this change in 0.7 and up I believe (I try to get some more information about this)

**Comment by CezarT** [comment] 2016-12-13 09:56
@jvanbaarsen and @josegonzalez Thank you both for discussing in detail this issue. With regards to "Compiling Ruby/Rails" on every deploy, is it possible to somehow make it run only when they change? I also don't remember this step running on every deploy before.  Jeroen, did you find additional info on this topic?

**Comment by josegonzalez** [comment] 2017-01-09 07:20
I've never seen it continually recompile the application, though if thats an issue, its a buildpack issue, not something to do with herokuish/dokku. We simply use whatever Heroku provides in our Herokuish package.

**Comment by josegonzalez** [comment] 2017-01-20 00:24
@jvanbaarsen if you're interested in raising the timeout, go ahead, otherwise I'm going to close this out.

**Closed by josegonzalez** 2017-01-20 00:24 UTC
Labels: type: support

**Comment by markysharky70** [comment] 2017-01-23 05:55
@jvanbaarsen Hi - ran across this thread while troubleshooting my new Linode deployment and it turns out I'm having this same problem with my Linode in Fremont, CA.  When I up the --max-time to  120 and run the curl command that was enough to make it work for me.

**Comment by josegonzalez** [comment] 2017-01-23 06:00
The issue is documented in our troubleshooting docs.
