### ISSUE TITLE
Add a warning in the installer which tells the user about the changes which will be made both to their docker images, and their nginx configuration

### ISSUE THREAD

**Issue by Nevin1901** [dokku/dokku#4305] opened 2021-01-07 19:57 UTC
## Description of problem
I was looking to install dokku, and planning to gradually migrate all of my services over to it. However, when I ran the install script, there was no sort of warning or text which stated that all of my nginx config files would be unlinked, and my docker images would be stopped. A warning in both the script, or the site which the user would have to accept would be nice to avoid this type of headache in the future, as I was doing this on my one and only vps.

### How reproducible
Many users who install might have this problem

### Steps to Reproduce

1. wget https://raw.githubusercontent.com/dokku/dokku/v0.22.7/bootstrap.sh
2. sudo DOKKU_TAG=v0.22.7 bash bootstrap.sh

#### Actual Results
All of my nginx configuration files were unlinked from sites-available, and all of my docker images were stopped.

#### Expected Results
A warning to clarify that this would happen, so I could have avoided the problems.

## Environment Information
OS: Ubuntu Server 18.04

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
Installed via bootstrap script found on dokku's website.

### Additional information
No additional information

**Comment by josegonzalez** [comment] 2021-01-07 21:16
Wait we stop docker images? I'm pretty sure we don't touch anything that doesn't have a `dokku` tag...

**Comment by Nevin1901** [comment] 2021-01-07 23:15
I looked through the code of the script and my guess is that during the re installation, docker and nginx reset their configuration. Tomorrow I will do further testing on a linux server running under a VM.

**Comment by josegonzalez** [comment] 2021-01-14 13:34
@Nevin1901 did you have a chance to look at this again?

**Comment by Nevin1901** [comment] 2021-01-14 15:17
Yea, I don't think the problem isn't in the install script itself, but somewhere in the makefile. https://github.com/dokku/dokku/blob/a53b5953ea4003d1c5d2fe45a3b3935fa33c1905/Makefile#L174 could be the cause of all of the images getting stopped, but I'm not 100% sure. Something which is also odd is that the nginx configuration was reset, but I see no references to how it could have happened both in the install script, or the makefile. I'll try setting up a docker image with nginx, docker, and dokku to see if I can replicate the error.

**Comment by josegonzalez** [comment] 2021-01-14 15:34
The Makefile isn't run at all when you install via the method you chose. That is only performed for a from-source install.

**Comment by AubreyHewes** [comment] 2021-01-21 22:42
@Nevin1901 

I think the reason your running containers stopped is due to docker having being updated (as was outdated). (The dokku install script does update docker (@josegonzalez ?). 
In this case the docker service would have been restarted. All containers that are not set to restart will not restart see [docker restart policy](https://docs.docker.com/config/containers/start-containers-automatically/)

Are you sure your current nginx sites-enabled were also unlinked as well?

**Comment by josegonzalez** [comment] 2021-01-21 23:37
Oh thats a good catch on the bootstrap script running the docker script. I think we should probably bail on running that subscript if the `docker` binary is detected?

**Comment by AubreyHewes** [comment] 2021-01-22 00:49
@josegonzalez dokku version depends on a docker version (functionality)... so maybe only bail if it meets.. semver check?

i.e. current dokku functionality depends on at least docker version x... else update docker..

**Comment by josegonzalez** [comment] 2021-01-22 00:53
Yeah I think checking the base version is probably fine, though parsing it is a different matter. Seems the current output of `docker -v` is something like:

```shell
Docker version 20.10.2, build 2291f61
```

So parsing the output of `docker -v | cut -d ' ' -f3` should let us skip the docker install.

Also, the docker install step waits for like... 30 seconds? before continuing it's install. I don't think we need to guard against that, folks will either read or they won't.

**Comment by AubreyHewes** [comment] 2021-01-22 00:57
Obviously folks do not read that... maybe add a nice cli warning that docker may be updated and current containers may be not restarted (restart-policy). 
Parsing docker -v output is not the way.. could try to read `docker version` and parse that as yml easier.. though I am sure there is a wat to get machine readable version from the daemon..

**Comment by AubreyHewes** [comment] 2021-01-22 01:02
@josegonzalez  `docker version --format '{{.Server.Version}}'`

**Comment by josegonzalez** [comment] 2021-01-22 01:05
> Obviously folks do not read that

They'll also not read the cli warning ;)

**Comment by josegonzalez** [comment] 2021-01-22 01:06
Also neat, didn't realize you can format the docker version output. Seems like a great way forward (we'll still need to parse the major/minor release out of that).

**Comment by AubreyHewes** [comment] 2021-01-22 01:10
semver package does that for you... though I am thinking of a node package... probably also a go one for that?

**Comment by AubreyHewes** [comment] 2021-01-22 01:12
I stole that version format snippet from https://docs.docker.com/engine/reference/commandline/version/#get-the-server-version

**Comment by josegonzalez** [comment] 2021-01-22 01:12
I dont think we can depend on any external binaries here for version parsing, but also, we can do it in the [same way the `DOKKU_TAG` gets parsed](https://github.com/dokku/dokku/blob/master/bootstrap.sh#L69).

**Comment by AubreyHewes** [comment] 2021-01-22 01:12
yeah I get you.. starts with `at least` `X`

**Comment by josegonzalez** [comment] 2021-01-22 01:19
I think the problem is we're at the point where Dokku may or may not be installed. While I do like the idea of a go binary (or even a webservice!) that could tell you if you're at least at a particular semver version, the simplest solution for this particular case is just more shell script :(

**Comment by AubreyHewes** [comment] 2021-01-22 02:51
I hear you, but the idea is that we need to detect the current docker version is matching the minimal dokku docker version... the best way to do this is via a semver check... The dokku install could do this. Checking semver via bash is not maintainable.

**Comment by josegonzalez** [comment] 2021-01-22 02:56
Yeah the debian package already has that check [here](https://github.com/dokku/dokku/blob/master/debian/control#L6), but iirc a recent docker version wasn't available in Ubuntu/Debian (or Centos I guess). If that is no longer the case, we can probs just drop the docker install completely :)

**Comment by josegonzalez** [comment] 2021-01-22 03:07
Looks like we can drop the script-based docker install for ubuntu (will need to test): https://packages.ubuntu.com/xenial/docker.io

And for Debian buster: https://packages.debian.org/buster/docker.io

Debian Stretch is EOL (not on LTS), but I'm okay with dropping support for it at a minor release.

Centos 7 is the only currently supported Centos version, and they don't ship docker with Centos, but Podman (which we could mostly support by setting an alternative `DOKKU_BIN` env var but there are a bunch of things that wouldn't work that I don't care to test). Given that Centos is no longer really a thing, I feel comfortable dropping support for it in the bootstrap script. Folks who _need_ some form of Centos support (or Amazon Linux2 or Rocky Linux) can probably also run Dokku from a container _or_ sponsor work to support those new operating systems. That said, we can probably leave Centos alone for now and only remove the extra check for the debian-based installers.

**Comment by josegonzalez** [comment] 2021-01-22 03:44
Probably worth writing down a deprecation policy somewhere...

**Comment by AubreyHewes** [comment] 2021-01-22 22:31
> Looks like we can drop the script-based docker install for ubuntu (will need to test): https://packages.ubuntu.com/xenial/docker.io
> 
> And for Debian buster: https://packages.debian.org/buster/docker.io
> 
> Debian Stretch is EOL (not on LTS), but I'm okay with dropping support for it at a minor release.
> 
> Centos 7 is the only currently supported Centos version, and they don't ship docker with Centos, but Podman (which we could mostly support by setting an alternative `DOKKU_BIN` env var but there are a bunch of things that wouldn't work that I don't care to test). Given that Centos is no longer really a thing, I feel comfortable dropping support for it in the bootstrap script. Folks who _need_ some form of Centos support (or Amazon Linux2 or Rocky Linux) can probably also run Dokku from a container _or_ sponsor work to support those new operating systems. That said, we can probably leave Centos alone for now and only remove the extra check for the debian-based installers.

Drop support for all old stuff/eol/os-versions. dokku main/edge/canary/master needs to keep relevant with the times. Dokku usage should expect up2date administrators and should not support old/unsupported platforms. No self respecting dokku admin wants dokku to become some legacy all distribution supporting mess. Dokku needs to be fast moving to compete. This entails that admins need to be ... well admins.

**Comment by josegonzalez** [comment] 2021-03-22 21:31
Looks like installing via bootstrap doesn't update docker if it is already there (though debian/centos will if the docker version is older than 17.05.0, as that is a minimal dependency). Not much we can do about that.

That aside, @Cellane is working on getting the dokku-update command in a better spot for our existing users, and I'll add a note to the bootstrap about the removal. Once we complete #2247, then there won't be any nginx conf removals, so the only issue is if you have a very old docker version, in which case docker is just doing docker things.

**Comment by josegonzalez** [comment] 2021-03-22 21:33
Closing as there is a pull request open. Thanks for reporting.

**Closed by josegonzalez** 2021-03-22 21:33 UTC
Labels: merge-level: patch, needs: investigation, type: bug, type: enhancement
