### ISSUE TITLE
Find a break change on procfile-util (underscore become invalid)

### ISSUE THREAD

**Issue by HillLiu** [dokku/dokku#4146] opened 2020-10-06 03:32 UTC
Just let someone know if your keys of Procfile have underscore and will make your build failed.

such as 
```
worker_xxx: celery worker --app xxx
```

It's because procfile-util 0.9.0 update.
https://github.com/josegonzalez/go-procfile-util/commit/a4883145482e99c8c188fb71d5cd50eb74679993

It's better have some waring on build time, I can't see obvious error info with "dokku trace:on"

**Comment by gyfis** [comment] 2020-10-08 08:20
@HillLiu We also saw this issue, but I think the cause is not the `go-procfile-util` change (since that's not merged in dokku yet) - but this PR https://github.com/dokku/dokku/pull/4129 . 

I think this means you also cannot use upper-case or colons in the procfile definitions (which we tried). All lowercase works.

**Comment by HillLiu** [comment] 2020-10-08 18:40
@gyfis,  wow, it's cool that u catch the another similar issues.

I just downgrade procfile-util to 0.8.2 and it resolve my problem so not notice it.

I think it also because the latest dokku version was v0.21.4 which release on 8/28, the #4129 pr was merge on 9/10.
So after next version it will become a problem. it is good if someone could notice it early.

> @HillLiu We also saw this issue, but I think the cause is not the `go-procfile-util` change (since that's not merged in dokku yet) - but this PR #4129 .
> 
> I think this means you also cannot use upper-case or colons in the procfile definitions (which we tried). All lowercase works.

**Comment by josegonzalez** [comment] 2020-10-14 17:44
A recent release of go-procfile-util (0.9.0) restricts valid characters in a Procfile to make them more compatible with networking. This was done on purpose, as otherwise a ton of networking issues arise. Yes, we could paper over this in Dokku by inflecting things, but we should instead be stricter about what we accept.

If there was a standard for `Procfile` entries, I would also comply with that. I could, however, be convinced to relax this for now and restrict it in other ways.

Dokku itself will also raise the validation errors internally in the newer version.

**Comment by josegonzalez** [comment] 2020-11-08 23:36
I've rolled back this change for now. If anyone is seeing an issue where deploys fail due to Procfile entries, please upgrade `go-procfile-util` to the latest version.

**Closed by josegonzalez** 2020-11-08 23:36 UTC

**Comment by jlcastillo** [comment] 2021-01-05 14:49
> A recent release of go-procfile-util (0.9.0) restricts valid characters in a Procfile to make them more compatible with networking. This was done on purpose, as otherwise a ton of networking issues arise. Yes, we could paper over this in Dokku by inflecting things, but we should instead be stricter about what we accept.

A few questions about this topic:

1) Are underscores in app names creating networking issues to current Dokku users?
2) Isn't there a nicer way to handle it, without breaking existing deployments?
 
My answers would be 1) no, 2) yes, it would be nice if existing deployments could keep using underscores, and not allowing new apps use the underscore.

**Comment by josegonzalez** [comment] 2021-01-05 15:00
@jlcastillo Upgrade go-procfile-util to the latest version (0.11.0). It rolls back the change.

My answers on this topic are:

- Yes, they cause issues for users of the scheduler-kubernetes plugin (and yes, there are users of it). I also had someone report (via slack DM) something weird with internal networking where their client code didn't accept invalid DNS label names for http requests.
- Using one of the procfile-util versions that does strict checking by default wouldnt break a running app, just new deployments of new apps. There isn't any good way that doesn't make the codebase more complicated for me to track whether or not the app has been previously deployed with an older version of procfile-util. While that seems like its great for people who don't want to do anything to continue running, it's not super great for me to figure out a way to actually keep track of that sentinel value and then support this random one-off deprecated feature into the future.

Dokku 0.22.x requires at least version procfile-util 0.11.0 (so maybe you should update Dokku as well?) and has a note in the [upgrade guide](http://dokku.viewdocs.io/dokku/appendices/0.22.0-migration-guide/) surrounding valid names. We don't even perform strict checking at the moment, just made it sound scary in the upgrade docs, though 0.23.0 will turn on that strict checking.
