### ISSUE TITLE
Building node-sass using nodejs buildpack

### ISSUE THREAD

**Issue by RealOrangeOne** [dokku/dokku#2357] opened 2016-08-07 09:58 UTC
Have tried this multiple times, all with same result.
When I try to deploy my branch, the code pushes up fine, starts the build perfectly. But when it comes to building node-sass, it just dies. No error message, nothing! Build lock below

Dokku running on my VPS, installed through apt. System is 16.04 and fully up to date!

Any help or debugging advice would be great! 

### Stacktrace (slightly redacted)
    jake@TOO-Portable:~/Projects/*********$ git push -f dokku v4:master
    key_load_public: invalid format
    Counting objects: 3573, done.
    Delta compression using up to 4 threads.
    Compressing objects: 100% (1788/1788), done.
    Writing objects: 100% (3573/3573), 4.58 MiB | 3.97 MiB/s, done.
    Total 3573 (delta 1870), reused 2750 (delta 1447)
    -----> Cleaning up...
    -----> Building ********** from herokuish...
    -----> Adding BUILD_ENV to build environment...
    -----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
           Detected buildpacks: multi nodejs python
    -----> Multipack app detected
    =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs
    =====> Detected Framework: Node.js
           
    -----> Creating runtime environment
           
           NPM_CONFIG_LOGLEVEL=error
           NPM_CONFIG_PRODUCTION=false
           NODE_ENV=production
           NODE_MODULES_CACHE=true
           
    -----> Installing binaries
           engines.node (package.json):  5.10.1
           engines.npm (package.json):   unspecified (use default)
           
           Downloading and installing node 5.10.1...
           Using default npm version: 3.8.3
           
    -----> Restoring cache
           Skipping cache restore (new runtime signature)
           
    -----> Building dependencies
           Installing node modules (package.json)
           
           > node-sass@3.8.0 install /tmp/build/node_modules/node-sass
           > node scripts/install.js
           
           
           
           
    -----> Build failed
           
           We're sorry this build is failing! You can troubleshoot common issues here:
           https://devcenter.heroku.com/articles/troubleshooting-node-deploys
           
           If you're stuck, please submit a ticket so we can help:
           https://help.heroku.com/
           
           Love,
           Heroku
           
    To dokku@**********:**********
     ! [remote rejected] v4 -> master (pre-receive hook declined)
    error: failed to push some refs to 'dokku@**********:**********'

**Comment by josegonzalez** [comment] 2016-08-07 18:38
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems.

Also, do you have a sample project - perhaps just the package.json you are using - that I can use to debug the issue?

**Comment by RealOrangeOne** [comment] 2016-08-07 19:54
Project: https://github.com/RealOrangeOne/theorangeone.net/tree/v4. 

    jake@*************:~$ docker version
    Client:
     Version:      1.12.0
     API version:  1.24
     Go version:   go1.6.3
     Git commit:   8eab29e
     Built:        Thu Jul 28 22:11:10 2016
     OS/Arch:      linux/amd64

    Server:
     Version:      1.12.0
     API version:  1.24
     Go version:   go1.6.3
     Git commit:   8eab29e
     Built:        Thu Jul 28 22:11:10 2016
     OS/Arch:      linux/amd64
    jake@*************:~$ uname -a
    Linux TOO-webserver 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    jake@*************:~$ docker -D info
    Containers: 55
     Running: 0
     Paused: 0
     Stopped: 55
    Images: 46
    Server Version: 1.12.0
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 187
     Dirperm1 Supported: true
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Plugins:
     Volume: local
     Network: null host bridge overlay
    Swarm: inactive
    Runtimes: runc
    Default Runtime: runc
    Security Options: apparmor seccomp
    Kernel Version: 4.4.0-31-generic
    Operating System: Ubuntu 16.04.1 LTS
    OSType: linux
    Architecture: x86_64
    CPUs: 4
    Total Memory: 967.5 MiB
    Name: TOO-webserver
    ID: WETG:VEMV:3OEA:3CIL:A6NV:WS5I:ZNS6:EGIE:7DR6:XAD7:D6RN:PQQA
    Docker Root Dir: /var/lib/docker
    Debug Mode (client): true
    Debug Mode (server): false
    Registry: https://index.docker.io/v1/
    WARNING: No swap limit support
    Insecure Registries:
     127.0.0.0/8
    jake@*************:~$ sigil -v
    0.4.0
    jake@*************:~$ docker run -ti gliderlabs/herokuish:latest herokuish version
    herokuish: 0.3.18
    buildpacks:
      heroku-buildpack-multi     v1.0.0
      heroku-buildpack-ruby      v146
      heroku-buildpack-nodejs    v91
      heroku-buildpack-clojure   v75
      heroku-buildpack-python    v81
      heroku-buildpack-java      v44
      heroku-buildpack-gradle    v17
      heroku-buildpack-grails    v21
      heroku-buildpack-scala     v72
      heroku-buildpack-play      v26
      heroku-buildpack-php       v109
      heroku-buildpack-go        v44
      heroku-buildpack-erlang    fa17af9
      buildpack-nginx            v5
      emberjs.tgz                latest
    jake@*************:~$ dokku version
    [sudo] password for jake: 
    0.7.0
    jake@*************:~$ dokku plugin
    plugn: dev
      00_dokku-standard    0.7.0 enabled    dokku core standard plugin
      20_events            0.7.0 enabled    dokku core events logging plugin
      apps                 0.7.0 enabled    dokku core apps plugin
      build-env            0.7.0 enabled    dokku core build-env plugin
      certs                0.7.0 enabled    dokku core certificate management plugin
      checks               0.7.0 enabled    dokku core checks plugin
      common               0.7.0 enabled    dokku core common plugin
      config               0.7.0 enabled    dokku core config plugin
      docker-options       0.7.0 enabled    dokku core docker-options plugin
      domains              0.7.0 enabled    dokku core domains plugin
      enter                0.7.0 enabled    dokku core enter plugin
      git                  0.7.0 enabled    dokku core git plugin
      logs                 0.7.0 enabled    dokku core logs plugin
      named-containers     0.7.0 enabled    dokku core named containers plugin
      nginx-vhosts         0.7.0 enabled    dokku core nginx-vhosts plugin
      plugin               0.7.0 enabled    dokku core plugin plugin
      postgres             1.0.0 enabled    dokku postgres service plugin
      proxy                0.7.0 enabled    dokku core proxy plugin
      ps                   0.7.0 enabled    dokku core ps plugin
      repo                 0.7.0 enabled    dokku core repo plugin
      shell                0.7.0 enabled    dokku core shell plugin
      ssh-keys             0.6.4 enabled    dokku core ssh-keys plugin
      storage              0.7.0 enabled    dokku core storage plugin
      tags                 0.7.0 enabled    dokku core tags plugin
      tar                  0.7.0 enabled    dokku core tar plugin

Hope this helps

**Comment by RealOrangeOne** [comment] 2016-08-13 13:24
@josegonzalez have done some more testing on my server. Destroyed everything and reinstalled ubuntu 14.04, and it's working fine. Not sure why.

**Comment by josegonzalez** [comment] 2016-08-13 20:19
I'm guessing you changed node versions at some point. From a bit of research, it seems that if you do that, then the cache needs to be cleared before the next push, as otherwise compiled libraries will fail.

Closing since I also cannot reproduce.

**Closed by josegonzalez** 2016-08-13 20:19 UTC
Labels: needs: more info

**Comment by RealOrangeOne** [comment] 2016-08-13 20:45
node version stayed the same, as it was pinned in the package.json. But no I can't work it out wither
