### ISSUE TITLE
dokku rebuild fails after upgrading from v0.21 to v0.30

### ISSUE THREAD

**Issue by ersel** [dokku/dokku#5710] opened 2023-02-27 16:39 UTC
### Description of problem

Hi, we've recently upgraded our Dokku installation on Digital Ocean (ubuntu droplet) to v0.30 using 

```
sudo apt-get -qq -y --no-install-recommends install dokku herokuish sshcommand plugn gliderlabs-sigil dokku-update dokku-event-listener
```

Everything upgraded successfully, and when I run `dokku version` I can see:

```
dokku version 0.30.1
```

However when I try rebuilding some of my existing applications, `post-deploy` step fails with:

```
-----> Running post-deploy
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/dokku/dokku/plugins/common.ParseScaleOutput({0xc0000aa400, 0x0, 0xc0000506e0?})
        /go/src/github.com/dokku/dokku/plugins/common/common.go:399 +0x154
github.com/dokku/dokku/plugins/network.BuildConfig({0x7ffd903ca1f8, 0xd})
        /go/src/github.com/dokku/dokku/plugins/network/network.go:55 +0x116
main.main()
        /go/src/github.com/dokku/dokku/plugins/network/src/triggers/triggers.go:34 +0x534
 !     exit status 2
```

### Steps to reproduce

upgrade from v21 to v30

### dokku report $APP_NAME

```
root@mydokku:~# dokku report guestlist-api
-----> uname: Linux mydokku 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:           1987         668          86           2        1232        1157
       Swap:             0           0           0
-----> docker version: 
       Client: Docker Engine - Community
        Version:           19.03.13
        API version:       1.40
        Go version:        go1.13.15
        Git commit:        4484c46d9d
        Built:             Wed Sep 16 17:02:52 2020
        OS/Arch:           linux/amd64
        Experimental:      false
       
       Server: Docker Engine - Community
        Engine:
         Version:          19.03.13
         API version:      1.40 (minimum version 1.12)
         Go version:       go1.13.15
         Git commit:       4484c46d9d
         Built:            Wed Sep 16 17:01:20 2020
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.3.7
         GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
        runc:
         Version:          1.0.0-rc10
         GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
        docker-init:
         Version:          0.18.0
         GitCommit:        fec3683
-----> docker daemon info: 
       Client:
        Debug Mode: true
        Plugins:
         compose: Docker Compose (Docker Inc., v2.16.0)
       
       Server:
        Containers: 12
         Running: 7
         Paused: 0
         Stopped: 5
        Images: 54
        Server Version: 19.03.13
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
        runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
        init version: fec3683
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-52-generic
        Operating System: Ubuntu 20.04.1 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 1
        Total Memory: 1.941GiB
        Name: mydokku
        ID: PEEB:CHZO:EMP7:XJR5:2ZB7:QM5F:TPDW:PHRP:MO73:X7YR:V5PN:LJDA
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.25.1
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version: 
       herokuish: v0.5.40
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v244
         heroku-buildpack-nodejs    v202
         heroku-buildpack-clojure   v90
         heroku-buildpack-python    v223
         heroku-buildpack-java      v72
         heroku-buildpack-gradle    v38
         heroku-buildpack-scala     v96
         heroku-buildpack-play      v26
         heroku-buildpack-php       v227
         heroku-buildpack-go        v169
         heroku-buildpack-nginx     v22
         buildpack-null             v3
-----> dokku version: dokku version 0.30.1
-----> plugn version: plugn: 0.12.0build+3a27594
-----> dokku plugins: 
         00_dokku-standard    0.30.1 enabled    dokku core standard plugin
         20_events            0.30.1 enabled    dokku core events logging plugin
         app-json             0.30.1 enabled    dokku core app-json plugin
         apps                 0.30.1 enabled    dokku core apps plugin
         builder              0.30.1 enabled    dokku core builder plugin
         builder-dockerfile   0.30.1 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.30.1 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.30.1 enabled    dokku core builder-lambda plugin
         builder-null         0.30.1 enabled    dokku core builder-null plugin
         builder-pack         0.30.1 enabled    dokku core builder-pack plugin
         buildpacks           0.30.1 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.30.1 enabled    dokku core caddy-vhosts plugin
         certs                0.30.1 enabled    dokku core certificate management plugin
         checks               0.30.1 enabled    dokku core checks plugin
         common               0.30.1 enabled    dokku core common plugin
         config               0.30.1 enabled    dokku core config plugin
         cron                 0.30.1 enabled    dokku core cron plugin
         docker-options       0.30.1 enabled    dokku core docker-options plugin
         domains              0.30.1 enabled    dokku core domains plugin
         enter                0.30.1 enabled    dokku core enter plugin
         git                  0.30.1 enabled    dokku core git plugin
         haproxy-vhosts       0.30.1 enabled    dokku core haproxy-vhosts plugin
         letsencrypt          0.20.0 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.30.1 enabled    dokku core logs plugin
         mysql                1.19.4 enabled    dokku mysql service plugin
         network              0.30.1 enabled    dokku core network plugin
         nginx-vhosts         0.30.1 enabled    dokku core nginx-vhosts plugin
         plugin               0.30.1 enabled    dokku core plugin plugin
         proxy                0.30.1 enabled    dokku core proxy plugin
         ps                   0.30.1 enabled    dokku core ps plugin
         registry             0.30.1 enabled    dokku core registry plugin
         repo                 0.30.1 enabled    dokku core repo plugin
         resource             0.30.1 enabled    dokku core resource plugin
         run                  0.30.1 enabled    dokku core run plugin
         scheduler            0.30.1 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.30.1 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.30.1 enabled    dokku core scheduler-null plugin
         shell                0.30.1 enabled    dokku core shell plugin
         ssh-keys             0.30.1 enabled    dokku core ssh-keys plugin
         storage              0.30.1 enabled    dokku core storage plugin
         trace                0.30.1 enabled    dokku core trace plugin
         traefik-vhosts       0.30.1 enabled    dokku core traefik-vhosts plugin
=====> guestlist-api app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:             
=====> guestlist-api app information
       App created at:                1677510640
       App deploy source:             
       App deploy source metadata:    
       App dir:                       /home/dokku/guestlist-api
       App locked:                    false
=====> guestlist-api builder information
       Builder build dir:             
       Builder computed build dir:    
       Builder computed selected:     
       Builder global build dir:      
       Builder global selected:       
       Builder selected:              
=====> guestlist-api builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile               
       Builder dockerfile global dockerfile path: Dockerfile               
       Builder dockerfile dockerfile path:                          
=====> guestlist-api builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml               
       Builder lambda global lambdayml path: lambda.yml               
       Builder lambda lambdayml path:                          
=====> guestlist-api builder-pack information
       Builder pack computed projecttoml path: project.toml             
       Builder pack global projecttoml path: project.toml             
       Builder pack projecttoml path:                          
=====> guestlist-api buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:       
       Buildpacks list:               
       Buildpacks stack:              
=====> guestlist-api ssl information
       Ssl dir:                       /home/dokku/guestlist-api/tls
       Ssl enabled:                   true                     
       Ssl hostnames:                 api.mydomain.com       
       Ssl expires at:                May  7 12:46:50 2023 GMT 
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = R3
       Ssl starts at:                 Feb  6 12:46:51 2023 GMT 
       Ssl subject:                   subject=CN = api.mydomain.com 
       Ssl verified:                  self signed              
=====> guestlist-api checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
       Checks computed wait to retire: 60                       
       Checks global wait to retire:  60                       
       Checks wait to retire:                                  
=====> guestlist-api cron information
       Cron task count:               0
=====> guestlist-api docker options information
       Docker options build:          --link dokku.mysql.guestlist-db:dokku-mysql-guestlist-db 
       Docker options deploy:         --link dokku.mysql.guestlist-db:dokku-mysql-guestlist-db --restart=on-failure:10 
       Docker options run:            --link dokku.mysql.guestlist-db:dokku-mysql-guestlist-db 
=====> guestlist-api domains information
       Domains app enabled:           true                     
       Domains app vhosts:            api.mydomain.com     
       Domains global enabled:        true                     
       Domains global vhosts:         mydomain.com            
=====> guestlist-api git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                       634bc34                  
       Git source image:                                       
       Git last updated at:           1677510640               
=====> guestlist-api letsencrypt information
       Letsencrypt active:            true                     
       Letsencrypt autorenew:         true                     
       Letsencrypt computed dns provider:                          
       Letsencrypt global dns provider:                          
       Letsencrypt dns provider:                               
       Letsencrypt computed email:    info@redacted.com     
       Letsencrypt global email:                               
       Letsencrypt email:             info@redacted.com     
       Letsencrypt expiration:        1683463610               
       Letsencrypt computed graceperiod: 2592000                  
       Letsencrypt global graceperiod:                          
       Letsencrypt graceperiod:                                
       Letsencrypt computed lego docker args:                          
       Letsencrypt global lego docker args:                          
       Letsencrypt lego docker args:                           
       Letsencrypt computed server:   https://acme-v02.api.letsencrypt.org/directory
       Letsencrypt global server:                              
       Letsencrypt server:                                     
=====> guestlist-api logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:       
       Logs max size:                 
       Logs vector sink:              
=====> guestlist-api network information
       Network attach post create:           
       Network attach post deploy:           
       Network bind all interfaces:          false
       Network computed attach post create:  
       Network computed attach post deploy:  
       Network computed bind all interfaces: false
       Network computed initial network:     
       Network computed tld:                 
       Network global attach post create:    
       Network global attach post deploy:    
       Network global bind all interfaces:   false
       Network global initial network:       
       Network global tld:                   
       Network initial network:              
       Network static web listener:          
       Network tld:                          
       Network web listeners:                172.17.0.8:5000
=====> guestlist-api nginx information
       Nginx access log format:                                
       Nginx access log path:         /var/log/nginx/guestlist-api-access.log
       Nginx bind address ipv4:                                
       Nginx bind address ipv6:       ::                       
       Nginx client max body size:                             
       Nginx disable custom config:   false                    
       Nginx error log path:          /var/log/nginx/guestlist-api-error.log
       Nginx global hsts:             true                     
       Nginx computed hsts:           true                     
       Nginx hsts:                                             
       Nginx hsts include subdomains: true                     
       Nginx hsts max age:            15724800                 
       Nginx hsts preload:            false                    
       Nginx computed nginx conf sigil path: nginx.conf.sigil         
       Nginx global nginx conf sigil path: nginx.conf.sigil         
       Nginx nginx conf sigil path:                            
       Nginx proxy buffer size:       4096                     
       Nginx proxy buffering:         on                       
       Nginx proxy buffers:           8 4096                   
       Nginx proxy busy buffers size: 8192                     
       Nginx proxy read timeout:      60s                      
       Nginx last visited at:         1677515520               
       Nginx x forwarded for value:   $remote_addr             
       Nginx x forwarded port value:  $server_port             
       Nginx x forwarded proto value: $scheme                  
       Nginx x forwarded ssl:                                  
=====> guestlist-api proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 https:443:5000
       Proxy type:                    nginx
Error: No such object: 7ad68f951ef6b810d3102f74b74ea02da4fe80bf4633b9bdf425c878ebf8547d
=====> guestlist-api ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:              
       Ps restart policy:             on-failure:10
       Restore:                       false
       Running:                       false
       Status web 1:                  missing (CID: 7ad68f951ef)
=====> guestlist-api registry information
       Registry computed image repo:      dokku/guestlist-api
       Registry computed push on release: false
       Registry computed server:          
       Registry global push on release:   
       Registry global server:            
       Registry image repo:               
       Registry push on release:          
       Registry server:                   
       Registry tag version:              
=====> guestlist-api resource information
=====> guestlist-api scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:            
=====> guestlist-api scheduler-docker-local information
       Scheduler docker local disable chown:                          
       Scheduler docker local init process: true                     
       Scheduler docker local parallel schedule count:                          
=====> guestlist-api storage information
       Storage build mounts:                                   
       Storage deploy mounts:                                  
       Storage run mounts:      
```

proxy information seems to show an error message:
```
=====> guestlist-api proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 https:443:5000
       Proxy type:                    nginx
Error: No such object: 7ad68f951ef6b810d3102f74b74ea02da4fe80bf4633b9bdf425c878ebf8547d
```

**Comment by ersel** [comment] 2023-02-27 16:50
thank you @josegonzalez , running `dokku ps:scale my-app web=1` fixed it.

feel free to close this issue 👍

**Comment by josegonzalez** [comment] 2023-02-27 16:51
No I'll keep this open for now.

**Comment by josegonzalez** [comment] 2023-03-18 09:06
For anyone that sees this same problem, can you do:

```shell
# where $APP is your app name
ls -lah /var/lib/dokku/config/ps/$APP
cat /var/lib/dokku/config/ps/$APP/scale || true
```

The problem is the scale output is incorrect, but I don't know what the invalid value looks like, so I don't know what the correct conversion is.

For now, I'll guard against it by returning an error immediately that isnt a stacktrace.

**Comment by josegonzalez** [comment] 2023-03-18 09:16
Closing this as there is a pull request that should at least remove the stacktrace and give something of a hint to users.

**Closed by josegonzalez** 2023-03-18 09:16 UTC
Labels: type: bug, merge-level: patch, difficulty: easy, needs: plan, plugin: ps
