### ISSUE TITLE
gunicorn sibyl.wsgi: command not found on Django Project built with Cloud Native Buildpacks

### ISSUE THREAD

**Issue by dragonejt** [dokku/dokku#5687] opened 2023-02-17 18:20 UTC
### Description of problem

When I switched to Cloud Native Buildpacks (tried heroku and paketo) on my [Django project with gunicorn](https://github.com/dragonejt/sibyl), the build itself works fine but when the container starts up, the container fails and the error log is:
```
!     App container failed to start (web.1)
remote: =====> Start of sibyl container output (web.1)
remote:        gunicorn --worker-tmp-dir /dev/shm sibyl.wsgi: line 1: gunicorn --worker-tmp-dir /dev/shm sibyl.wsgi: No such file or directory
```
or

```
gunicorn sibyl.wsgi: gunicorn sibyl.wsgi: command not found
```

I did some investigation by building manually with the pack cli and heroku CNB buildpacks, and discovered that when environment variables are introduced, the same error can occur. I believe this is because the **docker run command is incorrect**, although this needs verification.

Pack CLI Build: (builds successfully)
```
pack build sibyl --builder heroku/buildpacks --env "DATABASE_URL=lol"
```

Invalid Docker Command that Provides Similar Output: (failure)
```
root@dragonejt:~/sibyl# docker run sibyl -e "DATABASE_URL=lol"
gunicorn sibyl.wsgi: gunicorn sibyl.wsgi: command not found
```

Correct Docker Command that starts up gunicorn: (success)
```
root@dragonejt:~/sibyl# docker run -e "DATABASE_URL=lol" sibyl
[2023-02-17 17:54:45 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-02-17 17:54:45 +0000] [1] [INFO] Listening at: http://127.0.0.1:8000 (1)
[2023-02-17 17:54:45 +0000] [1] [INFO] Using worker: sync
[2023-02-17 17:54:45 +0000] [13] [INFO] Booting worker with pid: 13
```

The difference is that in the incorrect command, the image name is inputted first and environment variables after, in the correct command the environment variables are inputted first, and the image name is at the end.

### Steps to reproduce

1. Have a Dokku App using Cloud Native Buildpacks and a Postgres Database on dokku postgres plugin
2. Clone https://github.com/dragonejt/sibyl and push to the dokku app using git
3. Build using heroku/buildpacks or other buildpacks like paketo will usually work, but running will fail.
4. The error is either that there is no such file or directory, or gunicorn command not found, depending on if command line arguments are added to the gunicorn command in Procfile.

### dokku report $APP_NAME

```
-----> uname: Linux dragonejt 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                      total        used        free      shared  buff/cache   available
       Mem:             969         387         130          14         451         399
       Swap:              0           0           0
-----> docker version:
       Client: Docker Engine - Community
        Version:           23.0.1
        API version:       1.42
        Go version:        go1.19.5
        Git commit:        a5ee5b1
        Built:             Thu Feb  9 19:47:01 2023
        OS/Arch:           linux/amd64
        Context:           default

       Server: Docker Engine - Community
        Engine:
         Version:          23.0.1
         API version:      1.42 (minimum version 1.12)
         Go version:       go1.19.5
         Git commit:       bc3805a
         Built:            Thu Feb  9 19:47:01 2023
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.6.18
         GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
        runc:
         Version:          1.1.4
         GitCommit:        v1.1.4-0-g5fd4c4d
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         buildx: Docker Buildx (Docker Inc.)
           Version:  v0.10.2
           Path:     /usr/libexec/docker/cli-plugins/docker-buildx
         compose: Docker Compose (Docker Inc.)
           Version:  v2.16.0
           Path:     /usr/libexec/docker/cli-plugins/docker-compose
         scan: Docker Scan (Docker Inc.)
           Version:  v0.23.0
           Path:     /usr/libexec/docker/cli-plugins/docker-scan

       Server:
        Containers: 22
         Running: 3
         Paused: 0
         Stopped: 19
        Images: 24
        Server Version: 23.0.1
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Using metacopy: false
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: systemd
        Cgroup Version: 2
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
        runc version: v1.1.4-0-g5fd4c4d
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: builtin
         cgroupns
        Kernel Version: 5.15.0-60-generic
        Operating System: Ubuntu 22.04.1 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 1
        Total Memory: 969.4MiB
        Name: dragonejt
        ID: a901e245-8319-46dd-a4ff-db4a569a5a6d
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> git version: git version 2.34.1
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version:
       herokuish: v0.5.40
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v244
         heroku-buildpack-nodejs    v202
         heroku-buildpack-clojure   v90
         heroku-buildpack-python    v223
         heroku-buildpack-java      v72
         heroku-buildpack-gradle    v38
         heroku-buildpack-scala     v96
         heroku-buildpack-play      v26
         heroku-buildpack-php       v227
         heroku-buildpack-go        v169
         heroku-buildpack-nginx     v22
         buildpack-null             v3
-----> dokku version: dokku version 0.30.0
-----> plugn version: plugn: 0.12.0build+3a27594
-----> dokku plugins:
         00_dokku-standard    0.30.0 enabled    dokku core standard plugin
         20_events            0.30.0 enabled    dokku core events logging plugin
         app-json             0.30.0 enabled    dokku core app-json plugin
         apps                 0.30.0 enabled    dokku core apps plugin
         builder              0.30.0 enabled    dokku core builder plugin
         builder-dockerfile   0.30.0 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.30.0 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.30.0 enabled    dokku core builder-lambda plugin
         builder-null         0.30.0 enabled    dokku core builder-null plugin
         builder-pack         0.30.0 enabled    dokku core builder-pack plugin
         buildpacks           0.30.0 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.30.0 enabled    dokku core caddy-vhosts plugin
         certs                0.30.0 enabled    dokku core certificate management plugin
         checks               0.30.0 enabled    dokku core checks plugin
         common               0.30.0 enabled    dokku core common plugin
         config               0.30.0 enabled    dokku core config plugin
         cron                 0.30.0 enabled    dokku core cron plugin
         docker-options       0.30.0 enabled    dokku core docker-options plugin
         domains              0.30.0 enabled    dokku core domains plugin
         enter                0.30.0 enabled    dokku core enter plugin
         git                  0.30.0 enabled    dokku core git plugin
         haproxy-vhosts       0.30.0 enabled    dokku core haproxy-vhosts plugin
         letsencrypt          0.20.0 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.30.0 enabled    dokku core logs plugin
         mongo                1.24.0 enabled    dokku mongo service plugin
         network              0.30.0 enabled    dokku core network plugin
         nginx-vhosts         0.30.0 enabled    dokku core nginx-vhosts plugin
         plugin               0.30.0 enabled    dokku core plugin plugin
         postgres             1.27.0 enabled    dokku postgres service plugin
         proxy                0.30.0 enabled    dokku core proxy plugin
         ps                   0.30.0 enabled    dokku core ps plugin
         registry             0.30.0 enabled    dokku core registry plugin
         repo                 0.30.0 enabled    dokku core repo plugin
         resource             0.30.0 enabled    dokku core resource plugin
         run                  0.30.0 enabled    dokku core run plugin
         scheduler            0.30.0 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.30.0 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.30.0 enabled    dokku core scheduler-null plugin
         shell                0.30.0 enabled    dokku core shell plugin
         ssh-keys             0.30.0 enabled    dokku core ssh-keys plugin
         storage              0.30.0 enabled    dokku core storage plugin
         trace                0.30.0 enabled    dokku core trace plugin
         traefik-vhosts       0.30.0 enabled    dokku core traefik-vhosts plugin
=====> sibyl app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:
=====> sibyl app information
       App created at:                1676237314
       App deploy source:             sibyl
       App deploy source metadata:    sibyl
       App dir:                       /home/dokku/sibyl
       App locked:                    false
=====> sibyl builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:     pack
       Builder global build dir:
       Builder global selected:
       Builder selected:              pack
=====> sibyl builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path:
=====> sibyl builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml
       Builder lambda global lambdayml path: lambda.yml
       Builder lambda lambdayml path:
=====> sibyl builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> sibyl buildpacks information
       Buildpacks computed stack:     paketobuildpacks/builder-jammy-full
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:              paketobuildpacks/builder-jammy-full
=====> sibyl ssl information
       Ssl dir:                       /home/dokku/sibyl/tls
       Ssl enabled:                   true
       Ssl hostnames:                 *.sibylmod.xyz sibylmod.xyz
       Ssl expires at:                Jan  7 03:35:00 2038 GMT
       Ssl issuer:                    C = US, O = "CloudFlare, Inc.", OU = CloudFlare Origin SSL Certificate Authority, L = San Francisco, ST = California
       Ssl starts at:                 Jan 11 03:35:00 2023 GMT
       Ssl subject:                   subject=O = "CloudFlare, Inc.", OU = CloudFlare Origin CA, CN = CloudFlare Origin Certificate
       Ssl verified:                  self signed
=====> sibyl checks information
       Checks disabled list:          none
       Checks skipped list:           none
       Checks computed wait to retire: 60
       Checks global wait to retire:  60
       Checks wait to retire:
=====> sibyl cron information
       Cron task count:               0
=====> sibyl docker options information
       Docker options build:          --link dokku.postgres.sibyldb:dokku-postgres-sibyldb
       Docker options deploy:         --link dokku.postgres.sibyldb:dokku-postgres-sibyldb --restart=on-failure:10
       Docker options run:            --link dokku.postgres.sibyldb:dokku-postgres-sibyldb
=====> sibyl domains information
       Domains app enabled:           true
       Domains app vhosts:            api.sibylmod.xyz
       Domains global enabled:        true
       Domains global vhosts:         by.dragonejt.dev
=====> sibyl git information
       Git deploy branch:             main
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:
       Git source image:
       Git last updated at:           1676620582
=====> sibyl letsencrypt information
       Letsencrypt active:            false
       Letsencrypt autorenew:         false
       Letsencrypt computed dns provider:
       Letsencrypt global dns provider:
       Letsencrypt dns provider:
       Letsencrypt computed email:
       Letsencrypt global email:
       Letsencrypt email:
       Letsencrypt expiration:        2146448100
       Letsencrypt computed graceperiod: 2592000
       Letsencrypt global graceperiod:
       Letsencrypt graceperiod:
       Letsencrypt computed lego docker args:
       Letsencrypt global lego docker args:
       Letsencrypt lego docker args:
       Letsencrypt computed server:   https://acme-v02.api.letsencrypt.org/directory
       Letsencrypt global server:
       Letsencrypt server:
=====> sibyl logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:
       Logs vector sink:
=====> sibyl network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:          false
       Network computed attach post create:
       Network computed attach post deploy:
       Network computed bind all interfaces: false
       Network computed initial network:
       Network computed tld:
       Network global attach post create:
       Network global attach post deploy:
       Network global bind all interfaces:   false
       Network global initial network:
       Network global tld:
       Network initial network:
       Network static web listener:
       Network tld:
       Network web listeners:                172.17.0.4:5000
=====> sibyl nginx information
       Nginx access log format:
       Nginx access log path:         /var/log/nginx/sibyl-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx client max body size:
       Nginx disable custom config:   false
       Nginx error log path:          /var/log/nginx/sibyl-error.log
       Nginx global hsts:             true
       Nginx computed hsts:           true
       Nginx hsts:
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx computed nginx conf sigil path: nginx.conf.sigil
       Nginx global nginx conf sigil path: nginx.conf.sigil
       Nginx nginx conf sigil path:
       Nginx proxy buffer size:       4096
       Nginx proxy buffering:         on
       Nginx proxy buffers:           8 4096
       Nginx proxy busy buffers size: 8192
       Nginx proxy read timeout:      60s
       Nginx last visited at:         1676635348
       Nginx x forwarded for value:   $remote_addr
       Nginx x forwarded port value:  $server_port
       Nginx x forwarded proto value: $scheme
       Nginx x forwarded ssl:
=====> sibyl proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 https:443:5000
       Proxy type:                    nginx
=====> sibyl ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: 008e5b3b50d)
=====> sibyl registry information
       Registry computed image repo:      dokku/sibyl
       Registry computed push on release: false
       Registry computed server:
       Registry global push on release:
       Registry global server:
       Registry image repo:
       Registry push on release:
       Registry server:
       Registry tag version:
=====> sibyl resource information
=====> sibyl scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:
=====> sibyl scheduler-docker-local information
       Scheduler docker local disable chown:
       Scheduler docker local init process: true
       Scheduler docker local parallel schedule count:
=====> sibyl storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:
```
### Additional information

I have tried this with all types of heroku CNB buildpacks and paketo buildpacks. The build process always works, but running the container starts the issue.

Procfile(s):
```
web: gunicorn --worker-tmp-dir /dev/shm sibyl/wsgi.py
release: python manage.py makemigrations && python manage.py migrate
```

This results in the `gunicorn --worker-tmp-dir /dev/shm sibyl.wsgi: No such file or directory` error

```
web: gunicorn sibyl.wsgi
release: python manage.py makemigrations && python manage.py migrate
```

This results in the `gunicorn sibyl.wsgi: command not found` error

**Comment by josegonzalez** [comment] 2023-02-17 20:01
For future reference, enclosing code in three backticks does a better job of highlighting code on github markdown: https://github.github.com/gfm/#fenced-code-blocks

I don't think the issue is what you are saying - env vars don't get attached to the end of a process like that. It almost seems like the builder is taking the command and args and running it as a single binary vs doing a string split. I'll take a look though.

**Comment by josegonzalez** [comment] 2023-02-17 20:44
Okay the problem here has to do with changes in how processes get launched. For pack, it seems like we'll want to set the arg `--entrypoint launcher` for `deploy` and `run` containers, as otherwise the default process type gets launched and the command/args are passed as arguments to the process type.

See this doc for more info: https://buildpacks.io/docs/app-developer-guide/run-an-app/#user-provided-shell-process

**Comment by josegonzalez** [comment] 2023-02-17 21:08
Closing as there is a pull request open. Thanks for reporting!

**Closed** 2023-02-17 21:08 UTC
Labels: type: bug, needs: investigation, plugin: builders

**Comment by dragonejt** [comment] 2023-02-18 00:02
Thank you for the super-fast turnaround time!

**Comment by dragonejt** [comment] 2023-02-21 17:17
@josegonzalez I can confirm that my app is now running successfully after being built with Cloud Native Buildpacks since dokku v0.30.1
