### ISSUE TITLE
Unable to install on Raspbian 11 (bullseye)

### ISSUE THREAD

**Issue by thomasfedb** [dokku/dokku#5185] opened 2022-05-17 13:03 UTC
### Description of problem

Attempting to install via `bootstrap.sh` fails when the script attempt to install the `dokku` package.

### Steps to reproduce

1. New install of Raspberry Pi OS Lite (64bit)
2. `wget https://raw.githubusercontent.com/dokku/dokku/v0.27.4/bootstrap.sh; sudo DOKKU_TAG=v0.27.4 bash bootstrap.sh`

### dokku report $APP_NAME

Output of `bootstrap.sh` is:

```
--- snip ---
--> Installing dokku
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
2022-05-17 13:56:29 URL:https://d28dx6y1hfq314.cloudfront.net/505/623/gpg/dokku-dokku-FB2B6AA421CD193F.pub.gpg?t=1652792489_599118cab768376258d9e5a2d8c855013408a4d3 [3937/3937] -> "-" [1]
OK
deb https://packagecloud.io/dokku/dokku/debian/ bullseye main
E: Unable to correct problems, you have held broken packages.
```

Full output here: https://gist.github.com/thomasfedb/1874a236b7bdc8f26ff1a66d55af0a30

**Comment by thomasfedb** [comment] 2022-05-17 13:10
Running with `bash -x` shows that the issue occurs here:
https://github.com/dokku/dokku/blob/5df4bd710a960ca6e3b56f566cf3e8149528e4a1/bootstrap.sh#L227

```
+ echo '--> Installing dokku'
--> Installing dokku
+ wget -nv -O - https://packagecloud.io/dokku/dokku/gpgkey
+ apt-key add -
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
2022-05-17 14:07:34 URL:https://d28dx6y1hfq314.cloudfront.net/505/623/gpg/dokku-dokku-FB2B6AA421CD193F.pub.gpg?t=1652793154_d8fff99a8aeddf84211c6a70eb7dba7f9a6646bc [3937/3937] -> "-" [1]
OK
+ echo 'deb https://packagecloud.io/dokku/dokku/debian/ bullseye main'
+ tee /etc/apt/sources.list.d/dokku.list
deb https://packagecloud.io/dokku/dokku/debian/ bullseye main
+ apt-get update -qq
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n 0.27.4 ]]
+ apt-get -qq -y install dokku=0.27.4
E: Unable to correct problems, you have held broken packages.
```

**Comment by thomasfedb** [comment] 2022-05-17 13:10
Appears to be a dependency issues with the `dokku` package:

```
admin@raspberrypi:~ $ sudo apt-get -y install dokku=0.27.4
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dokku : PreDepends: gliderlabs-sigil but it is not installable
         PreDepends: plugn (>= 0.3.0) but it is not installable
         Depends: docker-image-labeler (>= 0.2.2) but it is not installable
         Depends: netrc but it is not installable
         Depends: procfile-util (>= 0.11.0) but it is not installable
         Recommends: herokuish (>= 0.3.4) but it is not installable
         Recommends: dokku-update but it is not going to be installed
         Recommends: dokku-event-listener but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by josegonzalez** [comment] 2022-05-17 14:38
Yeah looks like we didn't publish `arm64` for raspbian/bullseye for those. I can take care of that today, thanks for filing a ticket!

**Comment by thomasfedb** [comment] 2022-05-18 12:09
Thanks @josegonzalez, please let me know when to try again

**Comment by Technerder** [comment] 2022-05-21 06:12
Looking forward to this as well! Is there a temporary workaround that would allow us to test out Dokku while we wait for the `arm64` dependency packages to be pushed out?

**Comment by josegonzalez** [comment] 2022-05-21 06:18
The files should be uploaded now, try it again?

**Comment by Technerder** [comment] 2022-05-21 06:53
Still seem to be running into the same issue on a completely fresh install of `Raspberry Pi OS Lite (64-bit)` from the official raspberry pi imager.

Manual: 
```output
user@rpi:~ $ sudo apt-get install dokku
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dokku : PreDepends: gliderlabs-sigil but it is not installable
         PreDepends: plugn (>= 0.3.0) but it is not installable
         Depends: docker-image-labeler (>= 0.2.2) but it is not installable
         Depends: netrc but it is not installable
         Depends: procfile-util (>= 0.11.0) but it is not installable
         Recommends: herokuish (>= 0.3.4) but it is not installable
         Recommends: dokku-update but it is not going to be installed
         Recommends: dokku-event-listener but it is not installable
E: Unable to correct problems, you have held broken packages.
```


Install script from site: 
```log
user@rpi:~ $ wget https://raw.githubusercontent.com/dokku/dokku/v0.27.4/bootstrap.sh
--2022-05-21 02:47:06--  https://raw.githubusercontent.com/dokku/dokku/v0.27.4/bootstrap.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9585 (9.4K) [text/plain]
Saving to: ‘bootstrap.sh’

bootstrap.sh                  100%[=================================================>]   9.36K  --.-KB/s    in 0.001s

2022-05-21 02:47:06 (15.6 MB/s) - ‘bootstrap.sh’ saved [9585/9585]

user@rpi:~ $  sudo DOKKU_TAG=v0.27.4 bash bootstrap.sh
Preparing to install v0.27.4 from https://github.com/dokku/dokku.git...
--> Ensuring we have the proper dependencies
Selecting previously unselected package libgirepository-1.0-1:arm64.
(Reading database ... 35576 files and directories currently installed.)
Preparing to unpack .../0-libgirepository-1.0-1_1.66.1-1+b1_arm64.deb ...
Unpacking libgirepository-1.0-1:arm64 (1.66.1-1+b1) ...
Selecting previously unselected package gir1.2-glib-2.0:arm64.
Preparing to unpack .../1-gir1.2-glib-2.0_1.66.1-1+b1_arm64.deb ...
Unpacking gir1.2-glib-2.0:arm64 (1.66.1-1+b1) ...
Selecting previously unselected package libpackagekit-glib2-18:arm64.
Preparing to unpack .../2-libpackagekit-glib2-18_1.2.2-2_arm64.deb ...
Unpacking libpackagekit-glib2-18:arm64 (1.2.2-2) ...
Selecting previously unselected package gir1.2-packagekitglib-1.0.
Preparing to unpack .../3-gir1.2-packagekitglib-1.0_1.2.2-2_arm64.deb ...
Unpacking gir1.2-packagekitglib-1.0 (1.2.2-2) ...
Selecting previously unselected package python3-dbus.
Preparing to unpack .../4-python3-dbus_1.2.16-5_arm64.deb ...
Unpacking python3-dbus (1.2.16-5) ...
Selecting previously unselected package python3-gi.
Preparing to unpack .../5-python3-gi_3.38.0-2_arm64.deb ...
Unpacking python3-gi (3.38.0-2) ...
Selecting previously unselected package python3-pycurl.
Preparing to unpack .../6-python3-pycurl_7.43.0.6-5_arm64.deb ...
Unpacking python3-pycurl (7.43.0.6-5) ...
Selecting previously unselected package python3-software-properties.
Preparing to unpack .../7-python3-software-properties_0.96.20.2-2.1_all.deb ...
Unpacking python3-software-properties (0.96.20.2-2.1) ...
Selecting previously unselected package software-properties-common.
Preparing to unpack .../8-software-properties-common_0.96.20.2-2.1_all.deb ...
Unpacking software-properties-common (0.96.20.2-2.1) ...
Setting up python3-dbus (1.2.16-5) ...
Setting up libpackagekit-glib2-18:arm64 (1.2.2-2) ...
Setting up python3-pycurl (7.43.0.6-5) ...
Setting up python3-software-properties (0.96.20.2-2.1) ...
Setting up libgirepository-1.0-1:arm64 (1.66.1-1+b1) ...
Setting up gir1.2-glib-2.0:arm64 (1.66.1-1+b1) ...
Setting up gir1.2-packagekitglib-1.0 (1.2.2-2) ...
Setting up python3-gi (3.38.0-2) ...
Setting up software-properties-common (0.96.20.2-2.1) ...
Processing triggers for libc-bin (2.31-13+rpt2+rpi1+deb11u2) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for dbus (1.12.20-2) ...
--> Note: Installing dokku for the first time will result in removal of
    files in the nginx 'sites-enabled' directory. Please manually
    restore any files that may be removed after the installation and
    web setup is complete.

    Installation will continue in 10 seconds.
--> Initial apt-get update
Selecting previously unselected package apt-transport-https.
(Reading database ... 35793 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_2.2.4_all.deb ...
Unpacking apt-transport-https (2.2.4) ...
Setting up apt-transport-https (2.2.4) ...
--> Installing docker
2022-05-21 02:47:49 URL:https://get.docker.com/ [19305/19305] -> "-" [1]
# Executing docker install script, commit: 614d05e0e669a0577500d055677bb6f71e822356
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/debian/gpg" | gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg
+ sh -c chmod a+r /usr/share/keyrings/docker-archive-keyring.gpg
+ sh -c echo "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends docker-ce docker-ce-cli containerd.io docker-compose-plugin >/dev/null
+ version_gte 20.10
+ [ -z  ]
+ return 0
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-ce-rootless-extras >/dev/null
+ sh -c docker version
Client: Docker Engine - Community
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:15:56 2022
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:14:19 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

================================================================================

To run Docker as a non-privileged user, consider setting up the
Docker daemon in rootless mode for your user:

    dockerd-rootless-setuptool.sh install

Visit https://docs.docker.com/go/rootless/ to learn about rootless mode.


To run the Docker daemon as a fully privileged service, but granting non-root
users access, refer to https://docs.docker.com/go/daemon-access/

WARNING: Access to the remote API on a privileged Docker daemon is equivalent
         to root access on the host. Refer to the 'Docker daemon attack surface'
         documentation for details: https://docs.docker.com/go/attack-surface/

================================================================================

--> Installing dokku
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
2022-05-21 02:48:52 URL:https://d28dx6y1hfq314.cloudfront.net/505/623/gpg/dokku-dokku-FB2B6AA421CD193F.pub.gpg?t=1653116032_e76c082ff3c1c36aa996adfbe7772adfefaed8fb [3937/3937] -> "-" [1]
OK
deb https://packagecloud.io/dokku/dokku/debian/ bullseye main
E: Unable to correct problems, you have held broken packages.
```

**Comment by josegonzalez** [comment] 2022-05-21 06:54
@Technerder what happens when you run the following:

```
 sudo apt-get install gliderlabs-sigil plugn docker-image-labeler netrc procfile-util herokuish dokku-update dokku-event-listener
```

**Comment by Technerder** [comment] 2022-05-21 06:54
```output
user@rpi:~ $  sudo apt-get install gliderlabs-sigil plugn docker-image-labeler netrc procfile-util herokuish dokku-update dokku-event-listener
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package gliderlabs-sigil is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package plugn is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package docker-image-labeler is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package netrc is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package procfile-util is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package herokuish is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package dokku-event-listener is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gliderlabs-sigil' has no installation candidate
E: Package 'plugn' has no installation candidate
E: Package 'docker-image-labeler' has no installation candidate
E: Package 'netrc' has no installation candidate
E: Package 'procfile-util' has no installation candidate
E: Package 'herokuish' has no installation candidate
E: Package 'dokku-event-listener' has no installation candidate
```

**Comment by josegonzalez** [comment] 2022-05-21 06:56
Okay other than herokuish, those others should exist.

What is the output of:

```shell
cat /etc/apt/sources.list.d/dokku.list
```

**Comment by Technerder** [comment] 2022-05-21 06:56
Only this one line
```output
deb https://packagecloud.io/dokku/dokku/debian/ bullseye main
```

**Comment by josegonzalez** [comment] 2022-05-21 06:59
Hmmm shouldnt that say `raspbian` instead of `debian`? 🤔

**Comment by josegonzalez** [comment] 2022-05-21 06:59
Or are you using a debian/bullseye install instead of raspbian/bullseye?

**Comment by Technerder** [comment] 2022-05-21 07:14
I'm using the `Raspberry Pi OS Lite (64-bit)` release from within the Raspberry pi imager. I never modified the contents of the `/etc/apt/sources.list.d/dokku.list` sources file but I think the reason `debian` is used instead of `raspbian` is because of line [266](https://github.com/dokku/dokku/blob/master/bootstrap.sh#L266) of the official dokku installer as it displays `debian` when I run the command. 

I changed the file contents to be `deb https://packagecloud.io/dokku/dokku/raspbian/ bullseye main` and after an `sudo apt update` and `sudo apt install dokku` the output is slightly different

```output
user@rpi:~ $ sudo apt update && sudo apt install dokku
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://security.debian.org/debian-security bullseye-security InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 https://download.docker.com/linux/debian bullseye InRelease
Hit:5 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:6 https://packagecloud.io/dokku/dokku/raspbian bullseye InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dokku:armhf : PreDepends: nginx:armhf (>= 1.8.0) or
                           openresty:armhf but it is not installable
               PreDepends: dnsutils:armhf
               PreDepends: sudo:armhf
               PreDepends: python3:armhf but it is not going to be installed
               Depends: locales:armhf but it is not installable
               Depends: sshcommand:armhf (>= 0.12.0) but it is not installable
               Depends: docker-engine-cs:armhf (>= 17.05.0) but it is not installable or
                        docker-engine:armhf (>= 17.05.0) but it is not installable or
                        docker-io:armhf (>= 17.05.0) but it is not installable or
                        docker.io:armhf (>= 17.05.0) but it is not going to be installed or
                        docker-ce:armhf (>= 17.05.0) but it is not installable or
                        docker-ee:armhf (>= 17.05.0) but it is not installable or
                        moby-engine:armhf but it is not installable
               Depends: software-properties-common:armhf but it is not installable
               Depends: parallel:armhf but it is not installable
               Depends: python-software-properties:armhf but it is not installable or
                        python3-software-properties:armhf but it is not installable
               Depends: rsyslog:armhf but it is not going to be installed
               Recommends: herokuish:armhf (>= 0.3.4) but it is not installable
               Recommends: dokku-update:armhf but it is not installable
               Recommends: dokku-event-listener:armhf but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by josegonzalez** [comment] 2022-05-21 07:17
@Technerder are you able to [connect to our chat](https://dokku.com/docs/getting-started/where-to-get-help/)? I thought this was about arm64, not arm, but your errors there point out armhf (which is arm).

**Comment by Technerder** [comment] 2022-05-21 07:20
I should be in the `general` channel of the Discord now

**Comment by josegonzalez** [comment] 2022-05-21 07:46
Okay the issue is that 64-bit Raspbian is actually based on Debian. I'll need to go back and update the MRs so that the packages are uploaded to the correct OS for 64bit.

**Comment by thomasfedb** [comment] 2022-05-26 06:55
Hey @josegonzalez is this worth testing again yet?

**Comment by josegonzalez** [comment] 2022-05-26 14:23
Yeah try it and see @thomasfedb .

**Comment by josegonzalez** [comment] 2022-05-29 20:15
Closing as I'm pretty sure we publish everything now automatically. Feel free to comment if you have issues.

**Closed by josegonzalez** 2022-05-29 20:15 UTC
Labels: type: bug, needs: investigation

**Comment by thomasfedb** [comment] 2022-06-03 02:28
Looks to be working! Thanks @josegonzalez
