### ISSUE TITLE
None routeable background worker with disable vhosts

### ISSUE THREAD

**Issue by lafama** [dokku/dokku#3265] opened 2018-09-09 14:53 UTC
## Description of problem
Background none-routeable worker process without any domains deploys with the following error
```Application deployed:
/var/lib/dokku/core-plugins/available/common/functions: line 871: /home/dokku/VHOST: No such file or directory
       http://
```
This causes other apps to fails to deploy or rebuild failing with
```
nginx: [emerg] host not found in upstream "workerapp-5000" in /home/dokku/workerapp/nginx.conf:18
nginx: configuration file /etc/nginx/nginx.conf test failed
       validate_nginx failed. contents of /home/dokku/newapp/nginx.conf 
```

### How reproducible
on all new installations after upgrading to  v0.12.12 

### Steps to Reproduce
1. Create new app
2. Disable Vhost ```dokku domains:disable node-js-app``

#### Actual Results
```
Running nginx-pre-reload
       Reloading nginx
nginx: [emerg] host not found in upstream "workerapp-5000" in /home/dokku/workerapp/nginx.conf:18
nginx: configuration file /etc/nginx/nginx.conf test failed
       validate_nginx failed. contents of /home/dokku/app1/nginx.conf below...

server {
  listen      [::]:80;
  listen      80;
  server_name app.domain.com; 
  access_log  /var/log/nginx/api-access.log;
  error_log   /var/log/nginx/api-error.log;

  return 301 https://$host:443$request_uri;

}

server {
  listen      [::]:443 ssl ;
  listen      443 ssl ;
  
  server_name app.domain.com; 
  access_log  /var/log/nginx/api-access.log;
  error_log   /var/log/nginx/api-error.log;

  ssl_certificate     /home/dokku/app1/tls/server.crt;
  ssl_certificate_key /home/dokku/app1/tls/server.key;
  ssl_protocols       TLSv1.2;
  ssl_prefer_server_ciphers on;

  keepalive_timeout   70;
  

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://app1-5000;
    
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/app1/nginx.conf.d/*.conf;

  error_page 400 401 402 403 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 /400-error.html;
  location /400-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 404 /404-error.html;
  location /404-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 500 501 502 503 504 505 506 507 508 509 510 511 /500-error.html;
  location /500-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }
}

upstream app1-5000 {

  server 172.17.0.2:5000;
}

       validate_nginx failed. contents of /home/dokku/app2/nginx.conf below...

...more apps
```

### `dokku report APP_NAME` output
```
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:           2000         977         406           1         615         795
       Swap:          1999        1500         499
-----> docker version: 
       Client:
        Version:           18.06.1-ce
        API version:       1.38
        Go version:        go1.10.3
        Git commit:        e68fc7a
        Built:             Tue Aug 21 17:24:56 2018
        OS/Arch:           linux/amd64
        Experimental:      false
       
       Server:
        Engine:
         Version:          18.06.1-ce
         API version:      1.38 (minimum version 1.12)
         Go version:       go1.10.3
         Git commit:       e68fc7a
         Built:            Tue Aug 21 17:23:21 2018
         OS/Arch:          linux/amd64
         Experimental:     false
-----> docker daemon info: 
       Containers: 30
        Running: 16
        Paused: 0
        Stopped: 14
       Images: 105
       Server Version: 18.06.1-ce
       Storage Driver: overlay2
        Backing Filesystem: extfs
        Supports d_type: true
        Native Overlay Diff: true
       Logging Driver: json-file
       Cgroup Driver: cgroupfs
       Plugins:
        Volume: local
        Network: bridge host macvlan null overlay
        Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
       Swarm: inactive
       Runtimes: runc
       Default Runtime: runc
       Init Binary: docker-init
       containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
       runc version: 69663f0bd4b60df09991c08812a60108003fa340
       init version: fec3683
       Security Options:
        apparmor
        seccomp
         Profile: default
       Kernel Version: 4.4.0-134-generic
       Operating System: Ubuntu 16.04.5 LTS
       OSType: linux
       Architecture: x86_64
       CPUs: 2
       Total Memory: 1.953GiB
       Name: chi-ela-app-jan-2018
       ID: 4X6R:AZL6:3QEV:HNWD:57JK:5YJ7:AWDA:IJMP:5W4L:2UUT:CBLQ:CHJF
       Docker Root Dir: /var/lib/docker
       Debug Mode (client): true
       Debug Mode (server): false
       Registry: https://index.docker.io/v1/
       Labels:
       Experimental: false
       Insecure Registries:
        127.0.0.0/8
       Live Restore Enabled: false
       
WARNING: No swap limit support
-----> sigil version: 0.4.0
-----> herokuish version: 
       herokuish: 0.4.3
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v188
         heroku-buildpack-nodejs    v123
         heroku-buildpack-clojure   v82
         heroku-buildpack-python    v136
         heroku-buildpack-java      v62
         heroku-buildpack-gradle    v27
         heroku-buildpack-scala     v82
         heroku-buildpack-play      v26
         heroku-buildpack-php       v137
         heroku-buildpack-go        v89
         buildpack-nginx            v9
-----> dokku version: 0.12.12
-----> dokku plugins: 
       plugn: 0.3.0
         00_dokku-standard    0.12.12 enabled    dokku core standard plugin
         20_events            0.12.12 enabled    dokku core events logging plugin
         apps                 0.12.12 enabled    dokku core apps plugin
         build-env            0.12.12 enabled    dokku core build-env plugin
         certs                0.12.12 enabled    dokku core certificate management plugin
         checks               0.12.12 enabled    dokku core checks plugin
         common               0.12.12 enabled    dokku core common plugin
         config               0.12.12 enabled    dokku core config plugin
         docker-options       0.12.12 enabled    dokku core docker-options plugin
         domains              0.12.12 enabled    dokku core domains plugin
         enter                0.12.12 enabled    dokku core enter plugin
         git                  0.12.12 enabled    dokku core git plugin
         letsencrypt          0.8.8 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.12.12 enabled    dokku core logs plugin
         network              0.12.12 enabled    dokku core network plugin
         nginx-vhosts         0.12.12 enabled    dokku core nginx-vhosts plugin
         plugin               0.12.12 enabled    dokku core plugin plugin
         proxy                0.12.12 enabled    dokku core proxy plugin
         ps                   0.12.12 enabled    dokku core ps plugin
         repo                 0.12.12 enabled    dokku core repo plugin
         scheduler-docker-local 0.12.12 enabled    dokku core scheduler-docker-local plugin
         shell                0.12.12 enabled    dokku core shell plugin
         ssh-keys             0.12.12 enabled    dokku core ssh-keys plugin
         storage              0.12.12 enabled    dokku core storage plugin
         tags                 0.12.12 enabled    dokku core tags plugin
         tar                  0.12.12 enabled    dokku core tar plugin
=====> workerapp app information
       App dir:                       /home/dokku/workerapp       
       Git sha:                       ff4d18c                  
       Deploy source:                 git                      
       Locked:                        false                    
=====> workerapp ssl information
       Ssl dir:                       /home/dokku/workerapp/tls   
       Ssl enabled:                   false                    
       Ssl hostnames:                                          
       Ssl expires at:                                         
       Ssl issuer:                                             
       Ssl starts at:                                          
       Ssl subject:                                            
       Ssl verified:                                           
=====> workerapp checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> workerapp docker options information
       Docker options build:                                   
       Docker options deploy:         --restart=on-failure:10  
       Docker options run:                                     
=====> workerapp domains information
       Domains app enabled:           false                    
       Domains app vhosts:                                     
       Domains global enabled:        false                    
       Domains global vhosts:                                  
=====> workerapp git information
       Git rev env var:               GIT_REV                  
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
=====> workerapp network information
       Network bind all interfaces:   false
       Network listeners:             
=====> workerapp proxy information
       Proxy enabled:                 true                     
       Proxy type:                    nginx                    
       Proxy port map:                                         
=====> workerapp ps information
       Processes:                     1                        
       Deployed:                      true                     
       Running:                       true                     
       Restore:                       true                     
       Restart policy:                on-failure:10            
       Status workerapp.1:               running    (CID: 72f23b150882)
=====> workerapp scheduler-docker-local information
       Scheduler docker local disable chown:                          
=====> workerapp storage information
       Storage build mounts:                                   
       Storage deploy mounts:                                  
       Storage run mounts:  
```

> This is required! Issues missing this information may be closed.
>
> For problems affecting all applications, the report output for a broken application is useful for our debugging.
> You may also run `dokku report` without any arguments to display the top-level reporting information.

### Additional information

- `docker inspect CONTAINER_ID` (if applicable):
  (BEWARE: `docker inspect` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):
- `cat /home/dokku/<app>/nginx.conf` (if applicable):
- Link to the exact repository being deployed (if possible/applicable):
- If a deploy is failing or behaving unexpectedly:
  - Application name
  - The type of application being deployed (node, php, python, ruby, etc.)
  - If using buildpacks, which custom buildpacks are in use
  - If using a `Dockerfile`, the contents of that file
  - If it exists, the contents of your `Procfile`.
- Output of failing Dokku commands after running `dokku trace on`
  (BEWARE: `trace on` will print environment variables for some commands, be sure you're not exposing any sensitive information when posting issues. You may replace these values with XXXXXXX):

**Comment by josegonzalez** [comment] 2018-09-09 21:46
What is the output of:

```
dokku ps:scale APP
```

**Comment by lafama** [comment] 2018-09-10 03:11
```
-----> Scaling for workerapp
-----> proctype           qty                                                                          
-----> --------           ---                                                                          
-----> web                0                                                                            
-----> worker             1  
```

**Comment by josegonzalez** [comment] 2018-09-11 20:47
Thats... interesting. Do you have the output of a deploy after running the following:

```
dokku trace on
```

We shouldn't be generating nginx config if you dont have a web process scaled in.

**Comment by andreroggeri** [comment] 2018-09-17 16:53
Same occurred to me. 
The quick fix what to delete the nginx file for the app (/home/dokku/bot/nginx.conf)

But I had to do this every deploy / server reboot

**Comment by lafama** [comment] 2018-09-18 04:14
@josegonzalez I checked and tried to rebuild the app but we don't have that file 
```/home/dokku/workerapp/nginx.conf```
So the trace would have to be the same as above

**Comment by josegonzalez** [comment] 2018-09-20 03:08
Do you have a sample app I can use to replicate this issue? I'm stepping through the code and am not sure how you're getting to the place you're getting, so being able to completely reproduce this would be great.

**Comment by andreroggeri** [comment] 2018-09-20 04:14
@josegonzalez I could not reproduce it on a local box, but on my production environment I can reproduce it easily. I'll try to put the logs here

**Comment by andreroggeri** [comment] 2018-09-20 04:35
Hmm, the file seems to be created on reboot, how can I get the logs from startup ?

**Comment by josegonzalez** [comment] 2018-09-20 04:35
Which file gets created on reboot?

**Comment by andreroggeri** [comment] 2018-09-20 04:36
The nginx.conf for the worker-only app

**Comment by josegonzalez** [comment] 2018-09-20 04:36
Check `/var/log/dokku`. We log that in a `dokku-restore` service.

**Comment by andreroggeri** [comment] 2018-09-20 05:18
Well, actually not so easy to reproduce.
Here my steps:
1. Rebuild the worker-only app
2. Reboot server
3. Rebuild the worker again

> andre@agendaodonto-ubuntu:~$ sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
andre@agendaodonto-ubuntu:~$ dokku --trace ps:rebuild worker-app2 > trace.txt 2>&1
andre@agendaodonto-ubuntu:~$ sudo nginx -t
nginx: [emerg] host not found in upstream "worker-app2-5000" in /home/dokku/worker-app2/nginx.conf:18
nginx: configuration file /etc/nginx/nginx.conf test failed
andre@agendaodonto-ubuntu:~$

Trace file contents: https://pastebin.com/7tnm0Bft

**Comment by lafama** [comment] 2018-09-29 12:33
yes after a reboot i can now trace this file 
```
/home/dokku/workerapp/nginx.conf
```
Deleting it seem to fix the problem. I  guess the file should not be there on a worker process

**Comment by josegonzalez** [comment] 2018-10-06 20:37
Remove that file and then run:

```
dokku --trace ps:start workerapp
```

And gist all the output for me. Thanks!

**Comment by josegonzalez** [comment] 2018-11-04 21:13
Closing as there hasn't been an update in almost a month.

**Closed by josegonzalez** 2018-11-04 21:13 UTC
