### ISSUE TITLE
SSL_SERVER_NAME not populated even though ssl is set up for vhost

### ISSUE THREAD

**Issue by dewey** [dokku/dokku#6990] opened 2024-07-11 17:36 UTC
### Description of problem

I believe there's a bug where the `SSL_SERVER_NAME` variable is not populated in the nginx template even though it's set up for the app. I'm talking about the bit of the nginx config template below. The bug wouldn't really show up as by default there's both a `SSL_SERVER_NAME` and a `NOSSL_SERVER_NAME` line, so the `NOSSL_SERVER_NAME` would then always work it seems.

```
{{ else if eq $scheme "https"}}
server {
  listen      [{{ $.NGINX_BIND_ADDRESS_IP6 }}]:{{ $listen_port }} ssl {{ if eq $.HTTP2_SUPPORTED "true" }}http2{{ end }};
  listen      {{ if $.NGINX_BIND_ADDRESS_IP4 }}{{ $.NGINX_BIND_ADDRESS_IP4 }}:{{end}}{{ $listen_port }} ssl {{ if eq $.HTTP2_SUPPORTED "true" }}http2{{ end }};
  {{ if $.SSL_SERVER_NAME }}server_name {{ $.SSL_SERVER_NAME }}; {{ end }}
  {{ if $.NOSSL_SERVER_NAME }}server_name {{ $.NOSSL_SERVER_NAME }}; {{ end }}
```
Line: https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil#L73

Looking a the configured app I can see that the vhosts and ssl certificates are set up correctly:

```
root@server:~# dokku domains:report example.com
=====> example.com domains information
       Domains app enabled:           true
       Domains app vhosts:            www.example.com example.com
       Domains global enabled:        true
       Domains global vhosts:         other-domain.com
```

```
root@server:~# dokku certs:report example.com
=====> example.com ssl information
       Ssl dir:                       /home/dokku/example.com/tls
       Ssl enabled:                   true
       Ssl hostnames:                 example.com www.example.com
       Ssl expires at:                Oct  8 18:22:26 2024 GMT
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = E5
       Ssl starts at:                 Jul 10 18:22:27 2024 GMT
       Ssl subject:                   subject=CN = www.example.com
       Ssl verified:                  verified by a certificate authority
```

### Steps to reproduce

Copy template from https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil into your app, push code. I changed the template to something like this, to make it more obvious:

```
  {{ if $.SSL_SERVER_NAME }}server_name ssl: {{ $.SSL_SERVER_NAME }}; {{ end }}
  {{ if $.NOSSL_SERVER_NAME }}server_name no ssl: {{ $.NOSSL_SERVER_NAME }}; {{ end }}
```

This resulted in the generated template in `/home/dokku/example.com/nginx.conf` to look like this:

```
server {
  listen      [::]:443 ssl http2;
  listen      443 ssl http2;

  server_name no ssl: www.example.com example.com;
  access_log  /var/log/nginx/example.com-access.log;
  error_log   /var/log/nginx/example.com-error.log;
  underscores_in_headers off;
```

### dokku report $APP_NAME

```
ubuntu@notmyhostname:~$ dokku report notmyhostna.me
-----> uname: Linux notmyhostname 5.15.0-113-generic #123-Ubuntu SMP Mon Jun 10 08:16:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                      total        used        free      shared  buff/cache   available
       Mem:           31991         620         535           2       30835       30908
       Swap:           1535           1        1534
-----> disk utilization:
       Filesystem      Size  Used Avail Use% Mounted on
       /dev/md2        1.8T  640G  1.1T  37% /
       /dev/md1        988M  134M  787M  15% /boot
-----> disk inode utilization:
       Filesystem     Inodes IUsed IFree IUse% Mounted on
       /dev/md2         117M  455K  116M    1% /
       /dev/md1          64K   596   64K    1% /boot
-----> docker version:
       Client: Docker Engine - Community
        Version:           27.0.3
        API version:       1.46
        Go version:        go1.21.11
        Git commit:        7d4bcd8
        Built:             Sat Jun 29 00:02:33 2024
        OS/Arch:           linux/amd64
        Context:           default

       Server: Docker Engine - Community
        Engine:
         Version:          27.0.3
         API version:      1.46 (minimum version 1.24)
         Go version:       go1.21.11
         Git commit:       662f78c
         Built:            Sat Jun 29 00:02:33 2024
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.7.18
         GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
        runc:
         Version:          1.7.18
         GitCommit:        v1.1.13-0-g58aa920
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client: Docker Engine - Community
        Version:    27.0.3
        Context:    default
        Debug Mode: true
        Plugins:
         buildx: Docker Buildx (Docker Inc.)
           Version:  v0.15.1
           Path:     /usr/libexec/docker/cli-plugins/docker-buildx
         compose: Docker Compose (Docker Inc.)
           Version:  v2.28.1
           Path:     /usr/libexec/docker/cli-plugins/docker-compose

       Server:
        Containers: 7
         Running: 6
         Paused: 0
         Stopped: 1
        Images: 51
        Server Version: 27.0.3
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Using metacopy: false
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: systemd
        Cgroup Version: 2
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
        runc version: v1.1.13-0-g58aa920
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: builtin
         cgroupns
        Kernel Version: 5.15.0-113-generic
        Operating System: Ubuntu 22.04.4 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 8
        Total Memory: 31.24GiB
        Name: notmyhostname
        ID: 652aee41-5202-4345-a806-d20b9873459b
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
         File Descriptors: 60
         Goroutines: 65
         System Time: 2024-07-12T10:47:45.065422075Z
         EventsListeners: 0
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> herokuish version:
       herokuish: v0.9.2
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v272
         heroku-buildpack-nodejs    v254
         heroku-buildpack-clojure   v91
         heroku-buildpack-python    v252
         heroku-buildpack-java      v73
         heroku-buildpack-gradle    v39
         heroku-buildpack-scala     v98
         heroku-buildpack-play      v26
         heroku-buildpack-php       v253
         heroku-buildpack-go        v192
         heroku-buildpack-nginx     v25
         buildpack-null             v3
-----> dokku version: dokku version 0.34.6
-----> dokku-event-listener version: v0.17.0
-----> dokku-update version: dokku-update v0.9.4
-----> docker-container-healthchecker version: v0.11.0
-----> docker-image-labeler version: v0.8.0
-----> git version: git version 2.34.1
-----> lambda-builder version:        v0.8.0
-----> netrc version: v0.10.0
 !     pack binary is not available
-----> plugn version: plugn: v0.16.0
-----> sigil version: v0.11.0
-----> sshcommand version: sshcommand v0.18.0
-----> dokku plugins:
         00_dokku-standard    0.34.6 enabled    dokku core standard plugin
         20_events            0.34.6 enabled    dokku core events logging plugin
         app-json             0.34.6 enabled    dokku core app-json plugin
         apps                 0.34.6 enabled    dokku core apps plugin
         builder              0.34.6 enabled    dokku core builder plugin
         builder-dockerfile   0.34.6 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.34.6 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.34.6 enabled    dokku core builder-lambda plugin
         builder-nixpacks     0.34.6 enabled    dokku core builder-nixpacks plugin
         builder-null         0.34.6 enabled    dokku core builder-null plugin
         builder-pack         0.34.6 enabled    dokku core builder-pack plugin
         buildpacks           0.34.6 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.34.6 enabled    dokku core caddy-vhosts plugin
         certs                0.34.6 enabled    dokku core certificate management plugin
         checks               0.34.6 enabled    dokku core checks plugin
         common               0.34.6 enabled    dokku core common plugin
         config               0.34.6 enabled    dokku core config plugin
         cron                 0.34.6 enabled    dokku core cron plugin
         docker-options       0.34.6 enabled    dokku core docker-options plugin
         domains              0.34.6 enabled    dokku core domains plugin
         enter                0.34.6 enabled    dokku core enter plugin
         git                  0.34.6 enabled    dokku core git plugin
         haproxy-vhosts       0.34.6 enabled    dokku core haproxy-vhosts plugin
         letsencrypt          0.20.4 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.34.6 enabled    dokku core logs plugin
         mongo                1.36.11 enabled    dokku mongo service plugin
         mysql                1.40.0 enabled    dokku mysql service plugin
         network              0.34.6 enabled    dokku core network plugin
         nginx-vhosts         0.34.6 enabled    dokku core nginx-vhosts plugin
         openresty-vhosts     0.34.6 enabled    dokku core openresty-vhosts plugin
         plugin               0.34.6 enabled    dokku core plugin plugin
         ports                0.34.6 enabled    dokku core ports plugin
         postgres             1.37.0 enabled    dokku postgres service plugin
         proxy                0.34.6 enabled    dokku core proxy plugin
         ps                   0.34.6 enabled    dokku core ps plugin
         redis                1.37.5 enabled    dokku redis service plugin
         registry             0.34.6 enabled    dokku core registry plugin
         repo                 0.34.6 enabled    dokku core repo plugin
         resource             0.34.6 enabled    dokku core resource plugin
         run                  0.34.6 enabled    dokku core run plugin
         scheduler            0.34.6 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.34.6 enabled    dokku core scheduler-docker-local plugin
         scheduler-k3s        0.34.6 enabled    dokku core scheduler-k3s plugin
         scheduler-null       0.34.6 enabled    dokku core scheduler-null plugin
         shell                0.34.6 enabled    dokku core shell plugin
         ssh-keys             0.34.6 enabled    dokku core ssh-keys plugin
         storage              0.34.6 enabled    dokku core storage plugin
         trace                0.34.6 enabled    dokku core trace plugin
         traefik-vhosts       0.34.6 enabled    dokku core traefik-vhosts plugin
=====> notmyhostna.me app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:
=====> notmyhostna.me app information
       App created at:                1720635949
       App deploy source:             git-push
       App deploy source metadata:    81c36cbb092b7f39533f43de60d15c158fb9588e
       App dir:                       /home/dokku/notmyhostna.me
       App locked:                    false
=====> notmyhostna.me builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:
       Builder global build dir:
       Builder global selected:
       Builder selected:
=====> notmyhostna.me builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path:
=====> notmyhostna.me builder-herokuish information
       Builder herokuish computed allowed: true
       Builder herokuish global allowed: true
       Builder herokuish allowed:
=====> notmyhostna.me builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml
       Builder lambda global lambdayml path: lambda.yml
       Builder lambda lambdayml path:
=====> notmyhostna.me builder-nixpacks information
       Builder nixpacks computed nixpackstoml path: nixpacks.toml
       Builder nixpacks global nixpackstoml path: nixpacks.toml
       Builder nixpacks nixpackstoml path:
       Builder nixpacks computed no cache: false
       Builder nixpacks global no cache: false
       Builder nixpacks no cache:
=====> notmyhostna.me builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> notmyhostna.me buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-22
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
=====> notmyhostna.me caddy information
       Caddy image:                   lucaslorentz/caddy-docker-proxy:2.9
       Caddy letsencrypt email:
       Caddy letsencrypt server:      https://acme-v02.api.letsencrypt.org/directory
       Caddy log level:               ERROR
       Caddy polling interval:        5s
       Caddy tls internal:            false
=====> notmyhostna.me ssl information
       Ssl dir:                       /home/dokku/notmyhostna.me/tls
       Ssl enabled:                   true
       Ssl hostnames:                 notmyhostna.me www.notmyhostna.me
       Ssl expires at:                Oct  8 17:38:45 2024 GMT
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = E5
       Ssl starts at:                 Jul 10 17:38:46 2024 GMT
       Ssl subject:                   subject=CN = notmyhostna.me
       Ssl verified:                  verified by a certificate authority
=====> notmyhostna.me checks information
       Checks disabled list:          none
       Checks skipped list:           none
       Checks computed wait to retire: 60
       Checks global wait to retire:  60
       Checks wait to retire:
=====> notmyhostna.me docker options information
       Docker options build:
       Docker options deploy:         --restart=on-failure:10
       Docker options run:
=====> notmyhostna.me domains information
       Domains app enabled:           true
       Domains app vhosts:            notmyhostna.me www.notmyhostna.me
       Domains global enabled:        true
       Domains global vhosts:         notmyhostna.me
=====> notmyhostna.me git information
       Git deploy branch:             main
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       HEAD
       Git source image:
       Git last updated at:           1720720010
=====> notmyhostna.me haproxy information
       Haproxy image:                 byjg/easy-haproxy:4.4.0
       Haproxy letsencrypt email:
       Haproxy letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Haproxy log level:             ERROR
=====> notmyhostna.me letsencrypt information
       Letsencrypt active:            true
       Letsencrypt autorenew:         true
       Letsencrypt computed dns provider:
       Letsencrypt global dns provider:
       Letsencrypt dns provider:
       Letsencrypt computed email:    mail@notmyhostna.me
       Letsencrypt global email:      mail@notmyhostna.me
       Letsencrypt email:
       Letsencrypt expiration:        1728409125
       Letsencrypt computed graceperiod: 2592000
       Letsencrypt global graceperiod:
       Letsencrypt graceperiod:
       Letsencrypt computed lego docker args:
       Letsencrypt global lego docker args:
       Letsencrypt lego docker args:
       Letsencrypt computed server:   https://acme-v02.api.letsencrypt.org/directory
       Letsencrypt global server:
       Letsencrypt server:
=====> notmyhostna.me logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:
       Logs max size:
       Logs vector global image:      timberio/vector:0.39.0-debian
       Logs vector sink:
=====> notmyhostna.me network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:          false
       Network computed attach post create:
       Network computed attach post deploy:
       Network computed bind all interfaces: false
       Network computed initial network:
       Network computed tld:
       Network global attach post create:
       Network global attach post deploy:
       Network global bind all interfaces:   false
       Network global initial network:
       Network global tld:
       Network initial network:
       Network static web listener:
       Network tld:
       Network web listeners:                172.17.0.6:5000
=====> notmyhostna.me nginx information
       Nginx access log format:
       Nginx computed access log format:
       Nginx global access log format:
       Nginx access log path:
       Nginx computed access log path: /var/log/nginx/notmyhostna.me-access.log
       Nginx global access log path:  /var/log/nginx/notmyhostna.me-access.log
       Nginx bind address ipv4:
       Nginx computed bind address ipv4:
       Nginx global bind address ipv4:
       Nginx bind address ipv6:
       Nginx computed bind address ipv6: ::
       Nginx global bind address ipv6: ::
       Nginx client max body size:
       Nginx computed client max body size: 1m
       Nginx global client max body size: 1m
       Nginx disable custom config:
       Nginx computed disable custom config: false
       Nginx global disable custom config: false
       Nginx error log path:
       Nginx computed error log path: /var/log/nginx/notmyhostna.me-error.log
       Nginx global error log path:   /var/log/nginx/notmyhostna.me-error.log
       Nginx hsts include subdomains:
       Nginx computed hsts include subdomains: true
       Nginx global hsts include subdomains: true
       Nginx hsts max age:
       Nginx computed hsts max age:   15724800
       Nginx global hsts max age:     15724800
       Nginx hsts preload:
       Nginx computed hsts preload:   false
       Nginx global hsts preload:     false
       Nginx hsts:
       Nginx computed hsts:           true
       Nginx global hsts:             true
       Nginx last visited at:
       Nginx nginx conf sigil path:
       Nginx computed nginx conf sigil path: nginx.conf.sigil
       Nginx global nginx conf sigil path: nginx.conf.sigil
       Nginx proxy buffer size:
       Nginx computed proxy buffer size: 4k
       Nginx global proxy buffer size: 4k
       Nginx proxy buffering:
       Nginx computed proxy buffering: on
       Nginx global proxy buffering:  on
       Nginx proxy buffers:
       Nginx computed proxy buffers:  8 4k
       Nginx global proxy buffers:    8 4k
       Nginx proxy busy buffers size:
       Nginx computed proxy busy buffers size: 8k
       Nginx global proxy busy buffers size: 8k
       Nginx proxy read timeout:
       Nginx computed proxy read timeout: 60s
       Nginx global proxy read timeout: 60s
       Nginx underscore in headers:
       Nginx computed underscore in headers: off
       Nginx global underscore in headers: off
       Nginx x forwarded for value:
       Nginx computed x forwarded for value: $remote_addr
       Nginx global x forwarded for value: $remote_addr
       Nginx x forwarded port value:
       Nginx computed x forwarded port value: $server_port
       Nginx global x forwarded port value: $server_port
       Nginx x forwarded proto value:
       Nginx computed x forwarded proto value: $scheme
       Nginx global x forwarded proto value: $scheme
       Nginx x forwarded ssl:
       Nginx computed x forwarded ssl:
       Nginx global x forwarded ssl:
=====> notmyhostna.me openresty information
       Openresty access log format:
       Openresty access log path:     /var/log/nginx/notmyhostna.me-access.log
       Openresty allowed letsencrypt domains func base64: cmV0dXJuIHRydWUK
       Openresty bind address ipv4:
       Openresty bind address ipv6:   ::
       Openresty client max body size:
       Openresty error log path:      /var/log/nginx/notmyhostna.me-error.log
       Openresty global hsts:         true
       Openresty computed hsts:       true
       Openresty hsts:
       Openresty hsts include subdomains: true
       Openresty hsts max age:        15724800
       Openresty hsts preload:        false
       Openresty image:               dokku/openresty-docker-proxy:0.8.0
       Openresty letsencrypt email:
       Openresty letsencrypt server:  https://acme-v02.api.letsencrypt.org/directory
       Openresty proxy buffer size:   4k
       Openresty proxy buffering:     on
       Openresty proxy buffers:       8 4k
       Openresty proxy busy buffers size: 8k
       Openresty proxy read timeout:  60s
       Openresty underscore in headers: off
       Openresty x forwarded for value: $remote_addr
       Openresty x forwarded port value: $server_port
       Openresty x forwarded proto value: $scheme
       Openresty x forwarded ssl:
=====> notmyhostna.me ports information
       Ports map:
       Ports map detected:            http:80:5000 https:443:5000
=====> notmyhostna.me proxy information
       Proxy computed type:           nginx
       Proxy enabled:                 true
       Proxy global type:             nginx
       Proxy type:
=====> notmyhostna.me ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: 032c7e26e2a)
=====> notmyhostna.me registry information
       Registry computed image repo:        dokku/notmyhostna.me
       Registry computed push on release:   false
       Registry computed server:
       Registry global image repo template:
       Registry global push on release:
       Registry global server:
       Registry image repo:
       Registry push extra tags:
       Registry push on release:
       Registry server:
       Registry tag version:
=====> notmyhostna.me resource information
=====> notmyhostna.me scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:
=====> notmyhostna.me scheduler-docker-local information
       Scheduler docker local init process: true
       Scheduler docker local parallel schedule count:
=====> notmyhostna.me scheduler-k3s information
       Scheduler k3s computed deploy timeout:       300s
       Scheduler k3s computed image pull secrets:
       Scheduler k3s computed letsencrypt server:   prod
       Scheduler k3s computed namespace:            default
       Scheduler k3s computed rollback on failure:  false
       Scheduler k3s deploy timeout:
       Scheduler k3s global deploy timeout:         300s
       Scheduler k3s global image pull secrets:
       Scheduler k3s global ingress class:          nginx
       Scheduler k3s global kube context:
       Scheduler k3s global kubeconfig path:        /etc/rancher/k3s/k3s.yaml
       Scheduler k3s global letsencrypt email prod:
       Scheduler k3s global letsencrypt email stag:
       Scheduler k3s global letsencrypt server:     prod
       Scheduler k3s global namespace:              default
       Scheduler k3s global network interface:      eth0
       Scheduler k3s global rollback on failure:    false
       Scheduler k3s image pull secrets:
       Scheduler k3s letsencrypt server:
       Scheduler k3s namespace:
       Scheduler k3s rollback on failure:
=====> notmyhostna.me storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:
=====> notmyhostna.me traefik information
       Traefik api enabled:           false
       Traefik api vhost:             traefik.dokku.me
       Traefik basic auth password:
       Traefik basic auth username:
       Traefik dashboard enabled:     false
       Traefik image:                 traefik:2.11.2
       Traefik letsencrypt email:
       Traefik letsencrypt server:    https://acme-v02.api.letsencrypt.org/directory
       Traefik log level:             ERROR
       Traefik http entry point:      http
       Traefik https entry point:     https
```

### Additional information

```
ubuntu@notmyhostname:~$ dokku ports:report notmyhostna.me
=====> notmyhostna.me ports information
       Ports map:
       Ports map detected:            http:80:5000 https:443:5000
```

**Comment by josegonzalez** [comment] 2024-07-11 23:40
Please fill out the missing information requested in the issue template. Since I'm unable to replicate this, it would be useful to see the report and trace output so I can investigate further.

**Comment by dewey** [comment] 2024-07-12 10:59
Hey, sorry about that! I added the `dokku report` output now, but I'm unsure which command I should run to get the tracing information as I just push and then look at the nginx config to see the behavior.

I'm using https://github.com/dokku/heroku-buildpack-nginx, so my "notmyhostna.me" app just has an index.html, an empty .static file and the [nginx.conf.sigil](https://github.com/user-attachments/files/16192689/nginx.conf.sigil.zip) I mentioned above.

**Comment by josegonzalez** [comment] 2024-07-12 15:21
if you turn on trace mode via `dokku trace:on`, any subsequent dokku commands will have trace mode enabled.

**Comment by dewey** [comment] 2024-07-12 15:27
I ran `dokku ps:rebuild notmyhostna.me` after enabling tracing, let me know if that gives you all the info you need.

[dokku-rebuild-trace.txt.zip](https://github.com/user-attachments/files/16196163/dokku-rebuild-trace.txt.zip)

**Comment by josegonzalez** [comment] 2024-09-24 00:54
This is by design. The SSL_SERVER_NAMES is the _extra_ names that are included in your certificates. It covers everything not already in the other variable. The change was introduced in #2519 8 years ago.

I'm going to close this for now, but feel free to comment if this is breaking a specific workflow for you and I can debug further.

**Closed by josegonzalez** 2024-09-24 00:54 UTC
Labels: type: bug, needs: investigation, plugin: nginx
