### ISSUE TITLE
Rebooting Ubuntu 16.04 VM on AWS Lightsail instance causes Dokku to re-route sub-domains to the wrong app...

### ISSUE THREAD

**Issue by emveeoh** [dokku/dokku#2597] opened 2017-02-06 18:09 UTC
**Description of problem:**
AWS Lightsail Ubuntu 16.04 VM created (512 MB RAM, 1 vCPU, 20 GB SSD). Applied updates/upgrades. Added swap.img due to low ram. Installed Dokku using (curl | bash) bootstrap.sh script.

I am running 4 Node JS apps (websites) on one Dokku instance. 

Pushed the following 4 apps:
```
GLOBAL: emveeoh.com
emveeoh.com, www.emveeoh.com, emveeoh.emveeoh.com --> emveeoh
paypie.emveeoh.com --> paypie
saber.emveeoh.com --> saber
spiceace.emveeoh.com --> spiceace

LOGIN/PASSWORD: mvo/(leave empty)

emveeoh.com = static IP:  34.197.36.7
```

All apps work perfectly until I reboot the VM. When it comes alive again, The routing has changed and is no longer working properly. Sub-domains are being routed to the wrong app.

```
GLOBAL: emveeoh.com
emveeoh.com, www.emveeoh.com, emveeoh.emveeoh.com --> emveeoh
paypie.emveeoh.com --> saber
saber.emveeoh.com --> spiceace
spiceace.emveeoh.com --> paypie
```
**Additional notes:**
- I can fix each app by re-uploading it (git push origin master). However, it will change again after rebooting the VM.

- I currently have dokku-letsencrypt plugin installed. However, the routing problem occurs even with no plugins installed. So, it's probably not dokku-letsencrypt at fault.

**Dokku Report:**
```
ubuntu@ip-172-26-11-214:~$ dokku report
-----> uname: Linux ip-172-26-11-214 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
              total        used        free      shared  buff/cache   available
Mem:            486         191          23           3         271         255
Swap:           999           3         996
-----> docker version: 
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
-----> docker daemon info: 
Containers: 34
 Running: 4
 Paused: 0
 Stopped: 30
Images: 46
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 119
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 486.7 MiB
Name: ip-172-26-11-214
ID: 67LI:UDK2:IRC5:Q42W:UYHN:PG2G:CFAK:QKVK:B6U5:NBRV:BUR6:K77A
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
-----> sigil version: 0.4.0
-----> herokuish version: 
herokuish: 0.3.24
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v150
  heroku-buildpack-nodejs    v93
  heroku-buildpack-clojure   v75
  heroku-buildpack-python    v97
  heroku-buildpack-java      v48
  heroku-buildpack-gradle    v19
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v72
  heroku-buildpack-play      v26
  heroku-buildpack-php       v117
  heroku-buildpack-go        v54
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
-----> dokku version: 0.8.0
-----> dokku plugins: 
plugn: 0.2.2
  00_dokku-standard    0.8.0 enabled    dokku core standard plugin
  20_events            0.8.0 enabled    dokku core events logging plugin
  apps                 0.8.0 enabled    dokku core apps plugin
  build-env            0.8.0 enabled    dokku core build-env plugin
  certs                0.8.0 enabled    dokku core certificate management plugin
  checks               0.8.0 enabled    dokku core checks plugin
  common               0.8.0 enabled    dokku core common plugin
  config               0.8.0 enabled    dokku core config plugin
  docker-options       0.8.0 enabled    dokku core docker-options plugin
  domains              0.8.0 enabled    dokku core domains plugin
  enter                0.8.0 enabled    dokku core enter plugin
  git                  0.8.0 enabled    dokku core git plugin
  letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.8.0 enabled    dokku core logs plugin
  named-containers     0.8.0 enabled    dokku core named containers plugin
  nginx-vhosts         0.8.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.8.0 enabled    dokku core plugin plugin
  proxy                0.8.0 enabled    dokku core proxy plugin
  ps                   0.8.0 enabled    dokku core ps plugin
  repo                 0.8.0 enabled    dokku core repo plugin
  shell                0.8.0 enabled    dokku core shell plugin
  ssh-keys             0.8.0 enabled    dokku core ssh-keys plugin
  storage              0.8.0 enabled    dokku core storage plugin
  tags                 0.8.0 enabled    dokku core tags plugin
  tar                  0.8.0 enabled    dokku core tar plugin

```

**Comment by josegonzalez** [comment] 2017-02-06 18:11
Can you gist the contents of each apps' `nginx.conf` and the output of `docker inspect` for each of the containers?

**Comment by emveeoh** [comment] 2017-02-06 18:33
https://gist.github.com/emveeoh/64d4d47f2e01ecc6d5d07c8ca29faa83

**Comment by josegonzalez** [comment] 2017-02-06 18:34
Can you also gist the output of `docker inspect` for each of the containers?

**Comment by emveeoh** [comment] 2017-02-06 18:42
Not sure how to do the `docker inspect`... Can you provide instructions please?

**Comment by emveeoh** [comment] 2017-02-06 18:45
Sorry... I figured it out. Adding the docker inspect output to gist shortly...

**Comment by emveeoh** [comment] 2017-02-06 18:53
@josegonzalez  Sorry for the delay... Still learning Docker commands... lol...  The gist has been updated with the `docker inspect` output you requested. I really appreciate the help Jose!

**Comment by emveeoh** [comment] 2017-02-06 21:27
@josegonzalez 

I just did another re-boot of the VM and the app mappings have changed again.

Now, the apps map to the following sub-domains:

**Comment by josegonzalez** [comment] 2017-02-07 03:33
Pretty sure this is a manifestation of the same reboot issue. Implementing #2403 would fix this issue. Closing as all the work is outlined there in case there is enterprising individual out there who would like to work on it.

**Closed by josegonzalez** 2017-02-07 03:33 UTC
Labels: needs: more info

**Comment by emveeoh** [comment] 2017-02-07 04:55
@josegonzalez 

This would seem to make Dokku unusable for anyone needing to host multiple apps on a single VM.
Until the networking is fixed, Dokku can only reliably host a single app per VM?

**Comment by josegonzalez** [comment] 2017-02-07 04:59
There isn't any bug here at all. Dokku works as intended, except in the case where docker broke how they assign IPs to containers on boot. They previously restored everything about the container and at some point decided "fuck it, you all get a new ip". The bug is in Docker, and we need to work around it.

If you'd like to contribute - either via time or money - perhaps we can clear the hurdle of Dokku not working for this specific case?

**Comment by emveeoh** [comment] 2017-02-07 05:08
@josegonzalez  Thank you very much for helping to identify the issue and for all of your hard work on the Dokku project. The best solution is to just re-push the apps after each VM reboot.

**Comment by josegonzalez** [comment] 2017-02-07 05:09
Heh I thought so.

You can also swap `ps:restore` for `ps:rebuild` in the `dokku-redeploy` service (in `/etc/systemd/system/dokku-redeploy.service` for systemd or `/etc/init/dokku-redeploy.conf` for upstart). That'll trigger a rebuild of all your apps, and go through the normal setup of nginx confs etc.

**Comment by emveeoh** [comment] 2017-02-07 05:12
Thank you sir! I will implement that advice asap.

**Comment by emveeoh** [comment] 2017-02-07 05:28
Also... Even though I'm not competent enough to help with coding the solution and don't have a lot of money, I am trying to help the Dokku community by posting this AWS LightSail Dokku tutorial...  So, please know that your efforts are inspiring myself and others.

https://github.com/emveeoh/dokku-on-aws-lightsail-tutorial

**Comment by josegonzalez** [comment] 2017-02-07 05:32
You could instead contribute a tutorial to our [official blog](https://github.com/dokku/dokku.github.io), where we will keep it up to date, as opposed to having yet another outdated Dokku tutorial (which ends up being an issue for people who end up installing old stuff and wondering why our docs don't apply to them).
