### ISSUE TITLE
Dokku containers stopped after non-graceful server restart

### ISSUE THREAD

**Issue by NDuggan** [dokku/dokku#2536] opened 2016-12-20 13:48 UTC
**Description of problem:**
*As a side-note, I've tried reproducing this problem by manually running `reboot` but everything comes back up fine with that method.*

After a power-cut and UPS failure the server rebooted and in the logs I can see that `dokku ps:restore` was triggered, but all of the containers didn't come back up.

The weirdest part is that you can see "production web" is running but when accessing production via the browser the app returns a 502 bad gateway. But when accessing staging, the app loads fine (even though "staging web" is stopped); to top it off because the "staging" domain seems to be using the production container, the connected database is that of the production app.

I only have one redirect setup for production which takes the `www` to `non-www`; staging doesn't have any redirects setup.

```bash
$ dokku ps:scale production
-----> Scaling for production
-----> proctype           qty
-----> --------           ---
-----> web                4
```

```bash
$ dokku ps:scale staging
-----> Scaling for staging
-----> proctype           qty
-----> --------           ---
-----> web                1
-----> worker             1
```

```bash
$ dokku ls
-----> App Name           Container Type            Container Id              Status
production                web                       703abf45b9a7              running
production                web                       58b4f7db1bf9              stopped
production                web                       33d904054d31              stopped
production                web                       e57ee335a626              stopped
staging                   web                       1292726d087f              stopped
staging                   worker                    aa17c5da1418              running
```

```bash
$ docker ps
CONTAINER ID        IMAGE                     COMMAND             CREATED             STATUS              PORTS               NAMES
aa17c5da1418        dokku/staging:latest      "/start worker"     28 hours ago        Up About an hour                        staging.worker.1
703abf45b9a7        dokku/production:latest   "/start web"        4 days ago          Up About an hour                        production.web.1
```

**Output of the following commands**

- `uname -a`:
```
Linux coyote 4.2.0-30-generic #36~14.04.1-Ubuntu SMP Fri Feb 26 18:49:23 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

- `free -m`:
```
             total       used       free     shared    buffers     cached
Mem:         15791       1684      14107          2        136        341
-/+ buffers/cache:       1206      14585
Swap:        16123          0      16123
```

- `docker version`:
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64
```

- `docker -D info`:
```
Containers: 33
 Running: 2
 Paused: 0
 Stopped: 31
Images: 61
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 132
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.2.0-30-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 15.42 GiB
Name: coyote
ID: UYTQ:UICQ:TQKL:OZ53:P7L2:ABLA:XIZ4:H6WU:VVYP:LPIE:FQ5E:SK65
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

- `sigil -v`:
```
0.4.0
```

- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
```
herokuish: 0.3.19
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v146
  heroku-buildpack-nodejs    v91
  heroku-buildpack-clojure   v75
  heroku-buildpack-python    v82
  heroku-buildpack-java      v46
  heroku-buildpack-gradle    v18
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v72
  heroku-buildpack-play      v26
  heroku-buildpack-php       v110
  heroku-buildpack-go        v44
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v6
  emberjs.tgz                latest
```

- `dokku version`:
```
0.7.2
```

- `dokku plugin`:
```
plugn: 0.2.2
  00_dokku-standard    0.7.2 enabled    dokku core standard plugin
  20_events            0.7.2 enabled    dokku core events logging plugin
  apps                 0.7.2 enabled    dokku core apps plugin
  build-env            0.7.2 enabled    dokku core build-env plugin
  certs                0.7.2 enabled    dokku core certificate management plugin
  checks               0.7.2 enabled    dokku core checks plugin
  common               0.7.2 enabled    dokku core common plugin
  config               0.7.2 enabled    dokku core config plugin
  docker-options       0.7.2 enabled    dokku core docker-options plugin
  domains              0.7.2 enabled    dokku core domains plugin
  enter                0.7.2 enabled    dokku core enter plugin
  git                  0.7.2 enabled    dokku core git plugin
  letsencrypt          0.8.6 enabled    Automated installation of let's encrypt TLS certificates
  logs                 0.7.2 enabled    dokku core logs plugin
  maintenance          0.4.0 enabled    Maintenance mode for apps
  named-containers     0.7.2 enabled    dokku core named containers plugin
  nginx-vhosts         0.7.2 enabled    dokku core nginx-vhosts plugin
  plugin               0.7.2 enabled    dokku core plugin plugin
  proxy                0.7.2 enabled    dokku core proxy plugin
  ps                   0.7.2 enabled    dokku core ps plugin
  redirect             0.4.0 enabled    Simple redirects for apps
  repo                 0.7.2 enabled    dokku core repo plugin
  shell                0.7.2 enabled    dokku core shell plugin
  slack                0.4.0 enabled    Slack notifier on deploy
  ssh-keys             0.7.2 enabled    dokku core ssh-keys plugin
  storage              0.7.2 enabled    dokku core storage plugin
  tags                 0.7.2 enabled    dokku core tags plugin
  tar                  0.7.2 enabled    dokku core tar plugin
```

Environment details (AWS, VirtualBox, physical, etc.): **physical**

How was Dokku installed?:
```
wget https://raw.githubusercontent.com/dokku/dokku/v0.7.2/bootstrap.sh  
sudo DOKKU_TAG=v0.7.2 bash bootstrap.sh  
```

How reproducible:
Only when the system shuts down unexpectedly. It's happened twice to me as we are currently moving the server from a bad location, but definitely not just a one-off.

Additional info:
To resolve it I just restarted all containers.
```
dokku ps:restartall
```

**Comment by josegonzalez** [comment] 2016-12-20 16:41
Related issue: https://github.com/dokku/dokku/issues/2403

I think sometimes docker assigns a new ip instead of restoring existing ones, and our `ps:restore` isn't accounting for that.

**Comment by joshmanders** [comment] 2016-12-20 17:15
Yup, I just ran into this today myself.

**Comment by josegonzalez** [comment] 2016-12-20 17:16
@joshmanders the issue is pretty well-scoped out if you (or anyone really) wants to work on it.

**Comment by joshmanders** [comment] 2016-12-20 17:16
I'll take a look at it this week and see if I can fix it.

**Comment by andyjeffries** [comment] 2016-12-29 17:47
Don't want to just add a me too, but I got bit by this too today. I've added the ps:restartall to /etc/rc.local just before the exit 0 line for now to work around it.

**Comment by josegonzalez** [comment] 2017-01-09 07:06
Closing this as the solution described in #2403 will take care of this, and there isn't any sense imo in keeping duplicate issues open.

**Closed by josegonzalez** 2017-01-09 07:06 UTC
Labels: type: bug
