### ISSUE TITLE
proxy:ports-add doesn't work correctly

### ISSUE THREAD

**Issue by agalisteo** [dokku/dokku#2888] opened 2017-08-28 12:23 UTC
Description of problem:
Creating a port mapping, the nginx configuration file is not generated correctly

Steps to Reproduce: 
```
dokku proxy:ports-add example http:9000:8080
```

Actual Results:
```
cat /home/dokku/example/nginx.conf
```
```
upstream example-8080 {

  server 172.17.0.14:5000;
}
```
Expected Results:
```
upstream example-8080 {

  server 172.17.0.14:8080;
}
```

Additional info:
Adding a port mapping like
```
dokku proxy:ports-add example http:9000:8080
```
the nginx configuration dont map the container port inside uptstream directive.

- `uname -a`: Linux s1 4.11.0-14-generic #20~16.04.1-Ubuntu SMP Wed Aug 9 09:06:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- `free -m`:              total        used        free      shared  buff/cache   available
Mem:          32070        5075        2210         468       24785       24535
Swap:          4093           1        4092
- `docker version`:Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64
Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:50:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
- `docker -D info`:
Containers: 60
 Running: 20
 Paused: 0
 Stopped: 40
Images: 339
Server Version: 17.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 426
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.11.0-14-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.32GiB
Name: s1
ID: 2WOH:EB6W:P36Z:3ATO:QATT:RECZ:JLWM:HYMC:PEIM:OFS5:T5PP:MPNU
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by josegonzalez** [comment] 2017-08-28 14:06
Is this a Dockerfile-based app?

**Comment by agalisteo** [comment] 2017-08-28 18:41
@josegonzalez No, is a puma server (websockets actioncable) launched by Procfile

**Comment by josegonzalez** [comment] 2017-08-28 18:45
If you are using buildpacks, you should just respect the $PORT environment variable. Managing ports is an advanced feature, mostly meant for usage with Dockerfile deploys.

Regardless, this specific "bug" of not respecting the port is caused by a weird interaction between setups like yours and a "fix" in the default template that is fixed in master.

**Closed by josegonzalez** 2017-08-28 18:45 UTC
Labels: type: bug
