### ISSUE TITLE
running "vagrant up dokku-windows" exits early

### ISSUE THREAD

**Issue by ZiadSalah** [dokku/dokku#2759] opened 2017-05-09 08:19 UTC
On a windows 10 machine:
Actual Results:
After running `vagrant up dokku-windows` accessing dokku.me shows me the nginx welcome page instead of the dokku admin page.
 
Expected Results:
Vagrant vm is setup correctly, exits cleanly, and I can access the admin page by navigating to the vm ip address

Additional info:

The output from the vagrant command ends with the following snippet:

```
==> dokku-windows: -----> Migrating zero downtime env variables to 0.5.x. The following variables have been deprecated
==> dokku-windows: =====> DOKKU_SKIP_ALL_CHECKS DOKKU_SKIP_DEFAULT_CHECKS
==> dokku-windows: =====> Please use dokku checks:[disable|enable] <app> to control zero downtime functionality
==> dokku-windows: =====> Migration complete
==> dokku-windows: =====>
==> dokku-windows: -----> Migrating zero downtime env variables to 0.6.x. The following variables will be migrated
==> dokku-windows: =====> DOKKU_CHECKS_ENABLED -> DOKKU_CHECKS_SKIPPED
==> dokku-windows: =====> Migration complete
==> dokku-windows: =====>
==> dokku-windows: Adding user dokku to group adm
==> dokku-windows: start: Job is already running: nginx
```

Note worthy, the last line about nginx is in red in the terminal.

Running `echo $?` immediately after outputs 0

- `uname -a`: CYGWIN_NT-10.0 admin 2.6.1(0.305/5/3) 2016-12-16 11:55 x86_64 Cygwin

**Comment by josegonzalez** [comment] 2017-05-11 05:16
Seems like nginx being started is the issue here. Can you modify line 68 of the vm to the following and bring up a new vm?

```
    vm.vm.provision :shell, :inline => "cd /vagrant/ && export DOKKU_BRANCH=`git symbolic-ref -q --short HEAD 2>/dev/null` && export DOKKU_TAG=`git describe --tags --exact-match 2>/dev/null` && TRACE=1 && cd /root/ && cp /vagrant/bootstrap.sh ./ && bash bootstrap.sh"
```

**Comment by ZiadSalah** [comment] 2017-05-11 22:20
Hi, here's the gist:
https://gist.github.com/ZiadSalah/b3a41236bc10a732784165409d753e42

**Comment by josegonzalez** [comment] 2017-05-11 22:22
Err try this instead:

```
vm.vm.provision :shell, :inline => "cd /vagrant/ && export DOKKU_BRANCH=`git symbolic-ref -q --short HEAD 2>/dev/null` && export DOKKU_TAG=`git describe --tags --exact-match 2>/dev/null` && export DOKKU_TRACE=1 && export TRACE=1 && cd /root/ && cp /vagrant/bootstrap.sh ./ && bash bootstrap.sh"
```

**Comment by ZiadSalah** [comment] 2017-05-11 22:47
Copied from a few lines before the first mention of nginx:
https://gist.github.com/ZiadSalah/5c757c474dd3239d18db6c9d48e2a469

Let me know if you need me to copy from an earlier point.

**Comment by ZiadSalah** [comment] 2017-05-29 22:43
If anyone runs into this issue and doesn't know how to proceed, my temporary workaround has been:
1) ssh into the vagrant vm `vagrant ssh dokku-windows`
2) `sudo -i` and then in /root/dokku run `make dokku-installer`

**Comment by josegonzalez** [comment] 2018-02-13 08:14
I'm going to close this. While local development on windows would be nice - since we might get more contributors - I do not have access to a windows machine to debug this issue and there hasn't been any attempt by external users to find the root cause.

**Closed by josegonzalez** 2018-02-13 08:14 UTC
Labels: difficulty: easy, needs: more info, type: bug
