### ISSUE TITLE
dokku_client complains on storage:mount

### ISSUE THREAD

**Issue by MarcDiethelm** [dokku/dokku#2449] opened 2016-10-06 13:51 UTC
Description of problem:

On local machine with `alias dokku=path/to/dokku_client`:

```shell
$ dokku storage:mount cloud /etc/dokku/vendor-app/config:/var/www/html/config
storage:mount requires an app and a two paths divided by colon.
```

Running the command on the server works normally.

- server `uname -a`: Linux hostname 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- local `uname -a`: Darwin hostname 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
- `dokku version`: 0.7.2
- Output of failing Dokku commands after running `dokku trace on`:  
Interesting, this also fails!

```shell
$ dokku trace on
Valid trace options are [on/off]
```

- Environment details: DO dokku app install, upgraded with apt-get
- Local bash version: 4.4.0
- Local `ssh -V`: OpenSSH_6.9p1, LibreSSL 2.1.8

**Comment by josegonzalez** [comment] 2016-10-06 14:20
More or less a dupe of #2368 :(

**Closed by josegonzalez** 2016-10-06 14:20 UTC
