### ISSUE TITLE
HTTP NGINX error 500 after deploy (for 1-2 minute)

### ISSUE THREAD

**Issue by FilipLukac** [dokku/dokku#3620] opened 2019-07-22 07:48 UTC
# Description of your problem
I got an error from nginx everytime I do build (http-500 error ) for ~1minute. After 1 minute I refresh application and everything works as expected

I'm using these buildpacks:

```
https://github.com/heroku/heroku-buildpack-php
https://github.com/heroku/heroku-buildpack-nodejs
```

### How reproducible
I'm not pretty sure how to reproduce, we migrated Dokku from DigitalOcean to AWS ec2 (same distribution Ubuntu 18)

### Steps to Reproduce

1. Build a PHP application
2. Deploy php application
3. Get nginx error 500 for a 1 minute

### `dokku report APP_NAME` output
```
-----> uname: Linux ip-172-31-42-156 4.15.0-1043-aws #45-Ubuntu SMP Mon Jun 24 14:07:03 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:          16039        1112       12023          40        2904       14559
       Swap:             0           0           0
-----> docker version:
       Client:
        Version:           18.09.6
        API version:       1.39
        Go version:        go1.10.8
        Git commit:        481bc77
        Built:             Sat May  4 02:35:57 2019
        OS/Arch:           linux/amd64
        Experimental:      false

       Server: Docker Engine - Community
        Engine:
         Version:          18.09.6
         API version:      1.39 (minimum version 1.12)
         Go version:       go1.10.8
         Git commit:       481bc77
         Built:            Sat May  4 01:59:36 2019
         OS/Arch:          linux/amd64
         Experimental:     false
-----> docker daemon info:
       Containers: 22
        Running: 2
        Paused: 0
        Stopped: 20
       Images: 21
       Server Version: 18.09.6
       Storage Driver: overlay2
        Backing Filesystem: extfs
        Supports d_type: true
        Native Overlay Diff: true
       Logging Driver: json-file
WARNING: No swap limit support
       Cgroup Driver: cgroupfs
       Plugins:
        Volume: local
        Network: bridge host macvlan null overlay
        Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
       Swarm: inactive
       Runtimes: runc
       Default Runtime: runc
       Init Binary: docker-init
       containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
       runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
       init version: fec3683
       Security Options:
        apparmor
        seccomp
         Profile: default
       Kernel Version: 4.15.0-1043-aws
       Operating System: Ubuntu 18.04.2 LTS
       OSType: linux
       Architecture: x86_64
       CPUs: 4
       Total Memory: 15.66GiB
       Name: ip-172-31-42-156
       ID: FBEC:VLFD:C42H:4UUA:V6D4:6DXY:HL45:W7KJ:4XAL:PTAS:RUUY:WI4Z
       Docker Root Dir: /var/lib/docker
       Debug Mode (client): true
       Debug Mode (server): false
       Registry: https://index.docker.io/v1/
       Labels:
       Experimental: false
       Insecure Registries:
        127.0.0.0/8
       Live Restore Enabled: false
       Product License: Community Engine

-----> sigil version: 0.4.0
-----> herokuish version:
       herokuish: 0.5.0
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v200
         heroku-buildpack-nodejs    v142
         heroku-buildpack-clojure   v83
         heroku-buildpack-python    v149
         heroku-buildpack-java      v63
         heroku-buildpack-gradle    v28
         heroku-buildpack-scala     v84
         heroku-buildpack-play      v26
         heroku-buildpack-php       v151
         heroku-buildpack-go        v104
         buildpack-nginx            v10
-----> dokku version: dokku version 0.17.2
-----> dokku plugins:
       plugn: 0.3.2
         00_dokku-standard    0.17.2 enabled    dokku core standard plugin
         20_events            0.17.2 enabled    dokku core events logging plugin
         app-json             0.17.2 enabled    dokku core app-json plugin
         app-predeploy-tasks  0.1.0 enabled    Run arbitrary app tasks prior to dokku's deploy phase
         apps                 0.17.2 enabled    dokku core apps plugin
         build-env            0.17.2 enabled    dokku core build-env plugin
         buildpacks           0.17.2 enabled    dokku core buildpacks plugin
         certs                0.17.2 enabled    dokku core certificate management plugin
         checks               0.17.2 enabled    dokku core checks plugin
         common               0.17.2 enabled    dokku core common plugin
         config               0.17.2 enabled    dokku core config plugin
         docker-options       0.17.2 enabled    dokku core docker-options plugin
         domains              0.17.2 enabled    dokku core domains plugin
         enter                0.17.2 enabled    dokku core enter plugin
         git                  0.17.2 enabled    dokku core git plugin
         logs                 0.17.2 enabled    dokku core logs plugin
         network              0.17.2 enabled    dokku core network plugin
         nginx-vhosts         0.17.2 enabled    dokku core nginx-vhosts plugin
         plugin               0.17.2 enabled    dokku core plugin plugin
         proxy                0.17.2 enabled    dokku core proxy plugin
         ps                   0.17.2 enabled    dokku core ps plugin
         repo                 0.17.2 enabled    dokku core repo plugin
         resource             0.17.2 enabled    dokku core resource plugin
         scheduler-docker-local 0.17.2 enabled    dokku core scheduler-docker-local plugin
         shell                0.17.2 enabled    dokku core shell plugin
         ssh-keys             0.17.2 enabled    dokku core ssh-keys plugin
         storage              0.17.2 enabled    dokku core storage plugin
         tags                 0.17.2 enabled    dokku core tags plugin
         tar                  0.17.2 enabled    dokku core tar plugin
         trace                0.17.2 enabled    dokku core trace plugin
=====> sloneek.com app information
       App dir:                       /home/dokku/sloneek.com
       Git sha:                       3888f8d7
       Deploy source:                 git
       Locked:                        true
=====> sloneek.com buildpacks information
       Buildpacks list:
CN = *.sloneek.com
error 20 at 0 depth lookup: unable to get local issuer certificate
=====> sloneek.com ssl information
       Ssl dir:                       /home/dokku/sloneek.com/tls
       Ssl enabled:                   true
       Ssl hostnames:                 *.sloneek.com sloneek.com
       Ssl expires at:                Oct  4 12:00:00 2019 GMT
       Ssl issuer:                    C = NL, O = Trust Provider B.V., OU = Domain Validated SSL, CN = Trust Provider B.V. TLS RSA CA G1
       Ssl starts at:                 Sep  4 00:00:00 2018 GMT
       Ssl subject:                   subject=CN = *.sloneek.com
       Ssl verified:                  self signed
=====> sloneek.com checks information
       Checks disabled list:          none
       Checks skipped list:           none
=====> sloneek.com docker options information
       Docker options build:
       Docker options deploy:         --restart=on-failure:10 -v /opt/dokku/sloneek.com/config:/app/app/config/local -v /opt/dokku/sloneek.com/logs:/app/log -v /opt/dokku/sloneek.com/sessions:/app/temp/sessions -v /opt/dokku/sloneek.com/uploads:/app/uploads
       Docker options run:            -v /opt/dokku/sloneek.com/config:/app/app/config/local -v /opt/dokku/sloneek.com/logs:/app/log -v /opt/dokku/sloneek.com/sessions:/app/temp/sessions -v /opt/dokku/sloneek.com/uploads:/app/uploads
=====> sloneek.com domains information
       Domains app enabled:           true
       Domains app vhosts:            sloneek.com
       Domains global enabled:        true
       Domains global vhosts:         sloneek.com
=====> sloneek.com git information
       Git rev env var:               GIT_REV
       Git deploy branch:             master
       Git global deploy branch:      master
=====> sloneek.com network information
       Network bind all interfaces:   false
       Network listeners:             172.17.0.2:5000
=====> sloneek.com proxy information
       Proxy enabled:                 true
       Proxy type:                    nginx
       Proxy port map:                http:80:5000 https:443:5000
=====> sloneek.com ps information
       Processes:                     1
       Deployed:                      true
       Running:                       true
       Restore:                       true
       Restart policy:                on-failure:10
       Ps can scale:                  true
       Status web.1:                  running    (CID: ea2a8295c7f6)
=====> sloneek.com scheduler-docker-local information
       Scheduler docker local disable chown:
=====> sloneek.com storage information
       Storage build mounts:
       Storage deploy mounts:         -v /opt/dokku/sloneek.com/config:/app/app/config/local -v /opt/dokku/sloneek.com/logs:/app/log -v /opt/dokku/sloneek.com/sessions:/app/temp/sessions -v /opt/dokku/sloneek.com/uploads:/app/uploads
       Storage run mounts:            -v /opt/dokku/sloneek.com/config:/app/app/config/local -v /opt/dokku/sloneek.com/logs:/app/log -v /opt/dokku/sloneek.com/sessions:/app/temp/sessions -v /opt/dokku/sloneek.com/uploads:/app/uploads
```

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

Amazon EC2 from `.sh` command (wget + sh)

### Additional information

Build and everything is working as expected - but we have this issue :\ I couldn't solve it

**Comment by josegonzalez** [comment] 2019-07-22 09:33
Do your app logs have anything indicating that the app is not yet ready to serve requests? Can you show the nginx error logs?

**Comment by FilipLukac** [comment] 2019-07-22 09:40
@josegonzalez nothing that indicates errors nor in access.logs

**Comment by josegonzalez** [comment] 2019-07-22 09:41
Do you have anything in front of your server, like a load balancer or some sort of CDN?

Can you gist the output of the deploy? Also, does your app have a `CHECKS` file?

**Comment by FilipLukac** [comment] 2019-07-22 09:46
1) We don't have any LoadBalancer or CDN (just simple EC2 as we had on DigitalOcean - on DigitalOcean everything worked as expected)

2) We don't have any `CHECKS` file


3) I'm adding one image with logs (after deploy) - left is `errro.log` and right is `access.log`

<img width="1446" alt="Screenshot 2019-07-22 at 11 44 53" src="https://user-images.githubusercontent.com/862354/61623004-2fd33500-ac76-11e9-8bb9-bec5b8735d39.png">



4) (I know, withtout Dokku Trace) but this is log from deploy (I cannot post TRACE log cause we have tens or hundreds of customers right now on service - so I cannot drop server for 1-2 minutes)

```
-----> App Procfile file found (/home/dokku/sloneek.com/DOKKU_PROCFILE)
       DOKKU_SCALE declares scale -> bower=0 gulp=0 migrations=0 web=1
-----> Attempting pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
-----> Default container check successful!
-----> Running post-deploy
-----> Configuring sloneek.com...(using built-in template)
-----> Creating https nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Found previous container(s) (ea2a8295c7f6) named sloneek.com.web.1
=====> Renaming container (ea2a8295c7f6) sloneek.com.web.1 to sloneek.com.web.1.1563788645
=====> Renaming container (fcfb231d6afe) focused_kilby to sloneek.com.web.1
-----> Shutting down old containers in 60 seconds
=====> ea2a8295c7f6516deddb24135887e3b3f463ff43281bcf0a189250375a2ffa41
=====> Application deployed:
       http://sloneek.com
       https://sloneek.com

To push.sloneek.com:sloneek.com
   3888f8d..5703a87  HEAD -> master

```

**Comment by josegonzalez** [comment] 2019-07-22 09:49
I wonder... is PHP serving up all those files for you, and maybe bailing because it can't find them on disk for some reason? Might be worth tossing in a `CHECKS` file to verify that the container is running and responding with 200s as expected before throwing it into production.

Very strange that it would start working after a minute or so. Can you reproduce this on a new server, either on DO or AWS?

**Comment by FilipLukac** [comment] 2019-07-22 09:51
I have one different think which is different from DigitalOcean service. (We don't have PostgreSQL service in Dokku anymore, we are using RDS - we had PostgreSQL container running on same server as PHP application - connected through `dokku postgres:link`). But this should not cause the problem.

I will try to reproduce

**Comment by josegonzalez** [comment] 2019-07-22 09:54
This doesn't really sound like a Dokku bug to be honest, more like potentially a bad app config somehow.

It might be worth it to setup NewRelic APM, Sentry Error Tracking or similar to see what sorts of requests are getting to your app, and why they are responding with 502s. 502 service unavailable indicates to me that the app is trying to contact some other service and having trouble, and potentially bubbling that error up.

**Comment by FilipLukac** [comment] 2019-07-22 09:56
@josegonzalez 
PS: We are doing build everyday (and its everytime like this, 1-2 minute server is off and then it starts working like a charm)
PS2: We have exactly same config as we had on DigitalOcean (exactly the same with the same app version).

On DigitalOcean it worked (then we migrated as I have written) and since we are on amazon, it doesn't. Maybe there is some problem with configuration cause of new version of Dokku (we had 1 year old version on DigitalOcean).

Anyway, thank you so much I will be investigating this problem. If I will fix or hit anything, I will reply in this comment.

**Comment by FilipLukac** [comment] 2019-07-22 09:58
Seems like problem with NGINX configuration, because I've found several articles like this:
https://serverfault.com/questions/317393/connect-failed-111-connection-refused-while-connecting-to-upstream
https://www.digitalocean.com/community/questions/nginx-connect-failed-111-connection-refused-while-connecting-to-upstream

IT seems like my problem. But fpm and nginx is handled by dokku right ? (cause I didn't modify any of nginx config or fpm config)

**Comment by josegonzalez** [comment] 2019-07-22 10:05
There is a host nginx from which you can grab error/access logs for all apps (unless you disable the proxy). For PHP, there is also usually a webserver _inside_ the container - apache or nginx - that proxies to PHP fastcgi or similar. How that works depends on what you have configured in your Procfile, and is governed by the PHP buildpack.

If you add a `CHECKS` file, the host nginx won't swap to the new container unless the container responds with 200 OK on the configured endpoints, meaning you can avoid downtime completely.

Whenever you get a chance, please turn on trace mode and trigger a deploy. I'd like to see the _entire_ deploy output - feel free to PM it to me on slack - as well as the contents of the nginx config both before _and_ after the deploy. Finally, I'd also like access/error logs during that time period, as that will let me know if the nginx errors are coming from new or old containers.

**Comment by FilipLukac** [comment] 2019-07-22 10:15
If will be doing next deploy, I will turn on trace and gits you outputs, thank you anyway, I'm going to write checks to prevent drop-down-times :))

**Comment by FilipLukac** [comment] 2019-07-22 10:20
I fixed it temporarily by writing checks (thank you so much). I will provide trace logs as soon as possible

**Comment by josegonzalez** [comment] 2019-08-01 22:20
Friendly _bump_.

**Comment by josegonzalez** [comment] 2019-08-05 20:59
Closing as there hasn't been any update in two weeks. Feel free to comment and we'll reopen as appropriate.

**Closed by josegonzalez** 2019-08-05 20:59 UTC
Labels: needs: more info
