### ISSUE TITLE
After server where Dokku runs restarts, the apps are mismatched

### ISSUE THREAD

**Issue by sarsonj** [dokku/dokku#4126] opened 2020-09-07 20:00 UTC
#Description of problem
When I restart server, where Dokku is running, the apps are mismatched. Some of URLs shows different app, some of them shows just error page.

### How reproducible
Mostly when I restart Linux server, where Dokku is installed

### `dokku report APP_NAME` output
```
root@dokku:/home/sarsonj# dokku report status.babymonitor3g.com
-----> uname: Linux dokku.tappytaps.com 5.7.6-x86_64-linode136 #1 SMP PREEMPT Wed Jun 24 15:41:07 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:           3918        1282         390         123        2245        2328
       Swap:           511          24         487
-----> docker version:
       Client: Docker Engine - Community
        Version:           19.03.8
        API version:       1.40
        Go version:        go1.12.17
        Git commit:        afacb8b7f0
        Built:             Wed Mar 11 01:25:58 2020
        OS/Arch:           linux/amd64
        Experimental:      false

       Server: Docker Engine - Community
        Engine:
         Version:          19.03.8
         API version:      1.40 (minimum version 1.12)
         Go version:       go1.12.17
         Git commit:       afacb8b7f0
         Built:            Wed Mar 11 01:24:30 2020
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.2.13
         GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
        runc:
         Version:          1.0.0-rc10
         GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
        docker-init:
         Version:          0.18.0
         GitCommit:        fec3683
-----> docker daemon info:
       Client:
        Debug Mode: true

       Server:
        Containers: 121
         Running: 25
         Paused: 0
         Stopped: 96
        Images: 275
        Server Version: 19.03.8
        Storage Driver: overlay2
         Backing Filesystem: <unknown>
         Supports d_type: true
         Native Overlay Diff: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
        runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
        init version: fec3683
        Security Options:
         seccomp
          Profile: default
        Kernel Version: 5.7.6-x86_64-linode136
        Operating System: Ubuntu 18.04.5 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 3.827GiB
        Name: dokku.tappytaps.com
        ID: 35YB:DBVC:YBRU:MYNS:GSW5:GKBM:WINJ:JZNO:IJFZ:IIIN:GIW7:HH2S
        Docker Root Dir: /mnt/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> sigil version: 0.6.0
-----> herokuish version:
       herokuish: 0.5.13
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v215
         heroku-buildpack-nodejs    v171
         heroku-buildpack-clojure   v84
         heroku-buildpack-python    v169
         heroku-buildpack-java      v66
         heroku-buildpack-gradle    v31
         heroku-buildpack-scala     v87
         heroku-buildpack-play      v26
         heroku-buildpack-php       v174
         heroku-buildpack-go        v142
         buildpack-nginx            v13
-----> dokku version: dokku version 0.21.4
-----> dokku plugins:
       plugn: 0.5.0
         00_dokku-standard    0.21.4 enabled    dokku core standard plugin
         20_events            0.21.4 enabled    dokku core events logging plugin
         app-json             0.21.4 enabled    dokku core app-json plugin
         apps                 0.21.4 enabled    dokku core apps plugin
         builder-dockerfile   0.21.4 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.21.4 enabled    dokku core builder-herokuish plugin
         buildpacks           0.21.4 enabled    dokku core buildpacks plugin
         certs                0.21.4 enabled    dokku core certificate management plugin
         checks               0.21.4 enabled    dokku core checks plugin
         common               0.21.4 enabled    dokku core common plugin
         config               0.21.4 enabled    dokku core config plugin
         docker-options       0.21.4 enabled    dokku core docker-options plugin
         domains              0.21.4 enabled    dokku core domains plugin
         enter                0.21.4 enabled    dokku core enter plugin
         git                  0.21.4 enabled    dokku core git plugin
         letsencrypt          0.9.3 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.21.4 enabled    dokku core logs plugin
         mongo                1.11.2 enabled    dokku mongo service plugin
         mysql                1.11.2 enabled    dokku mysql service plugin
         network              0.21.4 enabled    dokku core network plugin
         nginx-vhosts         0.21.4 enabled    dokku core nginx-vhosts plugin
         plugin               0.21.4 enabled    dokku core plugin plugin
         postgres             1.11.2 enabled    dokku postgres service plugin
         proxy                0.21.4 enabled    dokku core proxy plugin
         ps                   0.21.4 enabled    dokku core ps plugin
         redirect             0.6.2 enabled    Plugin for managing application redirects
         repo                 0.21.4 enabled    dokku core repo plugin
         resource             0.21.4 enabled    dokku core resource plugin
         scheduler-docker-local 0.21.4 enabled    dokku core scheduler-docker-local plugin
         shell                0.21.4 enabled    dokku core shell plugin
         ssh-keys             0.21.4 enabled    dokku core ssh-keys plugin
         storage              0.21.4 enabled    dokku core storage plugin
         tags                 0.21.4 enabled    dokku core tags plugin
         tar                  0.21.4 enabled    dokku core tar plugin
         trace                0.21.4 enabled    dokku core trace plugin
=====> status.babymonitor3g.com app information
       App deploy source:
       App dir:                       /home/dokku/status.babymonitor3g.com
       App locked:                    false
=====> status.babymonitor3g.com buildpacks information
       Buildpacks list:
CN = status.babymonitor3g.com
error 20 at 0 depth lookup: unable to get local issuer certificate
=====> status.babymonitor3g.com ssl information
       Ssl dir:                       /home/dokku/status.babymonitor3g.com/tls
       Ssl enabled:                   true
       Ssl hostnames:                 status.babymonitor3g.com
       Ssl expires at:                Oct 13 03:25:56 2020 GMT
       Ssl issuer:                    C = US, O = Lets Encrypt, CN = Lets Encrypt Authority X3
       Ssl starts at:                 Jul 15 03:25:56 2020 GMT
       Ssl subject:                   subject=CN = status.babymonitor3g.com
       Ssl verified:                  self signed
=====> status.babymonitor3g.com checks information
       Checks disabled list:          none
       Checks skipped list:           none
=====> status.babymonitor3g.com docker options information
       Docker options build:          --link dokku.postgres.status_babymonitor3g_com:dokku-postgres-status-babymonitor3g-com
       Docker options deploy:         --link dokku.postgres.status_babymonitor3g_com:dokku-postgres-status-babymonitor3g-com --restart=on-failure:10
       Docker options run:            --link dokku.postgres.status_babymonitor3g_com:dokku-postgres-status-babymonitor3g-com
=====> status.babymonitor3g.com domains information
       Domains app enabled:           false
       Domains app vhosts:
       Domains global enabled:        true
       Domains global vhosts:         dokku.tappytaps.com
=====> status.babymonitor3g.com git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       a6d7ab7
       Git last updated at:
=====> status.babymonitor3g.com network information
       Network attach post create:
       Network attach post deploy:
       Network bind all interfaces:   false
       Network web listeners:         172.17.0.25:5000
=====> status.babymonitor3g.com nginx information
       Nginx access log path:         /var/log/nginx/status.babymonitor3g.com-access.log
       Nginx bind address ipv4:
       Nginx bind address ipv6:       ::
       Nginx error log path:          /var/log/nginx/status.babymonitor3g.com-error.log
       Nginx hsts:                    true
       Nginx hsts include subdomains: true
       Nginx hsts max age:            15724800
       Nginx hsts preload:            false
       Nginx proxy read timeout:      60s
       Nginx last visited at:         1599507664
=====> status.babymonitor3g.com proxy information
       Proxy enabled:                 false
       Proxy port map:
       Proxy type:                    nginx
=====> status.babymonitor3g.com ps information
       Processes:                     1
       Deployed:                      true
       Running:                       true
       Restore:                       true
       Restart policy:                on-failure:10
       Ps can scale:                  true
       Status web.1:                  running    (CID: a87cabbd2048)
=====> status.babymonitor3g.com scheduler-docker-local information
       Scheduler docker local disable chown:
=====> status.babymonitor3g.com storage information
       Storage build mounts:
       Storage deploy mounts:
       Storage run mounts:
```
### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
Through standard shell script, Linode server
### Additional information
I read, that sometimes this issue happen and that I should run `Dokku proxy:build-config`, however, this doesn't help to me. Result:

```
root@dokku:/home/sarsonj# dokku proxy:build-config status.babymonitor3g.com
Error: No such object: dokku/status.babymonitor3g.com:latest
-----> Ensuring network configuration is in sync for status.babymonitor3g.com
-----> No matching configured domains for status.babymonitor3g.com found in SSL certificate. Your app will show as insecure in a browser if accessed via SSL
-----> Please add appropriate domains via the dokku domains command
-----> Configured domains for app:
=====> dokku.tappytaps.com
-----> Domains found in SSL certificate:
=====> status.babymonitor3g.com
grep: /home/dokku/status.babymonitor3g.com/VHOST: No such file or directory
Missing image for app
FAILED: exit status 1
```

The only what helps to me is to rebuild all apps. This is however takes hours....

**Comment by josegonzalez** [comment] 2020-09-07 20:02
> Error: No such object: dokku/status.babymonitor3g.com:latest

That seems like the image is missing? Are the containers running for that app? You can check this via `dokku ps:inspect $APP`.

Regardless, this seems like #3932. We basically need to delete all nginx configs at the beginning of ps:restore and let the restore create them as necessary.

**Comment by sarsonj** [comment] 2020-09-07 20:13
Thanks, 

it looks like, that image is here:
```
root@dokku:/home/dokku/status.babymonitor3g.com# dokku ps:inspect status.babymonitor3g.com
[
    {
        "AppArmorProfile": "",
        "Args": [
            "web"
        ],
        "Config": {
            "AttachStderr": true,
            "AttachStdin": false,
            "AttachStdout": true,
            "Cmd": [
                "/start",
                "web"
            ],
            "Domainname": "",
            "Entrypoint": null,
            "Env": [
                "PORT=5000",
                "USER=herokuishuser",
                "DYNO=web.1",
                "CACHE_PATH=/cache",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=XXXXXX"
            ],
            "Hostname": "a87cabbd2048",
            "Image": "dokku/status.babymonitor3g.com:latest",
            "Labels": {
                "com.dokku.app-name": "status.babymonitor3g.com",
                "com.dokku.container-type": "deploy",
                "com.dokku.dyno": "web.1",
                "com.dokku.image-stage": "release",
                "com.dokku.process-type": "web",
                "dokku": "",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vendor": "dokku"
            },
            "OnBuild": null,
            "OpenStdin": false,
            "StdinOnce": false,
            "Tty": false,
            "User": "",
            "Volumes": null,
            "WorkingDir": ""
        },
        "Created": "2020-07-17T13:36:35.079776636Z",
        "Driver": "overlay2",
        "ExecIDs": null,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/mnt/docker/overlay2/870f54e0c84ab8bee90ebb3680d0a2562d9e89dcc938ec612a84e31b3ba0d94e-init/diff:/mnt/docker/overlay2/a56753b22f9ae36436c88958de7e40b6213811f0d64edb76129ee2435bf41799/diff:/mnt/docker/overlay2/02040520559c859759a203a1fb2e679c32fb1c186a5c01a7c8e3d78004f98c91/diff:/mnt/docker/overlay2/7884d4c997d5d6a681377aa7d04010659b9ec794313aa38ddb645d16e2d9e9b3/diff:/mnt/docker/overlay2/2c8a0e46a4a1411f1e5e3027396965cc5e01f5f7162b11726b338b5893902c00/diff:/mnt/docker/overlay2/9adf640a68f55b238a8abb9f7f338cc932dc80ebd10f2e88567bc5d558bdd8d0/diff:/mnt/docker/overlay2/2a488da7f45c08fe905d0d5253476864c933d50f3b126ed432341a9a0071bf96/diff:/mnt/docker/overlay2/73c16d01bf06cb7c6a4666f622f77bbb6db88ed8ff1a5a1555c95982049c9574/diff:/mnt/docker/overlay2/99d167e92d6a6e786448b76afbc38b63a596b50a14a2cbebef083164cc97c9aa/diff:/mnt/docker/overlay2/4348242be224443f79369940fedf9b2bddc0e8d42299c30680da0a390d97de3b/diff:/mnt/docker/overlay2/0b3405a066e39885e3ceec3e56be135f563fe041c49b1191a394767db64cfac3/diff:/mnt/docker/overlay2/f7b4b01bc39305c25cb64a0d3d633fbabfac8c0d2396d667316c9b969c10dd26/diff:/mnt/docker/overlay2/6ed3758dd11a4e9b2db38dfb9c9afa10db68e78af1b37da1e455db6c068ca51c/diff:/mnt/docker/overlay2/460abdc546d75e7ad6ef11c02b812a846a47ba335a04aa890cf829aae46426cc/diff:/mnt/docker/overlay2/dd9963b6a8472441168cb3b1f0664b56792be596cd915baba4adf9786415391e/diff:/mnt/docker/overlay2/d1658f919f11c3477bf91685da8c597ad64b70402363082f842f52bc5d00b48a/diff:/mnt/docker/overlay2/766225bb2191c5fc0a9c9030802055fd486c2a031987c7babd4be6a66ea6f913/diff:/mnt/docker/overlay2/b05870392cfe9d7df0e37a0afccc4f11476c247e9d47b7e0a13d1126ca6551b8/diff:/mnt/docker/overlay2/628570beed057ec7881ec6087faad252777e02f7bd39a7395deb23bcd23a9d79/diff:/mnt/docker/overlay2/a27c833394a29d67686ccc4c9bbe83850cc8c22e1d03a5bfc83d476967a87010/diff",
                "MergedDir": "/mnt/docker/overlay2/870f54e0c84ab8bee90ebb3680d0a2562d9e89dcc938ec612a84e31b3ba0d94e/merged",
                "UpperDir": "/mnt/docker/overlay2/870f54e0c84ab8bee90ebb3680d0a2562d9e89dcc938ec612a84e31b3ba0d94e/diff",
                "WorkDir": "/mnt/docker/overlay2/870f54e0c84ab8bee90ebb3680d0a2562d9e89dcc938ec612a84e31b3ba0d94e/work"
            },
            "Name": "overlay2"
        },
        "HostConfig": {
            "AutoRemove": false,
            "Binds": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceWriteIOps": null,
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Cgroup": "",
            "CgroupParent": "",
            "ConsoleSize": [
                0,
                0
            ],
            "ContainerIDFile": "",
            "CpuCount": 0,
            "CpuPercent": 0,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpuShares": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "Devices": [],
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IOMaximumBandwidth": 0,
            "IOMaximumIOps": 0,
            "Init": true,
            "IpcMode": "private",
            "Isolation": "",
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "Links": [
                "/dokku.postgres.status_babymonitor3g_com:/status.babymonitor3g.com.web.1/dokku-postgres-status-babymonitor3g-com"
            ],
            "LogConfig": {
                "Config": {},
                "Type": "json-file"
            },
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "Memory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "NanoCpus": 0,
            "NetworkMode": "default",
            "OomKillDisable": false,
            "OomScoreAdj": 0,
            "PidMode": "",
            "PidsLimit": null,
            "PortBindings": {},
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ],
            "ReadonlyRootfs": false,
            "RestartPolicy": {
                "MaximumRetryCount": 10,
                "Name": "on-failure"
            },
            "Runtime": "runc",
            "SecurityOpt": null,
            "ShmSize": 67108864,
            "UTSMode": "",
            "Ulimits": null,
            "UsernsMode": "",
            "VolumeDriver": "",
            "VolumesFrom": null
        },
        "HostnamePath": "/mnt/docker/containers/a87cabbd20484c888c6560059e8f035b1f5b5b80b40bd29d0fa061a5f45bc106/hostname",
        "HostsPath": "/mnt/docker/containers/a87cabbd20484c888c6560059e8f035b1f5b5b80b40bd29d0fa061a5f45bc106/hosts",
        "Id": "a87cabbd20484c888c6560059e8f035b1f5b5b80b40bd29d0fa061a5f45bc106",
        "Image": "sha256:5e8738dcfee114df2b65332f4cf70af30f6806b945672155e0c2061cb9e7f4bf",
        "LogPath": "/mnt/docker/containers/a87cabbd20484c888c6560059e8f035b1f5b5b80b40bd29d0fa061a5f45bc106/a87cabbd20484c888c6560059e8f035b1f5b5b80b40bd29d0fa061a5f45bc106-json.log",
        "MountLabel": "",
        "Mounts": [],
        "Name": "/status.babymonitor3g.com.web.1",
        "NetworkSettings": {
            "Bridge": "",
            "EndpointID": "d1350b3354638e05726a8ad49f1d75db3b158ee8cb470821fb0d5cc473c9f1db",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "HairpinMode": false,
            "IPAddress": "172.17.0.25",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "MacAddress": "02:42:ac:11:00:19",
            "Networks": {
                "bridge": {
                    "Aliases": null,
                    "DriverOpts": null,
                    "EndpointID": "d1350b3354638e05726a8ad49f1d75db3b158ee8cb470821fb0d5cc473c9f1db",
                    "Gateway": "172.17.0.1",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "IPAMConfig": null,
                    "IPAddress": "172.17.0.25",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "Links": null,
                    "MacAddress": "02:42:ac:11:00:19",
                    "NetworkID": "770518698b7e011a8dc831df2b3c7f184c43d46e89c8264c61eba1ef6057898f"
                }
            },
            "Ports": {},
            "SandboxID": "60600f9767bd4f887c2cc15c181db6cda3cbe1387be87ba10d9c4ce2d9d0635f",
            "SandboxKey": "/var/run/docker/netns/60600f9767bd",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null
        },
        "Path": "/start",
        "Platform": "linux",
        "ProcessLabel": "",
        "ResolvConfPath": "/mnt/docker/containers/a87cabbd20484c888c6560059e8f035b1f5b5b80b40bd29d0fa061a5f45bc106/resolv.conf",
        "RestartCount": 0,
        "State": {
            "Dead": false,
            "Error": "",
            "ExitCode": 0,
            "FinishedAt": "2020-09-07T21:24:10.51257953+02:00",
            "OOMKilled": false,
            "Paused": false,
            "Pid": 6122,
            "Restarting": false,
            "Running": true,
            "StartedAt": "2020-09-07T19:25:51.215035547Z",
            "Status": "running"
        }
    }
]
```

I can find it when using `docker images`:

```
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
<none>                       <none>              5e8738dcfee1        7 weeks ago         2.05GB
```

what is strange, that newly regenerated images are different, have non null REPOSITORY. Could be issue somewhere here?

```
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
dokku/getstorky.com          latest              b6ccf60dd1c4        20 minutes ago      1.47GB
```

**Comment by josegonzalez** [comment] 2020-09-07 20:36
Looks like docker is caching the image name, but the sha matches. One thing we might want to do is check if the containers in the CONTAINER_ID files all exist and if they match. If they match, ensure the image is properly tagged based on the sha reported for the containers. If they don't match, rebuild the world.

`proxy:build-config` might want to call something like `plugn trigger ps-ensure-app $APP`, which (for scheduler-local) would ensure the image is tagged, which would avoid the failure you are seeing. This could also be called at the beginning in ps:restore as well.

**Comment by hippich** [comment] 2021-07-23 10:47
I was investigating a very similar-looking issue. I have a default app `000-default` to show when `Host:` did not match any app. But despite that, after the restart, yet to re-launched app domain was showing a different app from `000-default`. Turned out that nginx was looking for a server block with SSL configured and my `000-default` did not have any SSL configured. Adding SSL cert to `000-default` made nginx respond correctly during the dokku's restore process

**Comment by wdiechmann** [comment] 2021-09-03 08:27
auch - think I got bit by this 😢 

```
root@ugapp02:~# dokku ps:report astronaut
Error: No such object: b23b108c0f861e0ffad0d393c95d61103b0906f4c35b4fb268f3d199afdd5a86
=====> astronaut ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:              
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       false
       Status web 1:                  missing (CID: b23b108c0f8)
root@ugapp02:~# dokku ps:inspect astronaut
Error: No such container: b23b108c0f861e0ffad0d393c95d61103b0906f4c35b4fb268f3d199afdd5a86
[]
2021/09/03 10:20:43 exit status 1
 !     exit status 1
```

or not?

I read on this thread that all apps has to be rebuilt - that did not end well on previous run (couple of days ago) when I encountered an issue along these lines, but didn't pay attention to it and just wiped the entire thing and started over, but now this VM is going into staging and stuff, and I cannot keep wiping it - 

Any idea as to how I proceed from here?

**Comment by FlorianLoch** [comment] 2022-02-04 08:26
Hey there,
I am not sure the problem occurring to me actually relates to this issue - in case it does not I probably will need to create another issue ;)

Since using dokku with the great letsencrypt problem I am seeing the following issue: after restarting, dokku seems to mix up the apps and draws the wrong certificate for an app. Strangely, it does not happen to all deployed apps.

This time it happened to my main domain, which is bound to an app together with to other domains:
```
dokku domains:report cv
=====> cv domains information
       Domains app enabled:           true
       Domains app vhosts:            cv.fdlo.ch fdlo.ch www.fdlo.ch
       Domains global enabled:        true
       Domains global vhosts:         vps.fdlo.ch fdlo.ch
```

Requesting `https://cv.fdlo.ch` works fine - requesting `https://fdlo.ch` does not, the certificate from `cadvisor.vps.fdlo.ch` is used. 🤔 

<img width="1096" alt="Screenshot 2022-02-04 at 09 12 02" src="https://user-images.githubusercontent.com/5587805/152496098-b3bbb882-6aa0-4fe0-b1c9-ff991f11aa9e.png">


Any idea, why that would happen? I can fix it with `dokku letsencrypt:enable cv` again - but that is not so great for several reasons:
- Server restarts for whatever reason, page will be down till I notice it
- I basically need to check every (sub-) domain after every restart of dokku :(

If you need further information, I will try to provide it. Just will have to reproduce the bad state again.

**Comment by FlorianLoch** [comment] 2022-09-01 21:33
This still seems to occur - any progress in resolving this/tracking it down?

**Comment by josegonzalez** [comment] 2022-11-28 04:33
I can't fix anything if nginx is serving the wrong certificate for an app. That seems like a completely different issue, so please file a ticket for that.

A few notes for the wrong app being served up:

- When docker restarts a container, it doesn't always preserve the IP address. Thats a known issue that is how Docker works, and I cannot fix anything about this.
- On host reboot, a container IP may be re-assigned.
- On docker restart, a container IP may be re-assigned. You can somewhat avoid this by enabling `live-restore` in Docker.
- Our nginx plugin listens to container `$IP:$PORT`, where the `$IP` is retrieved at config build time.
- Dokku runs `ps:restore` on server reboot, which will clear out old proxy configs, rebuild missing containers, and rebuild the proxy configs as appropriate. This can take a while, so there is a moment where the nginx may be serving different containers if a container IP in use by one app container was reassigned to a different app's container.
- Dokku now provides alternative proxy plugins - caddy, traefik, and soon haproxy - which are immune to these sorts of routing issues as they integrate directly with the Docker daemon for information.
- Dokku installs the dokku-event-listener, which listens to docker events and rebuilds configs as it sees IPs for containers change. This catches most container crashing issues.

We've already done a ton of workarounds to make this work, and short of nginx directly talking to the docker daemon for upstreams (or using a docker-based DNS server to route based on some sort of internal hostnames), there isn't much we can do here.

I don't personally encounter this issue, but if I did, I would use one of the other proxy plugins.

**Closed by josegonzalez** 2022-11-28 04:33 UTC
Labels: plugin: proxy
